### ISSUE TITLE
Types are not found when using node with ESM and `typescript@4.7.2` with `NodeNext` 

### ISSUE THREAD

**Issue by julienfouilhe** [faker-js/faker#1004]
### Describe the bug

Yesterday Typescript released a new version (4.7.2) that  adds ESM support for Nodejs 16+ (see their [release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs)).

faker is broken when using it, here is the error:

```
Could not find a declaration file for module '@faker-js/faker'. '/Users/julien/cash/cash/node_modules/@faker-js/faker/dist/esm/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/faker-js__faker` if it exists or add a new declaration (.d.ts) file containing `declare module '@faker-js/faker';`

1 import { faker } from "@faker-js/faker";
```

I upgraded to 7.0.0 and it was fixed, but 7.0.1 reverts the fix (PR [here](https://github.com/faker-js/faker/pull/989)), I couldn't find the reason for that anywhere.

### Reproduction

Minimal repro is available here: https://github.com/julienfouilhe/faker-node-next-ts-repo with steps to reproduce available in the README.

### Additional Info

7.0.0 fixes the issue.

**Comment by Shinigami92** [comment]
> I couldn't find the reason for that anywhere

The issue was that TypeScript compatibility without using `NodeNext` fully broke
So we need to find a way that works with AND without using that

**Comment by Shinigami92** [comment]
Okay I'm confused, I don't understand why `"types": "index.d.ts"` is needed. If I change that the cjs version is broken.
So actually it was maybe my fault in https://github.com/faker-js/faker/pull/979/commits/371aeb8f63df320ac46d2c3632da7450816435ee and I'm sorry about that.

I now restructured the https://github.com/faker-js/playground and added a ts 4.7 nodenext playground!
And your initial PR without changing the "types" field is working...
I will try to reopen your initial PR so you get the commit credits

**Comment by Shinigami92** [comment]
Nevermind, cannot reopen a merged PR... would you like to re-create the PR? (just to get the credits)

**Comment by Shinigami92** [comment]
It just needs to be 

```jsonc
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "require": "./dist/cjs/index.js",
      "import": "./dist/esm/index.mjs"
    },
    "./locale/*": {
      "types": "./dist/types/locale/*.d.ts",
      "require": "./dist/cjs/locale/*.js",
      "import": "./dist/esm/locale/*.mjs"
    },
    "./package.json": "./package.json"
  },
```
