### ISSUE TITLE
Source code todo list v2

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1044]
This list contains all `TODO`s as of c5ac124ecafafc89bdd31a5870f325d671c7e9cf.

| Done | Issue/PR | File | Reporter | Description |
| - | - | - | - | --- |
| ⛔ | #1066 | [src/modules/address/index.ts:426](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/address/index.ts#L426) | @ST-DDT | Allow coordinate parameter to be [string, string]. |
| ❓ | - | [src/modules/address/index.ts:455](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/address/index.ts#L455) | @Shinigami92 | Provide an option property to provide custom circumferences. |
| ❓ | - | [src/modules/helpers/index.ts:225](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/helpers/index.ts#L225) | unknown | implement for letters e.g. [0-9a-zA-Z] etc. |
| ❓ | - | [src/modules/helpers/index.ts:398](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/helpers/index.ts#L398) | @Shinigami92 | We want to remove this default value, but currently it's not possible because some definitions could be empty |
| ❓ | - | [src/modules/helpers/index.ts:424](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/helpers/index.ts#L424) | @Shinigami92 | We want to remove this default value, but currently it's not possible because some definitions could be empty |
| ⛔ | - | [src/modules/image/providers/lorempicsum.ts:6](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/lorempicsum.ts#L6) | @ST-DDT | Rename to picsum? |
| ❓ | - | [src/modules/image/providers/lorempicsum.ts:69](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/lorempicsum.ts#L69) | @ST-DDT | This method does the same as image url, maybe generate a seed, if it is missig? |
| ✔ | #1065 | [src/modules/image/providers/lorempicsum.ts:80](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/lorempicsum.ts#L80) | @ST-DDT | Deprecate this method as it is duplicate and has nothing to do with lorempicsum. |
| ✔ | #1069 | [src/modules/image/providers/lorempixel.ts:47](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/lorempixel.ts#L47) | @ST-DDT | Deprecate this method as it is duplicate and has nothing to do with lorempixel. |
| ❓ | #1046 | [src/modules/image/providers/unsplash.ts:7](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/unsplash.ts#L7) | @ST-DDT | Remove unused(?) constant |
| ✔ | #1062 | [src/modules/image/providers/unsplash.ts:37](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/unsplash.ts#L37) | @ST-DDT | Deprecate this method as it is duplicate and has nothing to do with unsplash. |
| ❓ | #1059 | [src/modules/internet/index.ts:269](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/internet/index.ts#L269) | @Shinigami92 | We may want to return a IPv4 or IPv6 address here in a later major release |
| ❓ | - | [src/modules/name/index.ts:24](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/name/index.ts#L24) | @Shinigami92 | Remove fallback empty object when `strict: true` |
| ✔ | #1080 | [src/modules/name/index.ts:162](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/name/index.ts#L162) | @Shinigami92 | Add possibility to have a prefix together with a suffix |
| ✔ | #1080 | [src/modules/name/index.ts:168](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/name/index.ts#L168) | @Shinigami92 | Not sure if this fallthrough is wanted |
| ❓ | - | [src/modules/name/index.ts:227](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/name/index.ts#L227) | @Shinigami92 | Add female_suffix and male_suffix |
| ✔ | #1063 | [src/modules/phone/index.ts:28](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/phone/index.ts#L28) | @pkuczynski | simplify name to `number()` |
| ✔ | #1089 | [src/modules/random/index.ts:236](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/random/index.ts#L236) | @Shinigami92 | Tests covered `(count, options)`, but they were never typed like that |
| ✔ | #1050 | [src/modules/system/index.ts:22](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/system/index.ts#L22) | @ST-DDT | Replace with Array.from(Set) |
| ❓ | #395 | [src/modules/system/index.ts:176](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/system/index.ts#L176) | @prisis | add a parameter to have the possibility to have one or two ext on file. |
| ❓ | - | [test/all_functional.spec.ts:23](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/all_functional.spec.ts#L23) | @ST-DDT | these are TODOs (usually broken locale files) |
| ❓ | - | [test/all_functional.spec.ts:77](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/all_functional.spec.ts#L77) | @ST-DDT | Use random seed once there are no more failures |
| ❓ | - | [test/all_functional.spec.ts:91](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/all_functional.spec.ts#L91) | @ST-DDT | Remove once there are no more failures |
| ❓ | - | [test/all_functional.spec.ts:110](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/all_functional.spec.ts#L110) | @ST-DDT | Use random seed once there are no more failures |
| ❓ | - | [test/finance.spec.ts:228](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/finance.spec.ts#L228) | unknown | add support for more currency and decimal options |
| ❓ | - | [test/finance.spec.ts:403](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/finance.spec.ts#L403) | unknown | implement checks for each format with regexp |
| ❓ | #1115 | [test/internet.spec.ts:159](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L159) | @Shinigami92 | When providing params to `email`, it produces some not that predictable data |
| ❓ | - | [test/internet.spec.ts:480](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L480) | @Shinigami92 | Make tests more strict |
| ❓ | - | [test/internet.spec.ts:494](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L494) | @Shinigami92 | Understand what's going on |
| ❓ | - | [test/internet.spec.ts:586](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L586) | @Shinigami92 | I would say a non memorable password should satisfy `validator.isStrongPassword`, but it does not currently |
| ❓ | - | [test/internet.spec.ts:600](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L600) | @Shinigami92 | This should definitely be a strong password, but it doesn't :( |

Legend:

- ❓ not yet fixed/fix not merged yet
- ✔ fixed
- ⛔ won't fix

Please leave a comment if you are going to tackle a particular TODO to avoid conflicts.

<details>
<summary>The table was generated using this script</summary>

````sh
grep -r . -n -e "TODO" |\
	grep -v "/.git/" |\
	grep -v "TODO: Insert Title for ${locale}" |\
	sed 's/^\.\///' |\
	sed -E 's/: *\/\/ ?TODO:? / /' |\
	sed -E 's/@?ST-DDT/@ST-DDT/' |\
	sed -E 's/(:[0-9]+) /\1 | /' |\
	sed -E 's/\| ([^@])/| unknown | \1/' |\
	sed -E 's/ [0-9-]+: / | /' |\
	sed -E 's/:([0-9]+) / | \1 /' |\
	sed -E "s/([^ ]+) \| ([0-9]+)/[\1:\2](https:\/\/github.com\/faker-js\/faker\/blob\/$(git rev-parse HEAD)\/\1#L\2)/" |\
	sed 's/^/| ❓ | - | /' |\
	sed 's/$/ |/'
````

</details>

**Comment by xDivisionByZerox** [comment]
I would propose to set the rename of `LoremPicsum` to `Picsum` to `won't fix`. 
This line
[src/modules/image/providers/lorempicsum.ts:6](https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/image/providers/lorempicsum.ts#L6) | @ST-DDT | Rename to picsum?
-- | -- | --

The URL is just `'https://picsum.photo'` but the website is named 'Lorem Picsum'. So the class name checks out IMO.

**Comment by ST-DDT** [comment]
Ok, then please remove the todo and maybe adjust the jsdocs slightly.

**Comment by xDivisionByZerox** [comment]
About the todo in the random module: 
https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/modules/random/index.ts#L236

I can't find any test case that tests that specific signature. Can this todo be removed from the code base and set as `fixed` in the list?

**Comment by ST-DDT** [comment]
Sure

**Comment by xDivisionByZerox** [comment]
@Shinigami92 can you explain your to-do comment in the internet test file?
https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/test/internet.spec.ts#L494

I don't see what's wrong here.

**Comment by Shinigami92** [comment]
@xDivisionByZerox I assume I don't understand what
https://github.com/faker-js/faker/blob/045b8d60a984976b088d8bc28dc61798e9cad2bf/src/modules/internet/index.ts#L372-L374
does
I'm a bit confused by passing 3x 100 into `internet.color` still produces random values, this is a good thing and not wrong at all, I just don't understand :shrug: 
Would be happy if someone could explain and document that

**Comment by ST-DDT** [comment]
@xDivisionByZerox Will create an issue for each TODO that is still in the code.
