### ISSUE TITLE
How Many Words are in Each Category?

### ISSUE THREAD

**Issue by indicozy** [faker-js/faker#1047]
Hi everyone! I'm glad that there are people maintaining faker. I want to use faker to generate unique nicknames made with adjective, animal and color. Is there any data on the amount of words in every category? 

Sample code:
```js
const username =
  `${faker.word.adjective()}-${faker.color.human()}-${faker.animal.type()}`
```

**Comment by Shinigami92** [comment]
You could try access
```ts
faker.definitions.word.adjective.length
faker.definitions.color.human.length
faker.definitions.animal.type.length
```

:thinking:

**Comment by xDivisionByZerox** [comment]
It depends on the [locale](https://fakerjs.dev/api/localization.html) you use. Some locales sadly don't support all feature.
For en currently (v7.2.0):
- adjective: 1347
- colors human readable: 31
- animal types: 13

**Comment by indicozy** [comment]
What about to make some tables with lengths of words in the website?

**Comment by import-brain** [comment]
Hmm, we could definitely auto generate those tables with `.length` on all of our definitions...

**Comment by pkuczynski** [comment]
We could do a locale filter on the top. Most of the users would be anyway interested only in a particular locale...

**Comment by indicozy** [comment]
Alright, closing the issue. I'll send a feature request or PR later
