### ISSUE TITLE
deprecate locale switching during runtime 

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#1054]
### Clear and concise description of the problem

I don't see a use case where you wouldn't be able to instantiate a new faker instance with your desired locale and instead need the utility to change an instance's locale during runtime.

Dropping this feature allows some easier separation of concern handling and thus leading to a cleaner architecture for the library.

### Suggested solution

Deprecate (and later remove) the public accessibility of:
- `faker.locale`
- `faker.locales`
- `faker.localeFallback`
- `faker.setLocal()`

### Additional context

There is a [poll](https://github.com/faker-js/faker/discussions/1049) for dropping the feature of switching locales during runtime.

**Comment by Shinigami92** [comment]
This needs to be done together with e.g. #642, because with out that, it's nearly impossible to build own `Faker` instances.

**Comment by ST-DDT** [comment]
IMO its more like a precondition.

**Comment by ST-DDT** [comment]
Superseded by #1340
