### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by eliezercazares** [faker-js/faker#1072]
### Clear and concise description of the problem

How about something like below, w/randomized values:

input: faker.geolocation.coordinates();
output: {"lat":25.4765033,"long":-100.9765533} 

### Suggested solution

It would require a new module, namely "geolocation".

As of now it can return a couple floats, doesn't matter if it points to the sea or a desert.

### Alternative

The optimal way to go it's to perhaps input a parameter like a city, and obtain the coordinates through some service like google maps.

### Additional context

This module can return coordinates, cities, places.

**Comment by ST-DDT** [comment]
This is already implemented:

- https://fakerjs.dev/api/address.html#nearbyGPSCoordinate
- https://fakerjs.dev/api/address.html#latitude
- https://fakerjs.dev/api/address.html#longitude

**Comment by Shinigami92** [comment]
Already implemented
