### ISSUE TITLE
Error: Webpack Compilation Error ./node_modules/@faker-js/faker/dist/esm/chunk-4J2PVEV7.mjs 1:1430

### ISSUE THREAD

**Issue by foreverchaos** [faker-js/faker#1073]
### Describe the bug

Error: Webpack Compilation Error
./node_modules/@faker-js/faker/dist/esm/chunk-Y64C4BL4.mjs 1:1430
Module parse failed: Unexpected token (1:1430)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### Reproduction

1. add @faker-js/faker to package.json and npm install
2. import { faker } from '@faker-js/faker'

### Additional Info

version: 7.2.0

**Comment by ST-DDT** [comment]
Which version of node are you using?

**Comment by Shinigami92** [comment]
And which version of webpack!

**Comment by MitosisByProxy** [comment]
Have the same issue when using it in a cypress project.

My project dependencies:

    "@types/node": "^17.0.42",
    "cypress": "^10.1.0",
    "cypress-file-upload": "^5.0.3",
    "cypress-wait-until": "^1.7.2",
    "mochawesome": "^7.1.3",
    "npm-run-all": "^4.1.5",
    "typescript": "^4.7.3"

Version 10.1.0 of cypress seems to user "webpack": "^4.44.2". I'm using npm 6.14.5 and node v12.18.1.

Can't speak for @foreverchaos  but the issue seems the same. Hope it helps.

**Comment by Shinigami92** [comment]
> and node v12.18.1

Since v7 we officially dropped node v12 support, and require at least node v14

**Comment by Samyssmile** [comment]
I have same issue using faker js with cypress in my angular project.

- Angular 13
- Cypress 9.7.0
- faker-js 7.2.0

How to reproduce.

**npm install --save-dev @faker-js/faker**

```
import {faker} from "@faker-js/faker";

it('signup-signin-logout', function () {
  let username = faker.name.firstName()

}
```

> Error: Webpack Compilation Error
> ./node_modules/@faker-js/faker/dist/esm/chunk-4J2PVEV7.mjs 1:1430
> Module parse failed: Unexpected token (1:1430)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by agustindangelo** [comment]
Same error on a Cypress project:
```
Error: Webpack Compilation Error
./node_modules/@faker-js/faker/dist/esm/chunk-4J2PVEV7.mjs 1:1430
Module parse failed: Unexpected token (1:1430)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
```json
  "devDependencies": {
    "@faker-js/faker": "^7.2.0",
    "@wdio/allure-reporter": "^7.19.7",
    "@wdio/cli": "^7.19.7",
    "@wdio/local-runner": "^7.19.7",
    "@wdio/mocha-framework": "^7.19.7",
    "@wdio/spec-reporter": "^7.19.7",
    "chromedriver": "^101.0.0",
    "cypress": "^10.1.0",
    "wdio-chromedriver-service": "^7.3.2"
  },
}
```

- node v16.15.0

**Comment by MitosisByProxy** [comment]
> > and node v12.18.1
> 
> Since v7 we officially dropped node v12 support, and require at least node v14

Thx, I'll see if that works when I get back to the office. I do see some comments here that run higher versions of node and still have the same problem.

**Comment by Shinigami92** [comment]
Yeah, we are thinking it's not an issue with node14, but totally with incompatible to webpack v4
Webpack doesn't support new syntax
If babel can solve it right now, please use this option as workaround
Currently we do not have the team presence to discuss if we ever want to support webpack v4 again

In my opinion, and please do NOT take that set in stone, but really just my opinion,
I would like to leave webpack v4 behind and support webpack v5 and vite as these are just working

webpack 5.**73**.0 is the current version and v5 is out for 2 years now 
Maybe it's time to move on and a good time to migrate and update your projects... 🤷

**Comment by Shinigami92** [comment]
Oh and I definitely need to talk to @JessicaSachs when she is available again... because of Cypress

**Comment by codedevdev** [comment]
Same error node 16 :(
Cypress 10

**Comment by JessicaSachs** [comment]
Hey. Yeah, this is related to faker not polyfilling back far enough in the
browser bundle. Nothing to do with Node.

6.x doesn’t have this issue, I would revert back to 6.x if you’re running
into this error.

**Comment by Shinigami92** [comment]
@foreverchaos @MitosisByProxy @Samyssmile @danheim @agustindangelo @codedevdev 

Please checkout the newest version https://github.com/faker-js/faker/releases/tag/v7.3.0

**Comment by MitosisByProxy** [comment]
> @foreverchaos @MitosisByProxy @Samyssmile @danheim @agustindangelo @codedevdev
> 
> Please checkout the newest version https://github.com/faker-js/faker/releases/tag/v7.3.0

This resolves the issue! Thanks for the effort!
