### ISSUE TITLE
Setup `release-it` + changelog plugin

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1096]
### Replace https://github.com/conventional-changelog/standard-version with https://github.com/changesets/changesets

`standard-version` is deprecated and not maintained anymore: see https://www.npmjs.com/package/standard-version
The author suggests to use https://github.com/googleapis/release-please
We could look into that, but I would suggest to have a look into `changesets` as it is [used by pnpm](https://github.com/pnpm/pnpm/blob/47b5e45dd6f5eca91a5cedd059aed0f3a7e73be9/package.json#L6)

As changing the release process might produce a different style of `CHANGELOG.md`, I would prefer to make the move to a new release workflow in a major update of Faker.

`changesets` can definitely handle mono-repos and maybe someday we want to convert this repo to a monorepo, so when suggesting alternative tools or workflows, keep this in mind.

_related to_ https://github.com/faker-js/faker/issues/268

**Comment by Shinigami92** [comment]
Today I will try https://github.com/release-it/release-it with some of my personal repos

**Comment by ST-DDT** [comment]
**Team Decision**

We don't need this for v8.0.
(We will likely immediately start with v9 after v8.0)
