### ISSUE TITLE
Add support for https://placeholder.com as image provider

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1111]
### Clear and concise description of the problem

Add support for https://placeholder.com

### Suggested solution

Create random generated image URLs based on deterministic and seed via https://placeholder.com

### Additional context

I want to create simple grey or coloured placeholder images for my company's project.
I will used them as thumbnails for a video. Also at least the aspect ratio is important to be controlled.

**Comment by Devdre1909** [comment]
Hi @import-brain.
Can I work on this if anyone isn’t working on it?, and is there a proposed implementation?

**Comment by import-brain** [comment]
> Hi @import-brain.
> 
> Can I work on this if anyone isn’t working on it?, and is there a proposed implementation? 

Sure! I don't believe there is a proposed implementation, but I'll assign this to you now.

@Shinigami92, just checking, this is open for contributions, right?

**Comment by xDivisionByZerox** [comment]
This has been implemented in #1186.
