### ISSUE TITLE
Update .github/FUNDING.yml

### ISSUE THREAD

**Issue by jonah-williams** [faker-js/faker#112]
This currently mirrors the original settings from https://github.com/marak/Faker.js/ which means that github is displaying Marak as the sponsorable individual on this repo's page:
![image](https://user-images.githubusercontent.com/86003/149214460-8396bb02-6550-4c83-a6fd-300f1d8d9837.png)
and on issue pages:
![image](https://user-images.githubusercontent.com/86003/149214678-d0bc47b6-ad10-43e3-9696-9d473edeb57d.png)

Since this fork is trying to provide a version of the tool with a new set of maintainers you probably want to update this. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository for details.

**Comment by Shinigami92** [comment]
#43 #111 #56 #15 #110
