### ISSUE TITLE
`random.word()` can return undesirable non-alpha characters

### ISSUE THREAD

**Issue by griest024** [faker-js/faker#113]
### Describe the bug

The pool of strings from which `random.words()` pulls values includes strings that have parentheses, e.g. `Cocos (Keeling) Islands` and `Killer Whale (Orca)`. This can result in `(Keeling)` and `(Orca)` being returned.

There's a larger problem here of non-alphabetic characters being returned in words. Obviously some non-alpha characters are desired in words, e.g. `-`, but some are not. We should decide on the set of acceptable characters that `word()` can return and regex the others out.

### Reproduction

Mock `faker.fake` with the above mentioned values and you can see the bad returns.

### Additional Info

**Comment by pkuczynski** [comment]
I can work on this. Let me know if you want me to...

**Comment by griest024** [comment]
> I can work on this. Let me know if you want me to...

Sure I can assign you. What do you think should be the allowed chars? How would you handle other locales?

**Comment by pkuczynski** [comment]
I took a bit different approach. Have a look at #267

**Comment by Shinigami92** [comment]
I will try to create a PR soon that just uses a `/\w+/` regex
