### ISSUE TITLE
`faker.lorem.word` can return `undefined` despite being typed as `string`

### ISSUE THREAD

**Issue by justinsmid** [faker-js/faker#1131]
### Describe the bug

When calling `faker.lorem.word` with a length that doesn't have any matching words, it will return `undefined` while TypeScript thinks it's a `string`.

### Reproduction

```ts
const nonexistentWord = faker.lorem.word(9999) // <-- typed as `string`
console.log(nonexistentWord) // <-- will output `undefined`
```

**Comment by ST-DDT** [comment]
What is your expected behavior?

- Getting a word with a different length
- or always being forced to handle possibly undefined values?

**Comment by justinsmid** [comment]
I think i would personally expect it to be typed as `string | undefined`.

Getting a word with a different length when explicitly specifying a length seems like it'd be more troublesome, and having a function suddenly able to throw errors while other faker functions don't do so doesn't seem like a good idea either imo.

Splitting it up into separate methods like you suggested seems reasonable.

**Comment by MasterOdin** [comment]
Could the function be made such that if you pass in a length that's greater than any word, it caps the value to the max word length? The few times I've used this function in the past, it was being passed into a function or whatever that doesn't allow undefined, and adding `as string` to every usage would be pretty annoying. Why would someone want this function to return undefined?

**Comment by ST-DDT** [comment]
What about shorter words e.g. length = 1?

**Comment by MasterOdin** [comment]
`length <= 0` also returns undefined for all locales, but I'd argue there to just return `''` in those cases since. For `length = 1`, this only affects the hebrew locale, and there, maybe just bump it up to the next possible length (2)?

**Comment by hankucz** [comment]
In #1218 I implemented it in a way that if a user expects too long word, the maximum possible length is given.

**Comment by ST-DDT** [comment]
**Team decision**

- Throw an error by default, introduce options param that can be used to configure the errorHandling (e.g. return closest length).

**Further discussions**

- Introduce min and max length range in a separate PR. `word(number| {min: length, max: length, length, errorHandling})`

**Comment by ST-DDT** [comment]
Note since we need this in multiple modules this should be done in a new central method: `faker.helpers.stringArrayElement(elements, options)`

**Comment by ST-DDT** [comment]
Note2 it should be applies/used for all of our word methods (those with a length parameters).

**Comment by Shinigami92** [comment]
Just to raise my voice because I suffer in silence: I would suggest to name it strategy instead of errorHandling

**Comment by ST-DDT** [comment]
OK: ``strategy: 'fail' | 'return-any'``

**Comment by import-brain** [comment]
> OK.
> 
> `strategy: 'fail' | 'return-any' = 'fail'`
> 
> Or `fail-if-unavailable`? Or `throw-if-unavailable`?

What about just `throw`?
