### ISSUE TITLE
Faker date birthdate issue

### ISSUE THREAD

**Issue by dhagashDC** [faker-js/faker#1175]
### Describe the bug

faker.date.birthdate() is not working and not returning any value

### Reproduction

faker.date.birthdate() is not working and not returning any value

**Comment by Shinigami92** [comment]
Needs reproduction, cannot reproduce this with our stackblitz demo. everything seems to work fine.

**Comment by dhagashDC** [comment]
const { faker } = require('@faker-js/faker');

const date = faker.date.birthdate({ min: 1900, max: 2000, mode: 'year' });
console.log(date);

TypeError: faker.date.birthdate is not a function

**Comment by Shinigami92** [comment]
- which version?
- esm / cjs?
- does other functions work? is it a general issue?
- did you try re-install your node_modules?
- are you using the code in prod code but have installed faker in devDeps?
