### ISSUE TITLE
Deprecate company.name index parameter

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1178]
### Clear and concise description of the problem

https://github.com/faker-js/faker/blob/fbddaa39e830e1ac44e7821d219ca7859af79e95/src/modules/company/index.ts#L36

Using an index parameter is equal to using a fixed pattern, any changes on our side to the patterns would potentially break client code.

### Suggested solution

The parameter should be deprecated for removal. Users should either hardcode the pattern themselves or use a random pattern.

### Additional context

The method is being renamed in https://github.com/faker-js/faker/pull/1166.

**Comment by Minozzzi** [comment]
This issue is to be done after or before #1179?

**Comment by ST-DDT** [comment]
I think before #1179 but after #1166 .

**Comment by Minozzzi** [comment]
The #1166 already been merged. I would like to do this task too. Can you assign to me?
