### ISSUE TITLE
Localize format patterns for company.name

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1179]
### Clear and concise description of the problem

https://github.com/faker-js/faker/blob/fbddaa39e830e1ac44e7821d219ca7859af79e95/src/modules/company/index.ts#L37-L41

Currently the patterns are hardcoded to match English company names.

### Suggested solution

The patterns should be localized so other locales can define custom patterns.

### Additional context

There seems to be patterns/files for that already, but these needs to be checked/defined and referenced:
https://github.com/faker-js/faker/blob/fbddaa39e830e1ac44e7821d219ca7859af79e95/src/locales/en/company/name.ts#L1-L5
but there is nothing for that in: https://github.com/faker-js/faker/blob/fbddaa39e830e1ac44e7821d219ca7859af79e95/src/definitions/company.ts#L6

There are also other PRs that work on the method so this should only be done after both:

- https://github.com/faker-js/faker/pull/1166
- https://github.com/faker-js/faker/issues/1178

**Comment by ST-DDT** [comment]
@Shinigami92 Do you consider this a breaking change?

**Comment by Minozzzi** [comment]
Hello guys. I woud like contribute with this task.Can you guys assign to me?

**Comment by ST-DDT** [comment]
There is https://github.com/faker-js/faker/pull/1216 already.

**Comment by Shinigami92** [comment]
> There is #1216 already.

But it looks like that it is for the `name` module but this issue is about `company.name` 🤔 is it?

**Comment by ST-DDT** [comment]
Oh yeah, you are right.

**Comment by Minozzzi** [comment]
Alright @ST-DDT . I will try to contribute as best I can to this issue. 😀
