### ISSUE TITLE
Generated bitcoin addresses should pass validators.isBtcAddress

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1184]
### Clear and concise description of the problem

In #1181 the question came up, whether our [bitcoin generator](https://github.com/faker-js/faker/blob/15e3eed927953446d3e3aa8dcd7fca3f8472ff3e/src/modules/finance/index.ts#L213) produces valid bitcoin addresses.
According to [validators.isBtcAddress](https://github.com/validatorjs/validator.js/blob/1bb14e85dd7fb8cec8a43ff586c0d869977cd684/README.md?plain=1#L104) it doesn't do so all the time.

### Suggested solution

We should

- check whether the validator.js method is correct,
- use it in [our tests](https://github.com/faker-js/faker/blob/15e3eed927953446d3e3aa8dcd7fca3f8472ff3e/test/finance.spec.ts#L295),
- and verify that the tests pass.

**Comment by Minozzzi** [comment]
I would like to try contribute to this issue if it still hasn't been resolved. Can you assign to me?

**Comment by import-brain** [comment]
> I would like to try contribute to this issue if it still hasn't been resolved. Can you assign to me?

Sure!

**Comment by Minozzzi** [comment]
I took the regex from our tests and manually verified it at https://regexr.com/
I believe our bitcoin address generation is wrong.
Should we install the validatorjs package and apply it to bitcoin address tests with bitcoin address generation fix?

![image](https://user-images.githubusercontent.com/61752597/183303014-51d8edc5-40d7-464d-843a-b8adbf73d97d.png)
It's allowing the `i` character

**Comment by import-brain** [comment]
> @import-brain 
> 
> I took the regex from our tests and manually verified it at https://regexr.com/
> 
> I believe our bitcoin address generation is wrong.
> 
> Should we install the validatorjs package and apply it to bitcoin address tests with bitcoin address generation fix?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/61752597/183303014-51d8edc5-40d7-464d-843a-b8adbf73d97d.png)
> 
> It's allowing the `i` character

Sure, go for it!

**Comment by Minozzzi** [comment]
@ST-DDT @import-brain 
I've searched a little and I verified that lowercase `i` is permitted, the difference of validator.js and our validation on tests is the max chars.

Validator.js validation 
https://github.com/validatorjs/validator.js/blob/86a07ba4f3f710f639e92a62cf81dd3321ef9ee8/src/lib/isBtcAddress.js#L5

Our validation
https://github.com/faker-js/faker/blob/fda44bb899efbcbac2071a199964a3e269cbd805/test/finance.spec.ts#L293

And i verified that the max generated chars is different of our tests and validator.js
https://github.com/faker-js/faker/blob/15e3eed927953446d3e3aa8dcd7fca3f8472ff3e/src/modules/finance/index.ts#L214

I don't know say which is correct, I searched and almost all of the sites don't says the same thing about valid bitcoin address

**Comment by import-brain** [comment]
> I don't know say which is correct, I searched and almost all of the sites don't says the same thing about valid bitcoin address

Yeah, pretty much all websites say different things about the max and min lengths of bitcoin addresses.

**Comment by Minozzzi** [comment]
> > I don't know say which is correct, I searched and almost all of the sites don't says the same thing about valid bitcoin address
> 
> Yeah, pretty much all websites say different things about the max and min lengths of bitcoin addresses.

Yep. We should keep how many to min and max? Because, basically this is the diffeference of validatorjs

**Comment by import-brain** [comment]
> > > I don't know say which is correct, I searched and almost all of the sites don't says the same thing about valid bitcoin address
> > 
> > 
> > Yeah, pretty much all websites say different things about the max and min lengths of bitcoin addresses.
> 
> Yep. We should keep how many to min and max? Because, basically this is the diffeference of validatorjs

It's really confusing. At the top of [the Bitcoin wiki page on addresses](https://en.bitcoinwiki.org/wiki/Bitcoin_address), it says that Bitcoin addresses contain "27-34 alphanumeric Latin characters (except 0, O, I)". However, further down the same page, it says "Some Bitcoin addresses can be shorter than 34 characters (as few as 26) and still be valid".

**Comment by Minozzzi** [comment]
Maybe needs decision :thinking:

**Comment by ST-DDT** [comment]
**Team decision**

- We will use validatorJs for validation and will pass that library (or any other well known validation library).

**Comment by Minozzzi** [comment]
PR: #1375
