### ISSUE TITLE
chore: determine the purpose and usage of various test helpers

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#119]
```
test/support/chai.js 
test/support/function-helpers.js 
test/support/luhnCheck.js 
test/support/sinon-1.5.2.js 
test/support/walk_dir.js 
```

Are a few files in the codebase that I haven't reviewed, but I think are worth investigating whether they can be replaced with::

1. A more modern tool
2. A dev dep

**Comment by tmilewski** [comment]
Having looked through some of this...

`test/support/walk_dir.js` - Used by `test/run.js` which, as far as I can tell, itself is unused.

`test/support/chai.js` & `test/support/sinon-1.5.2.js` - Both are used by `test/browser.unit.html` which fails hard on the `main` branch. Seems pointless to touch that file given the sheer number of updates that are going in.

`test/support/luhnCheck.js` - looks to be valid

`test/support/function-helpers.js` - TBD amidst the changes.

**Comment by Shinigami92** [comment]
As a note for later readers:

- We migrated the `luhnCheck` to TypeScript
- We embedded some of the stuff of `function-helpers` in the dependen test file iteself
- We could happily get rid of the other files while migrating to vitest :partying_face: These were mostly just embedded dependencies or gulp related files
