### ISSUE TITLE
Random build pipeline error

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#1193]
### Describe the bug

A pipeline error seems to occur randomly.

The error states the following:

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Image > dataUri
Test Files  1 failed | 32 passed (33)
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

The module and function name at the end of the first line seems to be random as well.

I'm not able to reproduce this on my locale machine and according to @ST-DDT ([comment ref](https://github.com/faker-js/faker/pull/1174#issuecomment-1195105487)) they struggle with a  consistent reproduction as well.

### Reproduction

References to failed actions:
- [7517547166](https://github.com/faker-js/faker/runs/7517547166?check_suite_focus=true)
- [7524579587](https://github.com/faker-js/faker/runs/7524579587?check_suite_focus=true)
- [7523926505](https://github.com/faker-js/faker/runs/7523926505?check_suite_focus=true)
- [7569062123](https://github.com/faker-js/faker/runs/7569062123?check_suite_focus=true)

### Additional Info

This error always occurs in the job `Build & Unit Test: node-18, macos-latest`.

**Comment by xDivisionByZerox** [comment]
Do we not have a label for `ci`? Thats disappointing.

**Comment by import-brain** [comment]
> Do we not have a label for `ci`? Thats disappointing 😞.

We should definitely add one.

**Comment by Shinigami92** [comment]
This issue seems to vanished magically, maybe there was a vitest issue that caused it
I will close it for now and we can reopen if needed
