### ISSUE TITLE
Version 7.3.0: faker.name.fullName is not a function

### ISSUE THREAD

**Issue by jonathanlinat** [faker-js/faker#1208]
### Describe the bug

When I try to use `faker.name.fullName()`, my app crashes because that particular function doesn't exist.

![image](https://user-images.githubusercontent.com/14064112/181847734-c708d634-ae32-4906-a691-4b8ea45af68f.png)

![image](https://user-images.githubusercontent.com/14064112/181847412-fc00bc7c-5339-4aa7-b072-feb77c733a56.png)

### Reproduction

- Install `@faker-js/faker` version `7.3.0` using the command `npm install -D @faker-js/faker@7.3.0`
- Import the library: `const { faker } = require('@faker-js/faker')`
- Make use of `faker.name.fullName()` function

### Additional Info

The function is not present in the compiled bundle somehow..?

![image](https://user-images.githubusercontent.com/14064112/181847961-f19fe82a-b73b-46dc-ba10-066aa217a502.png)

The documentation has a reference to that particular function: https://fakerjs.dev/api/name.html#fullName

The source code also has a reference to it: https://github.com/faker-js/faker/blob/main/src/modules/name/index.ts#L184

**Comment by xDivisionByZerox** [comment]
I'm very sure this feature is not released yet. `faker.name.findName()` was renamed to `faker.name.fullName` in #1127 on the 19th of this month. But faker v7.3.0 was released on the 18th. So I'm there sure this feature didn't make it, but will be released in v7.4.

For now you can still use `faker.name.findName()`, should be the same implementation.

**Comment by jonathanlinat** [comment]
Perfect. Thanks.

**Comment by xDivisionByZerox** [comment]
May I ask: How did you get to know of `fullName()`? Was your IDE suggesting it via autocomplete?

**Comment by xDivisionByZerox** [comment]
>The [current documentation](https://fakerjs.dev/api/name.html#fullName) references that specific function.

Oh wow. Thank you, I will discuss this with the maintainers/members to pinpoint the problem.

**Comment by jonathanlinat** [comment]
You're welcome. 👍🏻

**Comment by xDivisionByZerox** [comment]
I will close this due to the circumstances. If you (or any other person) are against that, feel free to reopen.

**Comment by astanciu** [comment]
Ran into the same issue. faker.company.name is another example
