### ISSUE TITLE
Simplify `address.direction`

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#1228]
### Clear and concise description of the problem

There are 3 separate functions now `direction`, `cardinalDirection` and `ordinalDirection`, which is not convenience to use. Also they depend on specific order of localisation, which is hard to verify when reviewing PR.

### Suggested solution

Should we change the definition to look more like:

```js
interface Directions {
  cardinal: string[]
  ordinal: string[] // or intercardinal ?
  secondaryIntercardinal?: string[]
}

type DirectionType = keyof Directions
```

And then both `directions` and `directions_abbr` should use this type?

Additionally, I think it makes sense to simplify the usage and change `direction` signature to:

```js
direction ({ abbr: boolean, type: DirectionType, types: DirectionType[]})

// @examples
faker.address.direction() // 'north'
faker.address.direction({ abbr: true }) // 'N'
faker.address.direction({ type: 'ordinal' }) // 'north west'
faker.address.direction({ abbr: true, type: 'ordinal' }) // 'NW'
faker.address.direction({ abbr: true, types: ['ordinal', 'secondaryIntercardinal']  }) // 'NNW'
```

And then deprecate the other methods?

### Alternative

We might also skip `secondaryIntercardinal`...

**Comment by Shinigami92** [comment]
The proposed signature confuses me a bit:
e.g. what will happen if you call `faker.address.direction({ abbr: true, type: 'cardinal', types: ['ordinal']  })`
I as a user calling this or reading this code would be totally confused what it could return

**Comment by pkuczynski** [comment]
Yeah, good point! How about `direction ({ abbr: boolean, types: DirectionType[] })`?

**Comment by Shinigami92** [comment]
Both are better, lets discuss more on team meeting
But second proposed is also dangerous as you can call `direction ({ type: ['ordinal'], except: ['ordinal'] })` and we would need to throw an error

**Comment by ST-DDT** [comment]
**Team decision**

Refactor our locales to match these:

````ts
interface Directions {
  cardinal: string[]
  ordinal: string[]
}
````

Merge the directions functions into a single method:

````ts
direction ({ abbr?: boolean = false, type?: DirectionType | DirectionType[] = ['cardinal', 'ordinal'] })
````

Throw if `type` is an empty array.

**Comment by wael-fadlallah** [comment]
Hello, I can take care of this one, please assign it to me

**Comment by pkuczynski** [comment]
We already discussed this with @hankucz and she will look at it. Thank you @wael-fadlallah

**Comment by hankucz** [comment]
Yeah, I'm already looking into it

**Comment by xDivisionByZerox** [comment]
I'm closing this as #2476 provides the suggested change. If you think this is a mistake, please reopen the issue or create a new one with additional, related information.

- #2476
