### ISSUE TITLE
Fix the site description and meta tags for fakerjs.dev

### ISSUE THREAD

**Issue by JessicaSachs** [faker-js/faker#123]
### Describe the bug

When you link https://fakerjs.dev in chats like Discord or on Twitter, it won't render any rich preview or site description.

### Reproduction

<img width="387" alt="Screen Shot 2022-01-13 at 3 19 22 AM" src="https://user-images.githubusercontent.com/2801156/149292241-0e9677d7-f082-4250-9cdb-9611aa61b6ed.png">

### Additional Info

The rich preview currently has no creative to show. This is okay. Please use a placeholder image (any placeholder image). Maybe an abstract geometric background :-)

**Comment by imrishabh18** [comment]
I would like to take this issue up. Can you tell what should be the description to be used for the meta tag?

**Comment by seanCodes** [comment]
Looks like the SSL cert is also expired or invalid. Not sure if it’s related.

**Comment by JessicaSachs** [comment]
May not have propagated for you yet
<img width="700" alt="Screen Shot 2022-01-13 at 5 55 50 PM" src="https://user-images.githubusercontent.com/2801156/149421843-5128a564-2ca4-470f-87f3-4b418c938c2d.png">

**Comment by JessicaSachs** [comment]
> I would like to take this issue up. Can you tell what should be the description to be used for the meta tag?

Absolutely. Let's start with the tagline:

"Generate massive amounts of fake JSON data in the browser or node for testing and development. You can mock users, mock images, mock products, and mock transactions. You can also mock filesystem paths and folders!"

**Comment by imrishabh18** [comment]
@JessicaSachs Just to confirm that the meta tag is to be added to the [`config.mjs`](https://github.com/faker-js/faker/blob/main/docs/.vitepress/config.mjs#L101) file, right?
