### ISSUE TITLE
Sanitize html in docs

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1236]
https://github.com/faker-js/faker/blob/51a88634092dbe17985e434572385af4e99d1022/scripts/apidoc/signature.ts#L65

**Comment by import-brain** [comment]
Could we use [this package](https://www.npmjs.com/package/sanitize-html)?

**Comment by ST-DDT** [comment]
This is literally what we have used before:
https://github.com/faker-js/faker/blob/51a88634092dbe17985e434572385af4e99d1022/scripts/apidoc/signature.ts#L65-L76

**Comment by import-brain** [comment]
> This is literally what we have used before:
> 
> https://github.com/faker-js/faker/blob/51a88634092dbe17985e434572385af4e99d1022/scripts/apidoc/signature.ts#L65-L76

My bad, I skipped over the commented block. I just tried uncommenting the sanitizing code and the options object, but the test fails.

**Comment by xDivisionByZerox** [comment]
Sorry, I don't understand this issue. Could you give an example of where XSS would be possible? As far as I can tell only intern source code is used in the parsing process.

**Comment by ST-DDT** [comment]
This is an optional safeguard against issues in our jsdocs examples -> api docs (review) process.
The examples should stay exactly that: textual examples.
