### ISSUE TITLE
Use wrapped functions instead of classes for modules

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1250]
### Clear and concise description of the problem

Currently we need to bind `this` in the constructor of each module to support stuff like
```ts
const color = faker.color
color.rgb()
// and
const rgb = faker.color.rgb
rgb()
```

### Suggested solution

Instead of using js classes we could instead use wrapped functions like e.g. composables are working in Vue / VueUse

### Additional context

This might be a breaking change as with that you would not create a new class via `new Faker(...)` anymore
Also we need to benchmark if there would be performance regressions or benefits :thinking: 

I would like to setup a PR if this proposal gets accepted by the team

**Comment by ST-DDT** [comment]
**Team Decision**

We will think about this again when we actually start the tree shaking.

**Comment by ST-DDT** [comment]
I wrote a proposal for a design for this one in #2667 (because it is quite long)

- #2667

**Comment by ST-DDT** [comment]
Superseded by #2667

- #2667
