### ISSUE TITLE
Show right sidebar table of content for API Modules in documentation

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1262]
VitePress now support to show a sidebar on the right side that contains the table of content of the page.
We want to have this for our API Modules.
The old manually created TOC should be removed.

**Comment by Shinigami92** [comment]
I experimented a bit and found out that VitePress takes all the markdown h2 `##` elements of the page and count them as section titles and add these to the righthand sidebar.
Currently we are generating all sections via an embedded component that then uses `<h2>` tags.
VitePress currently cannot take these into account (pls subscribe to https://github.com/vuejs/vitepress/issues/785) and additionally we have to `anchor` links added to these h2 tags (which results in worse UX) 😬

So I see two ways of solving the problem:

1. Instead of using an embedded component we could just write the generated content into the markdown file directly and let VitePress do its job

2. Try to push @brc-dd, throw money at him 💸 and/or help him with PRs

**Comment by brc-dd** [comment]
Hi! I'll take a look on this today. Most probably, we will have to make the outline component ClientOnly.

**Comment by Shinigami92** [comment]
> Hi! I'll take a look on this today (or by Monday). Most probably, we will have to make the outline component ClientOnly.

My current attempt of hacking stuff

```ts
onMounted(() => {
  const asideRoot = document.querySelector('.aside ul.root') // Does not exist if not one static `##` exist

  for (const method of methods.value) {
    const li = document.createElement('li');
    li.setAttribute('data-v-32943baf', ''); // This is not possible to do outside of VitePress I assume
  
    li.innerHTML = `<a class="outline-link" href="#${method.name}" data-v-32943baf>${method.name}</a>
    <!--v-if-->`;
  
    asideRoot.appendChild(li)
  }
});
```

Maybe it helps in any kind of way 🤷 
But `active` class doesn't work on these post added links
