### ISSUE TITLE
Reduce dependency update PRs to once a week

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1275]
### Clear and concise description of the problem

Currently we are spammed by dependency update PRs that mostly add noise to the commit history.

### Suggested solution

Change the daily check to weekly. 
I prefer early Monday mornings for this, so we have enough time to review and merge them before our usual releases on some Mondays.

### Alternative

Switch to an on demand update check.

**Comment by import-brain** [comment]
I agree with switching the daily check to weekly, it gets tedious having to sift through all of the dependency PRs.

**Comment by Shinigami92** [comment]
For a written down comment: I tend to say yes, but => next Team Meeting

**Comment by xDivisionByZerox** [comment]
This has been fixed in #1302
