### ISSUE TITLE
Use word methods in `random.word()`

### ISSUE THREAD

**Issue by griest024** [faker-js/faker#129]
### Clear and concise description of the problem

As a developer, I want `random.word()` to draw from the entire pool of appropriate words.

### Suggested solution

Add the word methods (`word.noun`, `word.verb`, etc.) to the pool from which `random.word()` pulls.

https://github.com/faker-js/faker/blob/9506122a7725d9919e5a5c6ba036484cb608cd83/lib/random.js#L150-L182

### Alternative

These words might be transitively included via some other method, I'm not sure.

**Comment by Shinigami92** [comment]
Is this related to #276 ?
