### ISSUE TITLE
the output URL of `faker.image.avatar()` is not working.

### ISSUE THREAD

**Issue by y-okamoto-1113** [faker-js/faker#1292]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

If it's not a bug and I'm wrong, I apologize. 🙇 

The output URL of `faker.image.avatar()` is not working.
According to the following document, `faker.image.avatar()` returns a URL containing `cloudflare-ipfs.com` domain.
https://fakerjs.dev/api/image.html#avatar

But the fact is different.
It returns a URL containing `s3.amazonaws.com` domain, and this url doesn't return an image.

### Minimal reproduction code

The evidence is below.

https://user-images.githubusercontent.com/40970030/185805437-918ac542-ff79-4e1d-87b0-90ee487f058d.mov

1. Install [console importer](https://github.com/pd4d10/console-importer) in your browser
2. open `console` Tab on Browser Dev Tools.
3. run `$i('Faker')`
4. run `faker.image.avatar()`
5. click the URL

### Environment Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.41 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 98.0.1
    Safari: 15.6
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
You are using the wrong package.
Our package is: `@faker-js/faker` and our latest version is v7.4.0.
In the video you are using:
![grafik](https://user-images.githubusercontent.com/1579362/185808576-a7ca922d-bb45-446c-a518-4046b6d1b622.png)
Faker v3.1.0

Which might be a legacy version of the original faker. v3 (and everything prior to v6) is no longer maintained.
Please update to the current package/version.
