### ISSUE TITLE
Remove mime-db and use a small common set of mime-types

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1317]
### Clear and concise description of the problem

The mime-db is very large and most of the extensions are never used by anyone.

Also, not all mime-db entries pass the [validator.js#isMimeType](https://github.com/validatorjs/validator.js/blob/master/src/lib/isMimeType.js#L37) check.

![grafik](https://user-images.githubusercontent.com/1579362/187230860-63efea1b-b7c8-4f31-a670-5cd187366753.png)

### Suggested solution

Replace mime-db with a custom/common/useful set of mime types

### Alternative

Filter all mime-db entries to ensure they satisfy the [validator.js#isMimeType](https://github.com/validatorjs/validator.js/blob/master/src/lib/isMimeType.js#L37) check.

**Comment by ST-DDT** [comment]
I'll mark this as bug, because this causes some of our tests to fail, if we change their order.

**Comment by ST-DDT** [comment]
**Team decision**

We will limit mime-db to 10-50 common mime types and drop all other.

**Comment by xDivisionByZerox** [comment]
I'll deal with this.
