### ISSUE TITLE
Document how you can find data / how faker is modularized

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1323]
Add a section for how faker is modularized and how you can find for what you are searching for
This should also provide a link to the API-Search Index Page

**Comment by ST-DDT** [comment]
> Add a section for how faker is modularized

Could you explain a bit what you are referring to?
We have the modules, but these are already documented in the API and TS.

**Comment by Shinigami92** [comment]
A human readable introduction about how faker is build and design, for example that there are namespaces and you cannot just use e.g. `faker.randomInt()` but you need to know that it is foundable in the datatype/number module
Also e.g. what the helpers module is for
And generally stuff like this, but on one page summarized

**Comment by ST-DDT** [comment]
Sounds useful, but not sure how much this accounts for. So probably something for the usage section.

**Comment by ST-DDT** [comment]
@Shinigami92 Could you please produce a rough outline of what you are asking for here?
Then I can convert it into an actual thing.

@xDivisionByZerox Are you still interested in pushing this?

**Comment by Shinigami92** [comment]
So when you visit https://fakerjs.dev/ the first thing you click on is "Get Started"
So you land on https://fakerjs.dev/guide/
This should either be above "Environments" or between "Installation" and "Community"
There should be a section about how Faker is structured, maybe just 1 or 2 sections and an example of modules. Or maybe even an image? graphviz? 🤔

**Comment by ST-DDT** [comment]
Could you please explain your concept in more detail? Its okay to use ai generated image placeholders.
But for the rough concept of the page and why you want to explain them.
How would that explanation help/What would be the benefit of the page over our current api search page?

**Comment by Shinigami92** [comment]
As talked in voice chat: we could write a bit about helpers and some "easy"/"simple" modules and the "advanced" modules
easy=string,number,...
advanced=location,person,...

This all aims for users that are new to Faker and don't have the immediate intend to know that there is an api-search in the upper right corner. It aims for users that needs a flow-guide to the next steps.
