### ISSUE TITLE
Add a documentation page for how to use faker to create own crafted objects

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1325]
We would like to have a separate page in the docs that provides examples how faker can be used to craft custom objects
We already have such an example in our README.md so the contributor of this issue can orientate on that

**Comment by ST-DDT** [comment]
Maybe in a subsection of the Usage-Page.

**Comment by Shinigami92** [comment]
See https://github.com/faker-js/faker/issues/1324#issuecomment-1235755109

**Comment by 1LISA2** [comment]
![下载 (5)](https://user-images.githubusercontent.com/103248540/188253938-e2e540fe-eefc-472b-9347-ab47d466a8a2.jpeg)
![下载 (4)](https://user-images.githubusercontent.com/103248540/188253941-181a9978-2de9-41a7-a7bb-b9b3cc4eb805.jpeg)
