### ISSUE TITLE
Improve default seed initialization

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1333]
To avoid issues like this https://github.com/faker-js/faker/issues/1324#issuecomment-1236897601 where the faker instance is initialized by multiple threads in parallel (thus using the same timestamp in the seed)

https://github.com/faker-js/faker/blob/cc18b22e61fdfcd75db5196433931f00810393c5/src/modules/mersenne/index.ts#L11

The seed initialization should either take a more precise time source or add a random element (in the hope that this returns a different value per thread).

**Comment by Shinigami92** [comment]
So like in https://github.com/faker-js/faker/blob/cc18b22e61fdfcd75db5196433931f00810393c5/src/faker.ts#L243 we could replace it with `Math.ceil(Math.random() * Number.MAX_SAFE_INTEGER)`

**Comment by shraddhafalane** [comment]
Would like to work on it

**Comment by Shinigami92** [comment]
> Would like to work on it

@shraddhafalane Go for it
