### ISSUE TITLE
Rename Address module to Location

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1344]
### Clear and concise description of the problem

The address module contains more than just addresses.

### Suggested solution

* Rename the module to Location so it is clear that this contains also general location related methods.
* The Address module is degraded to an alias for two major versions

**Comment by ST-DDT** [comment]
See also #805

**Comment by ST-DDT** [comment]
Blocked by #932 / #1291

**Comment by ST-DDT** [comment]
Blocked by #1345

**Comment by Shinigami92** [comment]
I'm interested in being the champion of this (creating the PR when it's ready to start it)
