### ISSUE TITLE
Mark Mersenne module as internal and hide it from ts and the api-docs

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1348]
### Clear and concise description of the problem

The mersenne module is an internal module that should be called by external users/libraries.

### Suggested solution

- Mark the mersenne module as internal
- Hide the field references/mark them as internal or private
- Hide the Mersenne module from the api-docs

### Alternative

- Remove the mersenne module/merge it with the main Faker class

**Comment by ST-DDT** [comment]
Blocked by #932 / #1291

**Comment by Shinigami92** [comment]
Blocked by
- #1440
