### ISSUE TITLE
en_IND locale should be en_IN

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1354]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

All other locales use a two letter ISO code for country?

As this would be a breaking change probably en_IND should alias to en_IN

### Minimal reproduction code

```
> faker.locale="en_IN";

Uncaught:
n [Error]: Locale en_IN is not supported. You might want to add the requested locale first to `faker.locales`.
```

```
> faker.locale="en_IND";
'en_IND'
> faker.name.firstName()
'Devi'
```

### Environment Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 43.14 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 91.0.2
    Safari: 15.5
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by wael-fadlallah** [comment]
I'm happy to do this one, assign it to me if possible

**Comment by Shinigami92** [comment]
Hi @wael-fadlallah we released the final v7 and now going into development for v8
Please create a PR with this change, so that we can review and merge it
