### ISSUE TITLE
Blockchain wallet address

### ISSUE THREAD

**Issue by fandrupaw** [faker-js/faker#1391]
### Clear and concise description of the problem

would be nice to add blockchain wallet address generator

### Suggested solution

wallet address generator

**Comment by Shinigami92** [comment]
Is this related with 

https://github.com/faker-js/faker/blob/05aa9697707fb1f0e7981a2f93db631023042bd3/src/modules/finance/index.ts#L233

Or is it something separat? (_I'm personally not that deep into crypto currency_)

**Comment by fandrupaw** [comment]
yes, exactly what I need! Sorry, I missed that

**Comment by Shinigami92** [comment]
You can search for some terms on our API-Search site: https://fakerjs.dev/api/

Feel free to suggest some additions. Maybe you just searched for `wallet` 🤔
