### ISSUE TITLE
Rewrite in typescript and emit usable types

### ISSUE THREAD

**Issue by griest024** [faker-js/faker#14]

**Comment by ericjeker** [comment]
Not sure if this is a duplicate: https://github.com/faker-js/faker.js/issues/9

**Comment by damienwebdev** [comment]
I don't think this is a duplicate. There will be some period of time between `@faker-js/faker` v6 with Definitely typed and `@faker-js/faker` some future version where the codebase itself emits the types.

I think we keep this issue to track the future rewrite in typescript.

**Comment by damienwebdev** [comment]
Closing as this is merged and released as `6.0.0-alpha.3`
