### ISSUE TITLE
Update MIT license holder

### ISSUE THREAD

**Issue by KubaJastrz** [faker-js/faker#142]
I know almost nothing about legalities, but it looks like Marak Squires still holds the copyright rights to the forked code, according to the `MIT-LICENSE.txt`

https://github.com/faker-js/faker/blob/9506122a7725d9919e5a5c6ba036484cb608cd83/MIT-LICENSE.txt#L1-L3

**Comment by Shinigami92** [comment]
Thanks for notifying us, but we are aware of that.
We have plans to create a `LICENSE` file

**Comment by jcubic** [comment]
You can't remove the copyright from him, AFAIK, you can only add additional copyright on top.

**Comment by damienwebdev** [comment]
@jcubic this is correct. We'll be sure to keep the license consistent with the requirements of the MIT license.

**Comment by tonyqus** [comment]
@KubaJastrz  May I ask why do you wanna remove the original author? 

If you create a project with a few years efforts and it gets famous, will you wanna some other maintainer to remove you?
