### ISSUE TITLE
Add nanoid for uuid alternatives

### ISSUE THREAD

**Issue by fzn0x** [faker-js/faker#1426]
### Clear and concise description of the problem

nanoid is a great alternative for uuid, it is had less complexity and size.

it is commonly used for blog post unique urls.

### Suggested solution

Add nanoid, the logic should based on https://github.com/ai/nanoid

### Alternative

No alternative for https://github.com/ai/nanoid

**Comment by import-brain** [comment]
I would be for this, seems like a good feature to have.

**Comment by ST-DDT** [comment]
Blocked till the string module is introduced and the major shuffle for v8 is completed.
