### ISSUE TITLE
Set lint warnings to error

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1431]
### Clear and concise description of the problem

We previously fixed all lint warnings in our code, then we accidentally introduced a lint "warning" to our code.

### Suggested solution

Set lint levels to error, so that the build pipeline fails, if these things are added.

### Alternative

Manually check for lint warnings in each PR.

**Comment by xDivisionByZerox** [comment]
I like the idea. We have these rules for a reason, no reason to allow bypassing them.
