### ISSUE TITLE
Add global locale

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1441]
We want to move global locale data out of locale definitions to their related modules.
These data are the same for every language and therefore doesn't need to exist in locale `en` or be override-able by any other locale.

Example: mime-types, emojis, ...

**Comment by ST-DDT** [comment]
I think we should rather introduce a `global` locale.
Like any of our other data there is no reason why we shouldn't make them replaceable.

**Comment by Shinigami92** [comment]
As it doesn't make a difference if we put them in global locale or in the source directly, I'm fine with that, esm/cjs would duplicate them any way
We can only get rid of this duplication in the long run by getting rid of cjs in total :shrug: 

So yes, lets do it that way :+1:
