### ISSUE TITLE
Move internal code to own files

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1442]
We have code that are not exported as they are e.g. just utility functions that are not based on the faker seed.
These should be moved to separate files inside their modules or moved into a common folder if they are used by multiple modules.

For some code we even might need to flag them with the JSDoc tag `@internal` so no `.d.ts` files will be generated for them.

**Comment by ST-DDT** [comment]
Superseded by:

- remove unique
- #1118 / tree shaking refactoring
