### ISSUE TITLE
Introduce fakeArrayElement helpers

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1446]
### Clear and concise description of the problem

In a lot of places we have a list of patterns in our locales that should be processed by `fake()`.

So the code usually looks like this:

````ts
const patterns = faker.definitions.address.city;
const pattern = faker.helper.arrayElement(patterns);
return faker.helper.fake(pattern);
````

### Suggested solution

Add a new method that combines these two method calls into a single call:

````ts
return faker.helpers.fakeArrayElement( faker.definitions.address.city );
````

### Alternative

Change the `fake()` method to take both a `string` and `string[]` and if it is an array call `arrayElement` on the array before starting the normal procedure.

### Additional context

- [x] I'm willing to create a PR for this.

**Comment by ST-DDT** [comment]
The more I think about it the more I like the alternative.

**Comment by ejcheng** [comment]
> The more I think about it the more I like the alternative.

Yeah, I also think the alternative would be better than a new method.
