### ISSUE TITLE
en_IND should be an alias for en_IN in v8

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1454]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

https://github.com/faker-js/faker/issues/1354 was fixed in https://github.com/faker-js/faker/pull/1448 where the en_IND locale was renamed to en_IN

However to avoid an unnecessary breaking change, in v8 en_IND should be kept as an alias for en_IN, emitting a warning if used, and only completely removed in v9

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 43.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 91.0.2
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by wael-fadlallah** [comment]
@matthewmayer Do you have any insight about how to accomplish this?

**Comment by Shinigami92** [comment]
I think we can just add an `if->rewrite` here:

https://github.com/faker-js/faker/blob/0f9b0c64e556349cd02d54cb78a780373b2ddb97/src/faker.ts#L53-L60

But to be fully backward compatible, we also need to allow the old locale in the `UsableLocale` TypeScript type :thinking:

**Comment by ST-DDT** [comment]
@Shinigami92 We cannot do that there, because the import has changed. And in v8 we will stop changing/addressing locales via their names/keys.

**Comment by xDivisionByZerox** [comment]
We could "add" the `en_IND` back into our system. But instead of actually implementing it could behave like a proxy to `en_IN`:
1. Import `en_IN` locale
2. call our `deprecated` function
3. Export `en_IN as en_IND`

Since JS files are simply executed on import, the `deprecared` function will be called whenever we explicitly import `en_IND`.
