### ISSUE TITLE
Add banner to next.fakerjs.dev

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1456]
### Clear and concise description of the problem

Currently is it hard to spot whether you are on a production branch or our development branch.

Alternatively

### Suggested solution

Show a banner with a hint that the users is currently viewing the development branch.

It might be useful to always show the banner if the hostname is not `fakerjs.dev`.

The banner should contain a link to the production website (https://fakerjs.dev).

### Additional context

This originally came up here: https://github.com/faker-js/faker/pull/1438#issuecomment-1279750983

**Comment by Shinigami92** [comment]
@brc-dd told me we can use `layout-top` https://vitepress.vuejs.org/guide/theme-introduction#layout-slots for that :+1: 
I can tackle this, if no one else is interested in this. But first I would like to get some other of my PRs in a review-able state or even merged, so I don't have too many branches open from my site.
