### ISSUE TITLE
Rename `bannedChars` and `bannedDigits` in string module

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1465]
Extracted out of https://github.com/faker-js/faker/pull/1155#discussion_r922645362

The parameter names `bannedChars` and `bannedDigits` could be unified to e.g.:
- except
- without
- exclude

This needs to be done in v8.0 so we do not make breaking changes later on

**Comment by ST-DDT** [comment]
**Team decision**

- `exclude`

**Comment by ejcheng** [comment]
I can take this one

**Comment by matthewmayer** [comment]
as this is a breaking change should also be added to the migration guide #1518
