### ISSUE TITLE
Improve readability of `string.uuid`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1466]
Extracted from https://github.com/faker-js/faker/pull/1155#discussion_r967532808

In the string module's uuid method we have a code snippet using bit operations

```ts
const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
```

We want to get rid of these as they are hard to understand
This might result in a deterministic generated value change, but that's okay

**Comment by ST-DDT** [comment]
This probably sets the "version" of the uuid to v4.
https://github.com/uuidjs/uuid/blob/main/src/v4.js#L16

> We want to get rid of these as they are hard to understand

If we add a comment, then it should be fine.

**Comment by Kcops11** [comment]
Can I be assigned to this?
