### ISSUE TITLE
New method: `string.special`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1467]
### Clear and concise description of the problem

Extracted from https://github.com/faker-js/faker/pull/1155#issuecomment-1242676992

### Suggested solution

Add a `string.special` method that returns only special characters

**Comment by Minozzzi** [comment]
Could I work on it?

**Comment by ST-DDT** [comment]
Sure, but please wait till the string module PR is merged.

**Comment by Shinigami92** [comment]
@Minozzzi you can start

**Comment by notbrayton** [comment]
Hi, it seems like there has not been much action on this issue in a while. If that is the case, I would love the opportunity to tackle this issue.

**Comment by Minozzzi** [comment]
You can go ahead, it's really hard for me to make time for this :c
