### ISSUE TITLE
add options to faker.internet.url()

### ISSUE THREAD

**Issue by Vslava** [faker-js/faker#1474]
### Clear and concise description of the problem

faker.internet.url() produces URLs in `http://www.url.com` format (format 1).
There isn't any slash in the end of this URL. If I invoke `new URL('http://www.url.com').toString()`,
I'll get URL `http://www.url.com/` (format 2). A problem is that I use `https://github.com/Urigo/graphql-scalars`
and GraphQLURL resolver transforms URL from format 1 to format 2 by using `new URL()`.
It is a problem to compare format 1 with format 2 after I get a response from the GraphQL server.

### Suggested solution

I think that it needs to implement an argument in faker.internet.url() to generate URLs of format 1 or 2.
Maybe it is necessary to create a common config where we can set common arguments for methods
which will be used when the methods are invoked without any argument.

**Comment by Shinigami92** [comment]
I think we can introduce an option that will be default to `faker.datatype.boolean()` :thinking: 
But havn't thought deeply about that, might discuss with other members.

**Comment by Vslava** [comment]
@Shinigami92 Thank you for your answer but I wrote about `faker.internet.url()`. Are both `faker.datatype.boolean()` and `faker.internet.url()` connected?

**Comment by ST-DDT** [comment]
> @Shinigami92 Thank you for your answer but I wrote about `faker.internet.url()`. Are both `faker.datatype.boolean()` and `faker.internet.url()` connected?

I think @Shinigami92 is referring to a potentially new parameter:

````ts
url(appendSlash?: boolean) {
    appendSlash ??= faker.datatype.boolen();
    return 'https://' + domain() + (appendSlash ? '/' : '');
}
````

**Comment by Shinigami92** [comment]
Exactly what @ST-DDT wrote, but as option, so it's extensible in future:
```ts
url(options: { appendSlash?: boolean, schema?: 'http' | 'https', ... } = {}) {
	const {
		appendSlash = faker.datatype.boolen(),
		schema = 'http'
	} = options;
	return the rest...
}
```

**Comment by ejcheng** [comment]
I can take this

**Comment by ejcheng** [comment]
While we're adding the `appendSlash` param, should we also add a param for users to pick whether they want an `https` or `http` url?

**Comment by ST-DDT** [comment]
It probably doesn't hurt to add it. Though the default should be `https` (or a random one).
I'm not yet sure what to call the `appendSlash` option yet. Because I could imagine, that we also end up with adding `includePath`/`includeQueryParameter`/`includeFragement` (in a later PR?). So the question would then be "where"?

Please also adjust the methods docs to reflect that this method is about HTTP(s) URLs (and not FTP, ... ones). Or if it should be possible to create non http variants, then the scheme option should be a literal union.

**Comment by ejcheng** [comment]
> It probably doesn't hurt to add it. Though the default should be `https` (or a random one). I'm not yet sure what to call the `appendSlash` option yet. Because I could imagine, that we also end up with adding `includePath`/`includeQueryParameter`/`includeFragement` (in a later PR?). So the question would then be "where"?
> 
> Please also adjust the methods docs to reflect that this method is about HTTP(s) URLs (and not FTP, ... ones). Or if it should be possible to create non http variants, then the scheme option should be a literal union.

I'll put it as `appendSlash` for now, we can change the naming before we merge the PR if you want.

**Comment by Vslava** [comment]
@import-brain You forgot change the typescript type of url()

**Comment by ST-DDT** [comment]
> @import-brain You forgot change the typescript type of url()

Could you please always include some diff like examples/link so its easier to tell what you refer to exactly?
