### ISSUE TITLE
Support sub modules or not

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1475]
### Clear and concise description of the problem

Currently, we have sub modules e.g. the image providers. But they arent supported by our docs generation.

### Suggested solution

Decide whether we want sub modules or not.

If we want them, then they should be properly supported by the docs generation.
If not, we should deprecate them for removal.

### Additional context

If we are going to support them, we have to rename them, so their name can be used to automatically generate them.

E.g. `LoremImageModule` -> `faker.image.lorem`

I would take care of the docs generation changes.

**Comment by ST-DDT** [comment]
IMO it is OK to have them, maybe we should add a hint to them that these are external modules and thus may break somewhen in the future.

**Comment by Shinigami92** [comment]
I currently feel like I have much todo (in other projects), but as I want to champion the image module, I will try to first find a way of getting rid of the image providers as it is currently in v7.
If I didn't find a successful way the team accepts, then I'm going with the team and we might need to support these sub modules officially.

Linking:
- #1350

**Comment by ST-DDT** [comment]
We decide this when we need this.
