### ISSUE TITLE
@since values are wrong for faker.person.*

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1479]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

On 
https://next.fakerjs.dev/api/person.html#firstname

it lists "Available since v2.0.1" - this should be updated to "Available since v8.0.0" due to the whole module rename in #1343 

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 22.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 91.0.2
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
I have been looking at this multiple times now.
I'm still not sure about it, but I think it will be better, if we change the `@since` values accordingly.

**Comment by Shinigami92** [comment]
> I have been looking at this multiple times now. I'm still not sure about it, but I think it will be better, if we change the `@since` values accordingly.

Is it okay if we talk about this next meeting?

**Comment by ST-DDT** [comment]
**Team decision**

We should adjust the `@since` tags since the way of accessing the method has changed.
If users look at our documentation on our website they see a version and expect the method to be present in that version.

@matthewmayer Would you like to create a PR for this?

**Comment by matthewmayer** [comment]
added PR for faker.person and faker.location
