### ISSUE TITLE
docs/guide/usage.md references faker.person.findName but no such method exists in v8

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1498]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Obviously should be changed to `faker.person.fullName` 

However I think this raises a good point that its kinda annoying that faker.person.findName was removed, if someone upgrades from a `7.0 <= version < 7.4` to version 8 they have to do a double fix to get their `faker.name.findName` to be correct:

`faker.name.findName => faker.person.findName => faker.person.fullName`

Maybe it would be worth keeping faker.person.findName around for one more major version to ease upgrading?

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 46.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 91.0.2
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
We will publish an upgrade guide when releasing v8 that will list all required/recommended method changes, so I dont think it is necessary to keep it.

As for the actual bug, yes, it should be fixed.

If possible we should add a test/check to the docs/examples and deprecations.spec.ts, that ensures that docs/guide and the readme dont contain references to the deprecated `module.method`s.

Please let us know, if you are willing to tackle one or both parts.
