### ISSUE TITLE
Ecosystem>StackBlitz demo doesn't work on Chrome

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1505]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

1. Go to https://fakerjs.dev/
2. Click Ecosystem>StackBlitz
3. It goes to https://stackblitz.com/edit/faker-js-demo?file=index.ts
4. Console error
`request to https://nr.staticblitz.com/@faker-js%2ffaker failed, reason: socket hang up`

### Environment Info

```shell
n/a
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
I tested it with Firefox (W11 Desktop) and it works fine.
Which device type (desktop computer, tablet or mobile phone), OS and browser are you using?

**Comment by matthewmayer** [comment]
Chrome 106 desktop, MacOS 12.6

**Comment by ST-DDT** [comment]
@matthewmayer Thanks for your quick response.

@Shinigami92 Could you test this on your device as well? Is there anything we can do about it?
Since it is an external platform, we might be limited to bringing this to the attention of stackblitz.

**Comment by Shinigami92** [comment]
Yes, I can reproduce this on `Arch Linux x86_64 | 5.15.76-1-lts` `Chrome v107.0.5304.87`

![image](https://user-images.githubusercontent.com/7195563/198987665-98a4faff-3bf4-447e-a475-354b7144bf79.png)

Will try to update dependencies, but not sure if this is the problem.
Otherwise I know someone working at StackBlitz and will forward this to him.

**Comment by Shinigami92** [comment]
Yes... even in incognito mode with a fresh storage cache I can reproduce this.
I can also reproduce this on `MacOS Ventura 13.0` with `Chrome v107.0.5304.62`

Ping @patak-dev, send help
<img src="https://media.tenor.com/x7_sXvU2E9sAAAAd/kitties-cuteness-overload.gif" width="200px" />

**Comment by matthewmayer** [comment]
FWIW its now working again in Chrome for me.

**Comment by matthewmayer** [comment]
btw there's a couple of items in the StackBlitz demo which don't really show off best practices:

1. It's concatenating first and last name instead of using fullName
2. zh-CN is a bad choice of locale to demonstrate this, as Chinese names are written lastName-firstName with no space in between. Maybe just choose an alternative locale like French with a Western name order to demonstrate with?

**Comment by Shinigami92** [comment]
This is a Bug at StackBlitz itself, I recently had the same issue on StackBlitz but without any reference to Faker itself.
So this is not related to Faker itself.

For the comment about changing the content, please open another issue and propose something actively.
You can e.g. open a copy of the StackBlitz demo and if we like your change, we can copy and paste that over to our official demo.
