### ISSUE TITLE
How to generate unique emails

### ISSUE THREAD

**Issue by gustawdaniel** [faker-js/faker#1514]
I sometimes have error `E11000 duplicate key` because there is index on my database that require unique email.

How to force this library to generate unique values?

---

My current solution

```
faker.internet.email().replace(/@/, `${index}@`);
```

**Comment by ST-DDT** [comment]
Have a look at our documentation:
https://fakerjs.dev/api/helpers.html#unique

Does this answer your question?

**Comment by gustawdaniel** [comment]
Yes. Thank you werry much.

**Comment by klondikemarlen** [comment]
For other people, now that unique is deprecated, I usually use:
```js
email: `${faker.internet.email()}-${sequence}`,
```
e.g.
```js
Factory.define(({ sequence }) => {
  return {
    email: `${faker.internet.email()}-${sequence}`,
  }
})
```

This generates potential duplicate emails that are suffixed by an ever increasing value, so generally avoids duplication.
