### ISSUE TITLE
Transfer Faker Stackblitz Demo to Faker

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1525]
Currently the Stackblitz Demo is owned by @Shinigami92 it would be best if we transfer the demo to faker.

@Shinigami92 If you agree please add the accepted tag to this issue.

**Comment by Shinigami92** [comment]
Looks like there is the possibility to share ownership of the demo with other StackBlitz users

<img src="https://user-images.githubusercontent.com/7195563/200179944-a8aa082e-df33-42b8-9f94-36c81f9e460b.png" width="400px" />

You can give me an account name and I can add that to the list.
I would highly suggest doing it that way as then we don't need to change the links and our stats will get preserved.

<img src="https://user-images.githubusercontent.com/7195563/200180027-db0edd77-f2aa-472d-98d4-485f217aa168.png" width="300px" />

**Comment by Shinigami92** [comment]
@ST-DDT any updates for an account name?

**Comment by matthewmayer** [comment]
ref #1526

**Comment by ST-DDT** [comment]
You can only create an account from a Github person not an organization.

@Shinigami92 Please invite `ST-DDT` and `xDivisionByZerox` to the demo.

**Comment by Shinigami92** [comment]
> @Shinigami92 Please invite `ST-DDT` and `xDivisionByZerox` to the demo.

Done :heavy_check_mark:
