### ISSUE TITLE
Update Stackblitz Demo to follow best matching methods

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1526]
Originally posted here: https://github.com/faker-js/faker/issues/1505#issuecomment-1304464201

> btw there's a couple of items in the StackBlitz demo which don't really show off best practices:
>
> 1. It's concatenating first and last name instead of using fullName
> 2. zh-CN is a bad choice of locale to demonstrate this, as Chinese names are written lastName-firstName with no space in between. Maybe just choose an alternative locale like French with a Western name order to demonstrate with?

**Comment by matthewmayer** [comment]
Had a quick attempt at a nicer demo for v8, forked to:

https://stackblitz.com/edit/faker-js-demo-nbwfwq?file=index.ts

**Comment by ST-DDT** [comment]
I like it.

**Comment by matthewmayer** [comment]
@ST-DDT not urgent but probably makes sense to update this in the README with the release of v8, perhaps you would like to fork the code of my newer demo to be owned by faker-js?

**Comment by matthewmayer** [comment]
bumping this @faker-js/maintainers now v8 is stable could we move this new version to a faker-js user on StackBlitz and update in the README?

**Comment by ST-DDT** [comment]
Sorry, this was kind of forgotten. I'll try to get to it soon (I need @Shinigami92 for that).

**Comment by ST-DDT** [comment]
**Team Decision**

@xDivisionByZerox will update the demo, when @Shinigami92 gave us permissions.

**Comment by Shinigami92** [comment]
> @xDivisionByZerox will update the demo, when @Shinigami92 gave us permissions.

Permissions are now given

**Comment by matthewmayer** [comment]
@xDivisionByZerox you can copy paste from my version at https://stackblitz.com/edit/faker-js-demo-nbwfwq?file=index.ra

And also update the package.json to 8.0.2

**Comment by xDivisionByZerox** [comment]
I did update the [official Faker Demo](https://stackblitz.com/edit/faker-js-demo?file=index.ts) with the example @matthewmayer provided.
