### ISSUE TITLE
Highlighted modules on fakerjs.dev are different to README

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1532]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

From the README
- 💌 Locations - Generate valid looking Addresses, Zip Codes, Street Names, States, and Countries!
- ⏰ Time-based Data - Past, present, future, recent, soon... whenever!
- 🌏 Localization - Set a locale to generate realistic looking Names, Addresses, and Phone Numbers.
- 💸 Finance - Create stubbed out Account Details, Transactions, and Crypto Addresses.
- 👠 Products - Generate Prices, Product Names, Adjectives, and Descriptions.
- 👾 Hacker Jargon - “Try to reboot the SQL bus, maybe it will bypass the virtual application!”
- 🧍 Names - Generate virtual humans with a complete online and offline identity.
- 🔢 Numbers - Of course, we can also generate random numbers and strings.

From https://next.fakerjs.dev/

- 👠 Products - Generate Prices, Product Names, Adjectives, and Descriptions.
- 💸 Finance - Create stubbed out Account Details, Transactions, and Crypto Addresses.
-  💌 Locations - Generate valid Addresses, Zip Codes, Street Names, States, and Countries!
- 👾 Hacker Jargon - “Try to reboot the SQL bus, maybe it will bypass the virtual application!”
- ⏰ Time-based Data - Past, present, future, recent, soon... whenever!
- 🌏 Localization - Set a locale to generate realistic looking Names, Addresses, and Phone Numbers.

Seems these should be consistent? Add Names and Numbers? (And maybe Names should now be People?)

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 43.63 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 98.0
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by Shinigami92** [comment]
I will remove the `bug` label for now, as the WebSite has just space for 6 cards and this was an undocumented but intentional behavior.
But we can rethink about it.

**Comment by matthewmayer** [comment]
if limited to 6 i think people/names are more important than hacker jargon

**Comment by matthewmayer** [comment]
are you sure its limited to 6? https://vitepress.dev/reference/default-theme-home-page#features-section says "any number of features"

**Comment by Shinigami92** [comment]
I just thought so, but yes it is not hard limited, more like soft limited
like we should prevent using prime numbers as these are not divisible for responsive layouts and so a card would wrap into it's own line and so on

**Comment by ST-DDT** [comment]
@matthewmayer Is this still an issue?

**Comment by matthewmayer** [comment]
I think let's switch out the hacker jargon for person module?

**Comment by ST-DDT** [comment]
Yes. I wpuld probably also change the oder of elements.

- Person
- Location
- Date
- Finance
- Product
- Localization

Are you still interested in creating the PR?
