### ISSUE TITLE
Deprecate phone.number format parameter

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1541]
### Clear and concise description of the problem

The `format` can be used to overwrite the pattern that is used to generate the phone number.
Instead of passing it to phone.number the user should pass it directly to `helpers.replaceSymbolWithNumber` and build their own phone number method. Alternatively, they can add the format to our repository and thus provide it for everyone.

### Suggested solution

Deprecate the `format` parameter for removal.

### Alternative

- https://github.com/faker-js/faker/issues/1542

**Comment by ST-DDT** [comment]
**Team Decision**

- We don't want the format parameter.

**Comment by xDivisionByZerox** [comment]
In yesterdays meeting we completely skipped over the potential alternative you provided.
After having a look at that, I think it's a good proposal.

I just want to make clear, that I (we?) don't want the format parameter in it's current form as a custom template. Having a a format parameter which is a string union as proposed in #1542 seems fine to me.
