### ISSUE TITLE
Read-me references "Person" module

### ISSUE THREAD

**Issue by brunnerh** [faker-js/faker#1543]
In the Modules table there is this row:

<html>
<body>

Person | `faker.person.firstName()` | Cameron
-- | -- | --

</body>
</html>

Shouldn't this be the "Name" module and `faker.name.firstName()` function?

**Comment by ST-DDT** [comment]
The `next` branch is our default branch (to simplify development).

In `v8` the `name` module will be renamed to `person`, and thus the README was changed accordingly.
If you visit our current docs: https://fakerjs.dev/ or https://fakerjs.dev/api/name.html or https://github.com/faker-js/faker/tree/v7 then you will get the correct content for the latest released version.

Do you have a suggestion on how we could make this more obvious to or visitors?
Our "next" website https://next.fakerjs.dev/ has a banner for that, but unfortunately we don't have that option with github.

**Comment by brunnerh** [comment]
I guess changing the default branch would be the only option. E.g. change branches to: `..., v6, current, next`
`current` would then be the default and latest stable release (what now is `v7`). A new `v` branch would be created on major version releases.

Not sure how inconvenient that would be to manage, though.

**Comment by Shinigami92** [comment]
In some repos I saw "hints" like

> You are seeing the content of the next branch, if you want to see the vX please go to y
