### ISSUE TITLE
Add character length parameter to `lorem.text`

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1546]
### Clear and concise description of the problem

Sometimes we just want a text that has a particular length instead of conforming to arbitrary length units (lines/paragraphs).

### Suggested solution

Add length parameter to the `lorem.text` method.

`faker.lorem.text({ length: number | { min: number, max: number }})`

`faker.lorem.text({ length: 150 })`

> Nostrum nostrum aperiam vero eveniet quasi. Neque libero consequuntur molestias iste nihil corrupti ducimus suscipit. Ratione ducimus occaecati offic.

### Alternative

`faker.lorem.paragraphs(<sufficientlyLargeNumber>).substring(0, 150)`

### Additional context

Originally requested in [Discord](https://discord.com/channels/929487054990110771/929487054990110777/1040008594550161528) by kryp71c.

**Comment by ST-DDT** [comment]
Currently blocked by #1486

**Comment by mrzmyr** [comment]
@ST-DDT still blocked? #1486 seems merged

**Comment by ST-DDT** [comment]
@mrzmyr No, it is no longer blocked. Do you wish to work on this?

**Comment by mrzmyr** [comment]
@ST-DDT, nope, just wanted to ping.

**Comment by EarthyOrange** [comment]
@ST-DDT How should this be approached?

If I understood things correctly then once faker is initialized all the <name>Module classes are initialized.

To implement the `text` method, I think we will need to know the lengths of all the words declared in the required `locales` module. 

A few approaches that I can think of are:
- Since, we don't have that information available at the time of initialization we will need to compute it at run time; Perhaps when the method is called. It will be slightly slow to return on the first call but should be able to perform well in the subsequent calls.
- We change the Lorem's locales data to also hold the length of the words. I think there can be a script which calculates that and generates a new file for consumption. This would keep the first call performant but other methods will need to to be changed to accommodate this change.

**Comment by ST-DDT** [comment]
> If I understood things correctly then once faker is initialized all the Module classes are initialized.

Currently yes, this might change when we implement proper tree shaking.
Please note that the modules dont get reinitialized when the locale changes.

> To implement the `text` method, I think we will need to know the lengths of all the words declared in the required `locales` module.

I'm not sure about that. Could you please explain your idea in more detail? I think having a avg or mean length is sufficient to determine what to generate (sentence, paragraph, ...). Also I think generating that on the fly is fast enough for now.

**Comment by EarthyOrange** [comment]
Let's say we need a sentence that is exactly 150 characters long. We have a list of words of variable lengths per locale. So to generate a sentence for a locale:
 - Randomly choose a word (w1) from the list, such that w1.length < 150; Add to buffer.
 - Randomly choose a word (w2) from the list, such that w2.length < 150 - w1.length; Add to buffer.
 - And so on until we have a sentence that is exactly 150 characters long.

To be able to randomly choose a word from the list:
 - We need to group all the words in the list by their length
 - We randomly select a length followed by a random selection of word from the group of words corresponding to the length
 - We eliminate groups, from randomized selection, whose lengths don't satisfy the constraint w`N`.length < 150 - (w`1`.length + ... + w`N-1`.length)

> Please note that the modules dont get reinitialized when the locale changes.

Do we know how the APIs are generally invoked? Eg: Will the `text` method be invoked for all locales per import?
<pre>
import faker from '';

test("#1", () => { /* faker.text for en */ });
test("#2", () => { /* faker.text for de */ });
test("#3", () => { /* faker.text for es */ });
</pre>

**Comment by ST-DDT** [comment]
I think we could do that a tad more easily. We generate a paragraph/sentences until the char limit is exceeded, then excess chars are trimmed, finally the end of the sentence/paragraph is pseudo restored.

1) `Foo Bar. Foo Bar. Foo Bar.`
2) `Foo Bar. Foo Bar. Foo `
3) `Foo Bar. Foo Bar. Foo.`

**Comment by ghost** [comment]
I would like to work on this issue.

**Comment by ST-DDT** [comment]
@bmulholland If you would like to work on this, please leave a comment so we can assign the issue to you.

**Comment by bmulholland** [comment]
I'd love to, it's just not high on my priority list.

**Comment by ST-DDT** [comment]
Awesome. No hurry.
