### ISSUE TITLE
Add language

### ISSUE THREAD

**Issue by nicolasWD** [faker-js/faker#1548]
### Clear and concise description of the problem

I am looking to add random languages for a field "Spoken Languages"

### Suggested solution

Under faker.name please add language, like spoken language (e.g. English, Chinese, Spanish)

or

in faker.random.locale() you could add the option to return language name instead of the 2 letter code only

**Comment by ST-DDT** [comment]
Sounds like an interesting proposal.

Do you need a list/one of all languages in the world or one of the languages in your country/state?
Are you willing to create a PR for that?

**Comment by nicolasWD** [comment]
For the specific project I am working on, I need multiple unique world language names (e.g. English, French).

Yes, I can open a PR for this. Under which branch should I create the PR?

**Comment by nicolasWD** [comment]
Ok, please let me know of the next steps.

**Comment by ST-DDT** [comment]
This list might be a bit excessive:

- Fork Faker via the button in the top right corner
- Clone it to your computer
- Create a new branch based on `next`
- Add locale definitions in the [`location` category](https://github.com/faker-js/faker/blob/next/src/definitions/location.ts#L6)
- Create a new method in the [`location` module](https://github.com/faker-js/faker/blob/next/src/modules/location/index.ts#L6) called `language`
- Add `language` entries in the [`location` locale data](https://github.com/faker-js/faker/tree/next/src/locales/en/location).
- Write some [seeded](https://github.com/faker-js/faker/blob/next/test/location.spec.ts#L45) and [random-seeded tests](https://github.com/faker-js/faker/blob/next/test/location.spec.ts#L101).
- Update the locale tree and run the tests
- Commit, Push and Create a PR

See also here: https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md

Please let us know, if you have any questions or anything is unclear.

**Comment by nicolasWD** [comment]
Yes, I found Contributing a very nice and concise read. Will start immediately! Thank you!

**Comment by matthewmayer** [comment]
Would you expect it to return "German" or "Deutsch" in the `en` locale? Might need to split into two methods for that, or add a parameter to determine if you expect the locale name of the language.

https://en.wikipedia.org/wiki/Linguonym

**Comment by ST-DDT** [comment]
No, it will always return the name of the languages in the currently selected locale.
So in `en` it is `German` and in `de` it is `Deutsch`... 

If you want it in another locale, switch to that.

**Comment by xDivisionByZerox** [comment]
@nicolasWD Are you still working on that? Otherwise, I would label this with `help wanted` and unassign you so other people can take it.

**Comment by nicolasWD** [comment]
I did start it and was struck with some personal issues/drama. I would still be happy to continue this as it would be my first contribution here. I will let you know soon, if anything changes.

**Comment by xDivisionByZerox** [comment]
This is NOT scheduled for any specific release, so you are fine. Just wanted to know, so I can keep the tickets clean^^

**Comment by nicolasWD** [comment]
@xDivisionByZerox thank you, I appreciate it

**Comment by chrda81** [comment]
+1

**Comment by ST-DDT** [comment]
@chrda81 Please upvote the issue instead of posting `+1`.

**Comment by surisoko** [comment]
+1

**Comment by UmairJibran** [comment]
if it is still up for grabs, I would love to work on it!

**Comment by UmairJibran** [comment]
@ST-DDT  if it is still up for grabs, I would love to work on it!
