### ISSUE TITLE
Option to create random array of objects or arrays

### ISSUE THREAD

**Issue by nicolasWD** [faker-js/faker#1549]
### Clear and concise description of the problem

I need to create an array of objects with a random number of elements.

At the moment I am using Array.fill, followed by Array.map using faker.mersenne.rand to randomize the number of elements of my array.

### Suggested solution

Is there a way faker could simplify this instead ?

**Comment by ST-DDT** [comment]
This is planned as a new feature in v8: https://github.com/faker-js/faker/pull/1545 + https://github.com/faker-js/faker/pull/1486

````ts
faker.helpers.multiple(method: () => T, { count:  number | { min: number, max: number }});

faker.helpers.multiple(faker.datatype.number, { count: { min: 5, max: 10 }});
// [ 45614, 684631, 468435, 634639, 95460, 340]
faker.helpers.multiple(() => faker.datatype.number({min: 0, max: 1337}), { count: { min: 5, max: 42 }});
// [ 643, 468, 51, 10, 183, ... ]
````

Current workaround:

````ts
const length = faker.datatype.number({ min: 5, max: 10 });
return Array.from({ length }, () => 
  faker.datatype.number({min: 0, max: 1337})
);
````

**Comment by nicolasWD** [comment]
> This is planned as a new feature in v8: #1545 + #1486
> 
> ```ts
> faker.helpers.multiple(method: () => T, { count:  number | { min: number, max: number }});
> 
> faker.helpers.multiple(faker.datatype.number, { count: { min: 5, max: 10 }});
> // [ 45614, 684631, 468435, 634639, 95460, 340]
> faker.helpers.multiple(() => faker.datatype.number({min: 0, max: 1337}), { count: { min: 5, max: 42 }});
> // [ 643, 468, 51, 10, 183, ... ]
> ```
> 
> Current workaround:
> 
> ```ts
> const length = faker.datatype.number({ min: 5, max: 10 });
> return Array.from({ length }, () => 
>   faker.datatype.number({min: 0, max: 1337})
> );
> ```

Thank you, I will be waiting for the multiple method! Your workaround is much better for now!
