### ISSUE TITLE
firstName is broken in en_GH (Ghana)

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1552]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

en_GH locale returns literal  '{{person.female_first_name}}' or '{{person.male_first_name}}'

### Minimal reproduction code

```
faker.setLocale("en_GH")
faker.person.firstName() //returns '{{person.female_first_name}}' or '{{person.male_first_name}}'
```

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 44.64 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 98.0
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by wael-fadlallah** [comment]
Small correction

`faker.name.firstName() //returns '{{person.female_first_name}}' or '{{person.male_first_name}}'`

**Comment by wael-fadlallah** [comment]
Hey, I can fix this one

**Comment by ST-DDT** [comment]
FYI: This file is broken and needs to be removed/fixed: 

https://github.com/faker-js/faker/blob/801e9e0a6afa2bd472652eb7aaee5581ef458342/src/locales/en_GH/person/first_name.ts#L1
