### ISSUE TITLE
build: add src to .npmignore

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#156]
### Describe the bug

I was releasing `6.0.0-alpha.3` and I noticed that the `src` folder is in the distributable package.

### Reproduction

Run `npm pack` and review the subsequent tarball.

**Comment by Shinigami92** [comment]
Instead of using `.npmignore`, we should use `package.json`'s `files` field

**Comment by MohdImran001** [comment]
@Shinigami92 I'd like to work on it.
