### ISSUE TITLE
Rename company.suffix definition to company.legal_entity_type

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1574]
### Clear and concise description of the problem

The company suffixes currently refer to the company/business entity type (not sure about this term) and not a real suffix in the usual sense.

### Suggested solution

We should rename the `suffix` to `type` (both the definitions and method).

### Additional context

Discovered here: https://github.com/faker-js/faker/pull/1573

**Comment by ST-DDT** [comment]
Blocked by https://github.com/faker-js/faker/pull/1575

**Comment by xDivisionByZerox** [comment]
This is not blocking for `v8`. If we had found this earlier and deprecated in `v7.6` that would be something else. But in the current state, we can deprecated (and add the desired function) at any point during `v8.x`.

**Comment by xDivisionByZerox** [comment]
Regarding term: The german locale has a [legal_form](https://github.com/faker-js/faker/blob/1cadfb97856da17047fcb5dcb504c3418eeed145/src/locales/de/company/legal_form.ts) file. This could be a good name.

**Comment by matthewmayer** [comment]
The method is already deprecated. So this is just about how to name the definition file? Seems that doesn't really matter (and could even be locale dependant, for example if a locale typically has prefixes instead of suffixes for companies)

**Comment by xDivisionByZerox** [comment]
Probably also for later feature implementation. 
`company.suffix()` was simply not clear enough what its intent was. It could be implemented in a later version with a more descriptive name.
But for now only the definition file name.

These are my thoughts on this.

**Comment by matthewmayer** [comment]
FWIW Wikipedia calls these "Legal entity types" https://en.wikipedia.org/wiki/List_of_legal_entity_types_by_country

**Comment by xDivisionByZerox** [comment]
Discussion: What should the locale file be exactly renamed to? This decision should br made in a team meeting and should consider all already provided names.

**Comment by ST-DDT** [comment]
**Team Decision**

- We will rename `suffix` to `legal_entity_type`.

**Comment by ST-DDT** [comment]
This only affects the locale data/definitions -> v9.0 only.

**Comment by RacketyWater7** [comment]
I intend to take this issue as my first; but need a little heads up.

**Comment by ST-DDT** [comment]
> I intend to take this issue as my first; but need a little heads up.

Welcome to the project. What kind of heads up do you need?

**Comment by ST-DDT** [comment]
@RacketyWater7 We would like to include this in v9.0.
Do you have time to tackle this in this month?

**Comment by cakuki** [comment]
> @RacketyWater7 We would like to include this in v9.0. Do you have time to tackle this in this month?

Is there any target for v9 release?

**Comment by ST-DDT** [comment]
There is no specific target date.
We just plan to release it "soon"/after finishing the remaining tasks in our milestone:

- [Milestone v9.0](https://github.com/faker-js/faker/milestone/12)

I estimate this will take roughly a month (might be less, might be more).
