### ISSUE TITLE
Swap `allowLeadingZeros` default value to `true`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1592]
### Clear and concise description of the problem

Often we have a call like `faker.number.int(9)` and then convert it to a string

### Suggested solution

Implement a new method `faker.string.digit()` which returns a digit between `[0, 9]` and directly returns it as `string`

### Additional context

Found in
- #1122

**Comment by ejcheng** [comment]
I can take this one

**Comment by Shinigami92** [comment]
> I can take this one

Please wait until #1122 was merged

**Comment by ST-DDT** [comment]
I would rather change the spec for `string.numeric` to allow returning `'0'` when length is 1.

**Comment by Shinigami92** [comment]
Maybe lets make a benchmark of using `string.numeric({ allowLeadingZeros: true })` compared to `string.digit()` which just uses `number.int` under the hood

https://github.com/faker-js/faker/blob/6e1009ae0ab6a185eaf808e2dd4d8dcab65c79b6/src/modules/string/index.ts#L333-L388

**Comment by ST-DDT** [comment]
IMO we dont have to us a benchmark as long as it good enough. Otherwise we have to measure all our methods and reimplement them accordingly.

**Comment by Shinigami92** [comment]
> I would rather change the spec for `string.numeric` to allow returning `'0'` when length is 1.

Why do you want to confuse users with another behavior if the length input differs from one case to another case?
IMO it is a bit hard for the user to exactly know that they need to read the docs to find out that the behavior differs based of the used number passed into one and the same input parameter.

**Comment by ST-DDT** [comment]
0001 isnt a real world number, but 0 is.
IMO this doesnt even need to be mentioned in the jsdocs.

**Comment by Shinigami92** [comment]
**Team Decision:**

- Do not introduce new method digit
- Swap `allowLeadingZeros` parameter of `string.numeric` to default: true
- _clean up all out internal calls as they don't need `allowLeadingZeros` anymore
- After release, lets see if feedback from community comes back that this affected them
