### ISSUE TITLE
Refactor `number.float` parameter `precision` to `fractionDigits`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1596]
### Clear and concise description of the problem

We want to refactor the behavior of the `precision` parameter of `number.float` to be adjusted to `Number#toFixed` behavior.

This **wont** affect the _legacy_ `datatype.float` method!

### Suggested solution

- `precision` -> `fractionDigits`
- We then want to have a well defined developer experience and support steps like 0.4 and such
  So we might need an addition parameter like `step(s)` or `precision` and then talk about how this behaves
  - see #1595

### Additional context

Extracted from 
- #1122

**Comment by Shinigami92** [comment]
**Team Decision:**

We want support both parameters: `fractionDigits` and the second one
If they are incompatible throw an `FakerError`

**Comment by xDivisionByZerox** [comment]
I will take this.

**Comment by ST-DDT** [comment]
Please wait for https://github.com/faker-js/faker/pull/1675 to be merged.

**Comment by ST-DDT** [comment]
Continuation of the discussion that came up in https://github.com/faker-js/faker/pull/1855#issuecomment-1435655823

@matthewmayer suggested adding a new method for stepped values to separate it from float.

**Comment by ST-DDT** [comment]
@matthewmayer Do you have a suggestion for a method name for the new `step` method?

Maybe `faker.number.stepped`?

**Comment by ST-DDT** [comment]
**Team decision**

The proposal to move the `precision`/`step` logic into a different method has been rejected.
We will keep this `precision`/`step` option in the float method's single signature and document that the parameters are mutually exclusive.

**Comment by ST-DDT** [comment]
**Team Decision**

We don't need this for v8.0.
(We will likely immediately start with v9 after v8.0)

**Comment by ST-DDT** [comment]
Related issue: https://github.com/faker-js/faker/issues/2186

**Comment by matthewmayer** [comment]
So basically
- this would add a new parameter `fractionDigits` as an alternative to `precision`
- fractionDigits must be an integer
- if set then `precision = 10 ** -fractionDigits`

Would you allow negative fractionDigits? (`multipleOf:10` is probably clearer than `fractionDigits:-1`)

**Comment by ST-DDT** [comment]
> Would you allow negative fractionDigits? (`multipleOf:10` is probably clearer than `fractionDigits:-1`)

I'm not sure whether we should actually forbid badly readable input (unless it has other side effects).

**Comment by matthewmayer** [comment]
So probably allow between -18 and +18 (or whatever range works without issues)

**Comment by ST-DDT** [comment]
If we already have a check for the range then we can limit it to useful values. E.g. `0`-`18`
