### ISSUE TITLE
Newly deprecated methods like faker.datatype.bigInt should include a @see referencing their replacement

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1606]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Currently if you look at say https://next.fakerjs.dev/api/datatype.html#bigint you can see it's deprecated but its not clear what replaces it.

### Environment Info

```shell
n/a
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
@matthewmayer Yeah, you are right. We should also mention this in our upgrading docs.

**Comment by matthewmayer** [comment]
I feel the upgrading doc only has to mention breaking changes, not every method which is renamed

ie if faker.datatype.bigInt is deprecated in favour of faker.number.bigInt in v8 and removed in v9 then that needs to be mentioned in the v9 migration doc but is not essential in v8 migration doc.

**Comment by matthewmayer** [comment]
I noticed if you write like `@deprecated some message` then `some message` does not appear in the online docs. Perhaps that should also show in the yellow deprecation banner for more context?

**Comment by ST-DDT** [comment]
> I noticed if you write like `@deprecated some message` then `some message` does not appear in the online docs. Perhaps that should also show in the yellow deprecation banner for more context?

Good idea, I think we planned to do it at some point but forgot about it.
I created #1607 to track it.

**Comment by ST-DDT** [comment]
> I feel the upgrading doc only has to mention breaking changes, not every method which is renamed
> 
> ie if faker.datatype.bigInt is deprecated in favour of faker.number.bigInt in v8 and removed in v9 then that needs to be mentioned in the v9 migration doc but is not essential in v8 migration doc.

I'm not sure about that, IMO the introduction of the string and number modules, might be worth mentioning, since I think these methods are probably used in many applications. Maybe all, so that instead of spotting the deprecation message in the logs, you can just refer to the upgrading docs and do all of it at once. What do the others think? @faker-js/maintainers @faker-js/members

**Comment by matthewmayer** [comment]
Yeah I think major new modules can get mentioned (eg faker.person is already mentioned although it's not a breaking change)

**Comment by Shinigami92** [comment]
> What do the others think?

I'm fine with either way :shrug:, no strong opinions from my side

**Comment by matthewmayer** [comment]
Probably makes sense to break the guide into two sections, first an exhaustive list of breaking changes, and then a non-exhaustive list of deprecations and other changes.
