### ISSUE TITLE
Remove en_AU_ocker locale

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1612]
### Clear and concise description of the problem

Seems this locale was originally added as a jokey way to add Australian slang names

https://en.wikipedia.org/wiki/Ocker

`['Bazza', 'Bluey', 'Davo', 'Johno', 'Shano', 'Shazza'];`

But there's no API to access this:
https://github.com/faker-js/faker/blob/next/src/locales/en_AU_ocker/person/ocker_first_name.ts

So the only way is via `faker.helpers.fake`

> faker.setLocale("en_AU_ocker")
> faker.helpers.fake("{{person.ocker_first_name}}")
'Bluey'

This seems not worth maintaining a whole locale for, it gets in the way when trying to fix l10n bugs. Maybe remove for 8.0?

### Suggested solution

Remove en_AU_ocker

### Alternative

If there are sentimental reasons for keeping it, it could be kept (I'm not against Easter eggs per se)

**Comment by ST-DDT** [comment]
**Team Decision**

We want to keep it for now.
We might want to get rid of the ocker_first_name file though.

@matthewmayer Is that name list redundant to the first_name list? Should we merge them into one?

**Comment by matthewmayer** [comment]
i guess the first names are supposed to be supplementary to the standard first_name list? Would probably have to merge them in? They seem to be male nicknames.

I noticed https://github.com/faker-js/faker/blob/next/src/locales/en_AU_ocker/location/street_name.ts and https://github.com/faker-js/faker/blob/next/src/locales/en_AU_ocker/location/region.ts also have custom content including another joke reference https://en.wikipedia.org/wiki/Ramsay_Street

**Comment by Drnkmstr** [comment]
I put a little up on the subject, as when I'm running my units test until failure, this cause my tests to fail when I create a new CultureInfo object.
Would be great to bo able to opt out (or in) on this :)

Thanks !
