### ISSUE TITLE
Adding new feature `songName` in `faker.music`

### ISSUE THREAD

**Issue by fzn0x** [faker-js/faker#162]
### Clear and concise description of the problem

Adding new feature `songName` which is generate a random song name based on country locales, it's real song name not dummy ones.

### Suggested solution

Locales -> definitions -> data e.g https://github.com/faker-js/faker/blob/main/src/address.ts#L258 

### Additional context

This issue created for awareness if there's strategy to load locales in a more async and on-demand way.

**Comment by ST-DDT** [comment]
I think it's a good proposal. Contributions are welcome.
