### ISSUE TITLE
Add `pnpm run preflight` command

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1636]
### Clear and concise description of the problem

Currently there are many steps that should be run before committing, but have to be run manually one after the other.

- Formatting
- Linting?
- Update Test Snapshots
- Run Tests
- Generate Locales
- Generate Api-Docs

### Suggested solution

Introduce a command that runs all those commands using a single command. e.g. `pnpn run dev:complete`

**Comment by ST-DDT** [comment]
Partially blocked by: #1635

**Comment by matthewmayer** [comment]
as a relatively new contributor i would like this! Easy to forget a step

**Comment by matthewmayer** [comment]
i would vote for a catchier name though. like `pnpm run checks` or `pnpm run preflight` or `pnpm run checklist` or something like that.

**Comment by ejcheng** [comment]
> i would vote for a catchier name though. like `pnpm run checks` or `pnpm run preflight` or `pnpm run checklist` or something like that.

`preflight` sounds cool

**Comment by xDivisionByZerox** [comment]
I'll move the `needs decision` label from here into the PR #1846 itself.

**Comment by ST-DDT** [comment]
**Team Decision**

We will name this command `preflight`.

**Comment by Shinigami92** [comment]
I started to use this command and when switching branches the `pnpm install` makes now a ton of sense 👍 
I like it

I just also do `git switch X` -> `git pull --rebase` -> `pnpm run preflight`
