### ISSUE TITLE
new buzzword : Lifetime value

### ISSUE THREAD

**Issue by Busyvar** [faker-js/faker#1700]
### Clear and concise description of the problem

As mentioned in [this article](https://tech.slashdot.org/story/22/12/29/2219227/lifetime-value-is-silicon-valleys-next-buzzword) , the next buzzword in silicon valley will be "lifetime value".

### Suggested solution

I suggest to add _lifetime_ in business adjective list.

**Comment by ST-DDT** [comment]
@Busyvar If you have a small change like this, please create a PR for that immediately (instead of an issue) as it is easier to understand and review that way.

**Comment by xDivisionByZerox** [comment]
I'll consider this done since #1701 has been merged.
