### ISSUE TITLE
Generate random symbol (eg: ! _ #)

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#1711]
### Clear and concise description of the problem

Provide a method which would generate random symbol (non alphanumeric character), for example `!#_-/\.$`.

### Suggested solution

```js
faker.random.symbol() // #
```

**Comment by ST-DDT** [comment]
What is the difference to faker.string.special?
https://next.fakerjs.dev/api/string.html#special

Should we rename that method?

**Comment by pkuczynski** [comment]
No difference at all! It's actually what I was looking for, but could not find it... It's also on the `next` branch and I was looking at the stable. But yeah, I think it should be renamed to `symbol` as it is more common term... `string.special` does not sound like it generates a symbol to me... If we want to stick to `special` it should be rather `specialCharacters` but that's more in light of passwords. `symbol` seems more like a general term...

By the way, why method generating UTF-16 is called `sample`? :)

**Comment by Shinigami92** [comment]
We can rename it without making a breaking change, as the current released alpha is not intended to be "stable"

I would be ok with renaming it, but should it be symbol or symbols? it can generate more then one char 🤔

**Comment by pkuczynski** [comment]
> I would be ok with renaming it, but should it be symbol or symbols? it can generate more then one char 🤔

I was thinking the same, but if you look at `alpha` or `alphanumeric` - they also in a singular form. So I would keep it `symbol`. Especially default length is `1` (I assume)?

**Comment by pkuczynski** [comment]
I can provide a PR if everybody agrees...

**Comment by ST-DDT** [comment]
I'm fine with renaming.
How about `symbolic`? Similar to numeric?
Not sure if that conveys the correct meaning.

The jsdoc should contain both the symbol and special characters terms.

**Comment by ejcheng** [comment]
> > I would be ok with renaming it, but should it be symbol or symbols? it can generate more then one char 🤔
> 
> I was thinking the same, but if you look at `alpha` or `alphanumeric` - they also in a singular form. So I would keep it `symbol`. Especially default length is `1` (I assume)?

I would also keep it as `symbol`, considering the other methods are in singular form.

**Comment by matthewmayer** [comment]
FWIW i think the documentation should list out what "special" characters this pulls from. Only simple punctation marks? Spaces? Dingbats and emojis? Accented letters? The list seems short enough you could just list them explicitly.
```
! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
```

**Comment by xDivisionByZerox** [comment]
@pkuczynski Are you still interested in providing a PR for this Issue (or even already working on it)? Since this is blocking for v8 I'd like to not keep this around any longer.

**Comment by pkuczynski** [comment]
Go ahead. I am still tied with my personal life :(
