### ISSUE TITLE
faker.helpers.maybe doesn't always invoke callback with { probability: 1 }

### ISSUE THREAD

**Issue by NvGary** [faker-js/faker#1713]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

If you execute this block enough times you will experience an intermittent failure.
``` javascript
describe('maybe', () => {
    it('should always return the callback result when probability is 1', () => {
        const actual = faker.helpers.maybe(() => 'foo', { probability: 1 });

        expect(actual).toBe('foo');
    });
});
```

On dry reading the code this can happen when faker.datatype.float({ min: 0, max: 1}) returns 1. The subsequent 1 < 1 check fails and the callback is never executed.

### Minimal reproduction code
``` javascript
describe('maybe', () => {
    it('should always return the callback result when probability is 1', () => {
        jest.spyOn(faker.datatype, 'float').mockReturnValueOnce(1);
        const actual = faker.helpers.maybe(() => 'foo', { probability: 1 });

        expect(actual).toBe('foo');
    });
});
```

### Additional Context

A quick `1 <= 1` fix won't work as `maybe` should fail `{ probability: 0 }` and `faker.datatype.float` returning 0.

### Environment Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 772.65 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
Which version are you testing on?

https://github.com/faker-js/faker/blob/2a06b6a197d5fe6939eac05035ca8ef9a50a2e92/src/modules/helpers/index.ts#L401-L406
https://github.com/faker-js/faker/blob/2a06b6a197d5fe6939eac05035ca8ef9a50a2e92/src/modules/datatype/index.ts#L221-L224

Should catch probability == 1 and return true.

**Comment by ST-DDT** [comment]
Yes in v7.6.0 that is a bug, but we fixed it since.

Fixed in https://github.com/faker-js/faker/pull/1476

Thanks for bringing this to our attention anyway.

**Comment by NvGary** [comment]
Schoolboy error. Was working on 7.6.0. Should have checked the latest version 🤦
