### ISSUE TITLE
Lorem Ipsum for different languages

### ISSUE THREAD

**Issue by ming-codes** [faker-js/faker#1715]
### Clear and concise description of the problem

Currently faker only provide lorem for the English language. It would be great to include other languages as well to test out localized features. This is especially helpful for developers that does not know the localization language and still be able to deliver something presentable.

### Suggested solution

I think we should start with at least one East Asian language (Chinese, Korean, Japanese) and one MENA language (Arabic, Hebrew, Persian, Turkish), then expand to maybe cover Slavic languages.

The design should be extendable to allow developers to add their own language.

**Comment by ST-DDT** [comment]
🤔 

For the char = word based locales we could "reuse" the word data.

**Comment by matthewmayer** [comment]
Just to be pedantic, Lorem ipsum is not fake-English, its (poor) Latin :D So it can generally be used in any locale with a Latin alphabet.

**Comment by matthewmayer** [comment]
Note this is already implemented in certain languages e.g. Korean

https://github.com/faker-js/faker/blob/next/src/locales/ko/lorem/words.ts

```js
> faker.locale = "ko"
> faker.lorem.words()
'법률에 재외국민을 자유를'
```

**Comment by matthewmayer** [comment]
The following locales appear to have data from faker.lorem that isn't just a straight copy of the standard `en`/Latin lorem ipsum text
```
dv
en_BORK
es_MX
fa
he
hy
ja
ko
lv
ru
ur
vi
```

**Comment by ming-codes** [comment]
Oh hey, didn’t know about the locale setting. Looks like everything is there then and just need contributions for more languages 👍

**Comment by xDivisionByZerox** [comment]
It seems, that this explicit issue has been resolved. I will close this in favor of #1991.
Please feel free to reopen the issue if you think this was an error.
