### ISSUE TITLE
Better currencies

### ISSUE THREAD

**Issue by kg-currenxie** [faker-js/faker#1733]
### Clear and concise description of the problem

This will have mismatched data :)
```
supportedCurrency: {
  code: faker.finance.currencyCode(),
  name: faker.finance.currencyName()
}
```

### Suggested solution

Like `unit()`, it returns `{ name: 'meter', symbol: 'm' }`

It would be nice if `finance.currency()` returned `{ name: 'US Dollar', symbol: '$', code: 'USD' }`

**Comment by ST-DDT** [comment]
We are currently in a debate whether or not we should provide these complex objects (airport/airline...).

Could you give us an example why it is important that you get matching currency names and symbols instead of any?

Also could you think of a general rule what should be provided in these complex objects and what shouldnt?
Otherwise we might end up with something like food: ( name, description, ingredients and their amount, calories, ...)

**Comment by ST-DDT** [comment]
From the airline PR: https://github.com/faker-js/faker/pull/1699#discussion_r1070174368

> For me right now, it isn't important. So I'm good leaving the data the way it is now or splitting it up into separate airline.name: string[] and airline.iataCode: string[]` functions.

**Comment by kg-currenxie** [comment]
My use case: I'm mocking an API response, and I'd like to show currencies in my UI in a dropdown, like so `USD (Dollar)`. But I'd get `EUR (Indian Rupee)` 😂

**Comment by matthewmayer** [comment]
i think in general complex objects make sense if the objects reflect real-world things and so there's a fixed mapping between values.

For example 
```
ChemicalElement {code:"Au", name: "Gold"}
Airline {name:"British Airways", iataCode:"BA"}
Currency {code:"EUR", name:"Euro"}
```
but NOT when the values are themselves fake/arbitrary
```
Dish {name:"Fish and Chips", description: "A delicious flaky dish of cod and potatoes", calories: 1234}
Pet {name:"Fluffy", type:"Dog", color:"Black"}
```

**Comment by ejcheng** [comment]
> i think in general complex objects make sense if the objects reflect real-world things and so there's a fixed mapping between values.
> 
> For example
> 
> ```
> ChemicalElement {code:"Au", name: "Gold"}
> Airline {name:"British Airways", iataCode:"BA"}
> Currency {code:"EUR", name:"Euro"}
> ```
> 
> but NOT when the values are themselves fake/arbitrary
> 
> ```
> Dish {name:"Fish and Chips", description: "A delicious flaky dish of cod and potatoes", calories: 1234}
> Pet {name:"Fluffy", type:"Dog", color:"Black"}
> ```

This makes sense, it would be weird to create an object:

`{ name: faker.airline.airlineName(), iataCode: faker.airline.iataCode() }`

and get `{ name: "Icelandair", iataCode: "BA" }

**Comment by matthewmayer** [comment]
since the airline PR landed, and since this seems to follow the rule of thumb i wrote at https://github.com/faker-js/faker/issues/1733#issuecomment-1382657837 i went ahead and added a PR at #1809

**Comment by Shinigami92** [comment]
I'm sorry you missed https://github.com/faker-js/faker/pull/1699#issuecomment-1408734928

**Comment by matthewmayer** [comment]
Okay no worries just leave this unmerged until you make a final decision about how to handle these kind of issues.

**Comment by ST-DDT** [comment]
**Team decision**

We will support complex objects for static data (such as currency), but we won't add dynamic complex objects (such as a person{firstName, lastName}).

We have to add support for the fake method (https://github.com/faker-js/faker/issues/1850), deprecate the individual currencyName/code methods and remove datatype.object and array (Separate issues/PRs).
