### ISSUE TITLE
location.zipCodeByState should throw for unknown states

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1736]
### Clear and concise description of the problem

Currently, if the given state is not known, then a random zip code is returned.
Usually, if I pass a value to a method, then I expect it to use it and tell me if the value is wrong.

### Suggested solution

Throw if there is no data for that state.

### Alternative

Keep the method as is.

### Additional context

https://next.fakerjs.dev/api/location.html#zipcodebystate

**Comment by ST-DDT** [comment]
**Team decision**

If the user explicitly calls `zipCodeByState`, then it should make sure that the `state` is actually valid.
-> throw error if the state is unknown.

**Comment by Shinigami92** [comment]
> **Team decision**
> 
> If the user explicitly calls `zipCodeByState`, then it should make sure that the `state` is actually valid. -> throw error if the state is unknown.

Sounds legit to me :+1: 

---

I move this to v8 milestone so we do not put more and more into v8.0
It's not blocked and if someone works on it, go for it, but if not, it can be a bug-fix later in v8.x

**Comment by ST-DDT** [comment]
> I move this to v8 milestone so we do not put more and more into v8.0
> It's not blocked and if someone works on it, go for it, but if not, it can be a bug-fix later in v8.x

It would change documented api, so I consider this breaking:

> If a locale does not have a postcode_by_state definition, a random zip code is generated according to the locale's zip format.

**Comment by ST-DDT** [comment]
Pinging @0916dhkim to leave a comment hete so I can assign them to this issue for #1760 .

**Comment by 0916dhkim** [comment]
👍

**Comment by xDivisionByZerox** [comment]
If this is a breaking change, this needs to be put into the`8.0` milestone no?

**Comment by ST-DDT** [comment]
**Team Decision**

- We want to merge zipCode and zipCodeByState into a single method instead (https://github.com/faker-js/faker/issues/1346#issuecomment-1407728227)
- It will still throw an error if the state doesn't have a config.
