### ISSUE TITLE
Generated email addresses are sometimes invalid in certain locales

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1739]
### Clear and concise description of the problem

Sometimes the generated email addresses are invalid in certain locales:

- https://github.com/faker-js/faker/actions/runs/3921031720/jobs/6703049173
- https://github.com/faker-js/faker/actions/runs/3920956127/jobs/6703052613

There are actually two different errors here:

- The email address contains invalid characters
- The email address is too long

### Suggested solution

1. Replace all invalid characters
2. Limit the length of the generated e-mail address

### Additional context

(There might be a different issue with the input data as well, but the method should generate valid addresses nevertheless.)

**Comment by matthewmayer** [comment]
this is probably caused by #1554 - if there's a long unicode name, the resulting fallback string will be very long. Seems email addresses are limited to 64 chars for the local part.

**Comment by ST-DDT** [comment]
#1746 fixes part two of the problem.

**Comment by matthewmayer** [comment]
And part 1 should also be fixed for el and fa
