### ISSUE TITLE
Setup a new bundling process

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#174]
### Clear and concise description of the problem

We want to switch away from the old gulp bundling process and modernize it.
Also we want to produce `esm`, `cjs` and `umd`

### Suggested solution

Use e.g. [`rollup`](https://github.com/rollup/rollup), [`preconstruct`](https://github.com/preconstruct/preconstruct) or [`microbundle`](https://github.com/developit/microbundle)

**Comment by pkuczynski** [comment]
I can work on this. Let me know if you want me to...

**Comment by Shinigami92** [comment]
> I can work on this. Let me know if you want me to...

Sorry, I did not linked the new "already in awaiting review" PR
