### ISSUE TITLE
test/locales.spec.ts makes the tests run extremely slow

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1747]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

`pnpm run test` often fails or is extremely slow on my machine (a M1 Macbook Air). Sometimes it gets completely stuck and sometimes completes with various timeouts/failures after 20 minutes.

<img width="689" alt="Screenshot 2023-01-17 at 11 38 22" src="https://user-images.githubusercontent.com/152770/212816056-92c5e47b-b0fc-4fac-b509-3b5171696181.png">

Deleting the file test/locales.spec.ts seems to solve the problem:

```Duration  80.20s (transform 16.34s, setup 0ms, collect 170.85s, tests 126.45s)```

(i found the offending file by binary search, by deleting some of the tests and seeing what made the problem go away).

I'm not sure exactly what in that file is causing the problem

### Environment Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 48.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 98.0
    Safari: 16.1
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment]
This is kind of related to/duplicate of https://github.com/faker-js/faker/issues/1747.
Workaround: https://github.com/faker-js/faker/issues/1635#issuecomment-1377860845

If you have an idea, on how to fix the performance tests, we would appreciate the input.

**Comment by matthewmayer** [comment]
the update to vitest 0.27.3 seems to have fixed this.

```
Test Files  35 passed (35)
      Tests  42956 passed | 4034 skipped | 31 todo (47021)
   Start at  15:28:44
   Duration  44.17s (transform 5.27s, setup 3ms, collect 112.57s, tests 44.07s)
```
