### ISSUE TITLE
Add faker.helpers.objectEntry

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1764]
So we could use ObjectKeys to get a random key and then get the values for it.
Or alternatively we introduce `objectEntry` that returns `[key, value]` directly.

What do you think?

_Originally posted by @ST-DDT in https://github.com/faker-js/faker/pull/1761#discussion_r1083471463_

**Comment by ST-DDT** [comment]
**Team Decision**

We want this.

**Comment by Janaki4** [comment]
Hey , I would i like to work on this . Is this issue still open . If Yes , can you assign it to me ? Thanks

**Comment by Janaki4** [comment]
hey , I see no documents are there for setting up the enviropnment . Can you please share any document or steps to set up environment ? Thanks

**Comment by ST-DDT** [comment]
You need Git, an IDE such as VS Code, Node and pnpm.
Please search for yourself on how to download and install them.
If you are done with that you have to clone this repository and open it with your IDE.
See also: https://docs.github.com/en/get-started/exploring-projects-on-github/finding-ways-to-contribute-to-open-source-on-github

**Comment by Janaki4** [comment]
@ST-DDT , I got that. I'm trying to build the project by following the steps in CONTRIBUTION.md . (pnpm install , and pnpm run build) . But itss not helping . Project doesn't start or run . Please guide me on this.

**Comment by matthewmayer** [comment]
Please paste the full output of what you see when you type pnpm install and pnpm run build.

**Comment by Janaki4** [comment]
![Faker](https://user-images.githubusercontent.com/102728536/229339358-a459adbf-a577-4657-82be-a1a7a5a04b76.png)
@matthewmayer , Nothing runs or start when i run these commands. FYI : I'm using windows.

**Comment by ST-DDT** [comment]
Nothing is supposed to run as this is a library.
Is there anything that lead you to this assumption that we can improve?

You just have to add the method implementation and tests for this feature.
We also have a playground repository that you can use to test the code yourself via pnpm dependency overwrite linking to your local fork.

**Comment by matthewmayer** [comment]
> ![Faker](https://user-images.githubusercontent.com/102728536/229339358-a459adbf-a577-4657-82be-a1a7a5a04b76.png)
> 
> @matthewmayer , Nothing runs or start when i run these commands. FYI : I'm using windows.

It seems to be working fine. 

You would then need to make changes to the code for example to add the new objectEntry method

When you have finished run `pnpm run build` again. Assuming no errors then run `node` to enter the node CLI where you can test everything works as you expect.

**Comment by Janaki4** [comment]
Okay guys.

**Comment by suyashgulati** [comment]
I have created a PR for this issue #2123
Can someone please assign this issue to me?
cc: @Shinigami92
