### ISSUE TITLE
Add support for count ranges in helpers.arrayElements

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1771]
### Clear and concise description of the problem

Most of our methods that allow specifying a length or count allow specifying them as range.

E.g. https://next.fakerjs.dev/api/helpers.html#multiple

But `helpers.arrayElements` does not.

https://next.fakerjs.dev/api/helpers.html#arrayelements

### Suggested solution

Add support for `count: number, {min: number, max: number}` using [`helpers.rangeToNumber()`](https://next.fakerjs.dev/api/helpers.html#rangetonumber).

### Additional context

Found in https://github.com/faker-js/faker/issues/1765

**Comment by ejcheng** [comment]
I can take this one
