### ISSUE TITLE
Treatment of the "tussenvoegsel", the family name affix in the Dutch locale

### ISSUE THREAD

**Issue by amarillion** [faker-js/faker#1777]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

TL;DR:

1. Dutch affixes are currently broken
2. It doesn't make sense to generate random(affix) + random(family name without affix)
3. Current PR using middle name to track affix has advantages and disadvantages.
4. Proposal: keep affix + family names together, and remove the concept entirely from faker.

Longer version:

I'm following up from a discussion on Discord and creating an issue as requested.

Dutch family names often have an affix, a.k.a. "tussenvoegsel" (https://en.wikipedia.org/wiki/Tussenvoegsel), such as "van", "de", "van der" and a few other variants. It's very common, in this list of top 100 Dutch family names, roughly 30% have an affix (See: https://nl.wikipedia.org/wiki/Lijst_van_meest_voorkomende_achternamen_van_Nederland).

There used to be support for this in faker, but this no longer works. If I set the locale to 'nl' and generate names with `faker.name.fullName()`, you never get any name with an affix. 

The way faker used to do this, wasn't really realistic. Affixes are part of the family name. The way the old version of faker would merge a random affixless family name with a random affix isn't really realistic. "van der Meer" (lit: from the lake) is a valid Dutch name, "Kuipers" (cooper) as well. "van der Kuipers" (from the cooper???) is nonsensical.

You're probably wondering why the affix is important anyway, if they're really just part of the family name. There is one simple answer: sorting. In a list of names, the affix is ignored when sorting. Dutch administrative systems (from governmental systems to the junior football club spreadsheet) track the affix separately, solely for this reason.

New code being prepared (https://github.com/matthewmayer/faker/tree/chore/fullname-name-patterns) treats the affix as a middle name. This approach has a certain advantage: the affix can be extracted separately, which makes it easier to write some custom sorting code according to the Dutch sorting rules. But it also has disadvantages. Firstly, Dutch persons can have middle names too. Secondly, you still have the problem that the random affix doesn't necessarily match the random family name. 

Proposal:

We can take a much simpler route: make the affix part of the family name, put them all together in `locales/nl/person/last_name.ts`. 
I'm preparing a PR to this effect.

Upside is that it's really simple.
Downside is that you need to extract the affix with a regular expression if you want to sort those names.

Alternative:

The fully proper solution is to create an extra field, called 'affix' or 'tussenvoegsel' for Dutch names, and pick them from an array of affix + surname pairs. I think this solution would be overkill for the purposes of Faker. 

### Minimal reproduction code

import { faker } from '@faker-js/faker';

faker.locale = 'nl';
let affixCount = 0;
for (let i = 0; i < 1000; ++i) {
	const name = faker.name.fullName();
	if (name.includes(' van ') || name.includes(' de ')) { affixCount++; }
}
console.log(affixCount); // -> prints 0

### Additional Context

Tested with faker 7.6.0

### Environment Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 18.21 GB / 31.08 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.n/bin/node
    npm: 8.11.0 - ~/.n/bin/npm
  Browsers:
    Chromium: 109.0.5414.74
    Firefox: 109.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by matthewmayer** [comment]
> "van der Meer" (lit: from the lake) is a valid Dutch name, "Kuipers" (cooper) as well. "van der Kuipers" (from the cooper???) is nonsensical.

This seems the critical part, since only certain combinations are logical/common, it makes sense to just put the affixes directly in the surname file. So this PR seems like the best strategy.

Can I suggest we merge https://github.com/faker-js/faker/pull/1637 first, and then follow up with additional PRs for locale-specific corrections like this one?
