### ISSUE TITLE
Letter "Đ" in latin while using the `hr` locale is incorrect

### ISSUE THREAD

**Issue by bdimitrovski** [faker-js/faker#1800]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

When using the `hr` or generally latin locale, there is an issue that the latin character Đ is wrongly transliterated into "ð" by my system, which takes the user's first name and last name, and forms a username in the format of `firstName.lastName`.

To give an example: 
- If I manually enter "Đina Đovani" into the system, that works. The capital character "Đ" correctly transliterates into lowercase "đ", which finally, in turn, does transliteration (by my system) to "dj". The character in question is https://www.compart.com/en/unicode/U+0110
- However, if I let faker generate a name for me, and the name + surname string turns out to be "Đina Đovani", this mistakenly gets detected as https://www.compart.com/en/unicode/U+00D0, whose lowercase version is the letter https://www.compart.com/en/unicode/U+00F0, and then my system cannot handle this and errors.

### Minimal reproduction code

I am using Cypress for E2E testing, and this is a part of the function that generates that aforementioned name:

```typescript
`${utils.generateRandomData().name.firstName()} ${utils.generateRandomData().name.lastName()}`
``` 

where `generateRandomData()` is simply an interface to the `faker` object.

The Faker lib is imported like:

```typescript
import { faker } from '@faker-js/faker/locale/hr';
```

### Environment Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 60.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6.1
  npmPackages:
    @faker-js/faker: ^7.6.0 => 7.6.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
@bdimitrovski There seems to be something missing, because AFAICT a strict concatenation shouldn't change letters. 
And if it does I'm not sure how we could prevent/fix that.
You also mention lowercase which I don't see in the reproduction code.

Please also provide a complete test case like this, otherwise I'm unable to reproduce the error.

````ts
faker.seed(1137);
const firstName = faker.name.firstName(); // A
...

expect(x).toBe(y);
````

**Comment by bdimitrovski** [comment]
There shouldn’t be anything missing, just replace https://www.compart.com/en/unicode/U+00D0

with https://www.compart.com/en/unicode/U+0110 in the dataset,
because it is simply not the correct latin letter at all.

The lowercase letter is irrelevant in this case, as my system automatically transforms + transliterates things like “Đina Đovani” to “djina.djovani”.

However, if the very same input like above comes from faker,
it gets transformed into “ðina.ðovani”, which my system rightfully deems as incorrect.

**Comment by ST-DDT** [comment]
I got somewhat confused by "latin letters", because the Croatian letters don't look like the latin letters I know.

So just to sum it up:
Our `hr` dataset contains two different characters that look identical, but one is wrong?

TODO: Replace [compart.com/en/unicode/U+00D0](https://www.compart.com/en/unicode/U+00D0) -> [compart.com/en/unicode/U+0110](https://www.compart.com/en/unicode/U+0110)

I verified the char code using this page: https://www.lernenwirkroatisch.de/blog/grundlagen-der-kroatischen-sprache-die-dialekte-das-alphabet-und-die-aussprache
I haven't checked which files are affected.

Thanks for bringing this to our attention.

We are currently very busy, so we would appreciate external help.

**Comment by bdimitrovski** [comment]
@ST-DDT 

> So just to sum it up:
> Our hr dataset contains two different characters that look identical, but one is wrong?

Yes, that is correct - the encoding is much different, and does not produce the desired result.

However, instead of fixing this, and possibly interfering with the original author's work, I have now created a proper new language (Serbian, Latin), which much of the Faker's community here in Serbia would appreciate anyway.
Please check it out: https://github.com/faker-js/faker/pull/1801 

This should address the weird latin characters issue for me and others looking to randomise data in their tests, and bring some more diversity into generating unique Serbian data like names, surnames, months, phones etc. I would definitely be interested to expand the dataset in time :)

**Comment by matthewmayer** [comment]
I did a bit more research on this. They are definitely different letters which happen to look the same in capital form.

1. Ð - LATIN CAPITAL LETTER ETH' (U+00D0) - more info at https://en.wikipedia.org/wiki/Eth - used in Icelandic, Faeroese
2. Đ - LATIN CAPITAL LETTER D WITH STROKE (U+0110) - more info at https://en.wikipedia.org/wiki/D_with_stroke - used in Croatian, Serbian, Sami, Vietnamese

https://stackoverflow.com/questions/65315353/what-is-the-difference-between-u00d0-and-u0110

Doing a global search for the 1st version shows it appears incorrectly in both `hr` and `vi` locales.
