### ISSUE TITLE
`hr` locale has excessive number of lastNames

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1802]
https://github.com/faker-js/faker/blob/next/src/locales/hr/person/last_name.ts has more than 11,000 names and is 166KB in size. This is 5 times larger than any other locale (`it` is next with 2170).

Maybe just randomly pick a 20% subset to keep?

**Comment by matthewmayer** [comment]
The only locale files over 100KB found via `find . -type f -size +100k` are:

```
./cz/location/street_name.ts
./hr/person/last_name.ts
./hu/word/adjective.ts
./hu/word/noun.ts
```

**Comment by ST-DDT** [comment]
We plan to limit the number of allowed elements to ~1000 or less.
