### ISSUE TITLE
Double last names in some locales

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1817]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

#1637 has caused a problem in some locales for example `es` which have name patterns like

`'{{person.firstName}} {{person.lastName}} {{person.lastName}}'`

### Minimal reproduction code
```
const {faker} = require("@faker-js/faker")
faker.locale = "es"
faker.person.fullName() //'Anni Cervantes Cervantes'
```

### Environment Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) x64 Apple M1
    Memory: 37.86 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 109.0.1
    Safari: 16.2
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by 0916dhkim** [comment]
Opened a bugfix PR #1822 :+1:

**Comment by matthewmayer** [comment]
We now have three potential solutions in  #1818  #1819 and #1822

@faker-js/maintainers in the next meeting maybe you can discuss which direction you prefer.

**Comment by ST-DDT** [comment]
**Team Decision**

We decided on #1819 (with changes).
