### ISSUE TITLE
Add section to CONTRIBUTING about how to source data

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1820]
### Clear and concise description of the problem

It comes up fairly frequently e.g. on  https://github.com/faker-js/faker/pull/1778 and https://github.com/faker-js/faker/pull/1699  that it's not clear how to source data for locales. Perhaps we could add a new section to CONTRIBUTING with some tips e.g. 
https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md

### Suggested solution

Add a section of tips, something like

* Faker shouldn't contain copyrighted materials
* Facts cannot be copyrighted, so for example if you are translating a finite known list of things like the names of chemical elements into another language, that's fine
* But if you are compiling list of for example popular personal names or cities, don't copy directly from a single source (Wikipedia, 'most popular lists', government data sites etc) - as compiling a list of facts can be copyrighted https://en.wikipedia.org/wiki/Copyright_in_compilation
* It's best to refer to multiple sources and use your own judgement/knowledge to make a sample list of data

**Comment by ST-DDT** [comment]
Yes, it is always good to have documentation to refer to.
Do you wish to address this/create a PR for it?

**Comment by matthewmayer** [comment]
Sure
