### ISSUE TITLE
Turn on strictNullChecks in tsconfig

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1834]
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L11

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1837
- https://github.com/faker-js/faker/issues/1838

**Comment by Shinigami92** [comment]
This raised around 200 errors

Mostly coming from `this.faker.definitions.xy` might be `undefined`

So theoretically this is related to
- #893

**Comment by ST-DDT** [comment]
I consider this blocked by #893

**Comment by xDivisionByZerox** [comment]
@Shinigami92 are you working on this? Is this blocked by #2102?

**Comment by Shinigami92** [comment]
> @Shinigami92 are you working on this? Is this blocked by #2102?

Yes and yes 👍

**Comment by ST-DDT** [comment]
I started a PR to fix this: https://github.com/faker-js/faker/pull/2435

- https://github.com/faker-js/faker/pull/2435
