### ISSUE TITLE
Turn on strictBindCallApply in tsconfig

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1835]
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L12

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1834
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1837
- https://github.com/faker-js/faker/issues/1838

**Comment by Shinigami92** [comment]
I tried to set `strictBindCallApply: true` but I have a problem in line

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/src/modules/helpers/unique.ts#L140

But as we want to get rid of this anyway
- #1785

I will put no more effort into `strictBindCallApply` until then

**Comment by ST-DDT** [comment]
Is it possible to just replace `this` with `undefined`?

**Comment by Shinigami92** [comment]
> Is it possible to just replace `this` with `undefined`?

Could you explain a bit how you come to this conclusion? I would like to understand what your thought-process is.

**Comment by ST-DDT** [comment]
Since the value isnt bound to anything useful in the first place (aka this isnt bound to anything specific since it isnt even in the helpers module directly and thus doesnt get bound by the constructor). We could just drop it entirely.
Or am I missing something?

**Comment by Shinigami92** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/7195563/218711706-287a456f-9fcf-4724-b884-fd8b612e50be.png">

I suggest setting `strictBindCallApply` locally and try around a bit on your own
That could speed up the process and doesn't require so much writing here

**Comment by ST-DDT** [comment]
Done: https://github.com/faker-js/faker/pull/1842

**Comment by ST-DDT** [comment]
Blocked by #1842

---

I no longer know how to fix these lines:

````ts
this[name] = this[name].bind(this);
````

For most modules I can simply do:

````ts
this[name] = this[name].bind(this, ...[]);
````

but that doesn't work for the helpers module.

**Comment by ST-DDT** [comment]
Blocked by #2102.

- #2102

**Comment by xDivisionByZerox** [comment]
I will close this as this has been activated implicitly in #2102.
