### ISSUE TITLE
Turn on strictPropertyInitialization in tsconfig

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1836]
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L14

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1834
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1837
- https://github.com/faker-js/faker/issues/1838

**Comment by Shinigami92** [comment]
This is blocked by 
- #1834

As `strictNullChecks` is a precondition

**Comment by ST-DDT** [comment]
Blocked by #2102.

- #2102

**Comment by xDivisionByZerox** [comment]
I will close this as this has been activated implicitly in #2102.
