### ISSUE TITLE
Turn on noImplicitAny in tsconfig

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1837]
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L15

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1834
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1838

**Comment by xDivisionByZerox** [comment]
This has been partially reintroduced in #2102.
