### ISSUE TITLE
Turn on noImplicitThis in tsconfig

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1838]
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L16

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1834
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1837

**Comment by Shinigami92** [comment]
I tried to set `noImplicitThis: true` but I have a problem in line

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/src/modules/helpers/unique.ts#L140

But as we want to get rid of this anyway
- #1785

I will put no more effort into `noImplicitThis` until then

**Comment by ST-DDT** [comment]
Fixed via: https://github.com/faker-js/faker/pull/1842
