### ISSUE TITLE
github-actions bot also triggers when build step failed

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1840]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

This is an `infra` bug in our CI

The github-actions bot also triggers when build step failed
Then it suggest to run `pnpm run generate:locales`, `pnpm run generate:api-docs`, and `pnpm run test -u`
But these are totally wrong suggestions as the build step already failed

I see two solutions:
1. Do not print the github-actions bot when the build or anything before that already failed (my preferred solution)
2. Listing all comments that needs to be done to fix the CI (this could get very spammy and unnecessary verbose)

### Additional Context

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7195563/218677142-dd66d1df-3837-4882-bd83-48a286641c48.png">

### Environment Info

```shell
-
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by xDivisionByZerox** [comment]
This will be solved by #1846 as well

**Comment by ST-DDT** [comment]
> This will be solved by #1846 as well

🤔  We either have to change the wording to not explicitly refer to uncommitted changes
or have to change the conditions for firing the message.

**Comment by xDivisionByZerox** [comment]
@ST-DDT can this be considered fixed and closed?

**Comment by ST-DDT** [comment]
No, the message still refers to uncommited changes, but also triggers for test failures and other stuff IIRC.
(Also the message only triggers for members and not external contributors.)
