### ISSUE TITLE
Improve error message in `birthday`

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#1841]
## Description

Currently, when `faker.date.birthday` is called with parameters where `min` > `max` an error in the form of `Max {number} should be larger than min {number}.` is thrown. Here, `{number}` isn't the input years (as one would expect), but the UNIX timestamp of the generated Dates.

## Solution

Move the validation to the top of the function and do it against the input parameters. Use the input parameters in the error message.

## Additional Information

Brought up in [#1833](https://github.com/faker-js/faker/pull/1833#discussion_r1105079757).

**Comment by johnmal-dev** [comment]
I'd love to take on this issue

**Comment by xDivisionByZerox** [comment]
You might want to wait for #1833 to get merged to avoid merge conflicts. This should be done in the next 24 hours, so I can already assign you.

**Comment by johnmal-dev** [comment]
I am ready to push the changes. Is this PR title ok? "fix: improve error message for faker.date.birthday"

**Comment by johnmal-dev** [comment]
Feedback is welcome! I hope to continue contributing as I learn more.
