### ISSUE TITLE
Add support for complex intermediate return types in fake method

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1850]
### Clear and concise description of the problem

Currently it is not possible to use methods, that return complex objects in the fake method, because it will only display `[object]`.

### Suggested solution

Add support for the following syntax:

````ts
faker.helpers.fake('{{airline.airport.code}}')
````

Which should be equivalent to:

faker.airline.airport().code

This should work for both method references and locale data references. 

### Additional context

Ref: https://github.com/faker-js/faker/issues/1733#issuecomment-1433439926

**Comment by ghost** [comment]
I would like to work on this issue.

**Comment by ST-DDT** [comment]
Awesome. Thanks for your help.

**Comment by ST-DDT** [comment]
@inkedtree Could you please give us an update on the progress here?

**Comment by ghost** [comment]
@ST-DDT To be honest, there is not much progress so far. Last time I worked on this issue, I thought about where I need to make changes in the code. In the last few weeks I was quite busy. I will try to make a PR this week, if that is okay for you.
