### ISSUE TITLE
Generate relational data

### ISSUE THREAD

**Issue by chuck-alt-delete** [faker-js/faker#1856]
### Clear and concise description of the problem

Faker is great at generating individual fields of fake data, and it would be even more useful if you could, for example, specify foreign key constraints so that a downstream database could show meaningful join results.

### Suggested solution

For one-one and one-many relations, it may be possible to initialize the faker instance with some foreign key constraints and it would traverse a directed acyclic graph to precompute a set of unique keys that obey those constraints.

**Comment by ST-DDT** [comment]
I think I understand what you wish to have, but I'm not sure what you expect us to do to provide these.

IMO you can create these relations by:

- 1-1 and 1-n (compositions): Creating the linked element(s) along with the main element.
- 1-n and m-n (aggregations): Creating a list of your entities and use helpers.arrayElement to pick one of them.

Does that satisfy your needs? If not please explain what you would like to have. Best with a code example.

**Comment by chuck-alt-delete** [comment]
Thanks for the quick response! Yes, that’s the approach I’m trying to implement. I was thinking it might be useful enough to build something into faker itself. Some function to take a set of relational data models and precompute keyspaces that respect those foreign key constraints.

This does sound out of scope of the library, but I just wanted to plant the seed of the idea in case it sparks some ideas. Feel free to close if you think this isn’t within the scope of the project.

**Comment by ST-DDT** [comment]
> Some function to take a set of relational data models and precompute keyspaces that respect those foreign key constraints.

Like this:

````ts
joinRelations(parents, 'childIds', (p) -> p.id, numberOfParents: 1, children, 'parentId', (c) -> c.id, numberOfChildren: { min: 0, max: 15 })
````

?
IMO this is unwieldy and stops working if you have any more complex relationship rules.
One of the complicating factors is that the relation handling needs to be dynamic e.g. mappedById vs embedded. I included the required parameters in the above signature for visualization.

If that's what you have in mind then IMO it doesnt really simplify the users code. We could however add some advanved usage examples to our docs.
So we could link them in the future and give our users some ideas.
What do you/the others think?

**Comment by Shinigami92** [comment]
> What do the others think?

I think this is far out of scope for Faker and should 100% be managed on the user's side.

I have a mocked layer for a GraphQL Gateway and use relational data there for my personal needs. Everything is working fine for testing and mocking purposes.

I wrote this several times in previous places here and there, I just repeat it again here:

```ts
// mocks/locations.ts
import { faker } from '@faker-js/faker';
import { Location } from 'src/locations/models/location.model';
import { createRandomNode } from './node';

export const LOCATIONS: Location[] = [];

export function createRandomLocation(): Location {
  const parentLocation = faker.helpers.arrayElement(LOCATIONS);

  return new Location({
    ...createRandomNode(),

    name: `Location ${faker.number.int({ max: 100 })}`,
    parentLocationId: parentLocation?.id,
  });
}

for (let index = 0; index < 15; index++) {
  LOCATIONS.push(createRandomLocation());
}
```

Then I can access `createRandomLocation` as well as `LOCATIONS` from other files and just build up my whole "database" or just have simple two entity relations for e.g. a test case.
I also sometimes do e.g.:
```ts
const camera = createRandomCamera()
const location = createRandomLocation()
camera.locationId = location.id
// ... proceed with test case
```

**Comment by xDivisionByZerox** [comment]
**Team decision**

Our existing [documentation](https://fakerjs.dev/guide/usage.html#create-complex-objects) is sufficient. Users should be able to figure out more complex behavior for their own use cases.
