### ISSUE TITLE
Failed to load resource: the server responded with a status of 429

### ISSUE THREAD

**Issue by kydner** [faker-js/faker#1868]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

i used faker image, but always error 429 when i reload browser, how handle this error?

### Environment Info

```shell
npmPackageFaker: image
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

yarn

**Comment by ST-DDT** [comment]
> i used faker image, but always error 429 when i reload browser, how handle this error?

Please paste the entire error here message here.
Did the image module return an url that was invalid or couldn't you generate an url?

- Missing `Minimal reproduction code`

**Comment by kydner** [comment]
1. Request URL:

   https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/36.jpg
   2. Request Method:
   GET
   3. Status Code:
   429
   4. Remote Address:
   104.17.96.13:443
   5. Referrer Policy:
   strict-origin-when-cross-origin

**Comment by kydner** [comment]
On first load is error 429 but, when reload again on same url success

**Comment by Shinigami92** [comment]
429 Too Many Requests https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

This is not related to Faker itself but that you are doing to many requests from your client to this provider
Faker "just" concatenates a string that is at the end an URL that the user who use Faker can then call.

---

BUT! I see you are using these for avatars and so I assume you need it the same as I need it for my project to mock some **faces**. We were talking already about how we could provide some alternatives for this and e.g. wanted to have a provider that provides AI generated non real world person faces. But a paid or non-deterministic provider is not an option.

A second alternative might be to create a repo under @faker-js org and upload images there. This would bring maintenance burden and also we might run into legal issues if we don't care to much about the data as then they are in our responsibility were as the current set is not that much but was "gifted" to us as a present (https://github.com/faker-js/faker/pull/95#issuecomment-1010609280)

**Comment by ST-DDT** [comment]
The original issue is outside of our control so I consider this as nothing to do for us here except documentation which is covered by https://github.com/faker-js/faker/issues/1783.

- https://github.com/faker-js/faker/issues/1783
