### ISSUE TITLE
Lib folder now needs built before running tests

### ISSUE THREAD

**Issue by clarkerican** [faker-js/faker#187]
It seems like now we need to build the lib folder when running tests. We should consider either:

1. Updating the README to include this in the Running Tests section 
2. Adding a "pretest" step that automatically builds the lib folder for the developer

**Comment by Shinigami92** [comment]
I think we now documented this in contribution.md and it doesn't count that much on project "stability"
I will close this for now
Feel free to reopen if really needed and update the issue
