### ISSUE TITLE
Can't join Discord community

### ISSUE THREAD

**Issue by sys13** [faker-js/faker#1890]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Trying to join the Discord channel from the link at the top right of the main website, or the link when opening a new issue.

There may be info to debug here: https://support.discord.com/hc/en-us/articles/360001556852

### Environment Info

```shell
N/A
```

### Which module system do you use?

- [x] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by Shinigami92** [comment]
https://discord.gg/wq78qyhdSZ

**Comment by Shinigami92** [comment]
Maybe we lost a server tier?

https://github.com/faker-js/faker/blob/f5b1c5a4734eef5d4ab5196238a464f0cac6fceb/netlify.toml#L26

**Comment by Shinigami92** [comment]
We lost partnertship :(

![image](https://user-images.githubusercontent.com/7195563/222821059-33c20163-7ebf-4ff4-802d-4479f9cff852.png)
