### ISSUE TITLE
Merge faker.defaultRefDate with faker.seed

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1895]
### Clear and concise description of the problem

When setting `faker.seed` it isn't clear that you also have to set a fixed `defaultRefDate` to get reproducible results for the faker.date.*() methods.

### Suggested solution

Add a `defaultRefDate` parameter/option to `faker.seed`.

Worth discussing:

Should the current (v8 new) `faker.defaultRefDate` method be removed?

### Alternative

Add `@see` to both methods.

### Additional context

Originally suggested here https://github.com/faker-js/faker/issues/1870#issuecomment-1455099749 by @luisjakon

**Comment by luisjakon** [comment]
If it's too much of a polluting change, perhaps it might be easier to just have a note or a link on reproducibility and fixation of seed and dates upfront (or early on) in the description as previously suggested. This way, hopefully it's not as surprising as it was to me while testing and running the code.  The other thing to consider is whether you might want to have an options object to seed or an engine init function that sets all useful parameters that faker may make use of in all other functions. Other than that, the current solution works fine and can be looked into in another revision. Thanks!

**Comment by Shinigami92** [comment]
**Team Decision**

For now we will just aim for better docs (using the alternative `@see`)

**Comment by ST-DDT** [comment]
Fixed via #1960
