### ISSUE TITLE
Add `commit-convention.md`

### ISSUE THREAD

**Issue by mbokinala** [faker-js/faker#190]
Currently, when attempting to commit with a message that does not follow the proper format enforced by [`scripts/verifyCommit.ts`](https://github.com/faker-js/faker/blob/31ad7328805486d9bda05b9b507fa02335ef24b0/scripts/verifyCommit.ts), the following error message is shown:

```
 ERROR  invalid commit message format.

  Proper commit message format is required for automated changelog generation. Examples:

    feat: add 'comments' option
    fix: handle events on blur (close #28)

  See .github/commit-convention.md for more details.
```

However, the file `.github/commit-convention.md` does not exist, so contributors must track down the `verifyCommit` script by looking at `package.json` to find the format/types for commit messages (like feat, fix, docs, dx, refactor, perf, test, etc).

An alternative to adding the file would be to describe the proper commit message convention in the error message itself and provide all the various options for the 'type' of the commit (`feat`, `fix`, etc). All the allowed types can be found [in `/scripts/verifyCommit.ts`](https://github.com/faker-js/faker/blob/31ad7328805486d9bda05b9b507fa02335ef24b0/scripts/verifyCommit.ts#L12)

**Comment by Shinigami92** [comment]
We took the script from [Vite](https://github.com/vitejs/vite).
Thanks for the hint :slightly_smiling_face: 
Are you willing to open a PR for this?

**Comment by mbokinala** [comment]
Sure, will do
