### ISSUE TITLE
Further improvements to migration guide for switching locales

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1905]
Followon from #1735

This "old" example in the migration guide on https://next.fakerjs.dev/guide/upgrading.html has problems

* The Old code doesn't compile on v7 - Faker, de_CH, de and en are not defined.
* I'm not sure what the correct syntax for a custom Faker instance was on v7.x?

Old:
```ts
import { faker } from '@faker-js/faker';

const customFaker = new Faker({
  locale: 'de_CH', // the expected locale
  fallbackLocale: 'de', // ensure we have a German fallbacks for addresses
  locales: { de_CH, de, en },
});
const a = customFaker.internet.email();
customFaker.locale = 'en'; // neither 'de_CH' nor 'de' have emojis
const b = customFaker.internet.emoji();
```

**Comment by matthewmayer** [comment]
Tried to tweak the old example to compile, but not sure what the correct syntax is for Faker v7.x?

**Comment by ST-DDT** [comment]
The old imports only work for CJS.

**Comment by matthewmayer** [comment]
I also get an error using CJS on faker 7

**Comment by ST-DDT** [comment]
Please post the error message or explain what isn't working.

**Comment by matthewmayer** [comment]
So for example with the code:

```
const {faker, Faker, de_CH, de, en} = require("@faker-js/faker")
const customFaker = new Faker({
  locale: 'de_CH', // the expected locale
  fallbackLocale: 'de', // ensure we have a German fallbacks for addresses
  locales: { de_CH, de, en },
});
const a = customFaker.internet.email();
customFaker.locale = 'en'; // neither 'de_CH' nor 'de' have emojis
const b = customFaker.internet.emoji();
```

i get the error
n [Error]: Locale de_CH is not supported. You might want to add the requested locale first to `faker.locales`.
    at Y.set locale [as locale] (/Users/matt/Documents/git/faker7/node_modules/@faker-js/faker/dist/cjs/faker.js:1:2767)
    at new Y (/Users/matt/Documents/git/faker7/node_modules/@faker-js/faker/dist/cjs/faker.js:1:2635)
    at Object.<anonymous> (/Users/matt/Documents/git/faker7/test.cjs:2:21)

**Comment by matthewmayer** [comment]
ok i think i got it. Faker 7.x.x used "localeFallback" but the docs say "fallbackLocale"
