### ISSUE TITLE
`cz` and `sk` still have bs_noun.ts files

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1916]
Looks like in #1860 which renamed bs_noun etc to buzz_noun, the `cz` and `sk` lists didn't get renamed e.g.:
https://github.com/faker-js/faker/blob/next/src/locales/sk/company/bs_noun.ts

However given these are just copies of the English lists, probably best just to delete?

**Comment by ST-DDT** [comment]
If these are just copies of the English list we should delete them.
Maybe do a general sweep and check/remove duplicates.
