### ISSUE TITLE
Default parameter value not showing up in faker.date.recent documentation

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1927]
<img width="736" alt="Screenshot 2023-03-14 at 16 55 44" src="https://user-images.githubusercontent.com/152770/224964204-c5fbcee2-0456-4375-9151-0f90255e420f.png">

For example no longer shows that faker.date.recent has a default of `1` for days

compare
https://fakerjs.dev/api/date.html#recent
and
https://next.fakerjs.dev/api/date.html#recent

Seems to be a regression from https://github.com/faker-js/faker/pull/1534

**Comment by ST-DDT** [comment]
Likely caused by or debug-able here:
https://github.com/faker-js/faker/blob/ddcb3ddce4e583753aaba5ad60ca2b5de3a58083/scripts/apidoc/signature.ts#L254

**Comment by matthewmayer** [comment]
i think the problem is previously parameter defaults were specified by writing `"Defaults to Foo."` at the end of the @param declaration but these were removed and replaced by `@default Foo`. So either `analyzeParameterOptions` needs to be modified to add support for the `@default` option or need to add back `Defauults to 1.` on this and similar options.

**Comment by ST-DDT** [comment]
I'll have a look.
