### ISSUE TITLE
Add overview guides to specific modules

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1928]
One thing I find a little lacking in the faker documentation is that on module pages like https://next.fakerjs.dev/api/date.html its just a alphabetical list of methods, without much guidance on what the important methods are, any general scope on what the module is for, more detailed examples which use more than one method, whether data is localized, etc.

I was thinking it could be nice to add an overview section to the top of each guide page. I prepared a draft PR with a few samples. If you think this would be useful I'd be happy to work on some more.

**Comment by matthewmayer** [comment]
@faker-js/maintainers  in general you are in favour of the idea?

**Comment by ST-DDT** [comment]
I like it. It is like a short introduction to the module and conjeys more information than the current: "Module with methods related to xyz".
