### ISSUE TITLE
Export assignment cannot be used when targeting ECMAScript modules

### ISSUE THREAD

**Issue by shernshiou** [faker-js/faker#193]
### Describe the bug

I received export error when building project with `@fakerjs/faker`

```
node_modules/@faker-js/faker/index.ts:4:1 - error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

4 export = faker;
  ~~~~~~~~~~~~~~~


Found 1 error.
```

### Reproduction

Install `@fakerjs/faker`

Build project with tsc

**Comment by Shinigami92** [comment]
This will be fixed already by next version due to excluding the `index.ts` from bundle.
See #173 for more
