### ISSUE TITLE
Clarify the difference between `faker.location.county` and `faker.location.state`

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1944]
The top-level administrative regions of a country can be called states (eg. in USA), provinces (e.g. in Canada) or counties (e.g. in UK), or various other names.

Currently there are seperate methods called `faker.location.state()` and `faker.location.county()`

It's clearer to have a single method for this.
The following locales have county definitions

* en, but it's a truncated version of the en_GB list
* el -> rename to state
* en_GB -> rename to state
* en_IE -> rename to state
* he -> contains a comment "Not relevant for Israel"
* ro, but it's a duplicate of the state list

**Comment by ST-DDT** [comment]
Isnt a county an adminstrative area within a state?

**Comment by matthewmayer** [comment]
> Isnt a county an adminstrative area within a state?

Not consistently. 
In the US yes in most states, but you dont write the county in a postal address.

**Comment by ST-DDT** [comment]
**Team Decision**

We want to keep `location.county()`.
We should however improve the documentation, that this usually refers to  administrative areas within a state:

Country | State | County | City
--- | -- | --- | ---
USA | Alabama | Baldwin |  Daphne
DE | NRW | Städteregion Aachen | Würselen

**Comment by matthewmayer** [comment]
> Team Decision
>
> We want to keep location.county().
> We should however improve the documentation, that this usually refers to administrative areas within a state:

hmm, none of the current locales actually do this though. We don't have second-level administrative regions implemented anywhere.

**Comment by xDivisionByZerox** [comment]
I'd consider this solved by #1987 and #2574. If you think this is a mistake, please write a comment or reopen the issue directly.

- #1987
- #2574
