### ISSUE TITLE
docs are confusing about default parameters of faker.color.rgb

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1957]
https://next.fakerjs.dev/api/color.html#rgb

options.prefix shows default `0x`

examples show both
```
faker.color.rgb() // => "#cdfcdc"
faker.color.rgb() // '0xffffFF'
```

In the code it actually seems to default to "#"

```
const {
      format = 'hex',
      includeAlpha = false,
      prefix = '#',
      casing = 'lower',
    } = options || {};
```

either
- change the docs to show "#" is default?
- change the code to show "0x" is default?

**Comment by ST-DDT** [comment]
Please try to assign labels, the project and milestone yourself when creating issues/PRs.

**Comment by matthewmayer** [comment]
Sure. Any guidance? Like I don't want to stick everything on milestone 8.0 and just make 8.0 longer and longer 😀

**Comment by matthewmayer** [comment]
Should there always be one p, c and m label?

**Comment by ST-DDT** [comment]
c: Yes, at least one
p: Exactly one
m: If applicable - some docs, infra and locale dont refer to a module or more than a few

I would also assign the bug label here since it refers to something being wrong.
And good first issue since it is easy.

And set the project to Status: Todo

**Comment by matthewmayer** [comment]
may not be good first issue as i'm not sure what the solution is :D change the default, or change the docs?

**Comment by ST-DDT** [comment]
> i'm not sure what the solution is

Then please add `needs team decision` as well, so we are aware that there is something to discuss here. Maybe also add a hint to the description stating you are not sure what the correct one is, optionally with your suggestion/recommendation.

**Comment by ST-DDT** [comment]
Thanks for your help ❤️ .

**Comment by matthewmayer** [comment]
@Shinigami92 was this just an oversight when https://github.com/faker-js/faker/pull/1644/files was implemented?

**Comment by Shinigami92** [comment]
Looks like this is a (docs)-bug already in v7.6.0 :thinking: 
https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/src/modules/color/index.ts#L309

I think for the easiness we should not change the implementation, but fix the docs
