### ISSUE TITLE
some urlPicsumPhotos are broken

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1964]
example https://picsum.photos/id/725/640/480

Unfortunately picsum.photos appears to have some gaps in the 1...1000 range

See https://github.com/DMarby/picsum-photos/issues/83

We could blacklist the missing images?

**Comment by matthewmayer** [comment]
Better idea

We can use https://picsum.photos/seed/SOMEVALUE/w/h instead then we don't need to worry about missing ids

**Comment by ST-DDT** [comment]
Lets do that.
