### ISSUE TITLE
Add `includeAlpha` to color examples

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1967]
can we add some `includeAlpha` examples too?

_Originally posted by @matthewmayer in https://github.com/faker-js/faker/pull/1958#discussion_r1145578744_

**Comment by matthewmayer** [comment]
i noticed that there are multiple documentation blocks above the different signatures, which have a different set of examples, for example this line https://github.com/faker-js/faker/blob/233a4def41ebd6ce5f7f66ceab19a87991269226/src/modules/color/index.ts#L296 but that doesnt show in the online documentation.

If there are multiple signatures, how does the api docs decide which one to use? Should they all have the same set of examples?

**Comment by ST-DDT** [comment]
It will show the last signature only.
