### ISSUE TITLE
Dark Mode for fakerjs.dev website

### ISSUE THREAD

**Issue by poyea** [faker-js/faker#197]
### Clear and concise description of the problem

We can provide a dark mode option for the entire documentation website. How about we make a [toggle](https://github.com/GoogleChromeLabs/dark-mode-toggle)? Or we may use `prefers-color-scheme`.

### Suggested solution

Implement a dark mode for the website

### Additional context

#195

**Comment by Shinigami92** [comment]
This issue could help :thinking: https://github.com/vuejs/vitepress/issues/251

**Comment by JessicaSachs** [comment]
Yeah there's work being done on this internally. Once it's ready we'll have dark mode for free.
