### ISSUE TITLE
Add tests for module jsdoc parsing

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1973]
### Clear and concise description of the problem

Currently we only have tests covering the signatures.

### Suggested solution

Add a test setup for modules as well.

- Deprecated and non-deprecated
- Containing references to fakerjs.dev and next.fakerjs.dev

### Alternative

None

### Additional context

Split from https://github.com/faker-js/faker/pull/1929

**Comment by ST-DDT** [comment]
Blocked by #2024

**Comment by ST-DDT** [comment]
This is no longer blocked. In fact we already have a base setup from #2101, we should probably extend it with more cases like `@deprecated`.

**Comment by xDivisionByZerox** [comment]
> Deprecated and non-deprecated

We do not log any messages when a module is deprecated. All of them are instantiated when a Faker instance is created which would lead to misleading logs.
How would you test this? What is the expected behavior to test?

**Comment by ST-DDT** [comment]
This is not about the module behavior being tested, but our jsdocs tooling.

**Comment by xDivisionByZerox** [comment]
So this is about the [`test\scripts\apidoc\module.spec.ts`](https://github.com/faker-js/faker/blob/3cfeb3814703d12a9e95ed684fc2c8f94d1f2c72/test/scripts/apidoc/module.example.ts) file, not [`test\scripts\apidoc\verify-jsdoc-tags.spec.ts`](https://github.com/faker-js/faker/blob/3cfeb3814703d12a9e95ed684fc2c8f94d1f2c72/test/scripts/apidoc/verify-jsdoc-tags.spec.ts)?

I was looking at the following test. But guess I looked at the wrong place:

https://github.com/faker-js/faker/blob/ee12c32fced6cdf6fef2c5993af84825fd88606f/test/scripts/apidoc/verify-jsdoc-tags.spec.ts#L154-L174

**Comment by ST-DDT** [comment]
Will be added in https://github.com/faker-js/faker/pull/2412

- https://github.com/faker-js/faker/pull/2412
