### ISSUE TITLE
Missing faker.location.state data in some locales

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1977]
Various locales are missing states (or equivalent 1st level administrative regions like provinces) so fall back to `en` states.
- af_ZA #1983
- dv
- fi #1986
- ge
- hr #2142
- hu #1990
- mk #2271
- pt_PT #2269
- sr_RS_latin #2270
- tr #2231
- vi #2128 
- zu_ZA #1983

I have already prepared data for some of these locales, but do you want this as 
- a) 1 big PR
- b) 12 small PRs, one per language

**Comment by ST-DDT** [comment]
IMO having one PR per locale group/language (`en_*`) would be best.
That way we can easily forward it to people knowledgeable about that language.

**Comment by matthewmayer** [comment]
going to close this. individual issues/PRs can be created for any remaining states with no data.
