### ISSUE TITLE
Accept dates as params for Date methods

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#198]
### Describe the bug

Old faker used to support dates for functions like `faker.date.past` or `faker.date.between`. New types do not allow such calls.

### Reproduction

```
const baseDate = new Date()

faker.past(1, baseDate)
```

**Comment by 1LISA2** [comment]
![下载](https://user-images.githubusercontent.com/103248540/188253644-71993c4b-89f4-4be9-8460-d152663063b2.jpeg)
