### ISSUE TITLE
deprecate regexpStyleStringParse

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1985]
**Team decision**

- For now we don't change the existing method
- Instead we will add a new method `string.fromRegExp(string | RegExp): string`
- We will create a separate issue regarding deprecation of the old method

_Originally posted by @ST-DDT in https://github.com/faker-js/faker/issues/1569#issuecomment-1343328129_

**Comment by xDivisionByZerox** [comment]
@matthewmayer What exactly is tracked by this issue? Can it be closed? For the actual depreciation, #1994 has been created.

**Comment by matthewmayer** [comment]
#1994 seems to be about deprecating faker.helpers.replaceSymbolWithNumber
this issue would be for deprecating faker.helpers.regexpStyleStringParse

**Comment by xDivisionByZerox** [comment]
Yes, you are correct. Excuse me, I was viewing those issues on my phone and got confused.

In that case, I'll add an `good first issue` label here as well.
