### ISSUE TITLE
Deprecate helpers.replaceSymbolWithNumber

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1994]
### Clear and concise description of the problem

The method `helpers.replaceSymbolWithNumber` is mostly a black box that does some arbritary char -> digit transformations.

The implementation contains unexpected branches.

### Suggested solution

1. Replace all usages in our code base with a 

````ts
string.replace(/char+/g, (m) => faker.string.numeric(m.length));
````

Deprecate `helpers.replaceSymbolWithNumber`

### Alternative

Keep the method as is

**Comment by ST-DDT** [comment]
Blocked by/Partially implemented by:

- https://github.com/faker-js/faker/pull/1992
- https://github.com/faker-js/faker/pull/1993

**Comment by ST-DDT** [comment]
**Team Decision**

We want this.

**Comment by suyashgulati** [comment]
@ST-DDT Can you assign this one to me

I am gonna use `String.replaceAll` instead of `String.replace` for this issue

Q1. Can you confirm one thing, as we are deprecating this function what would be the change required at this line [phone_number.ts#L13](https://github.com/faker-js/faker/blob/next/src/definitions/phone_number.ts#L13)

Q2. What will be the `@see` jsdoc for the deprecated function. `replaceSymbols`?

Q3. With deprecation, will there be any change in the tests? Should we remove tests or not?

**Comment by ST-DDT** [comment]
> Q1. Can you confirm one thing, as we are deprecating this function what would be the change required at this line [phone_number.ts#L13](https://github.com/faker-js/faker/blob/next/src/definitions/phone_number.ts#L13)

It should list the supported replacements.



> Q2. What will be the `@see` jsdoc for the deprecated function. `replaceSymbols`?

I dont think that we need one. The deprecation message can cover the string replace. Maybe we can refer to the new helpers regex method.

> Q3. With deprecation, will there be any change in the tests? Should we remove tests or not?

Tests shouldn't be removed. We might have to change some of them slightly (test snapshots etc).

**Comment by suyashgulati** [comment]
Thanks for the prompt replies

> > Q2. What will be the `@see` jsdoc for the deprecated function. `replaceSymbols`?
> 
> I dont think that we need one. The deprecation message can cover the string replace. Maybe we can refer to the new helpers regex method.

One thing I need help on, I might not be aware of `new helpers regex method`
Can you point me to that?

**Comment by ST-DDT** [comment]
Sure. https://fakerjs.dev/api/helpers.html#fromregexp

**Comment by matthewmayer** [comment]
The main reason for the existence of this method seems to be handling North American phone numbers which need the "no 0 or 1 in this position" symbol `!`. So maybe if we come up for a smarter way to deal with those in #2303 this method would no longer be needed.

**Comment by ST-DDT** [comment]
faker.helpers.fake would probably work.

**Comment by matthewmayer** [comment]
Maybe it would be best to keep the current implementation but only as an internal helper for phone number patterns? No longer expose it in helpers module after deprecation.

**Comment by ST-DDT** [comment]
@suyashgulati Are you still interested in this? 
We would like to wrap up v8 this week/shortly. Are you able to create a PR for the issue this week?

ToDos:
- Deprecate helpers.replaceSymbolWithNumber
- Move the current implemenation to an internal function similar to helpers.regexpStyleStringParse
- Replace all current usages of replaceSymbolWithNumber with the internal function
- Suggested replacements (for the deprecation message): `string.replace(/#+/g, (m) => faker.string.numeric(m.length));`

**Comment by suyashgulati** [comment]
@ST-DDT Yes I am still up for it. Thanks for the detailed todos. I wasn't clear about the expectation after the open ended discussion.
I will get into this shortly. Thanks.
