### ISSUE TITLE
Community providers aren't reproducible

### ISSUE THREAD

**Issue by LornaAS93** [faker-js/faker#1995]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Minimal reproduction code

```

```

### Environment Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 24.72 GB / 32.00 GB
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.14393.2007
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

other

**Comment by ST-DDT** [comment]
This doesn't look like JavaScript to me. Are you sure you opened the issue on the correct repository?

Also which community providers are you referring to?
