### ISSUE TITLE
More metadata for each locale

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2012]
follows on from #1978 
related to #1984 

I would like to see more metadata added for each locale, for example: 

```js
{
title:"German (Austria)",
endonym:"Deutsch (Österreich)", //in native language
code:"de_AT", //same as locale key
language:"de", //ISO_639-1
country:"AT", //ISO 3166-1 alpha-2. omitted if no country
rtl:false, //right-to-left
script:"Latn" //ISO_15924
}
```

I would be happy to implement this but maybe can get some feedback on the naming of the keys and values first?

**Comment by Shinigami92** [comment]
Especially the `code` can be used again for improved real checks for https://github.com/faker-js/faker/blob/9bf0a6d724c9503e104f307781db063b0afbd5b6/test/locale-imports.spec.ts#L15-L17
(and below)

**Comment by ST-DDT** [comment]
Do we require all fields?
Because if we do then we make creating custom locales harder and harder.
There are two approaches to that problem:
1. Make MetadataDefinitions optional and Partial and only require it for our own locales.
2. Create a customMetadata method or similar that can be used to create Metadata instances more easily.

I somewhat prefer 1.

**Comment by matthewmayer** [comment]
> Do we require all fields? Because if we do then we make creating custom locales harder and harder. There are two approaches to that problem:
> 
> 1. Make MetadataDefinitions optional and Partial and only require it for our own locales.
> 2. Create a customMetadata method or similar that can be used to create Metadata instances more easily.
> 
> I somewhat prefer 1.

also prefer 1.

**Comment by matthewmayer** [comment]
i think all built in locales (except base) should be able to fill in all properties except for country, which would only be for say en_AU and not en.

**Comment by matthewmayer** [comment]
might also need an optional "variant" to handle en_AU_ocker and en_BORK
