### ISSUE TITLE
loremflickr.com seems to be behind an authwall now

### ISSUE THREAD

**Issue by mcmxcdev** [faker-js/faker#2014]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Not sure if this is a temporary problem on their end or intentional, but we are unable to receive any images back anymore.

In our case, this is a problem when using `faker.image.abstract()` method.

### Additional Context

![image](https://user-images.githubusercontent.com/16797721/229375585-9f5f087e-9e80-4e40-bd8a-6b7dee72572c.png)

### Environment Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 8.37 GB / 30.72 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.volta/tools/image/node/18.14.1/bin/node
    npm: 9.3.1 - ~/.volta/tools/image/node/18.14.1/bin/npm
  Browsers:
    Brave Browser: 111.1.49.132
    Chrome: 111.0.5563.146
  npmPackages:
    @faker-js/faker: ^7.6.0 => 7.6.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by EricAgnitsch** [comment]
I thought I was going crazy lol. I wonder if this issue needs to be opened https://github.com/xvladqt/Faker-LoremFlickr instead? Hasn't been committed to in 3 years though :/

**Comment by edu-nixon** [comment]
> I thought I was going crazy lol.

Yes, me too, our dev environment is not looking too good.

This is an alternative that seems solid https://picsum.photos/

**Comment by ST-DDT** [comment]
In the upcoming v8 (currently only available as alpha) we have a new method explicitly for picsum photos.
https://next.fakerjs.dev/api/image.html#urlpicsumphotos

**Comment by ST-DDT** [comment]
The ruby team has the same issue, so I link their issue here as well, maybe somebody knows what is going on there:

- https://github.com/faker-ruby/faker/issues/2738

**Comment by matthewmayer** [comment]
i sent a DM to https://twitter.com/MastaBaba who maintained it to see if this is a deliberate removal or a temporary bug

**Comment by matthewmayer** [comment]
He replied

> Hi. No. The hosting provider was having an issue. The site should be back up and running.

**Comment by Shinigami92** [comment]
> In the upcoming v8 (currently only available as alpha) we have a new method explicitly for picsum photos.
> 
> https://next.fakerjs.dev/api/image.html#urlpicsumphotos

Just for the protocol: this won't had worked for the user's need of 'abstract' category 
Flickr is our only provider having categories

**Comment by matthewmayer** [comment]
All the category methods are deprecated though right?

**Comment by Shinigami92** [comment]
> All the category methods are deprecated though right?

There is still urlLoremFlickr

**Comment by matthewmayer** [comment]
The deprecation message for faker.image.abstract() etc points to faker.image.url() which doesn't support a category. 

Maybe we should change that to point to faker.image.urlLoremFlickr instead then?
