### ISSUE TITLE
Improve deprecation message for faker.image.abstract() etc

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2019]
The deprecation message for `faker.image.abstract()` etc points to `faker.image.url()` which doesn't support a category. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/152770/229682127-7335d5b0-d53b-4f49-aba2-10d4a68bb4f8.png">

_Originally posted by @matthewmayer in https://github.com/faker-js/faker/issues/2014#issuecomment-1494386708_

Maybe we should change that to point to faker.image.urlLoremFlickr({category:"abstract"}) instead then, since only this provider supports categories?

Alternatively faker.image.url() could be modified to accept a category parameter (in which case it would always use LoremFlickr instead of Picsum or LoremFlickr alternately)

**Comment by ST-DDT** [comment]
**Team Decision**

We want this.

- Add links to `faker.image.urlLoremFlickr({category})`
- Add `@see faker.image.url "If you just want an image"`
- Add `@see faker.iamge.urlLoremFlickr "If you want an image from loremflickr giving your more options for requesting a matching one."`
