### ISSUE TITLE
Merge faker.location.street() and faker.location.streetName()

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2020]
### Clear and concise description of the problem

From just the method names, it is confusing what each method does.

- https://next.fakerjs.dev/api/location.html#street
- https://next.fakerjs.dev/api/location.html#streetname

It also causes issues when a locale does not have a street_name_pattern or street_name locale file.

### Suggested solution

Merge both methods into one. (Not sure about the name yet)

````ts
faker.location.streetName({ allowGenerated: boolean = true });
````

### Alternative

- Rename the methods to account for them generating real and generated street names respectively.

### Additional context

Part of #1346

- #1346

**Comment by matthewmayer** [comment]
This one i'd consider not having a boolean parameter, as "real" and "generated" street names seem blurrier than cities. People cannot usually tell at a glance if a street name is real or generated, unlike with a city, and there are common real street names that repeat in a country.

**Comment by ST-DDT** [comment]
**Team Suggestion**

- We will merge both methods into one. Most likely `street()`
- We will start without a generated/fictional parameter and will add that back when users request them. (This avoids breaking the API when removing the parameter if unneeded)
- We will adjust the locale data name to explicitly refer to `street_pattern` instead of just `street`.

**Comment by ST-DDT** [comment]
**Team Decision**

We want this for v8.0.
