### ISSUE TITLE
EPIC: Add JSDoc descriptions

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#203]
### Clear and concise description of the problem

Most (if not all) of the functions already have JSDoc, but these are just simple e.g. `@param <fieldName>` without the descriptive text.
We found some documentation like https://github.com/faker-js/faker/pull/160, https://fakerjs.dev/api/datatype and e.g. these [schema definitions](https://github.com/faker-js/faker/blob/a973ee1ce64d2b593f64b633e927382280da8f27/src/internet.ts#L17-L180) that were just for generating documentation.

### Suggested solution

We would like to write these messages to the JSDoc comments, so that IDEs like VSCode can provide them via tooltips.

### Additional context

After this is done, we think that we can remove the schema definitions.

| Module      | Assignees   | #PR        | Done |
| ----------- | ----------- | ---------- | ---- |
| address.ts  | @mbokinala, @ST-DDT  | #230       |  ✔️ |
| animal.ts   | @mbokinala  | #250, #417 | ✔️   |
| commerce.ts | @ST-DDT     | #351       | ✔️ |
| company.ts  | @ST-DDT     | #423       | ✔️   |
| database.ts | @ST-DDT     | #424       | ✔️   |
| datatype.ts | @pkuczynski | #337       | ✔️   |
| date.ts     | @ST-DDT     | #427       | ✔️   |
| fake.ts     | @ST-DDT     | #406       | ✔️   |
| finance.ts  | @ST-DDT     | #434       | ✔️   |
| git.ts      | @ST-DDT     | #435       | ✔️   |
| hacker.ts   | @ST-DDT     | #436       | ✔️   |
| helpers.ts  | @ST-DDT     | #442 | ✔️ |
| image.ts    | @ST-DDT     | #437       | ✔️   |
| internet.ts | @ST-DDT | #447 | ✔️ |
| lorem.ts    | @ST-DDT | #458  | ✔️ |
| mersenne.ts | @ST-DDT     | #438       | ✔️   |
| music.ts    | @ST-DDT     | #390       | ✔️   |
| name.ts     | @ST-DDT     | #391       | ✔️   |
| phone.ts    | @pkuczynski | #397       | ✔️   |
| random.ts   | @pkuczynski @ST-DDT  | #408 #562  | ✔️ |
| system.ts   | @pkuczynski | #298       | ✔️   |
| time.ts     | @pkuczynski | #288       | ✔️   |
| unique.ts   | @ST-DDT     | #439       | ✔️   |
| vehicle.ts  | @pkuczynski | #274       | ✔️   |
| word.ts     | @pkuczynski | #273       | ✔️   |

**Comment by mbokinala** [comment]
@Shinigami92 I can work on this

**Comment by import-brain** [comment]
@Shinigami92 Please assign to @mbokinala, thanks

**Comment by Shinigami92** [comment]
Please not that it is very much to do in this PR. Maybe split it and multiple contributors can open PRs, communicating here or via Discord who is on which part or so.
That would also be easier to review.

**Comment by mbokinala** [comment]
> Maybe split it and multiple contributors can open PRs, communicating here or via Discord who is on which part or so.

Sounds good, shall we coordinate it on Discord?

**Comment by bl0cknumber** [comment]
> > Maybe split it and multiple contributors can open PRs, communicating here or via Discord who is on which part or so.
> 
> Sounds good, shall we coordinate it on Discord?

Yup we actively discussing everything about faker there :)

**Comment by pkuczynski** [comment]
If you need some help, I can jump in... I am not using discord much, but I can follow on the comment here...

**Comment by Shinigami92** [comment]
Take a look at https://github.com/faker-js/faker/pull/230 and https://github.com/faker-js/faker/pull/250
Just do exactly that for the other modules :slightly_smiling_face:

**Comment by pkuczynski** [comment]
> Take a look at #230 and #250
> Just do exactly that for the other modules 🙂

Is there a list whos working on what, so I can put my name on it and avoid duplicating work?

**Comment by Shinigami92** [comment]
@pkuczynski https://github.com/orgs/faker-js/projects/2

**Comment by ST-DDT** [comment]
I' tackle music next.

**Comment by ST-DDT** [comment]
That one was fast. So I'll tackle name next.

**Comment by pkuczynski** [comment]
I am going from the "bottom" of the list. The only reason why I moved to `datatype` was becuase it's reused in `radnom` which I tackle next...

**Comment by ST-DDT** [comment]
I will tackle `fake` next.

**Comment by pkuczynski** [comment]
`lorem` and `internet` for me please :)

**Comment by ST-DDT** [comment]
I'll tackle `company` next.

**Comment by ST-DDT** [comment]
I'll update `database.ts` next.

**Comment by ST-DDT** [comment]
Next will be 'date.ts'

**Comment by ST-DDT** [comment]
`finance.ts` will be my next one.

**Comment by ST-DDT** [comment]
I `git` it.

**Comment by ST-DDT** [comment]
`hacker` incoming.

**Comment by ST-DDT** [comment]
I can `image`ine doing another file now.

**Comment by ST-DDT** [comment]
I feel like a `mersenne`ary right now.

**Comment by ST-DDT** [comment]
I couldn't think of a `unique` sentence to write here, just now.

**Comment by ST-DDT** [comment]
I would like to thank all our helpers that contributed their time to address these issues.
Once all PRs have been reviewed and merged, we can close this issue.
I will tackle the last unclaimed one now: `helpers`

**Comment by ST-DDT** [comment]
@pkuczynski Do you have time to create the jsdocs PRs for lorem and internet this week.

**Comment by pkuczynski** [comment]
This week might be hard. Go for it. Random I did most, I can finish that one

**Comment by ST-DDT** [comment]
Internet is now covered: #447

**Comment by ST-DDT** [comment]
Lorem is covered by #458

**Comment by ST-DDT** [comment]
I created the last PR for `random`.
