### ISSUE TITLE
Don't allow faker.location.buildingNumber() to start with a 0

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2031]
### Clear and concise description of the problem

Building numbers that start with a zero lead to addresses like '013 Schultz Circles' which look incorrect.

```
faker.helpers.multiple(faker.location.buildingNumber, {count:100}).filter(x=>x.startsWith("0"))
[
  '050',   '01460', '07806',
  '001',   '05217', '0670',
  '07971', '076',   '03212',
  '034',   '062',   '005',
  '08119'
]
```

### Suggested solution

Change the patterns. As this uses replaceSymbolWithNumber we only have the choice of # (0-9) or ! (2-9) as special chars.

We can use a pattern like `['1##', '!##', '1###', '!###', '1####', '!####']` to ensure the numbers can start with any of 1-9, but not 0. This causes a slight side-effect that numbers starting with 1 will be more common. However Benford's law means thats not unrealistic anyway.

**Comment by ST-DDT** [comment]
IMO instead of doing this strange pattern duplication stuff we should rather change the implementation to not use replacewithnumber and instead use a simple regex replace with numeric without leading zero or something.

**Comment by ST-DDT** [comment]
See also

- https://github.com/faker-js/faker/issues/1994

**Comment by matthewmayer** [comment]
Note if you change the implementation it needs to handle a bunch of different localization patterns beyond simple numbers, i see the following unique patterns. Note the ones with slashes in, which have two numbers.

```
[
  ' #',      ' ##',     ' ###',  ' ####',
  ' s/n.',   '#',       '# bis', '##',
  '## bis',  '###',     '### I', '### II',
  '### III', '### bis', '####',  '#####',
  '###/#',   '###/2',   '###a',  '###b',
  '###c',    '##/#',    '##a',   '##b',
  '##c',     '#/#',     "'א#",   "'א##",
  "'ב#",     "'ב##",    ', #',   ', ##',
  'Bloc ##'
]
```

**Comment by ST-DDT** [comment]
**Team Decision**

- We will implement this via `arrayElement(patterns).replace(/#+/g, (m) => string.numeric(m.length)`
- The locale definition documentation will be extended to explicitly mention the `# -> number` transformation
- We will add a test that checks that it will not return leading zeros
