### ISSUE TITLE
Unify @see jsdoc tags

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#2057]
While working on some @see tags, because @ST-DDT and @xDivisionByZerox pointed that to me, I found that your current code base is very unstructurized in terms of the @see tag.

<img src="https://user-images.githubusercontent.com/7195563/232300106-d2798703-49d8-4084-b69c-eaa0b4239115.png" width="400px" />

Sometimes sentences are starting with an upper case, sometimes with a lower case.
Sometimes they end or end not with a period (`.`).
Sometimes they have no description at all.

**Comment by xDivisionByZerox** [comment]
If additional context after the `@see` tag should be a grammatically correct sentence. This means they should all that's with an uppercase letter and end with a period.
