### ISSUE TITLE
docs: scale the new faker panda logo up

### ISSUE THREAD

**Issue by JessicaSachs** [faker-js/faker#206]
(Once #205 is merged)

When we switched logos to be that panda magician, the sizes got a bit too small to look good. Can someone scale them up and vertically align the text so it looks good?

**Comment by poyea** [comment]
It seems the logo is aligned center already? (if you're referring to [README](https://github.com/faker-js/faker/blob/main/README.md))

**Comment by JessicaSachs** [comment]
Ah. In the docs https://fakerjs.dev there’s a logo in the top left corner
of the site. That logo looks really small and I want it to be bigger so
that it looks better.

**Comment by ST-DDT** [comment]
Which size would you like?
You can temporarily edit the size 
- by pressing F12 to open the developer console
- and pressing `Ctrl` + `Shift` + `C` and then clicking and thus selecting the logo
- then there should be a css/styles box on the right side of the developer tools, where you can adjust the `height` property.

I tried with 2rem for the logo and 1.8rem for the nav-bar-title which looked better for me, but we should potentially remove the sparks there.

On a sidenode, the favicon is hard to see in dark mode browsers.
![grafik](https://user-images.githubusercontent.com/1579362/150521022-a5aea7a1-e806-4586-a61f-1a498608f29e.png)

**Comment by prisis** [comment]
@ST-DDT i would go for 2rem for the logo :)

**Comment by ST-DDT** [comment]
> @ST-DDT i would go for 2rem for the logo :)
>
> For the favicon there is a way to have 2 favicon one for dark mode and one for the light one, maybe this is better?

Sounds like a good suggestion. I'm not familiar with that framework, do you know how to change it?
