### ISSUE TITLE
Document minimum Node for building with pnpm?

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2074]
Since the upgrade to pnpm 8 in #2039 it's not possible to build any more on Node 14 (see https://pnpm.io/installation#compatibility )

The library itself still seems to work fine on `^14.17.0`

Should this be documented somwhere e.g. in Contributing?

**Comment by Shinigami92** [comment]
I don't see this as valuable

The engines that are supported are "documented" here https://github.com/faker-js/faker/blob/bf67a219365d63c9430d4935056752859eaeaa8f/package.json#L134-L138

Also Node v14 will read EOL on 30. April 2023 (so in 9 days!)

v8.x will be the last version that supports Node v14 and TS below 5.0
In v9.0 we planned to force bump Node to >= v16 which will bring some new syntax sugar like `??=` and we can rely and ensure we are shipping no old TS breaking types

**Comment by ST-DDT** [comment]
I haven't tested it myself, but I assume trying to install/use pnpm 8 on node 14 will throw a hint that it requires node 16+. So they are likely to either upgrade or still have a pnpm v7 on their system.
With pnpm v7 they are still able to build the project, although the package lock file would be different. But I dont consider this a major problem.
