### ISSUE TITLE
Test failure for latitude

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2080]
FAIL  test/location.spec.ts > location > random seeded tests for seed 4743915782701865 > latitude() > returns latitude with min and max and default precision

**Comment by ST-DDT** [comment]
Please also link to the failing pipeline for more information.
https://github.com/faker-js/faker/actions/runs/4771531155/jobs/8483518852

**Comment by matthewmayer** [comment]
```ts
expect(
            latitude.toString().split('.')[1].length,
            'The precision of latitude should be 4 digits'
          ).lessThanOrEqual(4);
```
The problem is that this uses faker.number.float which occasionally (about every 10,000 test runs) will return say 2.0000 which is just returned as 2
```js
for (let i = 0;i<100000;i++) {
    const l = faker.location.latitude({ max: 5, min: -5 }); 
    if (l.toString().split(".")[1]==undefined) {
        console.log(l)
    }
}
```
```
-1
-3
-5
-4
5
-2
0
0
5
-2
2
-5
1
-4
-4
5
2
```

**Comment by ST-DDT** [comment]
We could remove the default precision from the call, since it is a number anyway?

**Comment by matthewmayer** [comment]
I would fix the test not the method. Expect no decimal point or no more than 4 digits after the decimal point.

**Comment by Shinigami92** [comment]
I'm also for fixing the test, not the method implementation

If we want to change the implementation, we should do this later and with a needs decision
