### ISSUE TITLE
date.anytime

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#2093]
Due to a requested reviews to use `between` instead of its own function, it slipped into the next branch that we dont have a method anymore that just provides a random date but without arguments/parameters
We need to fix that before releasing v8.0

https://github.com/faker-js/faker/pull/2053#issuecomment-1520404149

@ST-DDT suggested to add a `date.anytime` for that

**Comment by xDivisionByZerox** [comment]
Usually, we called those methods, that simply return "any" module-related value, `sample`. 

Examples:
- [faker.string.sample](https://github.com/faker-js/faker/blob/76c3080b758c3ced51d55e891396875a5004f5a8/src/modules/string/index.ts#L652)
- [faker.word.sample](https://github.com/faker-js/faker/blob/76c3080b758c3ced51d55e891396875a5004f5a8/src/modules/word/index.ts#L535)

**Comment by matthewmayer** [comment]
date.whenever

**Comment by ST-DDT** [comment]
The idea behind anytime is using it with optional options.
`anytime({ past: { days: 1}, future: { days: 42 } })`

**Comment by matthewmayer** [comment]
`faker.helpers.arrayElement([faker.date.past(), faker.date.future()])`

**Comment by Shinigami92** [comment]
> The idea behind anytime is using it with optional options. `anytime({ past: { days: 1}, future: { days: 42 } })`

In the first step, I would suggest to use `date.anytime()` or `date.between()`
Then in v8.1+ we can introduce params to date.anytime({ ... }) and move on from that

So for now we just "fix" the "there is no non-args date method"

Because we want to release (at least rc.0) end of this week :eyes:

**Comment by matthewmayer** [comment]
could this just be solved by adding defaults to the from and to parameters for between?

**Comment by ST-DDT** [comment]
> could this just be solved by adding defaults to the from and to parameters for between?

Theoretically yes, but from the method name you expect it to require parameters.
