### ISSUE TITLE
docs: document supported locales

### ISSUE THREAD

**Issue by bl0cknumber** [faker-js/faker#210]
### Clear and concise description of the problem

Document supported locales in https://github.com/faker-js/faker/tree/main/locale

Avoid related issues and discussions (e.g https://github.com/faker-js/faker/discussions/209)

### Suggested solution

Write supported locales in https://github.com/faker-js/faker/tree/main/locale

### Alternative

-

### Additional context

- Using table
- Add navigation to locale README in main README.

**Comment by Shinigami92** [comment]
We should do three things:

1. Add the supported locales in the VitePress docs
2. Add them in README.md (so that folks on the npm site can read it without the need of jump into docs but just searching with ctrl+f)
3. Add an enum/string literal that defines the locales and export it + type the functions in TS  
    But maybe it's possible to provide you own locale on demand from external, so it might need to be an `LiteralUnion` (see e.g. https://github.com/microsoft/TypeScript/issues/29729#issuecomment-471566609)

**Comment by Shinigami92** [comment]
Please also note that there is currently a huge PR that needs to be merged first, to reduce rebase/merge mess #169

**Comment by fncolon** [comment]
> We should do three things:
> 
> 1. Add the supported locales in the VitePress docs
> 2. Add them in README.md (so that folks on the npm site can read it without the need of jump into docs but just searching with ctrl+f)
> 3. Add an enum/string literal that defines the locales and export it + type the functions in TS
>    But maybe it's possible to provide you own locale on demand from external, so it might need to be an `LiteralUnion` (see e.g. [Literal String Union Autocomplete microsoft/TypeScript#29729 (comment)](https://github.com/microsoft/TypeScript/issues/29729#issuecomment-471566609))

Cool! especially number 3

**Comment by fncolon** [comment]
> Please also note that there is currently a huge PR that needs to be merged first, to reduce rebase/merge mess #169

Noted, thanks @Shinigami92

**Comment by Shinigami92** [comment]
Update to my comment: https://github.com/faker-js/faker/issues/210#issuecomment-1015139942

We now already have: https://github.com/faker-js/faker#localization and https://fakerjs.dev/api/localization#localization
We don't have an automatisation for updating these.
Also I think we should link from the README.md to the official docs, so we don't need to keep the README.md up to date.

Also we want inline dev docs for the Faker constructor `options.locale` + LiteralUnion typed

**Comment by ST-DDT** [comment]
I would like to do this.

**Comment by ST-DDT** [comment]
This is covered completely by #248 (TS) and #252 (docs)
