### ISSUE TITLE
Remove target=_blank from internal links in module overviews

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2100]
Actual:

1. Go to for example https://next.fakerjs.dev/api/commerce.html
2. Click productName in the overview
3. The link code is something like
```
<a href="https://next.fakerjs.dev/api/commerce.html#productname" target="_blank" rel="noreferrer"><code>productName()</code></a>
```

4. This causes the link to open in a new tab

Expected: It would be nicer if it just scrolled down the page to the correct place without openng a new tab

I think it worked previously when we just had #anchor links, but changing it to absolute links seems to cause the _blank to appear?

**Comment by ST-DDT** [comment]
Sorry for causing the regression on this one.
I will add tests for that so it won't happen again.
