### ISSUE TITLE
Notice of Legal action

### ISSUE THREAD

**Issue by wowowooooo** [faker-js/faker#213]
Stop your project now or I'll take action on them
Your project is unauthorized copy. It's completely illegal

**Comment by wowowooooo** [comment]
For all: Do not use this library. It's completely illegal. You should pay some money for it.

**Comment by wowowooooo** [comment]
I'm going to work with marak (original author of this project), to take legal action.

**Comment by MilosPaunovic** [comment]
Refer to [https://github.com/faker-js/faker/discussions/52]( https://github.com/faker-js/faker/discussions/52)

**Comment by damienwebdev** [comment]
To be perfectly clear. This project is explicitly legal under US law as per the license terms.

Additionally, @wowowooooo has no authority to make any such claim as he is not Marak, nor acting on behalf of Marak at Marak's request.
