### ISSUE TITLE
Move CONTRIBUTING to the guide?

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2139]
### Clear and concise description of the problem

https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md is not very prominent, or linked from the main documentation site. 

### Suggested solution

Move it to become a page of the documentation website at https://next.fakerjs.dev/guide/ ?
Leave a link in the CONTRIBUTING.md file to the new location for anyone browsing the repo directly

**Comment by Shinigami92** [comment]
IMO Contributing is something technical and to developers that are interested in working in GitHub.
The Contribution Guideline therefore is not really something that is relevant on the documentation website for Faker itself.
So if we want to do something like that, lets add somewhere a link in the docs to the CONTRIBUTING.md in the repo.

**Comment by matthewmayer** [comment]
sure, maybe a short page in the guide that points back in the other direction would work too.
