### ISSUE TITLE
Stuff for v8.0.1

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#2151]
- [x] Update playground
- [x] Switch Netlify
- [x] Update StackBlitz demo
- [x] Docs need to reference fakerjs.dev instead of next.fakerjs.dev
- [x] Improve v8.0.0 release with some notes about breaking changes and link to upgrading guide
- [x] Clean README.md (in v8 branch)

**Comment by matthewmayer** [comment]
Maybe also add a new announcement in https://fakerjs.dev/about/announcements.html ? Seems worthy of one.

**Comment by Shinigami92** [comment]
> Maybe also add a new announcement in [fakerjs.dev/about/announcements.html](https://fakerjs.dev/about/announcements.html) ? Seems worthy of one.

As well as social media post(s).

So yes, "but" this is not part for `v8.0.1` or like "we need to do that asap"
Quite the reverse, we want to do the announcement stuff and set v8 as stable only in a week or later.

**Comment by HonzaMac** [comment]
Can we also adjust Changelog.md? 

We received update via Renovate Bot, but changes show only 8.0.0 and 8.0.1, but nothing from previous alpha/beta release notes.

**Comment by Shinigami92** [comment]
> Can we also adjust Changelog.md?
> 
> We received update via Renovate Bot, but changes show only 8.0.0 and 8.0.1, but nothing from previous alpha/beta release notes.

This is unfortunately 🤔 the `Changelog.md` is auto-generated

Please read https://github.com/faker-js/faker/releases/tag/v8.0.1 and https://github.com/faker-js/faker/releases/tag/v8.0.0

**Comment by HonzaMac** [comment]
Can be the autogeneration fixed? It is confusing even when I read changelog file by self.

**Comment by matthewmayer** [comment]
Is there anything to stop us manually editing the Changelog.md (to merge all the alpha/beta/final release of 8.0.0 into one?)

**Comment by Shinigami92** [comment]
> Is there anything to stop us manually editing the Changelog.md (to merge all the alpha/beta/final release of 8.0.0 into one?)

It would need to be done within the PR when crafting a release, but we decided that we auto-generate the changelog but manually write the upper part of a release note if necessary
Also releases on GitHub can be edited and are not fixed to a released tag / npm dist folder

If renovate only parses Changelog.md files, then they should consider also at least to link to the GitHub release page

**Comment by matthewmayer** [comment]
Do you have an example of what renovate shows for a project with a dependency of faker 7.6.0 now that 8.0.1 is available?

**Comment by HonzaMac** [comment]
![image](https://github.com/faker-js/faker/assets/3055648/d1069fc6-17ad-4d7e-89f2-e86770d75272)

**Comment by Shinigami92** [comment]
Yeah... please open an issue at Renovate to tell them they should also link to GitHub Release Notes

In the meanwhile we will just try to to release so many alphas and betas maybe 🤔 ^^
