### ISSUE TITLE
Using Faker in react-native: `Can't find variable: Intl` error on android

### ISSUE THREAD

**Issue by bzhu-yara** [faker-js/faker#2171]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

After upgrading from version 7 to version 8, our react-native application crashes on Android devices.

We uses Expo 48.0.17, react-native 18.0.2 and tested on Android Tiramisu

Callstacks points to code here:

https://github.com/faker-js/faker/blob/614fd67f436546bafe1a1cafa579427255144274/src/modules/git/index.ts#L4

Assumption is that `Intl.DateTimeFormat` does not exists for react-native on android. 

### Environment Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 7.80 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.4
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

yarn

**Comment by Shinigami92** [comment]
This is unfortunate, caniuse.com has informed us that the majority supports it https://caniuse.com/?search=Intl.DateTimeFormat

Maybe you need a polyfill as a workaround? 🤔
A quick search-engine search directed me to e.g. this: https://snyk.io/advisor/npm-package/react-intl/functions/react-intl.DateTimeFormat

**Comment by matthewmayer** [comment]
Introduced here 

https://github.com/faker-js/faker/commit/99b6fb2c8d6d3e8ead53d7cc8d58bf615408860d

**Comment by matthewmayer** [comment]
You can reproduce a similar error in the Node CLI by deliberately overwriting Intl:
```
node
> Intl = null
> const {faker} = require("@faker-js/faker")
Uncaught TypeError: Cannot read properties of null (reading 'DateTimeFormat')
    at Object.<anonymous> (xxx/node_modules/@faker-js/faker/dist/cjs/modules/git/index.js:1:538)
```

**Comment by matthewmayer** [comment]
i added a tentative PR at #2172 which should mean Faker can be imported without crashing if Intl is not present, only the specific `faker.git.commitDate` and `faker.git.commitEntry` will throw a FakerError if the Intl methods are not available.

**Comment by matthewmayer** [comment]
@bzhu-yara could you confirm that upgrading to 8.0.2 fixes the crash?
