### ISSUE TITLE
Documentation for number.int default max value is not correct

### ISSUE THREAD

**Issue by dephiros** [faker-js/faker#2175]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

We are migrating from Faker 7 to Faker 8 and noticed deprecation warning for `datatype.number` to `number.int`
When applying the change to `number.int`, the [number generated is much larger than `min + 99999` as specified in the doc](https://fakerjs.dev/api/number.html#int) which cause our db test to break

Seems like it relates to https://github.com/faker-js/faker/issues/1598 but the doc was not updated

### Environment Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 16.33 MB / 16.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 14.17.6 - ~/Library/Caches/fnm_multishells/1601_1684935268559/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/Library/Caches/fnm_multishells/1601_1684935268559/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Firefox Developer Edition: 113.0
    Safari: 16.4
  npmPackages:
    @faker-js/faker: ^8.0.1 => 8.0.1
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

yarn

**Comment by matthewmayer** [comment]
Agreed, docs are wrong. It should be Number.MAX_SAFE_INTEGER https://github.com/faker-js/faker/blob/46b658524fb811bf9642293b4633a345459d4c0f/src/modules/number/index.ts#LL76C28-L76C51

**Comment by matthewmayer** [comment]
Probably the new bounds should also be noted in the migration guide here https://github.com/faker-js/faker/blob/46b658524fb811bf9642293b4633a345459d4c0f/docs/guide/upgrading.md?plain=1#L281

**Comment by Shinigami92** [comment]
This should go into `v8.0.2`
Can you (@dephiros) open a PR for this?

**Comment by dephiros** [comment]
> Can you (@dephiros) open a PR for this?

I am happy to. Can someone point me to where the doc is? Couldn't find in the /doc folder.

Can also poke around a bit more

**Comment by Shinigami92** [comment]
> I am happy to. Can someone point me to where the doc is? Couldn't find in the /doc folder.
> 
> Can also poke around a bit more

It's there: https://github.com/faker-js/faker/blob/614fd67f436546bafe1a1cafa579427255144274/src/modules/number/index.ts#L67

**Comment by dephiros** [comment]
sorry missed it the first time because I saw the larger number :)
```
options.max Upper bound for generated number. Defaults to `Number.MAX_SAFE_INTEGER`.
```
PR incoming

**Comment by Shinigami92** [comment]
> sorry missed it the first time because I saw the larger number :)
> 
> ```
> options.max Upper bound for generated number. Defaults to `Number.MAX_SAFE_INTEGER`.
> ```

That's also possibly the reason why this slipped into v8.0 :slightly_smiling_face:

**Comment by matthewmayer** [comment]
This doesn't seem to show up in https://fakerjs.dev/api/number.html#int yet

Is an extra step needed to update the docs after releaae?

**Comment by Shinigami92** [comment]
> This doesn't seem to show up in [fakerjs.dev/api/number.html#int](https://fakerjs.dev/api/number.html#int) yet
> 
> Is an extra step needed to update the docs after release?

Ah! I know what to do
I need to put the v8 branch to the state of the next branch
