### ISSUE TITLE
Document as own website

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#22]
Serve a documentation as own website.

We could e.g. use VitePress for that.
Happy to help if decision was made what to use for that website.
For now it would be enough to use `gh-pages`.

**Comment by damienwebdev** [comment]
I believe @JeffBeltran mentioned a docs website of some kind that he has already put together?

**Comment by JeffBeltran** [comment]
Yeah if it makes sense I could move over the repo to the org.

**Comment by damienwebdev** [comment]
@JeffBeltran I would love (and maybe this is an eventual goal) to get these docs closer to the relevant code and eventually get your docs auto-generated from the codebase rather a separate repo.

**Comment by schalkventer** [comment]
Might even be worth looking at obtaining `faker.js.org` site via https://js.org/?

**Comment by prisis** [comment]
I can buy fakerjs.org or faker-js.org if its needed

**Comment by JessicaSachs** [comment]
Hey all, I've made contact and gotten approved by Netlify for free OSS hosting. https://faker.dev is owned currently and https://fakerjs.dev is available. Conversations are happening in the Discord around hosting and domain names.

@Shinigami92 I've started a Vitepress spike.

**Comment by damienwebdev** [comment]
Closing re: #80
