### ISSUE TITLE
Update of type of options parameter for date.past, date.future, date.soon and date.recent

### ISSUE THREAD

**Issue by maurer2** [faker-js/faker#2205]
Hello, I noticed that the types for `date.past`, `date.future`, `date.soon` and `date.recent` in the [api documentation for date](https://fakerjs.dev/api/date.html#past) still list "number" as a valid type for the options parameter.
This seems to be leftover from version 7. The code examples don't show this kind of usage and and when trying to use it that way, e.g. `faker.date.past(50)`, a deprecation notice about `faker.date.soon(days, refDate)` getting removed in version 9, is shown when running eslint.
It might be prudent to remove "number" from the union type and only show the type as an optional options object.

Example

Old:
```ts
faker.date.past(options?: number | {
  refDate: Date | number | string,
  years: number
} = {}, legacyRefDate?: Date | number | string): Date
faker.date.past() // '2021-12-03T05:40:44.408Z'
faker.date.past({ years: 10 }) // '2017-10-25T21:34:19.488Z'
faker.date.past({ years: 10, refDate: '2020-01-01T00:00:00.000Z' }) // '2017-08-18T02:59:12.350Z'
```

New
```ts
faker.date.past(options?: {
  refDate: Date | number | string,
  years: number
} = {}, legacyRefDate?: Date | number | string): Date
faker.date.past() // '2021-12-03T05:40:44.408Z'
faker.date.past({ years: 10 }) // '2017-10-25T21:34:19.488Z'
faker.date.past({ years: 10, refDate: '2020-01-01T00:00:00.000Z' }) // '2017-08-18T02:59:12.350Z'
```

I had a go at it here: https://github.com/faker-js/faker/compare/next...maurer2:faker-past-fix:next

Cheers

**Comment by ST-DDT** [comment]
Please note that the last signature is a union of the deprecated and non deprecated ones.
It solely exists for the documentation on our website.
The method itself works as expected for all signatures even the deprecated ones.

So this is mainly a docs issue.

Should we remove deprecated signatures from our api docs?
Alternatively we could list all signatures individually (e.g. via a tab view).
Suggestions welcome.

**Comment by matthewmayer** [comment]
assuming the deprecated signatures will be removed on the next major, this seems like a temporary docs issue which will be resolved once v9 lands.

**Comment by maurer2** [comment]
Okay, makes sense. Thanks. Maybe a warning message regarding the deprecated parameter could be shown somehow.

**Comment by asapluiz** [comment]
can i work on this project?

**Comment by maurer2** [comment]
Sure. Go ahead. Thanks.

**Comment by ST-DDT** [comment]
**Team Decision**

- The docs already contain a hint that the parameter is deprecated.
- We plan to switch the docs view to a tab per signature, better highlighting the individual ones.
