### ISSUE TITLE
Pet names

### ISSUE THREAD

**Issue by Erik-Bjerke** [faker-js/faker#2206]
### Clear and concise description of the problem

There aren't pet names

### Suggested solution

Add pet names

**Comment by ShenoyAman** [comment]
i would like to work on  this issue

**Comment by ST-DDT** [comment]
> i would like to work on this issue

Currently, we are still waiting on user interest here. We will notify you/everyone when this has gained enough traction.
If you are interested in this feature itself, please don't forget to upvote it.

**Comment by benrobinsonuk** [comment]
This would be very useful for us too!

**Comment by matthewmayer** [comment]
faker-ruby has https://github.com/faker-ruby/faker/blob/main/lib/locales/en/dog.yml `faker.creature.dog.name`

**Comment by derekmedrano** [comment]
coming here a year later to say yes I would love pet names

**Comment by matthewmayer** [comment]
This now has 9 upvotes, so it's approaching the point where it gets considered for implementation :) For those who would find this useful, would you just want a generic name that would work for any kind of animal ("Coco", "Max", "Shadow")? Or might you want ones which are specific for a type of animal like cats ("Whiskers", "Mittens", "Felix") etc? (if so, which animals?)

What would the main use-cases be? Like faking a website for a vet clinic? Or a dog-walking service? Or just for fun?

**Comment by Erik-Bjerke** [comment]
> This now has 9 upvotes, so it's approaching the point where it gets considered for implementation :) For those who would find this useful, would you just want a generic name that would work for any kind of animal ("Coco", "Max", "Shadow")? Or might you want ones which are specific for a type of animal like cats ("Whiskers", "Mittens", "Felix") etc? (if so, which animals?)
> 
> What would the main use-cases be? Like faking a website for a vet clinic? Or a dog-walking service? Or just for fun?

Both would be great. Being able to get generic pet names or specific names by type of animal.

**Comment by ST-DDT** [comment]
> Both would be great. Being able to get generic pet names or specific names by type of animal.

Please answer the following questions:

What would the main use-cases be? Like faking a website for a vet clinic? Or a dog-walking service? Or just for fun?

Which types of animals do you need the names for?

**Comment by hikariatama** [comment]
+1, I need pet names

**Comment by ST-DDT** [comment]
> +1, I need pet names

@hikariatama Please answer the following questions:

What would the main use-cases be? Like faking data for a vet clinic? Or a dog-walking service? Or just for fun?

Which types of animals do you need the names for?

**Comment by benrobinsonuk** [comment]
Testing a pet apps, dog walking, daycare, vets, pet sitters, kennels,
catteries, dog daycare, dog training, breeding and so.

Thanks,
Ben

**Comment by hikariatama** [comment]
> > +1, I need pet names
> 
> @hikariatama Please answer the following questions:
> 
> What would the main use-cases be? Like faking data for a vet clinic? Or a dog-walking service? Or just for fun?
> 
> Which types of animals do you need the names for?

I can't share the details due to NDA, but what I can share is that I need it for the mock data for one of my corporate projects

**Comment by ST-DDT** [comment]
For your usecase, are dog names different from horse/another animal names? Are there names that could be used for all pets?

**Comment by benrobinsonuk** [comment]
I think that's probably fine, thanks for that, I'll relay it to the team.

Thanks for your help.

Ben

**Comment by matthewmayer** [comment]
This now has 13 upvotes, and should be easy enough to implement. Suggest we start with just a generic pet name list for any kind of pet, and then if there's demand later we could add specific cat or dog names etc.

What should the method name be?

`faker.animal.pet()`
`faker.animal.petName()`
?

**Comment by ST-DDT** [comment]
I would go for `petName`, because then it is easier to add catName, dogName etc. in the future.
`pet` isn't as clear, because it could return a pet type as well.

**Comment by suyashgulati** [comment]
Can assign to me?

I would also request @ST-DDT if you can point me to a PR where any new method on any module was added. 

It will be a good starting point for me to understand what all would be required when new implementation is getting added. Basically to understand how a fully-complete PR should look like after I am done.

**Comment by xDivisionByZerox** [comment]
> I would also request @ST-DDT if you can point me to a PR where any new method on any module was added.

You can take a look at #3162, which is the latest new method I know about.
I highly encouraged you to have a read through our [Contribution Documentation](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md) regardless.

**Comment by suyashgulati** [comment]
Thanks @xDivisionByZerox 

Yes I have gone through the docs once, also had some refactoring PRs merged previously. 
Just wanted to glance on how a new implementation PR should look like.
