### ISSUE TITLE
Localization for Farsi/Persian lang doesn't work in faker.word 

### ISSUE THREAD

**Issue by atenadadkhah** [faker-js/faker#2209]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

I'm trying to insert some words into my database in Farsi language but whatever I use with *faker.word* like `faker.word.noun()` or `faker.word.adverb()` they all come in English language while I'm importing `@faker-js/faker/locale/fa`.

### Environment Info

```shell
-
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
We dont have a list of Farsi words, we only have the following data: https://github.com/faker-js/faker/tree/next/src/locales/fa

If you need Farsi words, please create a new PR to add them. In the meantime you can add them yourself locally:

````ts
fakerFA.rawDefinitions.word.adjective = [...];
// or by passing them to the faker constructor
new Faker({locale: [fa, {word: {adjective: [...] }}] });
````

**Comment by ST-DDT** [comment]
Thanks for your time and we are looking forward to your contribution.
I assign this issue to you in the meantime.

**Comment by atenadadkhah** [comment]
I created  a PR at https://github.com/faker-js/faker/pull/2210
