### ISSUE TITLE
Test: Fix failing test finance in win32 system

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#223]
### Describe the bug

The below test is failing in GitHub Workflow's CI and needs to be fixed.

This was discovered in #179

### Reproduction

Remove the conditional wrapper and see CI failing

### Additional Info

https://github.com/faker-js/faker/blob/80e8b3d4aec2e8944f7488a86f6b1ad4d2b2445d/test/finance.unit.js#L283-L302

**Comment by ST-DDT** [comment]
Is this obsolete since #235 is merged?
