### ISSUE TITLE
ESlint just wants to elimenate Faker-js... You guys got the same thin

### ISSUE THREAD

**Issue by ImaBadSlime** [faker-js/faker#2243]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

But my ESLint is very aggressive towards faker-js cause it thinks that faker is any

Im using VSCode with ESLint plugin and i see this on every code line that uses faker:
![image](https://github.com/faker-js/faker/assets/93201060/91cb36cc-3d4b-4c0e-865d-190199558d20)

Three rules trigger at once:
- @typescript-eslint/no-unsafe-member-access
- @typescript-eslint/no-unsafe-call
- @typescript-eslint/no-unsafe-assignment

Of course, I can just deactivate these rules, but it feels kinda wrong, because they're part of @typescript-eslint/recommended-requiring-type-checking

So, what should I do to avoid these rules triggering?

### Minimal reproduction code

Code is basic
```
import { faker } from "@faker-js/faker";
const myFakeName = faker.person.fullName();
```

### Environment Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @faker-js/faker: ^8.0.2 => 8.0.2
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
Could you please add where these errors show up for completeness sake?

**Comment by ImaBadSlime** [comment]
> Could you please add where these errors show up for completeness sake?

Thanks for noticing, I've added a screenshot

**Comment by xDivisionByZerox** [comment]
Can you please provide your eslint config file as well as your `package.json` file. If you can't share your `package.json` please provide the versions of:
- typescript
- eslint
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser

**Comment by ImaBadSlime** [comment]
I just reopened the vscode and ESLint stopped showing that errors
Seems, it's some sort of a problem with vscode or ESLint plugin itself

I think the case is closed 😁
