### ISSUE TITLE
Alpha versions should not be published as latest on npm

### ISSUE THREAD

**Issue by marvinroger** [faker-js/faker#225]
### Describe the bug

Currently, v6.0.0-alpha.3 is published on npm under the `latest` tag. I think doing `npm i @faker-js/faker` should install the latest stable, not the latest alpha. Therefore, I'd suggest publishing `v6.0.0-alpha.3` under the `alpha` tag (`npm publish --tag alpha`), and publishing a `v5.5.4` (exact content of v5.5.3) under the `latest` tag.

### Reproduction

Run `npm i @faker-js/faker`, it installs the latest alpha instead of the latest stable.

### Additional Info

Note that maybe there's a valid reason to do so, I might be missing context here, since the library situation was/is quite complicated. 😉

**Comment by Shinigami92** [comment]
You are right, but

> Note that maybe there's a valid reason to do so, I might be missing context here, since the library situation was/is quite complicated.

that is somewhat theoretically the state.
Cause we already explicitly decided to create a new major version, we wanted to "inform" folks that there is that new version and to help us test it.
You are still free to use `^5.5.3` as range for now and it will use the old version. But please help us test the new v6 version.
We didn't change runtime code for now and we plan to not introduce runtime changes for the final 6.0.0 initial release.
It just has native TS support right now and you don't need `@types/faker` anymore.
Please also note that there were already some TS fixed already that are merged but not release yet under `v6.0.0-alpha.4`
We will release this next alpha in the next few days (hopefully :smiley:) and it will have esm and cjs / tree-shaking support :tada: 

You may want to subscribe to #169 and #217 

We also have a nice kind of Roadmap Board: https://github.com/orgs/faker-js/projects/2

**Comment by marvinroger** [comment]
Alright, thanks for the quick reply! I'll let you close the ticket or leave it open for others to see.

**Comment by cdierkens** [comment]
> You are still free to use ^5.5.3 as range for now and it will use the old version. But please help us test the new v6 version.

I think the confusion comes when you run a new install. Testing the Alpha should be opt in, and probably not the default.

**Comment by Shinigami92** [comment]
@cdierkens https://jubianchi.github.io/semver-check/#/^5.5.3/6.0.0-alpha.1

**Comment by cdierkens** [comment]
> @cdierkens [https://jubianchi.github.io/semver-check/#/^5.5.3/6.0.0-alpha.3](https://jubianchi.github.io/semver-check/#/%5E5.5.3/6.0.0-alpha.3)

I wasn't arguing constraints. Constraints come into play when I already have a dependency in the `package.json`

But when I run `yarn add --dev @faker-js/faker` I would expect to get the latest non alpha or beta with the either the default prefix or `^` if I've configured that as my constraint prefix.

**Comment by marvinroger** [comment]
> Cause we already explicitly decided to create a new major version, we wanted to "inform" folks that there is that new version and to help us test it.

Personally, I can understand the situation right now, because the current v5 is tied to the old `@types/faker`, and it's important to get rid of this dependency so the project can start clean. Moreover, there are apparently no runtime code changes, so I'd say, for this transitional state, as long as it's exceptional, it's fine.

However, I hope future releases will indeed respect the `latest` tag to be the stable release, and that alpha and betas would be released under their respective npm tags.

**Comment by JessicaSachs** [comment]
As per the above, won't fix. Going forward things will be normal and latest will be a non-alpha, non-beta version.
