### ISSUE TITLE
Lowercase email

### ISSUE THREAD

**Issue by 23navi** [faker-js/faker#226]
### Clear and concise description of the problem

As the email is the combination of random fname and lname, the produced email returns a capitalised email.

### Suggested solution

Just make the output as lowercase before return.

**Comment by Shinigami92** [comment]
Not sure if it really worth it. Why not just use `faker.internet.email().toLowerCase()`?
It's easier to do it outside as e.g. "revert" back to the current behavior.

**Comment by bl0cknumber** [comment]
I think you can use built in support for string for that :)
