### ISSUE TITLE
Searching unique on website suggests page that does not exist

### ISSUE THREAD

**Issue by drozd-A** [faker-js/faker#2267]
When searching for "unique" on https://fakerjs.dev/, a suggestion is provided that seems to suggest there's a documentation page called "Unique". When I click on this suggestion, it takes me to the 404 page.

https://github.com/faker-js/faker/assets/48000208/02e70cb3-55f1-49df-b981-5e08dd61492d

**Comment by xDivisionByZerox** [comment]
I can confirm that this bug exists :+1:

**Comment by ST-DDT** [comment]
I tried to fix the error, but the new faker.helpers.unique method doesn't show up.

**Comment by ST-DDT** [comment]
The bug still exists. Should we just remove the search or is there anybody that would like to investigate this?

**Comment by matthewmayer** [comment]
So this uses a third party search right https://github.com/algolia/algoliasearch-client-javascript

How does it work, does it provide any way like a web dashboard to configure it and inspect your search index?

**Comment by ST-DDT** [comment]
Yes, we already removed the unique from there but it seems to be back.
I assume that either the next or v7/v6 branches bleed into the main side search index wise.

**Comment by matthewmayer** [comment]
How does Algolia get the data? Does it scrape the public web? Can you specify which domains and subdomains it scrapes?

**Comment by matthewmayer** [comment]
The search index in general seems outdated. For example if you search for fullname it returns the old name module not person.

**Comment by ST-DDT** [comment]
Well, if you search for iban (which is new), it shows that as well. So its more of a pollution than being outdated.

**Comment by matthewmayer** [comment]
iban has been there since 4.0.0

isbn is new and doesn't appear in search.

**Comment by ST-DDT** [comment]
Ups 😳 . Mental typo.

**Comment by ST-DDT** [comment]
**Team decision**

- Create search index per major version + next
