### ISSUE TITLE
How to generate random phone number?

### ISSUE THREAD

**Issue by Chen-T** [faker-js/faker#2300]
Before I used the python version,it can generate multiple types of data,no property was found for the Js version to generate the phone number.
if so, please let me know. Thank you.

**Comment by ST-DDT** [comment]
https://fakerjs.dev/api/phone.html#number

**Comment by ST-DDT** [comment]
Does that answer your question?

**Comment by Chen-T** [comment]
> Does that answer your question?

Yes, thank you very much. I need this guide.
