### ISSUE TITLE
Support ISO 3166-1 numeric as variant for the country code API

### ISSUE THREAD

**Issue by suhaibmujahid** [faker-js/faker#2302]
### Clear and concise description of the problem

Currently only 'alpha-2' (two letter code) and 'alpha-3' (three letter code) are supported. In many cases, the [`numeric`](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) representation (three digit code) is needed. 

### Suggested solution

Support `numeric` as a variant so the API can return the three-digit country code.

**Comment by RobinvanderVliet** [comment]
I created #2325 to resolve this issue.

**Comment by xDivisionByZerox** [comment]
Since this feature request reflects the complete ISO standard, I would recommend accepting this issue.
