### ISSUE TITLE
Make "types" point to "dist/types/index.d.ts" in package.json

### ISSUE THREAD

**Issue by jgoux** [faker-js/faker#2306]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Hello 👋,

Currently, the key "types" in your package.json is pointing to "index.d.ts" which doesn't exist.

The right location seems to be "dist/types/index.d.ts".

I noticed that by using https://github.com/lukasbach/monaco-editor-auto-typings and trying to load the types for Faker.

If there is no reason for it to point to "index.d.ts" I'll be happy to open a PR to fix it. 😄 

### Environment Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/Library/pnpm/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment]
We do set it to the correct file in the `typesVersions` field:

https://github.com/faker-js/faker/blob/7f0daf3ddaa8956dc393964362eb696e23dc57d6/package.json#L33-L40

See also https://github.com/faker-js/faker/pull/1878, https://github.com/faker-js/faker/pull/1966

- https://github.com/faker-js/faker/pull/1878
- https://github.com/faker-js/faker/pull/1966

So AFAICT it's more like a bug in that other library?!
Or do you have more insight into the package.json magic?

**Comment by Shinigami92** [comment]
We once tried to set it to `dist/types/index.d.ts` and this broke the whole package TS support
Since we reverted the change we had no more issues

What I learned in the meantime is, that cjs and mjs can be supported with `.d.cts` and `.d.mts` files directly placed beside their `.cjs` or `.mjs` files. But then we would need to duplicate every types file and we actually don't want that.
Before we do that, we might go full esm-only and start to ignore such niche cases.

**Comment by jgoux** [comment]
> We once tried to set it to `dist/types/index.d.ts` and this broke the whole package TS support Since we reverted the change we had no more issues
> 
> What I learned in the meantime is, that cjs and mjs can be supported with `.d.cts` and `.d.mts` files directly placed beside their `.cjs` or `.mjs` files. But then we would need to duplicate every types file and we actually don't want that. Before we do that, we might go full esm-only and start to ignore such niche cases.

I tried to test faker against `arethetypeswrong` but unfortunately it can't resolve wildcard subpaths 😄: https://arethetypeswrong.github.io/?p=%40faker-js%2Ffaker%406.3.1

I think @andrewbranch could help you figure out what the proper setup for your types should be and why setting it to `dist/types/index.d.ts` didn't work!

In the meantime, I will try to send a PR to https://github.com/lukasbach/monaco-editor-auto-typings to be able to parse `typesVersions`. 👍

**Comment by ST-DDT** [comment]
It looks like there is currently no todo on our side here.
