### ISSUE TITLE
faker.image.dataUri is not random

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2307]
faker.image.dataUri is not random, it always returns the same image (a grey rectangle with the provided width/height in text)

https://stackblitz.com/edit/faker-js-demo-quium5?file=index.ts

Source: https://github.com/faker-js/faker/blob/651d1a8c/src/modules/image/index.ts#L373

I also noted that the width x height text doesn't fit for small `width` parameters

---

_Originally posted by @ST-DDT in https://github.com/faker-js/faker/pull/2273#discussion_r1290432388_

**Comment by matthewmayer** [comment]
Possible options
- make the color random? (but only works if color is NOT provided)
- add a random word e.g. from `faker.lorem.word()` in addition to the width x height text?
- pick two points and add a random line or rectangle somewhere in the SVG?

**Comment by ghost** [comment]
Making the color random if it is not provided is a great idea.

I also like the other two ideas. A quite similar option would be to add a random shape somewhere in the SVG.

**Comment by ST-DDT** [comment]
I created an issue for the (other) image functions as well.

- https://github.com/faker-js/faker/issues/2314

**Comment by matthewmayer** [comment]
better idea we could put a random emoji in the middle instead of a random word, then its locale indepdendent and you don't need to worry about the text being too long.

**Comment by OmkarPednekar** [comment]
Hey @ST-DDT this my first time contributing to a Open Source Project
This is the code which I have added to generate random color if color option is not provided is this correct? It creates a random HEX Color code
![image](https://github.com/faker-js/faker/assets/74041929/f523aff3-1778-4b6a-ab71-14b0bf0743d5)

**Comment by ST-DDT** [comment]
Close but we dont use Math.random because we want reproducible values. So we usually use faker.helpers.arrayElement or faker.number.int for that.

For this case specifically we already have a method that can generate rgb colors: 
https://fakerjs.dev/api/color.html#rgb

**Comment by OmkarPednekar** [comment]
so I should use that?
![image](https://github.com/faker-js/faker/assets/74041929/4fd1e581-0fd7-40af-8166-948a77f3e9bd)

**Comment by ST-DDT** [comment]
I would probably inline that and omit the args matching the defaults but yes.
Does svg only support lowercase rgb colors and not upper or mixed ones?

**Comment by OmkarPednekar** [comment]
It supports all

**Comment by OmkarPednekar** [comment]
Please Check my PR: https://github.com/faker-js/faker/pull/2316

**Comment by matthewmayer** [comment]
Any thoughts on including an emoji or a random shape/line? if we're going to do changes to this method to make it more random may as well do it all in one PR.

**Comment by ST-DDT** [comment]
I think we could randomly use one of these overlays:

- a random word
- a random emoji
- a random shape

(plus a new textColor, featureColor, or whateverColor option)

**Comment by matthewmayer** [comment]
if we omit random word it will still work in the `base` locale

**Comment by ST-DDT** [comment]
Well, if we argue like that then what if we don't have any locale data?
Then only a shape will work.
Maybe a "shuffle + first working" concept might be more safe in that regard.

Would the "feature"/"overlay" replace the current dimension text? (or would it be a 4th option?)

**Comment by matthewmayer** [comment]
think the dimenson text is useful so i'd probably do it next to / below / above the existing dimension text
