### ISSUE TITLE
Remove defaults from image module

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2314]
### Clear and concise description of the problem

Currently most of the [image module's functions](https://fakerjs.dev/api/image.html#url) have defaults for their options.
These defaults originate from the legacy faker project and are arbitrarily chosen.

### Suggested solution

Remove the defaults and make them random to increase the variety of our generated data.
The options should remain optional.

### Alternative

Keep it as is.

### Additional context

Related:

- https://github.com/faker-js/faker/pull/2273#discussion_r1290437511 (new `type` option)
- https://github.com/faker-js/faker/issues/2307 (limited to `dataUri`)

**Comment by olrtg** [comment]
I would like to work on this later this day!

**Comment by ST-DDT** [comment]
> I would like to work on this later this day!

Thanks. Please note that this is schedulled for v9.0 and thus might take a while before it can be merged (At least 2 weeks).

**Comment by olrtg** [comment]
Sure! no worries. And please note that I may not be able to work on this today 😆 but will try!

**Comment by olrtg** [comment]
Hey! two questions. What about `urlLoremFlickr` and `urlPicsumPhotos`? Both have a default width/height also. Should I randomize those two too?

And the other question is, what method should I use to randomize those values? Do you want to use `arrayElements`? What would be the set of values? 🤔

**Comment by ST-DDT** [comment]
> What about `urlLoremFlickr` and `urlPicsumPhotos`? Both have a default width/height also. Should I randomize those two too?

Yes. Please.

> And the other question is, what method should I use to randomize those values? Do you want to use `arrayElements`? What would be the set of values? 🤔

I would probably go for faker.number.int between 1px and 4k. We can discuss the exact values when we have the PR.

**Comment by olrtg** [comment]
Great! thanks for the quick reply. Will work on that!
