### ISSUE TITLE
Did marak committed su1c1d3? (had to censor)

### ISSUE THREAD

**Issue by NotNotMarshall** [faker-js/faker#232]
### Describe the bug

Did marak committed su1c1d3? (had to censor)
Is he on dru9s or something? 

### Reproduction

Did marak committed su1c1d3? (had to censor)
Is he on dru9s or something? 

### Additional Info

Did marak committed su1c1d3? (had to censor)
Is he on dru9s or something?

**Comment by NotNotMarshall** [comment]
I'm worried

**Comment by bl0cknumber** [comment]
Nope still alive and enjoying life https://twitter.com/marak/status/1483809614453956609
