### ISSUE TITLE
Move mocha to jest

### ISSUE THREAD

**Issue by bl0cknumber** [faker-js/faker#233]
## Reduce package installation, cause difficulties for audit if the project dependencies become larger, make it the number of dependencies smaller as possible.

<html>
<body>

test runner | testing framework
-- | --
requires other libraries to work | no preconfiguration required
offers a huge dose of flexibility regarding test development | focused on simplicity
originally designed for Node.js | originally designed for React

</body>
</html>

## Jest has more users between 2020 and 2021, a larger community, and created directly by facebook and it's largest open source (potentially can't be unmaintained unless it's mature and doesn't need anything else)

![jest-vs-mocha-downloads (1)](https://user-images.githubusercontent.com/50759463/150197268-1af6354c-ff94-4ff5-9baa-306cd2dc0989.png)

![Capture](https://user-images.githubusercontent.com/50759463/150197880-4f3654cf-0877-4a1b-9989-21873036cbc4.PNG)

## Mocha critical disadvantages

- Cannot test a promisified functions without assertion
- No assertion count in results (see https://github.com/mochajs/mocha/issues/800#issuecomment-17230542)
- Not as many reporter options as Jest

**Comment by Shinigami92** [comment]
We already think about to move to [vitest](https://vitest.dev/)

**Comment by bl0cknumber** [comment]
> We already think about to move to [vitest](https://vitest.dev/)

There's @antfu on it :) , closing..
