### ISSUE TITLE
Can add `sideEffects: false` to `package.json`

### ISSUE THREAD

**Issue by haydenull** [faker-js/faker#2335]
Is it possible to add sideEffects: false in the package.json file?

This can help rollup with tree shaking.

For example, I want to use fakerjs in development mode but remove it in production mode.

```ts
import { faker } from '@faker-js/faker'

if (import.meta.env.DEV) console.log(faker)
```

When sideEffects is not set to false, even if the condition of if statement is false, faker will still be bundled together.

**Comment by ST-DDT** [comment]
What are the requirements for our code to use that safely?

**Comment by haydenull** [comment]
In web development, intercept API requests and use faker return random data.

However, in production mode, interception is not necessary.

**Comment by ST-DDT** [comment]
Sorry, thats not what I meant.
What requirements has sideEffect: false for the Faker code? (Why isnt it true by default if it is that good.)

**Comment by haydenull** [comment]
Because removing code during tree shaking is a risky behavior, if a package not specify sideEffects as false, bundlers like rollup will assume that the code in this package has side effects.

In order to ensure the proper functioning of the code, rollup will retain them during tree shaking.

Wether to set `sideEffects: false` depends on whether the code of faker has any side effects. No modifications to the source code are required.

However, I am not familiar with the code of faker, so I cannot make a judgment.

**Comment by ST-DDT** [comment]
> Wether to set `sideEffects: false` depends on whether the code of faker has any side effects.

What is considered a side effect? A Faker internally shared global? Or does side effect require interaction with a third party library like registering a plugin in prettier?

**Comment by haydenull** [comment]
I think for faker, the main question is wether it modifies window or global objects. Or wether it introduced other packages with side effects.

`sideEffects: false` instructs the bundler to remove this package if its exported content is not being used.

I think if my code doesn't use any methods exported by faker, removing faker from build output would not break the program. Therefore, it can be considered as having no side effects.

**Comment by matthewmayer** [comment]
even if harmless, if this affects the behavior of the bundler it should probably be considered a semver-major change.
