### ISSUE TITLE
Some credit card issuers are defunct

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2344]
https://fakerjs.dev/api/finance.html#creditcardnumber

Various issuers found in the en locale are defunct:

https://en.wikipedia.org/wiki/Solo_(debit_card)
https://en.wikipedia.org/wiki/Switch_(debit_card)
https://en.wikipedia.org/wiki/Laser_(debit_card)
https://www.crunchbase.com/organization/instapayment-inc

https://github.com/faker-js/faker/blob/next/src/locales/en/finance/credit_card/index.ts

These should probably be removed, but this is a breaking change so defer to 9.0

**Comment by xDivisionByZerox** [comment]
Currently, we do not include locale data in semantic versioning. If we can change the structure of our lcoale definitions without having a breaking change we should not treat this change as breaking IMO.

**Comment by matthewmayer** [comment]
faker.finance.creditCardNumber({issuer:"solo"})
'6767-4689-2489-3566-749'

If we just remove the definitions then creditCardNumber falls back to picking a random issuer instead. This is probably OK.
