### ISSUE TITLE
Clarify that location state refers to ISO 3166-2

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2360]
### Clear and concise description of the problem

Currently the definition of location.state is not very precise.

### Suggested solution

Mention that it should refer to [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2).

**Comment by ST-DDT** [comment]
There is one issue with at though:
The iso lists more than the 1. administrative level.
E.g. regions, capital city, territory, state, ...

**Comment by matthewmayer** [comment]
I would put some wiggle room in the description. Something like "*Generally* these are the ISO 3166-2 subdivisions for a country". 

Note not all locales have a country attached (e.g. en, ar, es)

**Comment by ST-DDT** [comment]
Yeah, I had something similar in my mind:

> State or first level admin area. Might take inspiration from ISO...

I'm not good at writing squishy definitions.
