### ISSUE TITLE
Adding a new locale without street_name definitions causes test failure

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2364]
Currently if you add a new locale with say just the person definitions, you get a test failure in

```
 FAIL  test/all_functional.spec.ts > functional tests > yo > location > streetName()
Error: The locale data for 'location.street_name' are missing in this locale.
  Please contribute the missing data to the project or use a locale/Faker instance that has these data.
  For more information see https://fakerjs.dev/guide/localization.html
 ❯ Object.get src/locale-proxy.ts:88:15
     86|         );
     87|       } else if (value === undefined) {
     88|         throw new FakerError(
       |               ^
     89|           `The locale data for '${categoryName}.${entryName.toString()}' are missing in this locale.
     90|   Please contribute the missing data to the project or use a locale/Faker instance that has these data.
 ❯ LocationModule.streetName src/modules/location/index.ts:228:39
 ❯ testAssertion test/all_functional.spec.ts:169:44
```

So either 
1. you have to add a dummy street_name file like in #2363
2. or add the new locale name to BROKEN_LOCALE_METHODS under location.streetName

Neither of these are particularly intuitive for a new contributor starting work on a new locale.

I'm not sure specifically why this method fails and not other methods in the location module?

**Comment by ST-DDT** [comment]
This likely caused by this:

https://github.com/faker-js/faker/blob/8e4ea6790df4b987d1a8c6d32d1eee6db924bed3/src/modules/location/index.ts#L220-L230

In combination with it missing from en as fallback

https://github.com/faker-js/faker/blob/8e4ea6790df4b987d1a8c6d32d1eee6db924bed3/src/locales/en/location/index.ts#L19-L23

**Comment by ST-DDT** [comment]
As a workaround we could temporarily provide a list for en.

**Comment by matthewmayer** [comment]
or set `streetName: '*',` in BROKEN_LOCALE_METHODS?

**Comment by ST-DDT** [comment]
There appears to be 19 files that contains these:
https://github.com/search?q=repo%3Afaker-js%2Ffaker+.%2Fstreet_name+path%3A%2F%5Esrc%5C%2Flocales%5C%2F%2F&type=code

**Comment by matthewmayer** [comment]
as the streetName() method is deprecated and these defintiions are now only used indirectly by street(), i think just changing the BROKEN_LOCALE_METHODS entry to `streetName: '*',` for the remainder of 8.x is the simplest solution to skip the checks.

**Comment by xDivisionByZerox** [comment]
I'll provide a PR implementing `streetName` in `en_GB`, `en_US` and `en` which will be represented as a combination from the 2 previous ones.

I'm a little confused why this has not been done so far.
