### ISSUE TITLE
Avoid political debate with disputed area's `default_country.ts`

### ISSUE THREAD

**Issue by CoolPlayLin** [faker-js/faker#2368]
As the title shown. `default country` would raise possible political issue due to disputed area. These issues including sovereignty issues in different countries. We should find a method to resolve political issue as much as possible to avoid unnecessary hassle.

These location including disputed areas, areas with autonomy, areas that want independence and etc.

Example
- https://github.com/faker-js/faker/blob/next/src/locales/zh_TW/location/default_country.ts
   - Value in ISO: 中国台湾(Taiwan, Province of China)
   - Value in file: Taiwan(R.O.C)

**Comment by ST-DDT** [comment]
Please describe which countries/files are you referring to?

**Comment by CoolPlayLin** [comment]
@ST-DDT I think there is more disputed area doesn't only Taiwan is also applicable this issue. So, the title doesn't seems right

**Comment by CoolPlayLin** [comment]
I've modified @ST-DDT .
If faker.js has found way to resolve it, this issue could do as template issue for PR with political issue in the future

**Comment by xDivisionByZerox** [comment]
`default_country` is not part of the "offical" locale data set. So those files are essentially dead. We should first find a use case for those or even get completly rid of them.
