### ISSUE TITLE
helpers.multiple fails with a generic error when the number of elements exceeds 2^32 - 1

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2374]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

When calling faker.helpers.multiple() with a value of or over 2^32 the method will fail with a generic error.

````txt
RangeError: Invalid array length
    at Function.from (<anonymous>)
    at V.multiple (file:///.../faker/dist/esm/chunk-5MJ2XURO.mjs:13:698)
````

### Minimal reproduction code

````ts
faker.helpers.multiple(() => 1, { count: Number.MAX_SAFE_INTEGER });
````

### Additional Context

Created after some testing for #2372

- https://github.com/faker-js/faker/discussions/2372

This issue is NOT about handling the absence of a required parameter.

### Environment Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz       
    Memory: 5.91 GB / 15.78 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.1.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2215.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @faker-js/faker: 8.0.2 => 8.0.2
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment]
We have to decide on how to proceed here:

1) Should we limit the max number of array elements?
2) To which value should we limit the number of elements to?
3) By throwing an error or limiting the length
4) faker.string.sample() has a limit (2^20), all other string methods don't, should we apply the same limit everywhere?

**Comment by ST-DDT** [comment]
**Team Decision**

- Revert limit on 2^20 for faker.string.sample()

**Comment by ST-DDT** [comment]
Created PR #2497 to address this.

- #2497

**Comment by xDivisionByZerox** [comment]
I will close this issue. #2497 has been merged and was first release in https://github.com/faker-js/faker/releases/tag/v8.3.0.
