### ISSUE TITLE
Improve deprecation message for faker.phone.number(format)

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2413]
> It would be nice if at least a few options were available before the deprecation took effect. We have an simple use case like `faker.phone.number('##########')`, which I think would be hard to replicate until this is complete?

the direct replacement for `faker.phone.number('##########')` is `faker.helpers.replaceSymbolWithNumber('##########')` - maybe the deprecation message should be modified to make that clearer?

_Originally posted by @matthewmayer in https://github.com/faker-js/faker/issues/1542#issuecomment-1730810322_

**Comment by ST-DDT** [comment]
FFR: https://github.com/faker-js/faker/blob/005369b29c7ee290a870396ff0acc85e3f715e10/src/modules/phone/index.ts#L37

https://github.com/faker-js/faker/blob/005369b29c7ee290a870396ff0acc85e3f715e10/src/modules/phone/index.ts#L52-L59

**Comment by ST-DDT** [comment]
This should potentially list [`faker.numeric()`](https://fakerjs.dev/api/string.html#numeric) and [`faker.helpers.fromRegexp()`](https://fakerjs.dev/api/helpers.html#fromregexp) as alternatives.

**Comment by brandon-pereira** [comment]
I had `faker.phone.number("+1 (403) ###-####"),` and I use the [phone package](https://www.npmjs.com/package/phone) to validate phone  numbers. After removing the formatter, phone numbers like `347.494.6136 x4935` which are returned were failing the validation, so I ended up using `faker.helpers.replaceSymbolWithNumber("+1 (403) ###-####")` instead and it seems to work, but YMMV

**Comment by ST-DDT** [comment]
**Team Decision**

- We will implement this for v8.2
