### ISSUE TITLE
window.faker on faker.dev website

### ISSUE THREAD

**Issue by andylacko** [faker-js/faker#2426]
### Clear and concise description of the problem

I couldn't test the lib in 60sec on the internet.

### Suggested solution

Inspired by lodash.com. Just assign `window.faker = faker `on the faker.dev web and write console.info('You can test faker by accessing it here from console'). There will be the most up-to-date lib directly on you web to test.

<img width="973" alt="image" src="https://github.com/faker-js/faker/assets/7139923/c46f1e81-ca19-4042-85fc-e5eb97f8d67c">

**Comment by ST-DDT** [comment]
Workaround: https://fakerjs.dev/new

**Comment by matthewmayer** [comment]
The library is a bit heavyweight to load it just in case someone opens the console. 

I think we could rename Ecosystem>StackBlitz to something like "Try it!"

**Comment by Jason-bolt** [comment]
Exactly right @matthewmayer, I believe the word `Ecosystem` is not clear for users to identify
