### ISSUE TITLE
Check eslint-plugin-unicorn rules to enable/configure/disable

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2439]
Followup on #2418 

- #2418 

Currently all the following rules are disabled because they cause issues in the code:

## Undecided

| Rule | Count | Status/PR |
| --- | ---: | --- |
| [`unicorn/prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md) | 232 | 🤔 - #3320 |

Last updated: 2023-10-07

## Rejected

| Rule | Count | Status/PR |
| --- | ---: | --- |
| [`unicorn/import-style`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/import-style.md) | 8 | 🔴 - #2901 - doesn't do anything for us |
| [`unicorn/no-nested-ternary`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-nested-ternary.md) | N/A | 🔴 - incompatible with prettier |
| [`unicorn/no-null`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-null.md) | N/A | 🔴 - incompatible with TypeScript | 
| [`unicorn/no-object-as-default-parameter`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-object-as-default-parameter.md) | 6 | 🔴 - [Unicorn-Issue](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2199) |
| [`unicorn/no-zero-fractions`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-zero-fractions.md) | 17 | 🔴 - #2453 |
| [`unicorn/numeric-separators-style`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/numeric-separators-style.md) | 131 | 🔴 - #2815 |
| [`unicorn/number-literal-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/number-literal-case.md) | N/A | 🔴 - incompatible with prettier |
| [`unicorn/prefer-string-slice`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-slice.md) | 75 | 🔴 - string.subtring is sometimes easier to understand - #3247 ~~#2814~~ |
| [`unicorn/prefer-ternary`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-ternary.md) | 8 | 🔴 - #2464 |

## Accepted

| Rule | Count | Status/PR |
| --- | ---: | --- |
| [`unicorn/catch-error-name`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/catch-error-name.md) | 3 | 🟢 - #2471 |
| [`unicorn/consistent-destructuring`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/consistent-destructuring.md) | 4 | 🟢 - #2462 |
| [`unicorn/consistent-function-scoping`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/consistent-function-scoping.md) | 12 | 🟢 - #3255 - Related: #2667 |
| [`unicorn/escape-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/escape-case.md) | 3 | 🟢 - #2469 |
| [`unicorn/explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/explicit-length-check.md) | 4 | 🟢 - #2455 |
| [`unicorn/filename-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md) | 1203 | 🟢 - #2492 |
| [`unicorn/no-array-callback-reference`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-callback-reference.md) | 6 | 🟢 - #2722 |
| [`unicorn/no-array-for-each`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md) | 28 | 🟢 - #2461 |
| [`unicorn/no-array-reduce`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md) | 8 | 🟢 - #2479 |
| [`unicorn/no-array-push-push`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-push-push.md) | 4 | 🟢 - #2454 |
| [`unicorn/no-await-expression-member`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-await-expression-member.md) | 6 | 🟢 - #2812 |
| [`unicorn/no-console-spaces`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-console-spaces.md) | 2 | 🟢 - #2447 |
| [`unicorn/no-for-loop`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-for-loop.md) | 2 | 🟢 - #2490 |
| [`unicorn/no-hex-escape`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-hex-escape.md) | 1 | 🟢 - #2440 |
| [`unicorn/no-instanceof-array`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-instanceof-array.md) | 1 | 🟢 - #2459 |
| [`unicorn/no-negated-condition`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-negated-condition.md) | 2 | 🟢 - #2507 |
| [`unicorn/no-new-array`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-new-array.md) | 1 | 🟢 - #2441 |
| [`unicorn/no-process-exit`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-process-exit.md) | 1 | 🟢 - #2448 |
| [`unicorn/no-useless-switch-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-switch-case.md) | 4 | 🟢 - #2508 |
| [`unicorn/prefer-array-flat-map`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-flat-map.md) | 2 | 🟢 - #2446 |
| [`unicorn/prefer-array-some`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-some.md) | 1 | 🟢 - #2451 |
| [`unicorn/prefer-at`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-at.md) | N/A | 🟢 - #2654 |
| [`unicorn/prefer-code-point`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-code-point.md) | 14 | 🟢 - #2509 |
| [`unicorn/prefer-date-now`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md) | N/A | 🟢 - #2419 |
| [`unicorn/prefer-export-from`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-export-from.md) | 74 | 🟢 - #3272 |
| [`unicorn/prefer-includes`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-includes.md) | 3 | 🟢 - #2463 |
| [`unicorn/prefer-module`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md) | 10 | 🟢 - #2510 |
| [`unicorn/prefer-native-coercion-functions`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-native-coercion-functions.md) | 1 | 🟢 - #2445 |
| [`unicorn/prefer-negative-index`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-negative-index.md) | 1 | 🟢 - #2512 |
| [`unicorn/prefer-node-protocol`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md) | N/A | 🟢 - #2420 |
| [`unicorn/prefer-number-properties`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md) | 23 | 🟢 - #2452 |
| [`unicorn/prefer-object-from-entries`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-object-from-entries.md) | 3 | 🟢 - #2443 |
| [`unicorn/prefer-optional-catch-binding`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-optional-catch-binding.md) | 1 | 🟢 - #2491 |
| [`unicorn/prefer-string-replace-all`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-replace-all.md) | N/A | 🟢 - #2653 |
| [`unicorn/prefer-spread`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-spread.md) | 51 | 🟢 - #2421 |
| [`unicorn/prefer-string-starts-ends-with`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-starts-ends-with.md) | 1 | 🟢 - #2442 |
| [`unicorn/prefer-top-level-await`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-top-level-await.md) | 4 | 🟢 - #2680 |
| [`unicorn/require-array-join-separator`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/require-array-join-separator.md) | N/A | 🟢 - #2813 |
| [`unicorn/switch-case-braces`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/switch-case-braces.md) | 51 | 🟢 - #2721 |
| [`unicorn/text-encoding-identifier-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/text-encoding-identifier-case.md) | 3 | 🟢 - #2465 |

Please leave a comment if you wish to tackle any of these.

---

Legend:
- 🤔 : This needs a decision whether we want to enable this.
- 🔴 : We will not enable this rule.
- 🟡 : We probably want to enable this rule, but maybe with additional configuration.
- 🟢 : We want to enable this rule. Contributions welcome.
- `#1234` : Reference to the related PR.

The above list can be updated using the following command:

````sh
pnpm run lint | grep 'unicorn/' | sed 's/.*unicorn/unicorn/' | sort | uniq -c | sed -E 's/ *(.*) unicorn\/(.*)/\| [`unicorn\/\2`](https:\/\/github.com\/sindresorhus\/eslint-plugin-unicorn\/blob\/main\/docs\/rules\/\2.md) \| \1 \| 🤔 \|/'
````

**Comment by ST-DDT** [comment]
Created PR #2419 for [`unicorn/prefer-date-now`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md)

- #2419

**Comment by ST-DDT** [comment]
Created PR #2420 for [`unicorn/prefer-node-protocol`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md)

- #2420

**Comment by ST-DDT** [comment]
Created PR #2421 for [`unicorn/prefer-spread`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-spread.md)

- #2421

**Note:** The rule is contested.

**Comment by ST-DDT** [comment]
Created PR #2440 for [`unicorn/no-hex-escape`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-hex-escape.md)

- #2440

**Comment by ST-DDT** [comment]
Created PR #2441 for [`unicorn/no-new-array`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-new-array.md)

- #2441

**Comment by ST-DDT** [comment]
Created PR #2442 for [`unicorn/prefer-string-starts-ends-with`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-starts-ends-with.md)

- #2442

**Comment by ST-DDT** [comment]
Created PR #2443 for [`unicorn/prefer-object-from-entries`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-object-from-entries.md)

- #2443

**Comment by ST-DDT** [comment]
Created PR #2444 for [`unicorn/require-array-join-separator`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/require-array-join-separator.md)

- #2444

**Comment by ST-DDT** [comment]
Created PR #2445 for [`unicorn/prefer-native-coercion-functions`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-native-coercion-functions.md)

- #2445

**Comment by ST-DDT** [comment]
Created PR #2446 for [`unicorn/prefer-array-flat-map`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-flat-map.md)

- #2446

**Comment by ST-DDT** [comment]
Created PR #2447 for [`unicorn/no-console-spaces`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-console-spaces.md)

- #2447

**Comment by ST-DDT** [comment]
Created PR #2448 for [`unicorn/no-process-exit`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-process-exit.md)

- #2448

**Comment by ST-DDT** [comment]
Created PR #2451 for [`unicorn/prefer-array-some`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-some.md)

- #2451

**Comment by ST-DDT** [comment]
Created PR #2452 for [`unicorn/prefer-number-properties`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md)

- #2452

**Comment by ST-DDT** [comment]
Created PR #2453 for [`unicorn/no-zero-fractions`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-zero-fractions.md)

- #2453

**Comment by ST-DDT** [comment]
Created PR #2454 for [`unicorn/no-array-push-push`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-push-push.md)

- #2454

**Comment by ST-DDT** [comment]
Created PR #2455 for [`unicorn/explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/explicit-length-check.md)

- #2455

**Comment by ST-DDT** [comment]
⚠️ We are unable to enable [unicorn/no-object-as-default-parameter](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-object-as-default-parameter.md) due to https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2199

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2199

**Comment by ST-DDT** [comment]
Created PR #2459 for [`unicorn/no-instanceof-array`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-instanceof-array.md)

- #2459

**Comment by ST-DDT** [comment]
Created PR #2461 for [`unicorn/no-array-for-each`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md)

- #2461

**Comment by ST-DDT** [comment]
Created PR #2462 for [`unicorn/consistent-destructuring`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/consistent-destructuring.md)

- #2462

**Comment by ST-DDT** [comment]
Created PR #2463 for [`unicorn/prefer-includes`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-includes.md)

- #2463

**Comment by ST-DDT** [comment]
Created PR #2464 for [`unicorn/prefer-ternary`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-ternary.md)

- #2464

**Comment by ST-DDT** [comment]
Created PR #2465 for [`unicorn/text-encoding-identifier-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/text-encoding-identifier-case.md)

- #2465

**Comment by ST-DDT** [comment]
Created PR #2469 for [`unicorn/escape-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/escape-case.md)

- #2469

**Comment by ST-DDT** [comment]
Created PR #2471 for [`unicorn/catch-error-name`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/catch-error-name.md)

- #2471

**Comment by ST-DDT** [comment]
⚠️ [`unicorn/better-regex`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/better-regex.md) is blocked by #2466

- #2466

**Comment by ST-DDT** [comment]
Created PR #2479 for [`unicorn/no-array-reduce`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md)

- #2479

**Comment by ST-DDT** [comment]
Created PR #2487 for [`unicorn/better-regex`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/better-regex.md)

- #2487

**Comment by ST-DDT** [comment]
Created PR #2490 for [`unicorn/no-for-loop`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-for-loop.md) 

- #2490

**Comment by ST-DDT** [comment]
Created PR #2491 for [`unicorn/prefer-optional-catch-binding`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-optional-catch-binding.md)

- #2491

**Comment by ST-DDT** [comment]
Created PR #2492 for [`unicorn/filename-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md)

- #2492

**Comment by ST-DDT** [comment]
Created PR #2507 for [`unicorn/no-negated-condition`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-negated-condition.md)

- #2507

**Comment by ST-DDT** [comment]
Created PR #2508 for [`unicorn/no-useless-switch-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-switch-case.md)

- #2508

**Comment by ST-DDT** [comment]
Created PR #2509 for [`unicorn/prefer-code-point`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-code-point.md)

- #2509

**Comment by ST-DDT** [comment]
Created PR #2510 for [`unicorn/prefer-module`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md)

- #2510

**Comment by ST-DDT** [comment]
Created PR #2511 for [`unicorn/prefer-top-level-await`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-top-level-await.md)

- #2511

**Comment by ST-DDT** [comment]
Created PR #2512 for [`unicorn/prefer-negative-index`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-negative-index.md)

- #2512

**Comment by ST-DDT** [comment]
Created PR #3203 for [`unicorn/no-object-as-default-parameter`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-object-as-default-parameter.md)

- #3203

**Comment by ST-DDT** [comment]
@faker-js/members, @faker-js/maintainers I'm unsure about the consistent function scoping one.

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v56.0.0/docs/rules/consistent-function-scoping.md

It basically wants us to move most inline functions to be standalone methods.

e.g.  convert from

````ts
  dish(): string {
    const toTitleCase = (s: string) =>
      s
        .split(' ')
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');

    return toTitleCase(
      this.faker.helpers.arrayElement(this.faker.definitions.food.dish)
    );
  }
````

to

````ts
const toTitleCase = (s: string) =>
      s
        .split(' ')
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');

[...]

  dish(): string {
    return toTitleCase(
      this.faker.helpers.arrayElement(this.faker.definitions.food.dish)
    );
  }
````

**Comment by ST-DDT** [comment]
Also, what are your thoughts regarding

- [unicorn/prefer-export-from](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-export-from.md?rgh-link-date=2023-10-07T12%3A42%3A37Z)
- [unicorn/prevent-abbreviations](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md?rgh-link-date=2023-10-07T12%3A42%3A37Z)

?

**Comment by Shinigami92** [comment]
> @faker-js/members, @faker-js/maintainers I'm unsure about the consistent function scoping one.
> 
> * [sindresorhus/eslint-plugin-unicorn@`v56.0.0`/docs/rules/consistent-function-scoping.md](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v56.0.0/docs/rules/consistent-function-scoping.md?rgh-link-date=2024-11-10T18%3A38%3A48Z)
> 
> It basically wants us to move most inline functions to be standalone methods.
> 
> e.g. convert from
> 
> ```ts
>   dish(): string {
>     const toTitleCase = (s: string) =>
>       s
>         .split(' ')
>         .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
>         .join(' ');
> 
>     return toTitleCase(
>       this.faker.helpers.arrayElement(this.faker.definitions.food.dish)
>     );
>   }
> ```
> 
> to
> 
> ```ts
> const toTitleCase = (s: string) =>
>       s
>         .split(' ')
>         .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
>         .join(' ');
> 
> [...]
> 
>   dish(): string {
>     return toTitleCase(
>       this.faker.helpers.arrayElement(this.faker.definitions.food.dish)
>     );
>   }
> ```

This makes sense, because instead of every single function call, only once the function will be created and than reused for multiple calls of the outer function.

**Comment by ST-DDT** [comment]
Created PR #3255 for [`unicorn/consistent-function-scoping`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/consistent-function-scoping.md)

- #3255

**Comment by ST-DDT** [comment]
Created PR #3272 for [`unicorn/prefer-export-from`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-export-from.md)

- #3272

**Comment by ST-DDT** [comment]
[`unicorn/prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md) is going to be a large PR and I'm not entirely convinced the variable renames help that much.

IMO `i` is a well accepted index keyword. And even if we would rename these cases we would still need lots of ignores.
I created a few small (maybe too small?) PRs to address some reasonable suggestions, we can discuss how to proceed, once these are merged.

**Comment by xDivisionByZerox** [comment]
> [`unicorn/prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md) is going to be a large PR and I'm not entirely convinced the variable renames help that much.
> 
> IMO `i` is a well accepted index keyword. And even if we would rename these cases we would still need lots of ignores. I created a few small (maybe too small?) PRs to address some reasonable suggestions, we can discuss how to proceed, once these are merged.

I'm with you on this one. [See my comment in #3315](https://github.com/faker-js/faker/pull/3315#pullrequestreview-2476241534). While you could argue about some of the suggestions could be valid, I'd much rather see time spend on actual features or bug fixes for our users than having to fight in discussions about variable name nitpicking.

**Comment by ST-DDT** [comment]
Finally 🥳 

I created the last PR for this issue: #3320 for [`unicorn/prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md)

- #3320
