### ISSUE TITLE
ts ECMAScript  Consider using 'export default' 

### ISSUE THREAD

**Issue by zbcms** [faker-js/faker#245]
./node_modules/@faker-js/faker/index.ts:4:1
Type error: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

  2 | import { Faker } from './lib';
  3 | const faker: Faker = new Faker({ locales: require('./lib/locales') });
> 4 | export = faker;
    | ^

update:
export default faker;

**Comment by Shinigami92** [comment]
Duplicate of #217 

We are already on it :slightly_smiling_face:

**Comment by Shinigami92** [comment]
Will leave this open, so no more folks are creating multiple duplicates

**Comment by Shinigami92** [comment]
We released 6.0.0-alpha.5 and this should be fixed
