### ISSUE TITLE
Add tags for previous versions

### ISSUE THREAD

**Issue by MasterOdin** [faker-js/faker#246]
While it's nice to see that all prior versions were published on NPM to make switching over easy, would it be possible to also see all tags be created on this repo as well? It should largely just be a matter of going backwards through the [package.json commit history](https://github.com/faker-js/faker/commits/main/package.json) and find the commits Marak did that were commented with `Bump v...` or `[dist] ...`.

The covered use case would be someone on an older version of faker.js, it'd be nice for them to have some way to go back to an older version to see the code that's there as they implement something.

Happy to do the leg work to put together the list of tags / commits if that'd help a committer run it against the repo, but want to confirm a maintainer would do this before spending time on it.

**Comment by ST-DDT** [comment]
Archive to the rescue:
This should at least cover some of the older tags
https://web.archive.org/web/20201113033557/https://github.com/Marak/faker.js/tags

I tried to find a fork with the tags, but couldn't find any yet.

**Comment by MasterOdin** [comment]
Ah cool, I never would have thought to check the web archive. It looks like the commits there mostly line up with the aforementioned named commits. It is missing 5.2.0 - 5.5.3, but that's a relatively few versions in the scheme of it to link up to commits manually.

**Comment by JessicaSachs** [comment]
Need anything else on this or can we close?

**Comment by MasterOdin** [comment]
@JessicaSachs Someone with push access to actually add the tags to this repo (https://github.com/faker-js/faker/tags)?

**Comment by ST-DDT** [comment]
The following tags have been restored using the commit messages related to the `package.json`:

- `v5.2.0`
- `v5.3.0`
- `v5.3.1`
- `v5.4.0`
- `v5.5.0`
- `v5.5.1`
- `v5.5.2`
- `v5.5.3`

**Comment by ST-DDT** [comment]
The tag `6.0.0-alpha.0` has been renamed to `v6.0.0-alpha.0` to match the other tags.

**Comment by ST-DDT** [comment]
I consider this done now.

**Comment by MasterOdin** [comment]
Thanks for your work on this! Will make go looking at older versions much easier. :+1:
