### ISSUE TITLE
docs: import faker so it is accessible from the console

### ISSUE THREAD

**Issue by aadibajpai** [faker-js/faker#247]
### Clear and concise description of the problem

One of the things I liked about the old faker docs was that while perusing the API docs, you could have an inbuilt demo by just opening the browser console and trying it out. I saw that wasn't the case on <fakerjs.dev> but it would be very helpful to have that!

### Suggested solution

We include faker in the page, so it is accessible from the console.

**Comment by import-brain** [comment]
Do you mean you would like a little sandbox/playground to test out Faker on the website? @JessicaSachs, isn't this already being implemented? I don't remember.

**Comment by import-brain** [comment]
@Shinigami92 With the new StackBlitz, should this be closed? Or should we build this separately?

**Comment by Shinigami92** [comment]
I will leave this decision fully to @JessicaSachs :slightly_smiling_face:

**Comment by Shinigami92** [comment]
In our last team meeting we come to the conclusion that faker is too big to be loaded in background into the docs and very few people would really know that this feature would exist or even use this.
Nowadays we have tools like StackBlitz and other playgrounds, so we direct you to use these tools instead.
