### ISSUE TITLE
Placeholder.com no longer provides placeholder images

### ISSUE THREAD

**Issue by bragle** [faker-js/faker#2477]
In March, placeholder.com was acquired by a warehouse space company and no longer serves placeholder images. I'd be happy to provide a PR, but I'm not sure how cases like this should be handled since there's no way to really deprecate the function

**Comment by ST-DDT** [comment]
Thanks for bringing this to our attention.

I think having a deprecation PR asap will raise the awareness of this change. Then we can check whether there is a replacement domain or whether we have to remove the method in v9.
We plan to release v8.2 tomorrow. So it would be nice to have the deprecation in there. Do you have enough free time to do the PR?

**Comment by ST-DDT** [comment]
FFR: 
- https://fakerjs.dev/api/image.html#urlplaceholder
- https://github.com/faker-js/faker/blob/fd6557e4/src/modules/image/index.ts#L280
- https://via.placeholder.com/150x180/FF0000/FFFFFF.webp?text=lorem

The images still seem to work.

**Comment by ST-DDT** [comment]
We should check first whether they plan to continue their service.

**Comment by xDivisionByZerox** [comment]
List of websites providing similar servies:

- [placehold.co](https://placehold.co/600x400?text=test)
- [place-hold.it](https://place-hold.it/600x300&text=test)
- [images.placeholders.dev](https://images.placeholders.dev/?width=600&height=400&text=test)
- [dummyimage.com](https://dummyimage.com/600x400/000/fff&text=test) - website is fludded with ad's but API seems to work fine

**Comment by bragle** [comment]
You're right. I may very well be mistaken. Would probably be a good idea to get in touch with the owner of placeholder.com first. Sorry for not doing a more thorough check. Maybe the owner just wanted to open a warehouse space company and kept the previous service running, hehe 😸

**Comment by ST-DDT** [comment]
**Team Decision**

Thanks for bringing this to our attention.
The API seems to work perfectly for now.
We will monitor the situation and consider adding alternative url providers.

**Comment by monatemedia** [comment]
![Image](https://github.com/user-attachments/assets/7397d686-9483-4a95-af93-b9482339c2c0)

Good evening.

Placeholder.com no longer works.

I used this work around in my Laravel application:

            // Generate random image URL with colors and text
            'image_path' => 'https://placehold.co/'
                . fake()->numberBetween(300, 800) . 'x' // Width random between 300 and 800
                . fake()->numberBetween(200, 600) . '/' // Height random between 200 and 600
                . fake()->safeColorName() . '/' // Background color
                . fake()->safeColorName() . // Text color
                '.png?text=' . fake()->word(), // Random text for the image (optional)

**Comment by itisuniqueofficial** [comment]
**Use `img.itisuniqueofficial.com` — A Much More Advanced, Faster & Powerful Image Placeholder Tool**

📄 **Documentation:**
[https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html](https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html
)
✅ Superior to `placeholder.com` in performance, customization, and speed.
✅ Optimized for developers, bloggers, and creators.
✅ Easy-to-use API for generating dynamic placeholder images instantly.

**Comment by matthewmayer** [comment]
> **Use `img.itisuniqueofficial.com` — A Much More Advanced, Faster & Powerful Image Placeholder Tool**
> 
> 📄 **Documentation:**
> [https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html](https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html
> )
> ✅ Superior to `placeholder.com` in performance, customization, and speed.
> ✅ Optimized for developers, bloggers, and creators.
> ✅ Easy-to-use API for generating dynamic placeholder images instantly.

You might want to propose this in a new issue since this issue is already closed.

**Comment by matthewmayer** [comment]
> > **Use `img.itisuniqueofficial.com` — A Much More Advanced, Faster & Powerful Image Placeholder Tool**
> > 
> > 📄 **Documentation:**
> > [https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html](https://www.itisuniqueofficial.com/2025/05/img-itisuniqueofficial-com-documentation.html
> > )
> > ✅ Superior to `placeholder.com` in performance, customization, and speed.
> > ✅ Optimized for developers, bloggers, and creators.
> > ✅ Easy-to-use API for generating dynamic placeholder images instantly.
> 
> You might want to propose this in a new issue since this issue is already closed. 

Ah sorry I see you already did in 

https://github.com/faker-js/faker/issues/3505

**Comment by iamjaydatt** [comment]
img.itisuniqueofficial.com – The Ultimate Image Placeholder Generator

Looking for a faster, cleaner, and more powerful placeholder generator than the rest? Try img.itisuniqueofficial.com – lightweight, super fast, and easy to use for developers, bloggers, and designers.

* Generate placeholders in any size and format
* Customize background, text, and colors
* Works instantly with simple URLs
* Faster than other placeholder tools

Learn how to use it here: [https://img.itisuniqueofficial.com/documentation.html](https://img.itisuniqueofficial.com/documentation.html)

**Comment by dhanjeerider** [comment]
They transferred to new domain lol https://placehold.co/ 😂

**Comment by rudraksha-avatar** [comment]
> They transferred to new domain lol https://placehold.co/ 😂

Dude, https://img.itisuniqueofficial.com/
 is actually a really good placeholder image service. It’s much faster than most others, and the main point is that they use SVG, which makes it super lightweight and really comfortable to use for websites.
