### ISSUE TITLE
feat(educational institutions) Generate educational institutions information

### ISSUE THREAD

**Issue by clicktodev** [faker-js/faker#2483]
### Clear and concise description of the problem

There's no way to generate names of educational institutions.

### Suggested solution

An educational institution object that contains properties such as name, creation date, etc.
It could also be localized, you can pass a country and it will generate institutions from that country.

**Comment by ST-DDT** [comment]
Can you please give an API and data example how these should look like?

**Comment by matthewmayer** [comment]
`faker.helpers.fake(["University of {{location.city}}","{{location.city}} College"])` would do a decent job of this as a workaround

**Comment by clicktodev** [comment]
@matthewmayer Thanks, that workaround should be enough
