### ISSUE TITLE
Float between 0 and 1 not working

### ISSUE THREAD

**Issue by josephzidell** [faker-js/faker#2522]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

I am using `float`
```ts
faker.number.float({min: 0.001, max: 0.999, precision: 3});
```

What I expect is ...
A number such as `.123`, `.725`, etc.

What actually happening is ...
```
No integer value between 0.0003333333333333333 and 0.33299999999999996 found.
```

### Minimal reproduction code

https://runkit.com/embed/zwyer39xttm8

### Environment Info

```shell
System:
  OS: Mac
  CPU: Intel
  Memory: _ / _
  Container: No
  Shell: bash
Binaries:
  Node: _ - /usr/bin/node
  Yarn: _ - /usr/bin/yarn
  npm: _ - /usr/bin/npm
npmPackages:
  @faker-js/faker: ^8.1.0 => 8.1.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

yarn

**Comment by ST-DDT** [comment]
[Documentation](https://fakerjs.dev/api/number.html#float)

The `precision` option refers to the steps/multiple of that the method uses.
There is no integer between min: 0.001 and max: 0.999 (especially none that is divisible by 3).

Is it possible that you meant `faker.number.float({min: 0.001, max: 0.999, precision: 0.001});` ?

**Comment by josephzidell** [comment]
Thank you for the clarification. I was confused by the term precision, because in RDBMSs, precision is a whole number representing the number of decimal places. Cheers for this amazing package! 🍻
