### ISSUE TITLE
Birthdate with default values return age less than 18

### ISSUE THREAD

**Issue by mumumilk** [faker-js/faker#2534]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

I was running into flaky tests in my application, and narrowed it down to faker's `date.birthdate` method.

According to the docs:

>The options to use to generate the birthdate. If no options are set, an age between 18 and 80 (inclusive) is generated.

But there are times that an age less than 18 years old is generated. This does not happen every time, but I was able to get a specific seed and refDate to reproduce the issue.

### Minimal reproduction code

https://stackblitz.com/edit/vitest-dev-vitest-md9oj6?file=test%2Fsuite.test.ts

### Environment Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 65.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.123
    Edge: 119.0.2151.46
  npmPackages:
    @faker-js/faker: ^8.2.0 => 8.2.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
I can confirm the bug.
