### ISSUE TITLE
Add options to make locations coherent

### ISSUE THREAD

**Issue by Akryum** [faker-js/faker#2568]
### Clear and concise description of the problem

Currently location functions such as `city()` are fully random.

### Suggested solution

Add options to pass a country or other contextual information about the location to make it plausible.

Example:

```js
faker.location.city({ countryCode: 'FR' })
```

**Comment by ST-DDT** [comment]
The city names are partially random due to them having patterns.
But the patterns and generated names refer to the selected locale. The default faker instance is EN.
If you need FR city names, use the `fakerFR` import instead.

https://fakerjs.dev/guide/localization.html

Does that help you?

**Comment by ST-DDT** [comment]
Closing, because no feedback has been provided.

Please use `fakerFR.location.city()` instead or please describe why that doesn't help in your case.
