### ISSUE TITLE
Pejorative Expression in Hungarian locale

### ISSUE THREAD

**Issue by dev-el-op** [faker-js/faker#2575]
I found a pejorative expression among the Hungarian adopted words. In line 8173 of the /src/locales/hu/word/noun.ts file, the word means b*tch in Hungarian. One of our testers noticed it when in a literal translation the web address of one of the example sales locations became https://unbred-b*tch.com/ in Hungarian.

**Comment by dev-el-op** [comment]
Okey, now i found like 15 of them in the same file 😅

**Comment by matthewmayer** [comment]
Yes these should be removed (we did this for English in https://github.com/faker-js/faker/discussions/1631 )

Would you be able to make a PR for removing any offensive vocabulary in hu locale?

**Comment by dev-el-op** [comment]
Absolutely, I can take care of removing any offensive vocabulary in the Hungarian locale. I'll aim to submit a pull request for this task within this week.

**Comment by ST-DDT** [comment]
I also noticed, that the [file](https://github.com/faker-js/faker/blob/next/src/locales/hu/word/noun.ts#L10620) is huge with 10620 lines. We should reduce that to 1000 entries (not sure though whether it should be in a separate PR for the pejorative expression removal).

**Comment by ejcheng** [comment]
> I also noticed, that the [file](https://github.com/faker-js/faker/blob/next/src/locales/hu/word/noun.ts?rgh-link-date=2023-12-11T18%3A52%3A46Z#L10620) is huge with 10620 lines. We should reduce that to 1000 entries (not sure though whether it should be in a separate PR for the pejorative expression removal).

I think separating the PRs would be better--- remove the pejorative expressions first, then reduce to 1000 entries.

**Comment by matthewmayer** [comment]
Might be better to reduce to 1000 first, then less hunting is required for the pejorative expressions!

**Comment by ST-DDT** [comment]
@dev-el-op Do you have time to create a PR that removes those expressions?

**Comment by ST-DDT** [comment]
@dev-el-op Any idea when you have time for this?

**Comment by ST-DDT** [comment]
I created https://github.com/faker-js/faker/pull/2816 to hopefully remove all offending words.

- https://github.com/faker-js/faker/pull/2816

If there are other offending words please tell me.
Otherwise we have to do that in a future PR.
