### ISSUE TITLE
Don't use deprecated phone.numer(format) parameter as an example for faker.helpers.fake

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2580]
https://github.com/faker-js/faker/blob/8013fa0404ceea2636544606beba8c996add7d57/src/modules/helpers/index.ts#L1420

We should replace this example with one that doesn't use a deprecated parameter.

**Comment by matthewmayer** [comment]
How about this, shows quoted strings, unquoted strings, and JSON

```faker.helpers.fake('My sister {{person.firstName(female)}} and my brother {{person.firstName("male")}} live at {{location.streetAddress({ "useFullAddress": true })}}')```

**Comment by ST-DDT** [comment]
Fixed in https://github.com/faker-js/faker/pull/2668

- https://github.com/faker-js/faker/pull/2668
