### ISSUE TITLE
add multipleOf to faker.number.int

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2584]
_Originally posted by @matthewmayer in https://github.com/faker-js/faker/pull/2581#discussion_r1431611815_
            
Similar to faker.number.float, faker.number.int should also support a multipleOf parameter

**Comment by Shinigami92** [comment]
**Personal opinion:** I'm not sure if this is needed at all, _just for symmetry_ is not a so good reason :thinking:  
We could discuss this in one of the next meetings

**Comment by matthewmayer** [comment]
I think the main advantage is it could be used in helpers.fake patterns for other methods.

**Comment by Shinigami92** [comment]
> I think the main advantage is it could be used in helpers.fake patterns for other methods.

This is a really good point :+1:

**Comment by matthewmayer** [comment]
For example in the new food module there was a description like "400g of delicious steak"

A menu might realistically have a 350g or 400g steak but not a 362g steak.

**Comment by ST-DDT** [comment]
**Team Decision**

- We want this
