### ISSUE TITLE
Can't download any of the images from faker.internet.avatar

### ISSUE THREAD

**Issue by LucaPaterlini** [faker-js/faker#2598]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Hello,
it seems none of the faker.internet.avatar are getting downloaded as per the image.
<img width="1680" alt="Screenshot 2024-01-09 at 10 08 48" src="https://github.com/faker-js/faker/assets/2988412/85de061b-6712-4682-b20d-73c9152ff574">

### Minimal reproduction code

https://github.com/LucaPaterlini/SampleFaker/tree/main its a simple repo
the component that use the faker is 
this one https://github.com/LucaPaterlini/SampleFaker/blob/main/src/components/RenderPropsFaker.tsx

### Environment Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 14.29 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    bun: 1.0.11 - /usr/local/bin/bun
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 113.0.1774.35
    Safari: 17.2.1
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by LucaPaterlini** [comment]
[sandbox example](https://codesandbox.io/p/github/LucaPaterlini/SampleFaker/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr64qoyz00063b6ji19yqjzc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr64qoyy00023b6jo9nhqdi6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr64qoyy00043b6j7rcn4f4f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr64qoyz00053b6jcbuxqbg0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr64qoyy00023b6jo9nhqdi6%2522%253A%257B%2522id%2522%253A%2522clr64qoyy00023b6jo9nhqdi6%2522%252C%2522activeTabId%2522%253A%2522clr652cxy00c93b6k7ckp4ovw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clr652cxy00c93b6k7ckp4ovw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clr64qoyz00053b6jcbuxqbg0%2522%253A%257B%2522id%2522%253A%2522clr64qoyz00053b6jcbuxqbg0%2522%252C%2522activeTabId%2522%253A%2522clr651jc100a33b6ksjgl3w9z%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr651jc100a33b6ksjgl3w9z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clr64qoyy00043b6j7rcn4f4f%2522%253A%257B%2522id%2522%253A%2522clr64qoyy00043b6j7rcn4f4f%2522%252C%2522activeTabId%2522%253A%2522clr651a8x007h3b6k0s3fho5b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr64qoyy00033b6j2zk539ty%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr64qq44000gediofzlg3b58%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clr64riiq008q3b6j87q5txr7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr651a8x007h3b6k0s3fho5b%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ST-DDT** [comment]
> [sandbox example](https://codesandbox.io/p/github/LucaPaterlini/SampleFaker/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr64qoyz00063b6ji19yqjzc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr64qoyy00023b6jo9nhqdi6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr64qoyy00043b6j7rcn4f4f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr64qoyz00053b6jcbuxqbg0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr64qoyy00023b6jo9nhqdi6%2522%253A%257B%2522id%2522%253A%2522clr64qoyy00023b6jo9nhqdi6%2522%252C%2522activeTabId%2522%253A%2522clr652cxy00c93b6k7ckp4ovw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clr652cxy00c93b6k7ckp4ovw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clr64qoyz00053b6jcbuxqbg0%2522%253A%257B%2522id%2522%253A%2522clr64qoyz00053b6jcbuxqbg0%2522%252C%2522activeTabId%2522%253A%2522clr651jc100a33b6ksjgl3w9z%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr651jc100a33b6ksjgl3w9z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clr64qoyy00043b6j7rcn4f4f%2522%253A%257B%2522id%2522%253A%2522clr64qoyy00043b6j7rcn4f4f%2522%252C%2522activeTabId%2522%253A%2522clr651a8x007h3b6k0s3fho5b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr64qoyy00033b6j2zk539ty%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr64qq44000gediofzlg3b58%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clr64riiq008q3b6j87q5txr7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr651a8x007h3b6k0s3fho5b%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Works for me (Tested in Firefox and Chrome).

![grafik](https://github.com/faker-js/faker/assets/1579362/a66437d1-f7c2-47f8-bae0-b262cfa52583)

Could you please include the error message that you are getting?

**Comment by LucaPaterlini** [comment]
Hello and thanks for your kind reply,
maybe there is a restriction on downloading images from Italy 🤔 

https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/28.jpg

^^ to reduce the issue even more the browser its not able to download the images from Cloudflare [ from Italy]

As per the previous image.

Connection timeout on images download

<img width="1680" alt="Screenshot 2024-01-09 at 11 01 48" src="https://github.com/faker-js/faker/assets/2988412/53d831ac-4649-4009-8f67-95f2f1057879">

**Comment by xDivisionByZerox** [comment]
Works for me as well. Although, my company's network blocked the request. Might be a firewall problem on your side?

**Comment by ST-DDT** [comment]
Try using [`faker.image.avatar()`](https://fakerjs.dev/api/image.html#avatar) instead.

**Comment by LucaPaterlini** [comment]
<img width="1680" alt="Screenshot 2024-01-09 at 11 24 59" src="https://github.com/faker-js/faker/assets/2988412/77215538-86ee-416e-be27-0ce367929eb1">

with faker.image.avatar a portion of them (like around 20) loads while the others go timeout

**Comment by ST-DDT** [comment]
Then maybe just use [`faker.image.avatarGitHub`](https://fakerjs.dev/api/image.html#avatargithub) that does not contain the ipfs set.

**Comment by LucaPaterlini** [comment]
Yes it works with avatarGithub,
Thanks for the reply
