### ISSUE TITLE
Add method to return random languages (ISO-639 data)

### ISSUE THREAD

**Issue by jeremyhofer** [faker-js/faker#2622]
### Clear and concise description of the problem

I am currently working on a project where I would like to return a random ISO-639 code in mock data. It would be great for faker to support this internally similar to `location.countryCode`

### Suggested solution

I'm not sure which module it may fit in well today, or if a new module may make the most sense, but my proposal would be to add a `language` or `languageCode` method within faker. The method would take as input a `variant` based on the ISO-639 standard, defaulting to ISO-639-1 (2 character) codes when called without parameters.

Link to the standard: https://www.loc.gov/standards/iso639-2/php/code_list.php

The variants I propose to be implemented are:
1. `639-1` - to return `639-1` 2 character codes
2. `639-2` - to return `639-2` 3 character codes

The additional sets - `639-3`, `639-4`, `639-5` - may also be implemented. Similarly, the English, French, and German language names as defined in the standard could be added as variants.

Alternative to the specific sets, an `alpha-2` and `alpha-3` variant approach could be taken where `alpha-2` would be the 639-1 code set and `alpha-3` may be the 639-2 set.

**Comment by matthewmayer** [comment]
compare #1548 (requesting full language names)

**Comment by ST-DDT** [comment]
I would probably put it in the location module.

Also we should probably close #1548 (as superseded by this), as this has a better description.

**Comment by matthewmayer** [comment]
The codes like "en" are not locale dependent so they should be in fakerbase

The language names are locale dependent however. So it would probably be two methods?

faker.location.languageCode() and faker.location.language()

**Comment by ST-DDT** [comment]
I thought about using something like `[{ name: English, alpha2: EN, alpha3: ENG }, { name: German, alpha2: DE, alpha3: DEU }]`.

As for the `base` I though about using the languages own name as the name there, but not sure about that.
`[{ name: English, alpha2: EN, alpha3: ENG }, { name: Deutsch, alpha2: DE, alpha3: DEU }]`

Reason being, that some language selection dropdowns show the name, but internally use the code in their data.

**Comment by matthewmayer** [comment]
I'd still make it two methods for consistency with .country() and .countryCode()

Anyway I agree with closing #1548 to keep discussion and upvotes in one place

**Comment by ST-DDT** [comment]
I added this to our meeting notes for discussion:

- `faker.location.countryCode({variant: 'alpha-2'})` vs `faker.location.countryCode().alpha2`
- Make the human readable "name" a variant instead of a separate method.

**Comment by matthewmayer** [comment]
Note that only a small number of languages have a 2 character code. Many more have a three character code.

**Comment by ST-DDT** [comment]
**Preliminary Team Decision**

- We will **wait for more user interest** or at least after the major changes for v9.0 have been done.
- We will change the countryCode (and languageCode) methods to return complex objects.
- The languageCode method has a parameter to filter for the presence iso2 codes
- The actual implementation will be decided/discussed along with the pull request

**Comment by UmairJibran** [comment]
@matthewmayer do you want me to update faker.location.language() #3333 to return?
```JSON
[
  { "name": "English", "alpha2": "EN", "alpha3": "ENG" },
  { "name": "German", "alpha2": "DE", "alpha3": "DEU" }
]
```

Also should it support optional parameter to return array of strings via (`faker.location.language({variant: 'alpha-2'/'name'/'alpha-3'})`), if in case someone needs to only get list of language names as was requested in #1548

**Comment by ST-DDT** [comment]
> do you want me to update faker.location.language() #3333 to return?
> 
> ```json
> [
>   { "name": "English", "alpha2": "EN", "alpha3": "ENG" },
>   { "name": "German", "alpha2": "DE", "alpha3": "DEU" }
> ]
> ```

Yes, please.

> Also should it support optional parameter to return array of strings via (`faker.location.language({variant: 'alpha-2'/'name'/'alpha-3'})`), if in case someone needs to only get list of language names as was requested in #1548

No, there doesnt have to be a parameter influencing the return type.
`Faker.location.language().name` is simple enough.

**Comment by matthewmayer** [comment]
Note I think the language code should be lower case ie en not EN

**Comment by UmairJibran** [comment]
I just compiled the list, with Upper Case 😭
@matthewmayer should alpha3 be lowercase too?

**Comment by matthewmayer** [comment]
I would suggest all lowercase yes
