### ISSUE TITLE
Skypack CDN has not build

### ISSUE THREAD

**Issue by kristinademeshchik** [faker-js/faker#2624]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

https://cdn.skypack.dev/@faker-js/faker returns `Unexpected Error: Build was successful but could not be found.` error

### Environment Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 196.88 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.2.1
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by xDivisionByZerox** [comment]
Seems like an error on the side on Skypack. If you try to search on their site, you are getting HTTP 500 as well, currently.

Might need to wait some time. I'm not familiar with Skypac, tho.

**Comment by ST-DDT** [comment]
https://www.skypack.dev/search?q=%40faker-js%2Ffaker

See here for alternative hosters:

https://fakerjs.dev/guide/usage.html#cdn-deno

**Comment by ST-DDT** [comment]
Skypack seems to be abandoned.
We should remove it from our docs.

- https://github.com/skypackjs/skypack-cdn/issues/365
- https://github.com/skypackjs/skypack-cdn/issues/362
