### ISSUE TITLE
Title and buttons on homepage have gone blue?

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2626]
Has some CSS gone astray? Title is now blue and the Browse API button is quite hard to read.

https://fakerjs.dev/

<img width="672" alt="Screenshot 2024-01-28 at 20 21 45" src="https://github.com/faker-js/awesome-faker/assets/152770/423d9cdf-346e-4c47-8638-ea4ea3dff99e">

https://web.archive.org/web/20231129222728/https://fakerjs.dev/

<img width="657" alt="Screenshot 2024-01-28 at 20 21 36" src="https://github.com/faker-js/awesome-faker/assets/152770/1b9ee030-773c-4e89-8dad-7ff8f9ae1f29">

**Comment by Shinigami92** [comment]
It's just a redesign of Vitepress (we are mostly using the default theme)
Only the "Browse API" Button is slightly customized by us
Might need to use the text-color of the border like before

**Comment by Shinigami92** [comment]
AHA! the issue is that I only designed the button in dark mode, not respecting light mode at all :laughing: 
will fix it

**Comment by matthewmayer** [comment]
sorry added in wrong repo, moved here

**Comment by matthewmayer** [comment]
i thought the green looked nicer :)

looks like you can easily override the main theme colors by overriding some CSS vars, if we want the green back (or another color)

<img width="317" alt="image" src="https://github.com/faker-js/awesome-faker/assets/152770/f30e1144-451d-4f47-a4a0-f9276d1af084">

**Comment by Shinigami92** [comment]
If you like to change the color and want to customize the default style, pls open another PR

I just fixed the brand button's text in light mode

**Comment by Shinigami92** [comment]
@matthewmayer also ask yourself 2 questions :slightly_smiling_face: 

1. were you just used to the previous colors?
2. is it worth for you to maintain override of Vitepress design 🙃

But I wont hold you back :rocket:

**Comment by matthewmayer** [comment]
1. Yes
2. Yes

🤣

Will open a new PR

**Comment by xDivisionByZerox** [comment]
> 1. were you just used to the previous colors?

To prevent personal oppinion, we should maybe define a design spec for Faker's "branding". I'll add the point to the next meetings discussion list.

**Comment by matthewmayer** [comment]
could use the reds from the stripe of the hat perhaps

<img width="201" alt="image" src="https://github.com/faker-js/faker/assets/152770/8b6e1e7a-ff7b-4886-ac8f-f207c072c1e8">
