### ISSUE TITLE
Add support for generating Roman Numerals

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2649]
### Clear and concise description of the problem

It would be useful to be able to generate roman numerals, e.g. for sections of a fake document, or as a fake pattern to be used in another pattern like "Super Bowl XXVII".

### Suggested solution

```js
faker.number.romanNumeral({min:1, max: 100}) //XVII
```
min would default to 1 (you can't write 0 in roman numerals). max would probably be limited to 4999 as roman numerals are not as well-defined above 5000.
Maybe lowercase/uppercase options?

Not localizable. Since roman numerals are always written in latin script.

### Alternative

write custom conversion code eg. 

```js
convertToRomanNumerals(faker.number.int({min:1, max:4999}))
```

where convertToRomanNumerals is a suitable implementation from https://stackoverflow.com/questions/9083037/convert-a-number-into-a-roman-numeral-in-javascript

**Comment by WikiRik** [comment]
Would indeed be interesting at times to have this. I personally see no need for numerals above 4999 or lowercases ones. Min/max is indeed good to have.

**Comment by AmaanRS** [comment]
Should i implement this feature ?

**Comment by matthewmayer** [comment]
> Should i implement this feature ?

We normally wait until a feature has 10 GitHub upvotes. It's nearly there 😀

**Comment by ST-DDT** [comment]
@AmaanRS Do you need roman numerals by string length (range) or by value range?

**Comment by AmaanRS** [comment]
Yes, I need it by value range (eg: from 1 to 100)

**Comment by ST-DDT** [comment]
@AmaanRS Could you please describe your usecase? What will you use the output of the method for?

**Comment by AmaanRS** [comment]
I have to number the recipe in cookbook by roman numbers, and for that function i am writing tests, which needs random roman numbers

**Comment by AmaanRS** [comment]
So..., should i create it ?

**Comment by matthewmayer** [comment]
> So..., should i create it ?

Since there are now 10 upvotes, I think you could go ahead and start working on it to aid with discussion. Be sure to read the Contributing guide for advice. 

Be aware it will likely take some time to review and merge as the maintainers are busy getting v9 ready for release.

**Comment by AmaanRS** [comment]
So should i create a function named **convertToRomanNumerals** or a function on the property number named **romanNumeral**

**Comment by ST-DDT** [comment]
Please create a function in the number module, so that you can call it like this:

````ts
faker.number.romanNumerals()
````

**Comment by AmaanRS** [comment]
What about options ? (like min,max) or should i keep it from 1 to 4999 by default.

**Comment by matthewmayer** [comment]
Maybe singular romanNumeral rather than plural romanNumerals

**Comment by AmaanRS** [comment]
@ST-DDT I have written the function (draft) #3070
