### ISSUE TITLE
helpers.arrayElements should return a tuple instead of an array

### ISSUE THREAD

**Issue by cloud-walker** [faker-js/faker#2675]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

`faker.helpers.arrayElements([1, 2, 3], 2)` returns a type of `number[]`, when it should be `[number, number]`

`faker.helpers.arrayElements([1, 2, 3], {min: 2, max: 10})` returns a type of `number[]`, when it should be `[number, number, ...number[]]`

### Environment Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 21.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @faker-js/faker: ^8.4.1 => 8.4.1
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment]
I have a rough estimate on what you are asking, I'm just now sure how to properly model it with TS.
Especially in combination with the dynamic length ranges.
Could you please explain how you would handle that?

Also could you explain why you want this change? As that helps us understand your request better.

**Comment by cloud-walker** [comment]
Hi @ST-DDT the TS in this case is not the easiest in my experience, I've already done experiments on my codebase, and the problem to solve is similar to the one solved on remeda codebase for the [hasAtLeast](https://remedajs.com/docs/#hasAtLeast) function.

In our case the count maybe `undefined` or `number` or `{min: number; max: number}` so it's a bit more challenging.

> Also could you explain why you want this change? As that helps us understand your request better.

Using the [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) option the destructuring of the array generated by arrayElements becomes less ergonomic as the elements would be of type `T | undefined`

```ts
import {faker} from '@faker-js/faker'

const langsPool = ['en', 'it', 'fr', 'es'] as const

const [langA, langB] = faker.arrayElements(langsPool, 2)

// referencing langA and langB later on is not safe when in reality it should be
```

**Comment by ST-DDT** [comment]
We could limit the feature to fixed size arrays at first, so we split the method into separate signatures and add the feature only to one of them.

**Comment by ST-DDT** [comment]
One of the problems I see is that removing elements from the resulting array invalidates it's type then.

**Comment by cloud-walker** [comment]
I think that the helpers can continue to be dynamic as it is, we just need to handle a more complex type signature, I can try to make a PR, the same stuff apply to other helpers, like:

1. `multiple()`
2. `uniqueArray()`

I can obviously start small experimenting with arrayElements first

**Comment by matthewmayer** [comment]
faker.helpers.arrayElements() can work with any JavaScript array though, it's not necessary typed.

**Comment by cloud-walker** [comment]
@matthewmayer what do you mean? Of course it works with any array 🤔

**Comment by matthewmayer** [comment]
I mean tuples don't exist in JavaScript so would need to ensure this doesn't break anything for regular JavaScript arrays.

**Comment by cloud-walker** [comment]
oh I see, AFAIK tuple exists in TS only on the type level, so they are arrays anyway

**Comment by ST-DDT** [comment]
I think maybe we should create a separate method for tuples, because sometimes you fo actually want a starting array/data set that grows over time.

Also the tuples are a recursive and thus expensive types.

**Comment by Shinigami92** [comment]
> I think maybe we should create a separate method for tuples, because sometimes you fo actually want a starting array/data set that grows over time.
> 
> Also the tuples are a recursive and thus expensive types.

I'm not sure if it is worth to ship a same method to just differ the return type.
In that case, the user should just use a simple `as [...]` cast.

**Comment by ST-DDT** [comment]
**Team Decision**

We consider this a non goal because

- It can be easily achieved using casts `as [string, string]` which has significantly better performance than recursive types
- Or self crafted methods `return [value1(), value2()] as const`
- You might also want to generate tuples with mixed types `[number, string]` which we would consider dynamic complex objects and thus are not in the scope of faker
