### ISSUE TITLE
Special characters in email

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#272]
### Clear and concise description of the problem

Email addresses can contain special characters like `!#$%&'*+-/=?^_`{|}~` (see https://stackoverflow.com/a/2049510/1806316). Faker could support this (maybe with an option?), so generated data is more realistic...

### Suggested solution

Update `faker.internet.email` method.

**Comment by harsohailB** [comment]
@pkuczynski I would like to work on this feature. Feel free to assign me!
