### ISSUE TITLE
Make separate export for simpleFaker

### ISSUE THREAD

**Issue by Semigradsky** [faker-js/faker#2748]
### Clear and concise description of the problem

In my vite project I use only methods from simpleFaker. But there is no separate export for this, so I use this import:
```ts
import { simpleFaker } from "@faker-js/faker"
```

As I see the `esm/index.mjs` imports all files so i have a huge bundle.

I switched to import a one locale:
```ts
import { faker as simpleFaker } from "@faker-js/faker/locale/en"
```

it is a much better, but not enough.

### Suggested solution

I suggest to make separate export like this:
```ts
import { simpleFaker } from "@faker-js/faker/simpleFaker"
```

It shouldn't be hard but will nice decrease my bundle.

**Comment by xDivisionByZerox** [comment]
Great suggestion. Although, with v9, we work on finally getting tree shaking to work. That way, you should get a smaller bundle regardless of the import path you import from.

**Comment by matthewmayer** [comment]
What about
```js
import { faker } from "@faker-js/faker/locale/base"
```

(gets it down to about 200KB from 500KB)

**Comment by ST-DDT** [comment]
I think that is a good workaround between the simpleFaker and fakerEn.

**Comment by matthewmayer** [comment]
do you think its worth mentioning that option on the localization page here https://fakerjs.dev/guide/localization.html#individual-localized-packages

if so i can make a new PR for that

**Comment by xDivisionByZerox** [comment]
> do you think its worth mentioning that option on the localization page here [fakerjs.dev/guide/localization.html#individual-localized-packages](https://fakerjs.dev/guide/localization.html#individual-localized-packages)
> 
> if so i can make a new PR for that

I think [the usage page](https://fakerjs.dev/guide/usage.html#simple-data-generation) would be more fitting. The localization page alredy lists "base", but doesn't give any explaination what that exactly means.

**Comment by ST-DDT** [comment]
I think we could give it a try.

**Comment by ST-DDT** [comment]
Fixed by https://github.com/faker-js/faker/pull/2790

- https://github.com/faker-js/faker/pull/2790

You can already test in our alpha: 

- https://www.npmjs.com/package/@faker-js/faker/v/9.0.0-alpha.0
