### ISSUE TITLE
Email addresses are unknown on fakerHE in Hebrew

### ISSUE THREAD

**Issue by mordi9** [faker-js/faker#2776]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

When using faker.internet.email() with fakerHE, unknown email addresses are obtained, consisting of random characters. For example:
- 15t15q15f160.15c15l16215r@hotmail.com
- 15l15j15i15z15c15o3@gmail.com
- 15d16015z162_16215h16015r@yahoo.com

Suggested solution:
Add support for names in email addresses using simple pronunciation-hyphenation translation, which will allow creating more correct email addresses, even if the translation is not accurate.

Advantages:
Creating more realistic email addresses.
Improving the usability of fakerHE for Hebrew users.
effect:
This change will affect all fakerHE users who use faker.internet.email() to create Hebrew email addresses.

Code to create a translation using according to pronunciation
```

const hebrewAlphabet = {
  "א": "a",
  "ב": "b",
  "ג": "g",
  "ד": "d",
  "ה": "h",
  "ו": "v",
  "ז": "z",
  "ח": "ch",
  "ט": "t",
  "י": "y",
  "כ": "k",
  "ך": "kh",
  "ל": "l",
  "ם": "m",
  "מ": "m",
  "ן": "n",
  "נ": "n",
  "ס": "s",
  "ע": "a",
  "פ": "f",
  "ף": "ph",
  "צ": "ts",
  "ץ": "ts",
  "ק": "k",
  "ר": "r",
  "ש": "sh",
  "ת": "t",
  "ו": "v",
};

function pronounce(word) {
  let pronouncedWord = "";
  for (let i = 0; i < word.length; i++) {
    pronouncedWord += hebrewAlphabet[word[i]];
  }
  return pronouncedWord;
}

function translate(text) {
  const words = text.split(" ");
  const translatedWords = words.map(word => pronounce(word));
  return translatedWords.join(" ");
}

translate(inputText);
```

### Minimal reproduction code

```
const { fakerHE: faker } = require('@faker-js/faker');
const contacts = [];
for (let i = 0; i < 10; i++) {
    contacts.push({
      name: faker.person.fullName(),
      email: faker.internet.email(),
      phone: faker.phone.number(),
      location: faker.location.street() + " "  + faker.location.buildingNumber() + " " + faker.location.city()
    });
}
```

### Environment Info

```shell
node.js v18.16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
FFR:

- https://fakerjs.dev/api/internet.html#email
- https://github.com/faker-js/faker/blob/7c7f78daa0fef802af916c2f192cc36bee6c88d2/src/modules/internet/index.ts#L276
- https://github.com/faker-js/faker/blob/7c7f78daa0fef802af916c2f192cc36bee6c88d2/src/modules/internet/index.ts#L669-L671
- https://github.com/faker-js/faker/blob/next/src/modules/internet/char-mappings.ts

The username method uses a charMapping that you could extend for HE.

Contributions welcome.
