### ISSUE TITLE
Random CI test failure in date.birthdate for specific age

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2783]
I noticed the following CI failure:

>  ❯ test/modules/date.spec.ts  (519 tests | 1 failed) 143ms
>    ❯ test/modules/date.spec.ts > date > random seeded tests for seed 4910278082529783 > birthdate > returns a random birthdate for specific age
>      → expected 22 to be 21 // Object.is equality

https://github.com/faker-js/faker/actions/runs/8509928928/job/23306443483

https://github.com/faker-js/faker/blob/2e97b52c822c5fdaf1a67b955ad08450f59011fd/test/modules/date.spec.ts#L564-L582

I created this issue so that I don't forget about it. I might tackle it later this week.

Assumed cause: The generated birthdate is at the edge of the 21 age at generation time and at comparison time it just flipped to 22.

**Comment by matthewmayer** [comment]
i feel the way it calculates "age" in the test is weird. it basically boils down to doing this:
```js
function getAge(birthdate, refDate) {
    const value = birthdate.valueOf()
    const refDateValue = refDate.valueOf()
    const deltaDate = new Date(refDateValue - value)
    return deltaDate.getUTCFullYear() - 1970
}
```

but that can be off for leap years for example this returns 1, not 0
```
console.log(getAge(new Date('2019-03-01T01:00:00'), new Date('2020-02-29T01:00:00')))
```

**Comment by matthewmayer** [comment]
Where getAge is defined as above, there's a roughly 1/365 chance of failure:
```js
const refDateFixed = new Date("2024-04-02T12:00:00");
faker.seed(123456);
const results = faker.helpers.multiple(()=>getAge(faker.date.birthdate({mode:"age", min:21, max:21, refDate:refDateFixed}), refDateFixed),{count:1000000})
const counts = results.reduce((acc, age) => (acc[age] = (acc[age] || 0) + 1, acc), {})
console.dir(counts)
//{ '21': 997248, '22': 2752 }
```
