### ISSUE TITLE
Replace all FakerCloud links with a new source

### ISSUE THREAD

**Issue by prisis** [faker-js/faker#28]

**Comment by clarkerican** [comment]
@prisis Hey Daniel, I was thinking of just removing this for now ([PR](https://github.com/faker-js/faker.js/pull/27)). Although, if someone does end up creating a Faker Cloud, then we can add it back. Thoughts?

**Comment by prisis** [comment]
What I mean is, https://github.com/faker-js/faker.js/blob/29234378807c4141588861f69421bf20b5ac635e/lib/internet.js

**Comment by prisis** [comment]
Maybe we can replace it with https://github.com/leafac/fake-avatars/tree/main

**Comment by clarkerican** [comment]
Ahh, I see. Yea, we should update those

**Comment by Shinigami92** [comment]
https://github.com/faker-js/faker.js/discussions/26#discussioncomment-1934189
