### ISSUE TITLE
Convert MersenneTwister19937 to a class

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#280]
### Clear and concise description of the problem

Convert MersenneTwister19937 to a class

### Suggested solution

Convert MersenneTwister19937 to a class

**Comment by xDivisionByZerox** [comment]
Please assign me to this. I want to do this.

**Comment by xDivisionByZerox** [comment]
Should the `init_genrand` method still be called manually or be transformed to the constructor?

**Comment by xDivisionByZerox** [comment]
Or should this even be static factory methods?

**Comment by Shinigami92** [comment]
The code is from prior year < 2000...
We should document that we now heavily rewrite this and move forward, so I think it's okay to modify it to use camelCase etc, make it modern.
It should just do the exact same stuff as it does now, cause this is the base for faker's seed.
It is also not a problem to change something heavily, because we do not expose this, or at least we have not said that we support it for external usage.

**Comment by xDivisionByZerox** [comment]
I have written my thoughts in #530.
I will convert the style of the variables to cammelCase but drop the idea for factory methods (since it's not needed if not exposed).
