### ISSUE TITLE
Speed up normalisation code

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2804]
Split from https://github.com/faker-js/faker/pull/2791#issuecomment-2043464436

> Is there anything we can do to speed up the normalisation code?

Guess we can parallelize the processing of all methods in a module as well as the module processing in general. This would not fix the data normalization in general, tho. Any ideas on that?

**Comment by matthewmayer** [comment]
Could we do some form of caching (like the eslint cache) so it doesn't bother trying to re-normalize unchanged files that have already been normalised?

**Comment by Shinigami92** [comment]
> Could we do some form of caching (like the eslint cache) so it doesn't bother trying to re-normalize unchanged files that have already been normalised?

This was also my idea 🤔 
Before implementing something on our own, we should look if we can bring a caching dev-dependency for that 👀 

Edit: a really quick search brought e.g. https://www.npmjs.com/package/file-entry-cache to the table :eyes:

**Comment by xDivisionByZerox** [comment]
> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

☝️

**Comment by ST-DDT** [comment]
Before we jump into the caching rabit hole, we should try async IO first.

**Comment by Shinigami92** [comment]
> Before we into the caching rabit hole, we should try async IO first.

Oh! That might be a really good idea 👍

**Comment by matthewmayer** [comment]
For reference:
* At the moment, `pnpm run generate:locales` takes about 6s on my machine, a M1 Macbook Air (with only normalization for food module)
* if i comment out the other modules from `definitionsToSkip` this increases to 29s on the first run and 19s for subsequent runs.

So maybe the ~13 seconds slowdown is tolerable for now if it will make the code too complex to fix it.

**Comment by ST-DDT** [comment]
For me the baseline is:

- next-limited: 12s
- next-all: 34s

**Comment by ST-DDT** [comment]
I created a first refactor for async io:

- https://github.com/faker-js/faker/pull/2826
