### ISSUE TITLE
Localization lastName is not working

### ISSUE THREAD

**Issue by undermuz** [faker-js/faker#2833]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

This code produces base last names:

```javascript
import { fakerRU as faker } from "@faker-js/faker";

console.log(faker.person.lastName());
``` 

Expected: this code produces localizated last names

### Minimal reproduction code

https://codesandbox.io/p/sandbox/faker-js-ru-not-working-forked-cthnpl?file=%2Fsrc%2Findex.ts%3A20%2C41
```javascript
import { fakerRU, ru as localization } from "@faker-js/faker";

//THIS TEMP FIX:
// import { base, ru, Faker } from "@faker-js/faker";

// const customFaker = new Faker({
//   locale: [ru, base],
// });

const faker = fakerRU;

let maxIterations = 1000;
let found = false;
let i = 0;

console.log(localization);

const allLastNames = [
  ...localization.person.female_last_name,
  ...localization.person.male_last_name,
];

console.log(allLastNames);

while (!found && i++ < maxIterations) {
  const text = faker.person.lastName();

  console.log(text);

  found = allLastNames.some((t) => t === text);

  if (found) {
    console.log("Found", text);
    break;
  }
}

if (!found) console.log("Not found");
```

### Environment Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12600
    Memory: 16.03 GB / 31.75 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @faker-js/faker: ^8.4.1 => 8.4.1
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment]
Potential dublicate of https://github.com/faker-js/faker/issues/1677

- https://github.com/faker-js/faker/issues/1677

**Comment by matthewmayer** [comment]
This affects locales that have a male_last_name and female_last_name file but no last_name file.

Specifically:
```
sk
id_ID
lv
ru
uk
az
uz_UZ_latin
```

We can solve this by adding a last_name.ts file with mergeArrays. This is already done for these locales:
```
cs_CZ
dv
mk
```
