### ISSUE TITLE
Add more random color generators

### ISSUE THREAD

**Issue by deriegle** [faker-js/faker#286]
### Clear and concise description of the problem

As a developer using faker I want to generate random hexadecimal colors so that I can use it to generate random colors for things in my applications.

One use case example is the ability to generate a random color for a team/user in the application.

**I'd love to submit a PR for this if it's a welcomed change! 😄**

### Suggested solution

I'm not positive which namespace this would fit under, but an implementation like this could work to generate the color.

```js
const hexColorOptions = ['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'];
const color = ['#'];

for (let i = 0; i < 6; i++) {
  const index = faker.datatype.number({
    min: 0,
    max: hexColorOptions.length - 1,
  });

  color.push(hexColorOptions[index]);
}

return color.join('');
```

### Alternative

We could also generate RGBA, CMYK, HSL colors as well.

**Comment by prisis** [comment]
I would say the best namespace would be internet, there is a color function

**Comment by deriegle** [comment]
@prisis oops. I totally missed this in the documentation. There already is a hexadecimal color generator. Sorry about that.

https://fakerjs.dev/api/internet.html#hexadecimal-color

**Comment by prisis** [comment]
I will reopen it, because i think it would be nice to have the other functions RGBA, CMYK, HSL colors

**Comment by Shinigami92** [comment]
We should think about to move color out of commerce and internet and make its own module
I see this after 6.1, so long time goal :D

**Comment by deriegle** [comment]
I can put up a PR for adding the additional colors. I'll try to get to it in the next week.

Thanks! Love the idea to move them into their own color module.

**Comment by harsohailB** [comment]
@Shinigami92 Was this ever completed? If not, I am willing to work on moving the existing color API into its own module as well as introducing RGBA, CMYK, HSL colors.

**Comment by Shinigami92** [comment]
> @Shinigami92 Was this ever completed? If not, I am willing to work on moving the existing color API into its own module as well as introducing RGBA, CMYK, HSL colors. 

I'm not able to do much more stuff today, but just start drafting a PR, won't like to hold you back 🚀
But it could be that the wanted color module will be merged earliest v7+
So we will have some weeks to work on that module 🙂

**Comment by harsohailB** [comment]
> > @Shinigami92 Was this ever completed? If not, I am willing to work on moving the existing color API into its own module as well as introducing RGBA, CMYK, HSL colors.
> 
> I'm not able to do much more stuff today, but just start drafting a PR, won't like to hold you back 🚀 But it could be that the wanted color module will be merged earliest v7+ So we will have some weeks to work on that module 🙂

Sounds good! Thanks for all the help btw. I'm new to open source development so really appreciated 😊
