### ISSUE TITLE
EPIC: Improve test cases

### ISSUE THREAD

**Issue by prisis** [faker-js/faker#287]
List of test that need to be checked and adjusted:

| test                   | developer             |                   PR # |        Done        |
| :--------------------- | :-------------------- | ---------------------: | :----------------: |
| address.spec.ts        | @Shinigami92          |                   #285 | :heavy_check_mark: |
| all_functional.spec.ts | _can be skipped_      |                        | :heavy_check_mark: |
| animal.spec.ts         | @Shinigami92          |                   #293 | :heavy_check_mark: |
| commerce.spec.ts       | @Shinigami92          |                   #294 | :heavy_check_mark: |
| company.spec.ts        | @Shinigami92       |                  #493 | :heavy_check_mark:  |
| database.spec.ts       | @Shinigami92          |                   #393 | :heavy_check_mark: |
| datatype.spec.ts       | @Shinigami92          |                   #344 | :heavy_check_mark: |
| date.spec.ts           | @Shinigami92          |                   #312 | :heavy_check_mark: |
| fake.spec.ts           | _is okay_             |                        | :heavy_check_mark: |
| finance_iban.spec.ts   |      @Shinigami92                 |    #515                    |    :heavy_check_mark:                 |
| finance.spec.ts        |        @Shinigami92               |       #519                 |    :heavy_check_mark:                 |
| git.spec.ts            | @Shinigami92          |                   #425 | :heavy_check_mark: |
| helpers.spec.ts          | @Shinigami92 |                    #499 |      :heavy_check_mark:               |
| image.spec.ts          | @Shinigami92          |                   #414 | :heavy_check_mark: |
| internet.spec.ts       | @ST-DDT, @Shinigami92 | (partially) #258, #475 | :heavy_check_mark: |
| locales.spec.ts        | _can be skipped_      |                        | :heavy_check_mark: |
| lorem.spec.ts          | @Shinigami92          |                   #473 | :heavy_check_mark: |
| music.spec.ts          | @piotrekn             |                   #383 | :heavy_check_mark: |
| name.spec.ts           | @Shinigami92          |                   #372 | :heavy_check_mark: |
| phone_number.spec.ts   | @piotrekn             |                   #396 | :heavy_check_mark: |
| random.spec.ts         | @Shinigami92            |        #490                | :heavy_check_mark: |
| system.spec.ts         | @prisis               |                   #303 | :heavy_check_mark: |
| time.spec.ts           | @Shinigami92          |                   #421 | :heavy_check_mark: |
| unique.spec.ts         | @Shinigami92          |                   #370 | :heavy_check_mark: |
| vehicle.spec.ts        | @Shinigami92          |                   #469 |   :heavy_check_mark: |
| word.spec.ts           | @Shinigami92          |                   #470 | :heavy_check_mark: |
| hacker.spec.ts         | @Shinigami92          |                   #386 | :heavy_check_mark: |

- First step would be to create some seeds and a seed map with return values to always create the same data.
- Extend the test to run on every local that faker supports.
- Remove mock calls to test the function itself and not the mocked output.

**Comment by Shinigami92** [comment]
For the long run we could try to create a type + abstraction like this:

```ts
export type SeededRun<Module, K extends keyof Module = keyof Module> = {
  seed: number;
  expectations: {
    [P in K]: any;
  };
};
```

But it would be cool to also have somehow have the expectations values typed :thinking:

**Comment by piotrekn** [comment]
@prisis, I can do `music.spec.ts`, `phone_number.spec.ts` and `random.spec.ts`. Can you assign them to me , please?

**Comment by Shinigami92** [comment]
I will do :+1: Please make them in 3 dedicated PRs, then I will update the PR numbers also

**Comment by Shinigami92** [comment]
@prisis you missed `hacker` cause `hacker` doesn't has a test at all :scream: 
I think I will target `hacker` as next module
I will also add it now to the list above

**Comment by prisis** [comment]
It was hacked 🤣 yeah, was printing all test file out

**Comment by piotrekn** [comment]
Guys, this pattern is flawed:

```typescript
  // Create and log-back the seed for debug purposes
  faker.seed(Math.ceil(Math.random() * 1_000_000_000));

  describe(`random seeded tests for seed ${faker.seedValue}`, () => {
```

It should be more like this:

```typescript
  // Create and log-back the seed for debug purposes
  const seed = Math.ceil(Math.random() * 1_000_000_000);

  describe(`random seeded tests for seed ${seed}`, () => {
    beforeAll(() => {
      faker.seed(seed);
    });
```
...or even `beforeEach` instead of `beforeAll.
The problem is that `faker.seedValue` is a global variable, and every `faker.seed()` changes it. Once `seededRuns` have executed, the last set seed remains, not a random one.

Please review your PRs for that case.

**Comment by Shinigami92** [comment]
> Guys, this pattern is flawed:
> 
> ```ts
>   // Create and log-back the seed for debug purposes
>   faker.seed(Math.ceil(Math.random() * 1_000_000_000));
> 
>   describe(`random seeded tests for seed ${faker.seedValue}`, () => {
> ```
> 
> It should be more like this:
> 
> ```ts
>   // Create and log-back the seed for debug purposes
>   const seed = Math.ceil(Math.random() * 1_000_000_000);
> 
>   describe(`random seeded tests for seed ${seed}`, () => {
>     beforeAll(() => {
>       faker.seed(seed);
>     });
> ```
> 
> ...or even `beforeEach` instead of `beforeAll`. The problem is that `faker.seedValue` is a global variable, and every `faker.seed()` changes it. Once `seededRuns` have executed, the last seed set remains, not a random one we expect. The expression `faker.seed(Math.ceil(Math.random() * 1_000_000_000));` is executed once before all tests, on declaration.
> 
> Please review your PRs for that case.

You are missing that we added `faker.seed(seed)` in every single it block to ensure this behavior.
Even `beforeEach` was not safe enough, cause we sometimes have nested describe+it blocks in this loop.
If you found a specific test were we overseen this, please report it to us.

**Comment by ST-DDT** [comment]
@Shinigami92 I think you and @piotrekn are referring to different things.

As you can see there is no faker.seed() inside this section anymore:

https://github.com/faker-js/faker/blob/f1884becbc108c3ddbad952d879cec0fc5196e08/test/animal.spec.ts#L101-L115

However, this isn't needed because the main purpose of those methods is to randomly execute the methods and check for unexpected behavior. These tests should be removed in the medium term to remove the flaky test coverage behavior.
The faker seed is set once and logged to ensure that in the event of a failure, the test setup can be recovered by manually setting the seed. It is not required to have the exact seed for all methods.

**Comment by Shinigami92** [comment]
@ST-DDT ah yes, you are totally right

The weather is grey here and I feel a bit week today, so sorry if I confuse some stuff

**Comment by Shinigami92** [comment]
_Vehicle_ is driving me crazy, so I will tackle that now :stuck_out_tongue_winking_eye:

**Comment by Shinigami92** [comment]
For some tests I have no **word**s

**Comment by Shinigami92** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Comment by Shinigami92** [comment]
I will now rewrite the internet

**Comment by Shinigami92** [comment]
I will try targeting `finance_iban.spec.ts` now

**Comment by Shinigami92** [comment]
We are near to finish :checkered_flag: 

Only reviews are needed!

**Comment by Shinigami92** [comment]
All done :tada:
