### ISSUE TITLE
More varied product descriptions

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#2871]
### Clear and concise description of the problem

There are only 12 possible product descriptions in `faker.commerce.productDescription()` in `en`

### Suggested solution

Similar to how we handled `faker.food.description()`, switch to using `fake()` over `arrayElement()` and sprinkle some additional placeholders like  {{color.human}}, {{word.adjective}} in the descriptions for additional variety.

This would be backwards compatible with existing definitions in other locales, since fake patterns can just be static strings.

**Comment by ST-DDT** [comment]
@matthewmayer Please don't forget to upvote your own feature requests.
