### ISSUE TITLE
Can't use Faker with k6

### ISSUE THREAD

**Issue by pawfectQA** [faker-js/faker#2872]
### Clear and concise description of the problem

As a QA using faker I wish that I could use updated faker with k6 scripts. Now I get an error, that k6 doesn't support this module. I import it as `import { faker } from "@faker-js/faker";`, and when I run tests, I get this message: GoError: The moduleSpecifier "@faker-js/faker" couldn't be recognised as something k6 supports.
        at go.k6.io/k6/js.(*requireImpl).require-fm (native)

### Suggested solution

Maybe this helps somehow [k6 docs](https://grafana.com/docs/k6/latest/using-k6/modules/)

**Comment by ST-DDT** [comment]
Please provide us with a minimal reproduction example, so that we can have an in detail look at it and verify the solution ourselves.

**Comment by pawfectQA** [comment]
[test issue.zip](https://github.com/faker-js/faker/files/15198737/test.issue.zip)
the code itself can be with mistakes, but it lets test the issue. Thank you!

**Comment by ST-DDT** [comment]
@pawfectQA Thanks for providing the zip. Which version of k6 are you using?
I know you have included the exe in the zip, but I cannot verify its integrity as it seems to be an older version.

# EDIT: ⚠️ The checksums of the zipped and the v0.49 from github don't match.

**Comment by ST-DDT** [comment]
Have you tried with the latest version of k6 as well?

**Comment by pawfectQA** [comment]
I use v0.49 of k6

**Comment by pawfectQA** [comment]
I tried the latest version and it has the same issue.

**Comment by ST-DDT** [comment]
⚠️ The checksums of the zipped and the v0.49 from github don't match.

**Comment by pawfectQA** [comment]
the zipped one may be lower version because it includes some extension 🧐 but I tried all the latest versions too

**Comment by ST-DDT** [comment]
Instead of importing from `@faker-js/faker` try `https://cdn.jsdelivr.net/npm/@faker-js/faker@8.4.1/dist/esm/locale/en.mjs`

or adding a package.json with `@faker-js/faker` as depedency and run npm install and then use `./node_modules/@faker-js/faker`.

**Comment by ST-DDT** [comment]
Does that help you/fix the issues you have?

**Comment by pawfectQA** [comment]
It says: WARN[0002] The source for `https://cdn.jsdelivr.net/npm/@faker-js/faker@8.4.1/dist/esm/chunk-LSZKOVGW.mjs` needs to go through babel but is over 256000 bytes. For performance reasons source map support will be disabled for this particular file.

Still investigating

**Comment by pawfectQA** [comment]
and the second method gave me "node_modules\@faker-js\faker: Incorrect function."

**Comment by ST-DDT** [comment]
> and the second method gave me "node_modules@faker-js\faker: Incorrect function."

You might have to adjust the path to match your actual file system.

**Comment by ST-DDT** [comment]
Did you have any luck getting this to work?

**Comment by pawfectQA** [comment]
Hi! Sorry for the late reply. I upgraded to the last version of k6 and created patched exe file with older faker. Since then I didn't try to use your version.
