### ISSUE TITLE
Add Github action to enforce conventional commit names

### ISSUE THREAD

**Issue by clarkerican** [faker-js/faker#29]
We'll also need to update the Contributing guidelines

**Comment by Shinigami92** [comment]
https://github.com/vitejs/vite/blob/main/.github/semantic.yml
https://github.com/vitejs/vite/blob/8fb854fd62f0edc9b1d1bab79b7d9b11cd03cf90/package.json#L65

**Comment by clarkerican** [comment]
I like the idea of using simple git hooks!

**Comment by Shinigami92** [comment]
We did too :smiley:

**Comment by ericjeker** [comment]
Is this relevant as documentation? Looks very similar to what you have in Vite.
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by damienwebdev** [comment]
@ericjeker yes. This combined with https://github.com/conventional-changelog/standard-version will be the go-to.
