### ISSUE TITLE
npm install fails for package consumers due to "only-allow pnpm"

### ISSUE THREAD

**Issue by jbkly** [faker-js/faker#290]
### Describe the bug

First line of the readme Installation section suggests you can use npm, yarn, or pnpm to install faker:

`npm install @faker-js/faker --save-dev`

```
❯ npm install @faker-js/faker --save-dev
npm ERR! code 1
npm ERR! path ~/dev/myproject/node_modules/@faker-js/faker
npm ERR! command failed
npm ERR! command sh -c npx only-allow pnpm
npm ERR! ╔═════════════════════════════════════════════════════════════╗
npm ERR! ║                                                             ║
npm ERR! ║   Use "pnpm install" for installation in this project.      ║
npm ERR! ║                                                             ║
npm ERR! ║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
npm ERR! ║   For more details, go to https://pnpm.js.org/              ║
npm ERR! ║                                                             ║
npm ERR! ╚═════════════════════════════════════════════════════════════╝

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-01-24T23_47_37_989Z-debug.log
```

This commit (https://github.com/faker-js/faker/commit/a273f67066c7c19b01ff4348eb9d7e857615cca6) added `"preinstall": "npx only-allow pnpm"` to `package.json`. 

### Reproduction

`npm install @faker-js/faker --save-dev`

**Comment by ST-DDT** [comment]
This looks like a bug to me. @Shinigami92

**Comment by edilsonalves** [comment]
The same happens to me.

```
⚡️ npm install @faker-js/faker --save-dev
npm ERR! code 1
npm ERR! path /Users/edilson/Desktop/ze-projects/ze-communication-service/node_modules/@faker-js/faker
npm ERR! command failed
npm ERR! command sh -c npx only-allow pnpm
npm ERR! ╔═════════════════════════════════════════════════════════════╗
npm ERR! ║                                                             ║
npm ERR! ║   Use "pnpm install" for installation in this project.      ║
npm ERR! ║                                                             ║
npm ERR! ║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
npm ERR! ║   For more details, go to https://pnpm.js.org/              ║
npm ERR! ║                                                             ║
npm ERR! ╚═════════════════════════════════════════════════════════════╝

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-01-25T00_21_50_304Z-debug.log
```

**Comment by Lamia-Mihoubi** [comment]
Same:
![Screenshot 2022-01-25 064530](https://user-images.githubusercontent.com/29714883/150918389-5fcd07bf-9fb0-416f-85b3-0edec362830e.jpg)

**Comment by Shinigami92** [comment]
What 😱
How is this not a big for half a million people using Vite but for us 👀

There must be something I missed to correctly configure 🤔

**Comment by Shinigami92** [comment]
Another team member at Vite explained me:

> vite uses it in the monorepo root, which doesn't get published

I'm so sorry 🤦 I really didn't thought that preinstall will be just executed. Is this not a huge CVE? 👀🤔 is it possible to just `rm -Rf *` in preinstall?

**Comment by nimatrazmjo** [comment]
same 
<img width="682" alt="Screen Shot 2022-01-25 at 11 20 06 AM" src="https://user-images.githubusercontent.com/3712526/150925886-4bc54180-2090-45ec-a389-321d3817939e.png">
:

**Comment by ST-DDT** [comment]
@damienwebdev Any ETA on a fixed release?

**Comment by feedm3** [comment]
Quick fix for now: Pin the version in your `package.json` to `6.0.0-alpha.3`:

```
"@faker-js/faker": "6.0.0-alpha.3"
```

**Comment by Shinigami92** [comment]
https://www.npmjs.com/package/@faker-js/faker/v/6.0.0-alpha.5 it's released :partying_face: 

Sorry for that issue, but I'm happy that we have the alpha-phase
