### ISSUE TITLE
Create Intl based tests for date definitions

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2904]
To ensure the completeness of the weekdays and months, we should have tests that ensure we have the correct values.

_Originally posted by @ST-DDT in https://github.com/faker-js/faker/issues/2902#issuecomment-2115622767_

**Comment by sossost** [comment]
Hi! @ST-DDT I'm sossost, a new contributor. I would like to solve this issue.

**Comment by ST-DDT** [comment]
I assigned it to you. Thanks for your help.

**Comment by xDivisionByZerox** [comment]
> Hi! @ST-DDT I'm sossost, a new contributor. I would like to solve this issue.

Thank you for your interest in tackling this issue :heart:

We currently try to further improve our contribution documentation to enhance the DX for new contributors. Feel free to inform us if you get stuck while working on this issue and can't find documentation in the current contribution guides that would resolve your problem.

**Comment by xDivisionByZerox** [comment]
We close this as not planed: https://github.com/faker-js/faker/pull/2912#issuecomment-2439605068
