### ISSUE TITLE
Check whether the locale data should use locale aware sorting

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2905]
We should check whether the locale data should be sorted with their original locale in mind.

https://github.com/faker-js/faker/blob/7fb9bb52941e9c7bb458f1dc7cabb3737d05dffe/scripts/generate-locales.ts#L301

**Comment by ST-DDT** [comment]
Blocked by the initial sorting of the locale data after https://github.com/faker-js/faker/pull/2265

- https://github.com/faker-js/faker/pull/2265

**Comment by xDivisionByZerox** [comment]
Potentially relevant implementation details in https://github.com/faker-js/faker/pull/2265#issuecomment-1762819340.

> Same as with the language aware letters. I can extend the previos compare function to be numeric aware:
>
> ```ts
> const arr = ['B', 'A', 'Å', 'Å9', 'Å11']
> const sorted = arr.toSorted((a,b) => a.localeCompare(b, undefined, { numeric: true }));
> console.log(sorted); // ['A', 'Å', 'Å9', 'Å11', 'B']
> ```

**Comment by matthewmayer** [comment]
i tried a draft implementation at #2906 - this is imperfect, but gives you an idea of the scope of the likely changes if this is done.

**Comment by ST-DDT** [comment]
**Team Decision**

The current locale unaware sorting is good enough/the best approach for our contributor experience.

We will add a comment to the script similar to this one:

> We cannot sort this locale aware, as the sort order is not stable within node versions #2905

https://github.com/faker-js/faker/blob/a5ffca1c7863531d459f67cbab7bd9ba34d16904/scripts/generate-locales.ts#L300-L301

**Comment by Shinigami92** [comment]
I did some research, digged down the rabbit-hole and found a bit out about ICU

so FFR, here is a list of helpful links:

- https://nodejs.org/api/intl.html#providing-icu-data-at-runtime
- https://www.npmjs.com/package/icu4c-data?activeTab=versions
- https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/
- https://www.npmjs.com/package/node-icu
- https://github.com/Metrological/icudata/tree/master
- https://github.com/unicode-org/icu
- https://github.com/unicode-org/icu/releases/tag/release-75-1

This could be used to download the icu.dat file and store it in some cached way locally and pinned for execution when sorting

However I dont have the time right now, so it is just a way and idea and up for experimental grab if someone cares 🙂

**Comment by ST-DDT** [comment]
> We will add a comment to the script similar to this one:
> 
> > We cannot sort this locale aware, as the sort order is not stable within node versions #2905

Done:

- #2948
