### ISSUE TITLE
Use singular locale definition keys

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2911]
Followup for #2910 

- #2910 

Currently we have some locale files that use plural naming, and some that use singular naming.

| singular | plural |
| ------------------------------------------- | -------------------------------------------- |
| `faker.definitions.science.chemical_element` | `faker.definitions.system.directory_paths`   |

We should decide on one naming scheme and stick to that.

Currently, most definitions are singular.

**Comment by ST-DDT** [comment]
Blocked by #2910 

- #2910

**Comment by matthewmayer** [comment]
I don't think it's that important to rename them all, but if we are renaming from camel case to snake case may as well change at the same time.

**Comment by ST-DDT** [comment]
Currently the only plural names are the following:

- lorem.words
- system.directory_paths
- system.mime_types

The rest is singular.

**Comment by ST-DDT** [comment]
**Team Decision**

- We will name the locale data to singular.
- Because if they are used in fake they refer to only one element of that list
- Because of historic design decisions (pre v6)/backwards compatibility.
