### ISSUE TITLE
chat.fakerjs.dev

### ISSUE THREAD

**Issue by patak-dev** [faker-js/faker#295]
### Clear and concise description of the problem

Several projects redirect chat.project.dev to discord, and it is a useful convention.

It would also be nice to have social links in the landing of fakerjs.dev, and a Community section in the Getting Started guide

### Suggested solution

Support https://chat.fakerjs.dev/

### Additional context

Y'all are awesome, thanks for the work you are doing with faker-js!

**Comment by damienwebdev** [comment]
I have configured the domain, so this should be as simple as modifying https://github.com/faker-js/faker/blob/main/netlify.toml to as Netlify recommends.

https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
