### ISSUE TITLE
fakerjs.dev/new

### ISSUE THREAD

**Issue by patak-dev** [faker-js/faker#296]
### Clear and concise description of the problem

It would be good that fakerjs.dev/new would redirect to the main online demo for the project. This is a useful convention (used by https://sli.dev/new and https://vitest.dev/new).

In Vitest, we started with a StackBlitz demo updating it in the app but now migrated to use imports from GitHub. We moved the demo to our examples folder and linked vitest.dev/new to the SB GitHub import url. See: https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github

Yes, it is great to use the usual PR flow to update the demos

### Suggested solution

Implement redirect and move demo to the repo.

### Additional context

❤️

**Comment by import-brain** [comment]
We could have it redirect to the playground, once that is finished. (fakerjs.dev/playground) Is that what you mean by "main online demo"?

**Comment by Shinigami92** [comment]
@import-brain not directly, we want to setup a stackblitz env and redirect the path to that one

@JessicaSachs theoretically we may not need a playground at all then :eyes:

**Comment by import-brain** [comment]
> @import-brain not directly, we want to setup a stackblitz env and redirect the path to that one
> 
> 
> 
> @JessicaSachs theoretically we may not need a playground at all then :eyes: 

Yeah, setting up StackBlitz would be easier than making our own playground.

**Comment by Shinigami92** [comment]
Reference #46

**Comment by JessicaSachs** [comment]
No I definitely want a playground. We should have the stackblitz, too.

**Comment by damienwebdev** [comment]
https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

**Comment by luciferreeves** [comment]
I am also in the side of having our own playground. 

I can build a custom Faker playground from the ground up (would use some CSS/JS frameworks/libraries) 

Or we can all build a playground - if we put the playground to another repo which deploys to https://fakerjs.dev/new or https://playground.fakerjs.dev (I like the subdomain better - probably redirect the earlier to the latter) whenever there is a push to the master branch.

**Comment by ST-DDT** [comment]
This would also be consistent with chat.fakerjs.dev.

I'm not sure about what should be in the playground, maybe some dummy webapp, that generates random data on button click.
One of these views could be a registration form with
- username (verb-noun)
- password (alphanum, visible)
- password reset question (favorite vehicle)
- gender | firstname | lastname
- bio (some random text lorem)
- avatar (some random image)
- address
- iban

Or maybe that could be something for an example page.

**Comment by luciferreeves** [comment]
Actually I think, the playground should be fully featured. Allowing users to write/click on faker API methods and then there can be a console.like window which shows the output.

**Comment by Shinigami92** [comment]
Preparing a stackblitz: https://faker-js-demo.stackblitz.io
