### ISSUE TITLE
Move utils to the correct place

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2961]
Based on our team meeting:

We will put internal utilities in `src/internal/*.ts`
We will put external utilities in `src/utils/*.ts`
External utilities will be exported from the root of our library.
External utilities are not required to use a faker seed.

TODOs:

- Move generateMersenne*Randomizers() to src/utils
- Move src/utils/types.ts to src/internal/

**Comment by watercubz** [comment]
Hi team,

I understand, I have already solved the problem and in a moment I will upload the changes for code review. If you have another request regarding the issue, I am here.

Thank you!
