### ISSUE TITLE
Removal of functional code in faker.js security vulenrability

### ISSUE THREAD

**Issue by bdimitrovski** [faker-js/faker#2965]
`npm audit` reports a security vulnerability in faker.js version 6.6.6:

<img width="742" alt="Screenshot 2024-06-22 at 10 01 53" src="https://github.com/faker-js/faker/assets/4244896/cecd1101-c4dc-4b5e-9b54-71ff429d3afd">

This forces us to use faker@5.5.3, which is inconvenient, so this should be remediated.

Sources:
- https://github.com/advisories/GHSA-5w9c-rv96-fr7g

**Comment by matthewmayer** [comment]
You should switch to the supported `@faker-js/faker` package - see

https://v6.fakerjs.dev/migration-guide-v5/

Then you can follow the guides to upgrade to v7 and v8 if required

https://v7.fakerjs.dev/guide/upgrading.html

https://fakerjs.dev/guide/upgrading.html
