### ISSUE TITLE
arrayElement never returns zero-index element

### ISSUE THREAD

**Issue by alejandroiglesias** [faker-js/faker#2993]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Given this:
```
faker.helpers.arrayElement( [
  '+141' + faker.string.numeric( 8 ),
  null
] )
```
The first (zero-index) array item is never returned.

### Minimal reproduction code

```
faker.helpers.arrayElement( [
  '+141' + faker.string.numeric( 8 ),
  null
] )
```

### Environment Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 263.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - /opt/homebrew/bin/node
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 9.2.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @faker-js/faker: ^8.4.1 => 8.4.1
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by alejandroiglesias** [comment]
Closing since I could eventually get the first zero-indexed element.

**Comment by ST-DDT** [comment]
@alejandroiglesias faker.helpers.maybe might also be useful for your usecase.

https://fakerjs.dev/api/helpers.html#maybe
