### ISSUE TITLE
Remove logos that may not be Creative Commons or MIT Licensed

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#3]

**Comment by damienwebdev** [comment]
I've taken the time to make a new logo in Paint 3D. It's ok for now.

**Comment by damienwebdev** [comment]
![faker](https://user-images.githubusercontent.com/9029654/148663046-99899c11-9f4a-4a3a-a9a1-5515cf936988.jpg)

**Comment by import-brain** [comment]
@damienwebdev Should I close this? We pushed the panda logo PR.
