### ISSUE TITLE
Extend Docs to Describe Expected Usage with TypeScript

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#3006]
> [!NOTE]
> The updated requirements for the issues can be found [in this comment](https://github.com/faker-js/faker/issues/3006#issuecomment-2294968108).

### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

In a project where TypeScript is not configured to run in strict mode, the function `faker.helpers.arrayElement` can be called with `null` and `undefined`, which leads to errors during runtime.

### Minimal reproduction code

https://stackblitz.com/edit/faker-js-demo-c67mtj?file=index.ts

### Additional Context

This might be true for ALL functions, as `null` is assignable to everything in non-strict mode.

- This configuration was not discussed in https://github.com/faker-js/faker/issues/2725#issuecomment-2012927210.

### Environment Info

```shell
-
```

### Which module system do you use?

- [X] CJS
- [X] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment]
IMO we clearly define our needs/requirements.
If you choose to ignore them using js, non strict ts or unsafe casts, then you are on your own.

**Comment by xDivisionByZerox** [comment]
> IMO we clearly define our needs/requirements. If you choose to ignore them using js, non strict ts or unsafe casts, then you are on your own.

I don't know if I agree with this statement, especially since [TypeScripts default](https://www.typescriptlang.org/docs/handbook/2/basic-types.html#strictness) is still non-strict mode.

**Comment by ST-DDT** [comment]
**Team Decision**

- We assume that the user either uses strict TypeScript or handles the issues arising from not using it themselves.

**Comment by AmaanRS** [comment]
Can you please explain to me what exactly do i have to do, like do i have to types for this ?

**Comment by xDivisionByZerox** [comment]
@AmaanRS I'm not sure if I understand correctly. Are you asking for the tasks to do to work on the issue? 🤔

**Comment by ST-DDT** [comment]
> Can you please explain to me what exactly do i have to do, like do i have to types for this ?

@AmaanRS This is a documentation task, so it doesn't need any code changes.

---

@xDivisionByZerox I'm not exactly sure what should be done for this issue either.
Could you please explain what documentation do you want where?

**Comment by xDivisionByZerox** [comment]
> @xDivisionByZerox I'm not exactly sure what should be done for this issue either.
Could you please explain what documentation do you want where?

Of couse. IMO the [TypeScript section](https://fakerjs.dev/guide/usage.html#typescript-support) of our docs should add a note box hinting the user that using faker without (TS) strict mode might lead to unexpected behaviour which will not be worked around from our side.
