### ISSUE TITLE
Rename `userName` to `username`

### ISSUE THREAD

**Issue by glen-84** [faker-js/faker#3023]
The [`userName`](https://fakerjs.dev/api/internet.html#username) method in the internet module should be named `username` – consider deprecating the former.

https://english.stackexchange.com/questions/43436/username-user-name-or-user-name

**Comment by ST-DDT** [comment]
**Team Decision**

We will rename the `faker.internet.userName()` method to `faker.internet.username()`.
Contributions welcome.

**Comment by Shinigami92** [comment]
@glen-84 If you would like, you can contribute a PR

**Comment by suyashgulati** [comment]
Can you please assign to me? @Shinigami92
