### ISSUE TITLE
Vet v6.0.0-alpha.5 types emitted types against v5.5.3  

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#305]
We need to ensure that the types emitted from our packages are API compatible with the previous DefinitelyTyped package.

See:

1. #166 
2. #198 
3. `faker.address.nearbyGPSCoordinate` (`coordinate` is a ReadOnlyArray in DefinitelyTyped)
4. `faker.address.companyName` has an arg of `format` which should be `string | number`
5. `faker.database.column` is implicitly return typed as `string` in 6.0.0-alpha.5 but should be set to return `string`
7. `faker.database.type()` is implicitly return typed as `string` in 6.0.0-alpha.5 but should be set to return `string`
8. `faker.database.collation()` is implicitly return typed as `string` in 6.0.0-alpha.5 but should be set to return `string`
9. `faker.database.engine()` is implicitly return typed as `string` in 6.0.0-alpha.5 but should be set to return `string`
10. `faker.finance.currencyCode()` is return typed `any`
11. `faker.finance.currencyName()` is return typed `any`
12. `faker.finance.currencySymbol()` is return typed `any`
13. `faker.hacker.abbreviation()` is implicitly return typed as `string`
14. `faker.hacker.adjective()` is implicitly return typed as `string`
15. `faker.hacker.noun()` is implicitly return typed as `string`
16. `faker.hacker.verb()` is implicitly return typed as `string`
17. `faker.hacker.ingverb()` is implicitly return typed as `string`
18. `faker.hacker.phrase()` is implicitly return typed as `string`

I'm sure there are a few others, but we need to check type by type to ensure spec compatibility.

**Comment by Shinigami92** [comment]
It could help to look what the types were their, but keep in mind that also these could be out of sync from the source code and introduce false assumptions.
Don't just trust these blindly.

The Date type issue explicitly showed how wrong type assumption can nearly introduce new bugs to us without covered by the tests 😬

We are still in alpha and on some places I even did not assign a type **yet**, to explicitly find out what the real type is.

**Comment by Shinigami92** [comment]
Here is a version of the types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/291c346588768b8ea13472ff95bdacd659f67790/types/faker/index.d.ts

Note that there are also some interfaces like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/291c346588768b8ea13472ff95bdacd659f67790/types/faker/index.d.ts#L336

These could be helpful for https://github.com/faker-js/faker/pull/151/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R202, but I think I will split this PR into multiple smaller once anyway

**Comment by ST-DDT** [comment]
Is there a tool to automatically compare the types?

**Comment by Shinigami92** [comment]
@damienwebdev Would you like to update the description of this issue and notify me/us about what is still missing?
