### ISSUE TITLE
Switching to stylistic eslint plugin

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3068]
As `typescript-eslint` v8 removes some rules we are using in favor of https://eslint.style/, we want to implement e.g. `@stylistic/eslint-plugin-ts` so we can still benefit from rules like [`padding-line-between-statements`](https://eslint.style/rules/default/padding-line-between-statements)

This needs to be done, before we can merge #3064, so we don't loose the checks for these rules.

This issue was created out of a thread over in #3064:

    **todo (blocking):** before simply removing this lint rule, we need to add https://eslint.style/rules/ts/padding-line-between-statements

_Originally posted by @Shinigami92 in https://github.com/faker-js/faker/pull/3064#discussion_r1722393401_

In typescript-eslint v8 has been removed as it has been moved to the eslint-stylistic package.
This issues serves as a reminder to add the rule back and to unblock the dependency update: https://github.com/faker-js/faker/pull/3064

- https://github.com/faker-js/faker/pull/3064

**Comment by Shinigami92** [comment]
I updated the description of the issue to reflect more accurate what's going on and what is needed.

As I'm not sure if I have the time to tackle this in the upcoming days, the `good first issue` label is really welcome here.
