### ISSUE TITLE
Reduce frequency of dependency update PRs

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3077]
Currently we receive dependency update PRs once a week.
But it sometimes takes half a week to review and merge them and during that time I get a lot of emails regarding their updates.
So I propose to reduce the updates to once per month and on demand before updates.

Lets say we have 5 dependency PRs per week on average (this week it have been six).
This produces 38 mails per week = 152 mails/month.
If we reduce it to monthly and we assume 7 PRs. Then we get this number down to 53.
If we manually trigger the dependency updates (sequential, 7 PRs), this number goes down to 35.

As an additional benefit, this removes a lot of dependency updates from our release notes.
What do you think?

**Comment by matthewmayer** [comment]
Strong support. I find the dependency notifications very spammy 

And given faker only has devDependencies I don't think there is such an urgency to always be on the bleeding edge version.

**Comment by xDivisionByZerox** [comment]
This sounds reasonable to me.  I'd be in favor of manual, sequential PRs to further reduce the noise from renovate rebases as described by ST-DDT.

**Comment by Shinigami92** [comment]
**Team-Decision:**

For now we want to try out to simply ignore notifications of Renovate (or GitHub in general), if we do not feel like we have the time.

**Comment by ST-DDT** [comment]
**Team Decision**

Faker only has dev dependencies, so updates aren't critical to our users.
With our current release frequency it is sufficient to do the updates before we release.
We stick to monthly updates to get notified of breaking changes frequently/monthly.
