### ISSUE TITLE
Non-intuitive error if options property doesn't have jsdocs

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#3079]
```FakerApiDocsProcessingError: Failed to process parameter options at src/modules/number/index.ts:468:16 : Expected exactly one element for jsdocs, got 0```

_Originally posted by @AmaanRS in https://github.com/faker-js/faker/issues/3070#issuecomment-2323336805_

**Comment by matthewmayer** [comment]
i think previously the `verify @since tag` in https://github.com/faker-js/faker/blob/next/test/scripts/apidocs/verify-jsdoc-tags.spec.ts would throw the error expecting `@since to be present` but after merge of https://github.com/faker-js/faker/pull/2628 the `exactlyOne()` function in `value-checks.ts` is throwing a more cryptic error which doesnt mention `@since`

**Comment by ST-DDT** [comment]
Correction, the error is caused by the options properties (min and max) not having jsdocs.

**Comment by wedouglas** [comment]
@matthewmayer Are you going to cooperate with the return of RDCL's stolen property and data? Your previous statements and the proof of your actions can be posted here to ensure you are aware of it.
