### ISSUE TITLE
Deprecate code of merit

### ISSUE THREAD

**Issue by clarkerican** [faker-js/faker#31]
@damienwebdev and I discussed deprecating the Code of Merit and replacing it with a Code of Conduct. I just started small and deleted the Code of Merit, we can find an appropriate Code of Conduct to replace it with

Step 1: Remove Code of Merit https://github.com/faker-js/faker.js/pull/32#issue-1097070749
Step 2: [Add Standard Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md)

**Comment by damienwebdev** [comment]
@clarkerican I updated your comment with the link to the [Standard Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md)

**Comment by damienwebdev** [comment]
This is closed by #32 and #57
