### ISSUE TITLE
[9.0.0] Locale imports are not resoved when using NodeNext in tsconfig

### ISSUE THREAD

**Issue by sbaechler** [faker-js/faker#3105]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

When I use Faker in a Typescript project that has "module" and "moduleResolution" set to "NodeNext", the locale files cannot be resolved.

<img width="714" alt="Bildschirmfoto 2024-09-11 um 15 32 00" src="https://github.com/user-attachments/assets/73e580c9-4ce8-47ee-8f30-45dd1afaa0d2">

This only happens if the module resolution is set to NodeNext, but this is the recommended setting going forward.

There is currently a workaround by using a .mjs file for the import of the Faker modules.

### Environment Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.37 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.1 - ~/.nvm/versions/node/v22.4.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.4.1/bin/yarn
    npm: 10.8.3 - ~/projects/gvz/mock-data/node_modules/.bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 128.1.69.162
    Edge: 128.0.2739.67
    Safari: 17.6
  npmPackages:
    @faker-js/faker: ^9.0.0 => 9.0.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by Shinigami92** [comment]
<img width="650" alt="image" src="https://github.com/user-attachments/assets/26e16154-0480-4138-9a98-4d5b1ca3e270">

are you really sure about this?! 🤪 maybe have another look...

**Comment by xDivisionByZerox** [comment]
Closing this as duplicate as #3087. If you think this is a mistake, feel free to reopen this issue.
