### ISSUE TITLE
`faker.location.continent` for generating random (real) continents

### ISSUE THREAD

**Issue by joscha** [faker-js/faker#3164]
### Clear and concise description of the problem

I am currently generating fake data for results from an OpenAPI spec. The spec has an entity that is location data. It includes a continent. See https://github.com/planet-a-ventures/affinity-node/blob/4df29ba8e97f02715f381da76efe13146463d0a1/openapi/2024-10-08.json#L2827

As a developer using faker I want to be able to generate random continent names.

### Suggested solution

A new `locations.continent` method.

### Additional context

Implementation is here: https://github.com/faker-js/faker/pull/3162

**Comment by ST-DDT** [comment]
https://github.com/faker-js/faker/pull/3162#issuecomment-2402186426

One lesson we learned for sure is that lot location stuff seems simple, but the usecases vary a lot. Some people might need only the name, others might only need the code, and some need both related to each other (e.g. countries).

I did a quick google search and found this list of continent codes.

- https://github.com/datasets/continent-codes/blob/main/data/continent-codes.csv
- https://datahub.io/core/continent-codes

I have yet to check if these are an official thing.
(And I have never heart of them before either)

What do you/the others think?
