### ISSUE TITLE
add "locale" as a possible semantic pull request type

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#3179]
>  It is a locale PR. So I would love a `locale(module):` nomenclature. Until then it is I'm fine with either of those.

_Originally posted by @ST-DDT in https://github.com/faker-js/faker/issues/3173#issuecomment-2409028242_

**Comment by matthewmayer** [comment]
This would be used when just adding or removing locale data in a pull request
e.g. https://github.com/faker-js/faker/pull/3173 https://github.com/faker-js/faker/pull/3154 https://github.com/faker-js/faker/pull/3142

Would this simply be a matter of adding `locale` in 

https://github.com/faker-js/faker/blob/next/.github/workflows/semantic-pull-request.yml

?

**Comment by Shinigami92** [comment]
> Would this simply be a matter of adding `locale` in

No it wont, and it would even conflict with the current infra setup of producing separate sections for Changelog

e.g. https://github.com/faker-js/faker/blob/next/CHANGELOG.md#new-locales

**Comment by ST-DDT** [comment]
We could change it here: 

- https://github.com/faker-js/faker/blob/next/.versionrc.json

**Comment by Shinigami92** [comment]
Could we first discuss why the one is better than the other?

Right now we are sure what a fix and what a feat is
This has effect not only of incrementing the minor or biggie number, but also separate between updated and new locales

The module or locale (e.g. de) is also written into the commit message

Updating this process required also a search through the current contribution guide, so we do not forget something to update

My personal though is currently to not touch this process, but I'm by far not the only maintainer and maybe there is a benefit that I currently don't see

**Comment by ST-DDT** [comment]
My point of contention is, that we use the `locale` label, but the `feat`/`refactor` prefix.
Only for `fix`es we use both.

**Comment by matthewmayer** [comment]
I'm not too bothered whether we add a new label or not, maybe it's just a question of updating the documentation to make it clearer which one to pick?

**Comment by Shinigami92** [comment]
Ah now I see the `refactor(vehicle): add more non-US vehicle manufacturers`
because only `src/locales/en/vehicle/manufacturer.ts` were effectively touched for the outside-consumer, it should have been a `refactor(locale): add more non-US vehicle manufacturers`
and as you can see, the `vehicle` was already in the commit message and don't need to be addressed in commit scope a second time

But it is merged already 🤷, so better luck next time

**Comment by matthewmayer** [comment]
Refactors which add new data to existing locales seem different to refactors which actually change code (but don't change the output). But maybe it's fine to call them both refactor.

**Comment by ST-DDT** [comment]
**Team Decision**

- We will keep it as is for v9.x
