### ISSUE TITLE
faker.phone.number fails to generate international numbers

### ISSUE THREAD

**Issue by manchuck** [faker-js/faker#3185]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

When using `faker.phone.number({ style: 'international' })`, a deprecation warning is issued and no number is returned.

Using the code sample the output will be:

```
warn:     [@faker-js/faker]: faker.phone.number(format) is deprecated since v8.1 and will be removed in v9.0. Please use faker.phone.number(), faker.string.numeric() or faker.helpers.fromRegExp() instead.

International number: 
Number: (538) 625-6227 x991
```
,

### Minimal reproduction code

```js
const InternationalNumber = faker.phone.number({ style: 'international' }) ;
console.log(`International number: ${InternationalNumber}`);
const number = faker.phone.number();
console.log(`Number: ${number}`);
```

### Environment Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.45 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
  Browsers:
    Safari: 17.6
  npmPackages:
    @faker-js/faker: 8.4.1 => 8.4.1
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by xDivisionByZerox** [comment]
You have installed `@faker-js/faker: 8.4.1` as you can see by your provided "Environment Info". The `style` parameter has only been introduced in v9. 

You are getting the deprecation message (in v8) because only a single string argument, called `format`, was present back then:

> https://github.com/faker-js/faker/blob/98ff809bea1adcd9b2872b9a5a864a59f3df6b86/src/modules/phone/index.ts#L57-L65

Since the if block only checked for `!= null` your argument fulfills this check.

---

All you need to do is update to v9. If you want to use v8 of Faker refer to the v8 docs: https://v8.fakerjs.dev/api/phone.html#number

**Comment by manchuck** [comment]
@xDivisionByZerox You get all the internet points. Thanks
