### ISSUE TITLE
Extension to Vehicle Manufacturers List

### ISSUE THREAD

**Issue by suyashgulati** [faker-js/faker#3186]
As an Extension to Vehicle Manufacturers list over added by @matthewmayer in #2881.

Adding some more Manufacturers available in India from various geolocations: India, China, Czech to the data would be beneficial.

Examples:

Indian Manufacturers:
- Tata Motors
- Mahindra & Mahindra

India-Japan tie up in India:
- Maruti Suzuki

China:
- MG Motor

Czech:
- Skoda

I have added a PR as well, if issue is approved, we can use that.

**Comment by ST-DDT** [comment]
FFR: When adding/updating locale data you don't need to create a new issue.
