### ISSUE TITLE
Document npm scripts

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#322]
We should document

- which script should be run by humans in which order
- which scripts are required by CI/netlify-toml
- which are "just" sub-scripts

Potentially a part of #308

_Originally posted by @Shinigami92 in https://github.com/faker-js/faker/issues/289#issuecomment-1023405156_

**Comment by xDivisionByZerox** [comment]
This has been made a lot simpler #1846, because `preflight` is now the only script that needs to be run by a human.

In which form should the documentation be provided?

**Comment by matthewmayer** [comment]
Could probably expand the line in CONTRIBUTING which says:

`Please make sure that you run pnpm run preflight before making a PR to ensure that everything is working from the start.`

To something like

```
Please make sure that you run `pnpm run preflight` before making a PR to ensure that everything is working from the start. This is a shorthand for running the following scripts in order:
- `pnpm install` - installs npm modules defined in package.json
- `pnpm run generate:locales` - generates locale files
- `pnpm run generate:api-doc` - generates API documentation
- `pnpm run format` - runs prettify to format code
- `pnpm run lint` - runs ESLint
- `pnpm run build` - builds the code, both CommonJS and ESM versions
- `pnpm run test:update-snapshots ` - runs all tests, and updates any snapshots if needed
- `pnpm run ts-check` - checks TypeScript
```

**Comment by xDivisionByZerox** [comment]
That is a really good idea. 

Do you want to open a PR to make this change? Otherwise, I can do one and add you as a co-author.

**Comment by matthewmayer** [comment]
you go ahead? you may be able to write nicer descriptions. i wasn't too clear what pnpm run ts-check actually does.
