### ISSUE TITLE
This is a virus

### ISSUE THREAD

**Issue by jburke15** [faker-js/faker#3275]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

After trying to install faker into power shell. it rendered error codes which is fine and expected per usual but I closed out of power shell and was prompted with windows 32 per usual after reopening power shell but now compared to before when I right click power shell to switch to administrator the code for the same "faker" that produced all the errors  just automatically starts running, not allowing me to switch to administrator. kind of like a bot.
![Screenshot 2024-11-21 200959](https://github.com/user-attachments/assets/7c178bde-770e-4096-8b7d-f1d6e71b9c94)
*mind you all i did was right-click

### Environment Info

```shell
windows
powershell
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by jburke15** [comment]
this is creepy. i right clicked again
![Screenshot 2024-11-21 201734](https://github.com/user-attachments/assets/17d8a7d0-1598-4ba2-bac5-fe6a4bc9300e)

**Comment by matthewmayer** [comment]
Right clicking in powershell will paste whatever is on your clipboard. If these are not properly formatted commands then you will get errors. This isn't a bug with faker, so will close this issue.

**Comment by jburke15** [comment]
That’s funny. My bad.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
