### ISSUE TITLE
Broken accents with some generic first_name definitions in Italian locale

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#3280]
https://github.com/faker-js/faker/blob/56acea375da20fed64c7d9b5336ad078f4c6782a/src/locales/it/person/first_name.ts#L397

There are 6 names in the `it` `person.first_name.generic` list that appear to have broken accents

  - Esa�
  - Giosu�
  - Mos�
  - Nicol�
  - No�
  - Salom�
 
corresponding to

Esaù
Giosuè
Mosè
Nicolò
Noè
Salomè

in the male/female lists

**Comment by ST-DDT** [comment]
Would you like to create a PR for this?

**Comment by matthewmayer** [comment]
Will do. i want to track down where this was introduced first.

**Comment by ST-DDT** [comment]
Looks like it was introduced in #169

-  #169

---

- Before: 
  - https://github.com/faker-js/faker/blame/ae5992039da10fa3f5433f6bfc0e65bc351684fc/lib/locales/it/name/first_name.js#L396
  - https://github.com/faker-js/faker/commit/61d02960a9132fa2c4d4d7259883b2e944233bb9#diff-3bfd1decf8d704b83571293b5f5652114ea1234ce129a2b967b7067c7da84fd1L396
- After: 
  - https://github.com/faker-js/faker/blame/92a2f178343f4413bd6d782a7957eda86aa1b7b8/src/locales/it/person/first_name.ts#L396
  - https://github.com/faker-js/faker/commit/61d02960a9132fa2c4d4d7259883b2e944233bb9#diff-d9b007b750fab6413d9cfb3662e6061be8bff4f738b0feb284a60ab5cf43fa00R396

Though I'm unsure how this happened, as it only affects this particular file.

- https://github.com/search?q=repo%3Afaker-js%2Ffaker%20%EF%BF%BD&type=code (� in 1 files)
- https://github.com/search?q=repo%3Afaker-js%2Ffaker%20%C3%B9&type=code (ù in 7 files)
- https://github.com/search?q=repo%3Afaker-js%2Ffaker%20%C3%A8&type=code (è in 54 files)
- https://github.com/search?q=repo%3Afaker-js%2Ffaker%20%C3%B2&type=code (ò in 7 files)

Might be a charset detection glitch during commit or when opening the file with an IDE.
IMO we don't have to dig to deeply into this.
