### ISSUE TITLE
Add refresh button to the api docs examples

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3287]
### Clear and concise description of the problem

Currently, the documentation only provides a single example per invocation, this could result in wrong expectations of method return values.

See:

- https://github.com/faker-js/faker/issues/3283

### Suggested solution

Adding a refresh button to the example sections:

https://github.com/user-attachments/assets/f3b38e5b-a256-4114-9c62-0c969bfa7fdd

For that to work, we have to 

- trigger downloading of the latest faker version (on first press)
- change our apidocs json data to be js/ts, so that we can store actual code in there
- add a function `() => unknown[]` to the export data from the actual examples
- take each result JSON.stringify it and insert into the code block

### Alternative

Add more examples for the no args examples.

### Additional context

Original issue:

- https://github.com/faker-js/faker/issues/3283

Original fix suggestion:

- https://github.com/faker-js/faker/pull/3284

Alternative suggestion for a fix:

- https://github.com/faker-js/faker/pull/3284#discussion_r1859214745

**Comment by ST-DDT** [comment]
<details>
<summary>FFR: The preview in the video was created using this code:</summary>

````html
<button style="border: none; background: none; cursor: pointer;" onclick="
var lines = this.nextElementSibling.children[0].children[2].children[0].children;
lines[0].children[3].innerText = '// '+JSON.stringify(faker.lorem.sentences());
lines[1].children[5].innerText = '// '+JSON.stringify(faker.lorem.sentences(2));
const parts = JSON.stringify(faker.lorem.sentences(2, '\n')).split('\\n');
lines[3].children[0].innerText = '// '+parts[0];
lines[4].children[0].innerText = '// '+parts[1];
lines[5].children[7].innerText = '// '+JSON.stringify(faker.lorem.sentences({ min: 1, max: 3 }));
">
    <img src="https://upload.wikimedia.org/wikipedia/commons/c/ce/Ic_refresh_48px.svg" alt="Refresh Icon" width="24" height="24" style="display: inline-block; vertical-align: middle;">
</button>
````

The actual code should be more dynamic, so that it works without any configuration (and use a different svg).

The `x` in `lines[i].children[x]` is always the last element in the array. If that isn't the comment, then comment is in the next line.

`lines` can probably be resolved more easily via `this.nextElementSibling.querySelectorAll('.line');` (not tested)

No additional libraries needed.

</details>

**Comment by ST-DDT** [comment]
What do you think of this idea?

**Comment by sounmind** [comment]
Speaking as the author of the original issue, I think it's great idea.

**Comment by ST-DDT** [comment]
**Team Decision**

- We will try this
- There should be visual feedback while downloading the current faker version (spinner etc) for people with slow internet connections

**Comment by matthewmayer** [comment]
I think rather than just an icon it could be a smal button in the bottom right of the examples block like "Load more examples"

**Comment by ST-DDT** [comment]
Like this?

![load-more-examples button](https://github.com/user-attachments/assets/d992fb22-e4a8-44f0-b20b-c66d5b16bb4a)

I'm unsure how this will look like if the example is only a single line.

Do you want to append or replace the new examples?

**Comment by matthewmayer** [comment]
Replace like in your video.
