### ISSUE TITLE
datatype.number does not produce random number when min = max + precision

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#329]
### Describe the bug

`faker.datatype.number` returns always the same value `=max+precision`, when `min = max + precision`

### Reproduction

```
faker.datatype.number({ min: 100000 })
// 100000 - on every run
```

### Additional Info

A check ensuring `max` is reasonably larger then `min` is missing...

**Comment by luciferreeves** [comment]
The problem lies on this line:

```js
// src/datatype.ts > number(...) {...}

if (typeof options.max === 'undefined') {
    options.max = 99999;
}
```

Since `options.min` is already defined before we reach this line, we can change the implementation to this:

```js
if (typeof options.max === 'undefined') {
    options.max = options.min + 99999;
}
```

And it should work. (I hope)

**Comment by pkuczynski** [comment]
I know where is the problem :) I would normally provide a PR, but @Shinigami92 asked not to do anything until we go to 6.1. so I just created this issue...

**Comment by Shinigami92** [comment]
@pkuczynski We are working on `v6.1`. Would you like to tackle this? Or is it free to be grabbed by someone else?

**Comment by pkuczynski** [comment]
Yeah, let me have a look now :)

**Comment by pkuczynski** [comment]
> Yeah, let me have a look now :)

Done in #664
