### ISSUE TITLE
faker.helpers.objectKey and faker.helpers.objectValue examples are not very instructive

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#3303]
```ts
faker.helpers.objectKey({ myProperty: 'myValue' }) // 'myProperty'
faker.helpers.objectValue({ myProperty: 'myValue' }) // 'myValue'
```

we should use example objects with at least two key-values pairs so there is some randomness.

**Comment by ST-DDT** [comment]
Maybe use `{a:1, b: 2, c: 3}` (or even allLocales)?

And while objectEntry has two entries, we should edit that for consistency as well.

https://fakerjs.dev/api/helpers.html#objectentry

**Comment by matthewmayer** [comment]
Maybe something slightly more fun/memorable like
```{Cheetah: 120, Falcon: 390, Snail: 0.03}```
or
```{H: "Hydrogen", O: "Oxygen", C: "Carbon"}```

**Comment by ST-DDT** [comment]
Hi @matthewmayer ,

I hope you are doing well. I noticed that you self assigned this issue two weeks ago, and I wanted to check in to see if you're planning to create a PR for it or you self-assigned it by accident.

I'm wishing you a wonderful, (stress-free) and joyful time leading up to Christmas!

**Comment by matthewmayer** [comment]
Sure will get round to it in the next week or two (if someone else grabs it first I will not be offended)
