### ISSUE TITLE
Change api docs edit button to point to the ts files

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#332]
### Describe the bug

The [Suggest changes to this page](https://github.com/faker-js/faker/edit/main/docs/api/address.md) link on the api docs points to a file that does not exist. It should point to the ts files instead.

### Reproduction

- Navigate to https://fakerjs.dev/api/address.html#time-zone
- Press `Suggest changes to this page`
- You will end up on a github 404 page

**Comment by Shinigami92** [comment]
@ST-DDT Is this still an issue?

**Comment by ST-DDT** [comment]
Well, we explicitly hide the link now because it points to the wrong file.
Maybe, we may want to re-add it later.
