### ISSUE TITLE
datatype.datetime seed might not be working

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#334]
### Describe the bug

There was this comment in the jsdoc
https://github.com/faker-js/faker/blob/60b71fd257c2b95a6997f5aac516b88327a78f4b/src/datatype.ts#L92-L98

We are not sure if this is true or not, however this method relies underneath on `datatype.number` which might be also affected.

Discussed here: https://discord.com/channels/929487054990110771/929544761122111498/936559737540071434

### Reproduction

Needs investigation

**Comment by ST-DDT** [comment]
I could confirm that `datetime` does not work. However it is not related to the seeding. Instead it is related to dynamic bounds.

See #343 for the cause and fix.
