### ISSUE TITLE
datatype.hexaDecimal should be called datatype.hexadecimal

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#336]
### Describe the bug

The correct term is `hexadecimal`, without the capital `D`. See https://en.wikipedia.org/wiki/Hexadecimal

### Reproduction

N/A

**Comment by import-brain** [comment]
Should alphaNumeric also be renamed to alphanumeric?

**Comment by pkuczynski** [comment]
> Should alphaNumeric also be renamed to alphanumeric?

I think so...

**Comment by prisis** [comment]
Let's go for aliases for now and add a deprecated notice, in 7 or 8 we can remove it.

**Comment by Shinigami92** [comment]
As @damienwebdev and @mastermatt responded here https://github.com/faker-js/faker/pull/354#issuecomment-1026950523, I will close this issue for now as unwanted.
If there is still really a need, please reopen with new argumentations why it's useful.
