### ISSUE TITLE
Move random.word to word.any

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#339]
### Clear and concise description of the problem

Most of the methods of random already found their new home, like `random.number` > `datatype.number`

### Suggested solution

Move `random.word` to `word.any` and deprecate `random.word`.

### Additional context

https://github.com/faker-js/faker/pull/276#issuecomment-1024251316

**Comment by andrewgremlich** [comment]
I'll take this! Simple enough.

**Comment by andrewgremlich** [comment]
I see this PR though... should I wait until that is merged? https://github.com/faker-js/faker/pull/276

**Comment by pkuczynski** [comment]
> I see this PR though... should I wait until that is merged? https://github.com/faker-js/faker/pull/276

In principle no changes like this will be merged until 6.0 is released. So I would wait with this, yes.

**Comment by andrewgremlich** [comment]
Since 6.0 was released, I'll continue with this one!

**Comment by pkuczynski** [comment]
> Since 6.0 was released, I'll continue with this one!

Please don't. It has been already discussed and I am on it.

**Comment by ST-DDT** [comment]
I would like to get this implemented.

**Comment by import-brain** [comment]
> I would like to get this implemented.

I'll take this.
