### ISSUE TITLE
feat(lint): Properly setup eslint and decide on a set of rules or coding standard

### ISSUE THREAD

**Issue by ericjeker** [faker-js/faker#34]
- [ ] Define the rules we wanna use? Should we start with `eslint:recommended` or the existing rules, something else?
- [ ] Should we check the test folder? Currently, it's not covered.
- [ ] ... other?

**Comment by damienwebdev** [comment]
I think `eslint:recommended` would be a good starting point, likely whatever we can get done with a `lint fix` without breaking any tests is good.

For the moment, I don't think we should lint the test folder.

I would simply start by linting `lib`

**Comment by imrishabh18** [comment]
@Shinigami92 I would like to take this up and setup the eslint for this project. 😁

**Comment by Shinigami92** [comment]
@imrishabh18 Thanks for your help offer, but I think I will do this myself after I migrated the stuff to typescript this evening.
I have some very opinionated eslint setup and before we communicate back and forth and slow us down and do double work, ... I will do it myself :sweat_smile:
