### ISSUE TITLE
Use enum for male/female references

### ISSUE THREAD

**Issue by griest024** [faker-js/faker#352]
### Clear and concise description of the problem

References to male and female are done with hardcoded strings and numbers. https://github.com/faker-js/faker/blob/44628ecbbf8967c3a1313c6abfc62ad653cafe29/src/name.ts#L29-L35.

### Suggested solution

These should be replaced with enum values:

```ts
enum Sex {
  MALE = 'male',
  FEMALE = 'female',
  INTERSEX = 'intersex'
}
```

### Additional context

As an aside, `gender` is an inaccurate name for male and female. The correct term is `sex`.

**Comment by Shinigami92** [comment]
I would suggest to use type literals like `type Sex = 'male' | 'female'`

Beside that, I would highly like to have something like `type Sex = 'male' | 'female' | 'binary'` in the future

**Comment by griest024** [comment]
> I would suggest to use type literals like `type Sex = 'male' | 'female'`
> 
> Beside that, I would highly like to have something like `type Sex = 'male' | 'female' | 'binary'` in the future

I much prefer `enum`s; simple types can't be used as runtime values and we can't use it to replace hardcoded values.

**Comment by Shinigami92** [comment]
I like to provide enums, but not to force the usage
So we could to 

```ts
export enum Sex {
  MALE = 'male',
  FEMALE = 'female',
  INTERSEX = 'intersex'
}

export type SexType = 'male' | 'female' | 'intersex' | number

firstName(gender?: SexType): string { /*...*/ }
```

**Comment by griest024** [comment]
Yes as to the external usage we should accept more than just the enum. But for the internal usage I want to see `case Sex.MALE:` instead of `case 0:`.

**Comment by ST-DDT** [comment]
Please no numbers. Or what is your intention?

**Comment by Shinigami92** [comment]
[TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwMqjgbwLABQccAsgIIAyAonALxwDkqAhgDbAMA0hxAYleWp1GAM2At2XHnACSAOQAqVAEoYqADWEMAlohjAoAZ1ANCAX0KFQkWHBgBPMMEygFj5-QAGAEhxYQZp5wAD5wKKgARgaWBADGEIiG8CAAXC4gbk5aEhwA3DEiyIixMNoJcCLaRjByzKjAABQA5kgAJgYA-Gn+mcAAlGlJULpNuHBQwDDIUIiMDHBmQA)

**Comment by pkuczynski** [comment]
What would `intersex` or `binary` mean in this case? https://en.wikipedia.org/wiki/Sex does not list those terms...

**Comment by ST-DDT** [comment]
IMO this issue is already implemented.
https://github.com/faker-js/faker/blob/8369e190f728f6e75793ae4efac31e3116a67586/src/modules/name/index.ts#L3-L6

**Comment by pkuczynski** [comment]
I was only scanning the issues. If it's already implemented, we should close it. @griest024 wdyt?

**Comment by pkuczynski** [comment]
Btw. there is #353 suggesting renaming `gender` to `sex`...
