### ISSUE TITLE
system.semver should be called system.semVer

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#356]
### Describe the bug

"Semantic" and "Version" are two separate words, and all of the other methods that have two separate words as their name are in camelCase, with this being the only exception. This should probably be changed to semVer to ensure consistency of the codebase.

### Reproduction

Look at src/system.ts

**Comment by damienwebdev** [comment]
This is a breaking API change that (while nice to read) would serve users no purpose. I see no need to introduce a new API when one already exists.

**Comment by prisis** [comment]
How about a alias?
