### ISSUE TITLE
"Missing" text

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#364]
### Describe the bug

On every API category page, under the bulleted list of methods, there is always a string of text that says "Missing".

<img width="1124" alt="Screen Shot 2022-01-29 at 10 22 58 PM" src="https://user-images.githubusercontent.com/68196762/151685450-79161572-b3f7-4984-8290-c05db0db5965.png">

### Reproduction

See https://fakerjs.dev/api/animal.html#animal, https://fakerjs.dev/api/commerce.html, and https://fakerjs.dev/api/music.html for examples

**Comment by ST-DDT** [comment]
There is currently no description/jsdocs for the module classes. This will be fixed by jsdocs prs in the future.

**Comment by import-brain** [comment]
> There is currently no description/jsdocs for the module classes. This will be fixed by jsdocs prs in the future. The missing should raise awareness of that and help identify flaws with our documentation generation process.
> 
> [#351 (files)](https://github.com/faker-js/faker/pull/351/files#diff-de08590e5c14aea16434dc9ea0c3848afac0901881077df4f2ce8a6cf663fb42R3-R6)

I see, thanks for the clarification.
