### ISSUE TITLE
Provide a function to reset `faker.unique()`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#371]
### Clear and concise description of the problem

Currently `unique` uses a global constant that remembers which values where already provided back so these will not be provided back a second time.
It seems there is not possibility to reset this or provide a dedicated _cache_.

### Suggested solution

Provide the possibility to create a dedicated store that can be used.

### Additional context

https://github.com/faker-js/faker/blob/730ca6a65a29038636e8cc3eec12eacf929db7fb/src/vendor/unique.ts#L5

**Comment by fshafiee** [comment]
>IMO we should go for a parameter passed unique store.
The reset is just for backwards compatibility.
In 7.0 we could remove the global store and just use a parameter based one.

I have a case to make for the global store.

We are using using factory pattern, and the factory runs in a scope of single instance of the model. Therefore, the factory doesn't know if it's creating multiple instances or just one (it wouldn't help even if it did know).
Here's a sample:

```js
// Book Factory
defineFactory(
  BookEntity,
  (
    faker: Faker,
    context: {
      title?: string
    },
  ) => {
    const book = new BookEntity()
    book.title = context.title || faker.unique(faker.lorem.words)
    return book
  },
)
```

```js
// Inside a test body
const books = await factory(BookEntity)().createMany(3)
```

We could pass the faker instance (or the dictionary) as context to the factory, but this would result in unnecessary boilerplate code for something that should be very trivial and easy to achieve. It makes the test writing experience unnecessarily painful.
Ideally, it's the job for the test suite to set the global state in lifecycle hooks of the tests (`beforeEach`, `afterEach`, etc.), and the dictionary that is used to track the usage of these values is essentially the same thing as a database. It's keeping a global state and introduces side-effects and just like any other data-store, it's only logical to allow the global dictionary to be reset between tests. So, from the testing standpoint, a global store with ability to reset its state is more desirable. After all, uniqueness is a concept that makes sense in global context and it makes sense to handle it globally.

```js
beforeEach(async () => {
  DB.clear()
  Faker.reset()  // This is a static method, not a instance method
})
```

For inspiration: https://github.com/faker-ruby/faker#ensuring-unique-values

**Comment by Shinigami92** [comment]
@fshafiee Please open a new feature request issue or a discussion, but please don't write _especially such long_ answers into already merged and closed historical PRs, as the info you provide will go under here.
