### ISSUE TITLE
Unreachable code in finance.creditCardNumber()

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#375]
### Describe the bug

https://github.com/faker-js/faker/blob/d4125e2a7d69042c37ccecea89f1525c4424a45b/src/finance.ts#L231-L261

Due to 
https://github.com/faker-js/faker/blob/d4125e2a7d69042c37ccecea89f1525c4424a45b/src/finance.ts#L235
`localeFormat` cannot be a `string` thus
https://github.com/faker-js/faker/blob/d4125e2a7d69042c37ccecea89f1525c4424a45b/src/finance.ts#L247-L248
is unreachable

### Reproduction

Set the `faker.definitions.finance.credit_card` to a string and run the method.

### Additional Info

Discovered in #363

**Comment by xDivisionByZerox** [comment]
I would provide a PR for this, Can someone assign me to this?
