### ISSUE TITLE
Greek locale species the credit card at the wrong location

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#376]
### Describe the bug

The credit cards should be located here:

`src/locales/el/finance/credit_card/`

but are located here:

`src/locales/el/credit_card/`

(This was not caused by us/our refactoring: https://github.com/faker-js/faker/blob/6.0.0-alpha.0/lib/locales/el/index.js#L6)

### Reproduction

Try to use the greek ( `el`) credit card definitions using the default methods.

### Additional Info

Discovered in #363

Do not fix before #363 is merged.

**Comment by ST-DDT** [comment]
Milestone v6.0 or v6.1 ?

**Comment by Shinigami92** [comment]
> Milestone v6.0 or v6.1 ?

If it was cause by us, then maybe `v6.0`, if it introduce **runtime-changes** between `v5.5.3` and `v6.0`, then `v6.1`

**Comment by ST-DDT** [comment]
This was not caused by us. It does introduce runtime change, by providing other credit card information.

**Comment by Shinigami92** [comment]
> This was not caused by us. It does introduce runtime change, by providing other credit card information.

Okay, IMO this is fine, I think it like we also added some locales because they weren't imported.

**Comment by ST-DDT** [comment]
Do not fix before #363 is merged.

**Comment by ST-DDT** [comment]
Do not fix before #398 is merged.
