### ISSUE TITLE
Replace `new Date().setFullYear(...)` with `new Date(Date.UTC(...))`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#377]
### Describe the bug

We have some code parts in the codebase that resets the year, month and date part of a `Date` but not the time part.
These are not safe and deterministic.

### Reproduction

`new Date().setFullYear(2100, 1, 1) !== new Date(Date.UTC(2100, 0))`

### Additional Info

Example: https://github.com/faker-js/faker/blob/4d81ac46f169c4150f59ef3a3e790578028b57d1/src/datatype.ts#L112

**Comment by samnap11** [comment]
Is there a typo in the reproduction? Is this what you mean?
`new Date().setFullYear(2100, 0, 1) !== new Date(Date.UTC(2100, 0))`?

Nevertheless, the issue still stands. I can take this issue and work on the fix. Is that fine?

**Comment by Shinigami92** [comment]
#343 solves it in src code, but `date.spec.ts` still use `setFullYear` 🤔 

Also waiting on #200 and #576 before doing anything to reduce conflicts

**Comment by ST-DDT** [comment]
The tests don't need to be changed because they use relative dates whereas datetime uses a static boundary.
So IMO #343 fixes this issue fully.
