### ISSUE TITLE
Add Panda to animal module

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#382]
### Clear and concise description of the problem

Panda

### Suggested solution

https://www.youtube.com/watch?v=X21mJh6j9i4

**Comment by Shinigami92** [comment]
After researching 💯 of websites I found out that [by the molecular tests, they should be considered a sub-group of the bear family](https://www.chicagotribune.com/news/ct-xpm-1985-10-13-8503100134-story.html#:~:text=Judging%20by%20the%20molecular%20tests%2C%20they%20should%20be%20considered%20a%20sub%2Dgroup%20of%20the%20bear%20family.).

And then I just `CTRL+F`-ed the `src/` and found https://github.com/faker-js/faker/blob/9b0d1009134d0f0364b0a4851e03fd5e0af145f9/src/locales/en/animal/bear.ts#L2

<img src="https://c.tenor.com/-Y6seYBmowUAAAAd/shy-sad.gif" width="300px"/>

**Comment by ST-DDT** [comment]
IMO we can close this.
