### ISSUE TITLE
Setup and decide for Codecov vs Coveralls

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#387]
### Clear and concise description of the problem

We should decide which coverage reporting tool we should setup in our CI

### Suggested solution

Setup https://about.codecov.io/ or https://coveralls.io/

**Comment by ST-DDT** [comment]
I don't prefer one over the other.

**Comment by damienwebdev** [comment]
Hard no on codecov: https://github.com/graycoreio/daffodil/pull/625

**Comment by prisis** [comment]
Dont know which one is better but i used/using codecov without problems, didnt test it with a mono repo

**Comment by Shinigami92** [comment]
I'm searching right now trough the web and I found this

<img src="https://user-images.githubusercontent.com/7195563/151999568-51f45404-ea2e-45c3-ac4c-42e40cf62626.png" width="600px"/>

[marketplace](https://github.com/marketplace?query=coverage+sort%3Apopularity-desc&type=actions)

---

I also try to have a good contributor experience so I'm looking into how easy or hard to configure a PR report comment is

**Codecov:**
I found this: https://docs.codecov.com/docs/pull-request-comments
And here a random PR from their repo: `https://github.com/codecov/codecov-action/pull/633`

**Coveralls:**
I only found this: https://docs.coveralls.io/coveralls-notifications, they need access via a bot user?! no token?
Example PR of one of their repos: `https://github.com/coverallsapp/coveralls-node-demo/pull/13`
_it seems that they have not setup their own tool for their core repo_ :eyes: (https://github.com/coverallsapp/github-action)

---

This really non in depth and ultra fast review of these both tools let me highly tend to Codecov right now :thinking: 

But while researching, I also found `Codacy` :eyes: ... Just another tool :thinking: Not sure if it's worth to jump into that :shrug: 

---

At the end, I would love to have a PR comment that only updates itself and reports the coverage in a not too much verbose but helpful way.

**Comment by Shinigami92** [comment]
Based on @damienwebdev hard no, I start to tend to write just a bot that creates and updates a comment in a PR :thinking: 
Would be something like this: https://github.com/marketplace/actions/jest-coverage-report
But maybe for vitest or just native lcov support without referencing jest
