### ISSUE TITLE
Improve behavior of generate:locales

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#389]
Can we create a ticket to add a workflow test for this? that is only running if something in the locales folder did change?

@prisis 

> Can we create a ticket to add a workflow test for this? that is only running if something in the locales folder did change?

_Originally posted by @prisis in https://github.com/faker-js/faker/pull/252#discussion_r796805039_

**Comment by ST-DDT** [comment]
Are you referring to running the command in the workflow/ci pipeline and failing if it detects changes that weren't commited?

**Comment by prisis** [comment]
> Are you referring to running the command in the workflow/ci pipeline and failing if it detects changes that weren't commited?

Yeah, so we will not forget it :)
