### ISSUE TITLE
Accept numbers as params for Date methods

### ISSUE THREAD

**Issue by pkuczynski** [faker-js/faker#394]
### Clear and concise description of the problem

https://github.com/faker-js/faker/pull/200#issuecomment-1024802219

### Suggested solution

Accept timestamps

**Comment by xDivisionByZerox** [comment]
Now this sounds like a job for me!

**Comment by pkuczynski** [comment]
> Now this sounds like a job for me!

Bear in mind there is already PR from me doing this for Date object so better of extend this one I guess otherwise it will conflict

**Comment by xDivisionByZerox** [comment]
Ok, this even solves some concerns for me about accepting numbers but not plain dates. Thanks for the information

**Comment by ST-DDT** [comment]
This has been fixed in #670 in v6.1.
