### ISSUE TITLE
Module doesn't work when package.json type is "module"

### ISSUE THREAD

**Issue by AlphaBeta906** [faker-js/faker#409]
### Describe the bug

When I imported faker.js, it gave the error `TypeError: Cannot read properties of undefined (reading 'findName')`, when I did `console.log(faker.name)`, it outputted undefined. It does work when the package.json type isn't module.

This is the code for the original file:
```js
import faker from '@faker-js/faker';

console.log(faker.name.findName());
```

Here is the one without the "module" type:

```js
const { faker } = require('@faker-js/faker');

const randomName = faker.name.findName();

console.log(randomName)
```

### Reproduction

In a package.json file, make the "type" to "module". Then import faker.js, then place a function.

### Additional Info

The version number is 6.0.0-alpha.5.

**Comment by Shinigami92** [comment]
Could you please try this:

```diff
- import faker from '@faker-js/faker';
+ import { faker } from '@faker-js/faker';
```

**Comment by AlphaBeta906** [comment]
Oh it worked, thanks, but the documentation was the one that lead to this problem, as it wrote
```js
import faker from '@faker-js/faker';
```

Thanks!

**Comment by Shinigami92** [comment]
Could you point me where the doc is outdated?
