### ISSUE TITLE
tsc not finding types / noImplicitAny==false is required

### ISSUE THREAD

**Issue by ex-nerd** [faker-js/faker#444]
I'm trying to create my own faker instance with some custom types, something like this:

```typescript
import { Faker } from '@faker-js/faker';

export class MyFake extends Faker {
	readonly customFake = new CustomFake(this);
}

export class CustomFake {
	private readonly fake: MyFake;

	constructor(fake: MyFake) {
		this.fake = fake;
	}

	/* side note: this syntax seems a lot easier than the bind() stuff faker currently uses */
	public someFakeThing = () => {
		return "fake data";
	}
}
```

This builds fine as long as `tsconfig.json` `compilerOptions` contains `"noImplicitAny": false`, however without this flag the build fails with something like:

>src/myFake.ts:1:23 - error TS7016: Could not find a declaration file for module '@faker-js/faker'. '/LONG-PATH-TO/node_modules/@faker-js/faker/dist/cjs/index.js' implicitly has an 'any' type.
>   Try `npm install @types/faker-js__faker` if it exists or add a new declaration (.d.ts) file containing `declare module '@faker-js/faker';`
> 
> 1 import { Faker } from '@faker-js/faker';

**Comment by Shinigami92** [comment]
Could you setup a minimal reproduction via [fakerjs.dev/new](https://fakerjs.dev/new) and send the link here?
Than it could be easier for us to find the problem.

**Comment by ex-nerd** [comment]
Not familiar enough with the front-end side of things.  Here's a zip with a module that exhibits the bug (and fixes the typo in my original note).  Toggle `noImplicitAny` in `tsconfig.json` to see the issue.
[fakerbug.zip](https://github.com/faker-js/faker/files/8013172/fakerbug.zip)
.

**Comment by Shinigami92** [comment]
@ex-nerd :sweat_smile: 
StackBlitz is not only for Frontend, you can completely ignore the `html` stuff and just replace the `index.ts`'s content

**Comment by ex-nerd** [comment]
Sorry, long day and after midnight here.   I think this should have the info:

https://stackblitz.com/edit/faker-js-demo-y2n64z?devtoolsheight=33&file=index.ts

However, the error does not appear like it does using my standalone version (no idea what version of node/typescript stackblitz is using vs the older ones required by the lambda environment we use).

**Comment by Shinigami92** [comment]
Oh, could you tell me which TS version do you use?
It could be something to do that we only support TS 4.0+ (and even that I'm not sure about if this is fully working, it should work with TS 4.5)

**Comment by Shinigami92** [comment]
I'm not sure if it's worth to document somewhere that only TypeScript >=4.0 is supported. No library out there has such a documentation note and it's possible to find https://github.com/faker-js/faker/blob/1b08de821588a1d5a2436c177c20d60a66e8a977/package.json#L28

So TS 4.0 is out for around one and a half year now. And it's unusual that you need to rely on prior TS 4.0.
If an additional maintainer has the same opinion, we should close this issue.

**Comment by ex-nerd** [comment]
I don't think the restriction in package.json was present when I filed this bug, but yes that's certainly enough to notify developers of the version requirements.

For what it's worth, things actually do work just fine in node 12 and ts 3.9.x ...  just can't extend classes without the `noImplicitAny` flag.

**Comment by Shinigami92** [comment]
Yeah, I think that is okay right now. When Node v18 comes out we will also officially drop support for Node v12...
So we move forward anyways 🤷 

If you like to, you can also decide to close this issue 🙂

**Comment by ex-nerd** [comment]
Unfortunately, many of us in the enterprise world are stuck with old versions (even AWS lambda only supports v12 and v14). Working on getting that fixed, but it takes awhile to migrate a couple million lines of code.

**Comment by Shinigami92** [comment]
> Unfortunately, many of us in the enterprise world are stuck with old versions (even AWS lambda only supports v12 and v14). Working on getting that fixed, but it takes awhile to migrate a couple million lines of code.

If needed, we have all the tags from 5.5.3 and prior released and tagged 🙂 in our npm package and repo
