### ISSUE TITLE
vehicle undefined

### ISSUE THREAD

**Issue by hexdecimal16** [faker-js/faker#451]
### Describe the bug

faker.vehicle returns undefined

### Reproduction

`faker.vehicle.manufacturer()`

### Additional Info

@faker-js/faker": "^6.0.0-alpha.5"

**Comment by Shinigami92** [comment]
Please check first if you have used correct import strategy: https://fakerjs.dev/guide/#node-js
`import { faker } from '@faker-js/faker';`

**Comment by JoCat** [comment]
same problem but my import returns undefined or empty object

```js
import { faker } from '@faker-js/faker'
console.log(faker) // undefined
```
```js
import faker from '@faker-js/faker'
console.log(faker) // {}
```

i use Meteor 2.6

**Comment by hexdecimal16** [comment]
https://github.com/faker-js/faker/issues/451#issuecomment-1050013731
This worked for me as well.
