### ISSUE TITLE
`faker.unique` TS error 

### ISSUE THREAD

**Issue by v-iliescu** [faker-js/faker#456]
### Describe the bug

when using `faker.unique` with some other faker functions that take arguments, Typescript will throw an error

tried with:
* `faker.address.countryCode`
* `faker.datatype.number`
* `faker.random.arrayElement`
* `faker.internet.email`

### Reproduction

```javascript
import { faker } from '@faker-js/faker';

const code =  faker.unique(faker.address.countryCode, []);
const code2 =  faker.unique(faker.address.countryCode);
// const code3 =  faker.unique(faker.address.countryCode, 'US');
const code4 =  faker.unique(faker.address.countryCode, ['US']);
```
all the above throw TS errors but result seem to be ok except for `code3`.

**Comment by Shinigami92** [comment]
@import-brain I assume you have tried it due to you applied the `bug` label.
Do you have a reproduction environment or a StackBlitz link for this?
That would help to reduce my maintenance time :)

**Comment by import-brain** [comment]
> ```js
> const code =  faker.unique(faker.address.countryCode, []);
> ```

https://stackblitz.com/edit/faker-js-demo-kbblpv?file=index.ts

Here is the StackBlitz I used to test this issue. Looks like a type error to me.

**Comment by ST-DDT** [comment]
Did this work in 5.x before?

**Comment by v-iliescu** [comment]
@ST-DDT it's still working in `6.0.0-alpha.3`

**Comment by ST-DDT** [comment]
Then the bug was most likely introduced here:
https://github.com/faker-js/faker/pull/254/files#diff-37527bfbf98141fa6280776389dd1bc989f5b8b2791b7445cd2a7fefc563b22fR39

**Comment by Shinigami92** [comment]
This was the prev def: https://github.com/Ivan-Kuzmichev/DefinitelyTyped/blob/d04089192418ea5954df5abb0093f9e5c7e115a5/types/faker/index.d.ts#L329-L333

If someone wants to tackle it and update it, feel free to open a PR
Otherwise I can try to tackle it tomorrow or later, today I will not have time

**Comment by ST-DDT** [comment]
I will create a PR for that.

FFR: The original signature:

https://github.com/faker-js/faker/blob/29234378807c4141588861f69421bf20b5ac635e/lib/unique.js#L24

**Comment by ST-DDT** [comment]
FFR: There is also: #333
