### ISSUE TITLE
docs(demo): Create a demo website

### ISSUE THREAD

**Issue by ericjeker** [faker-js/faker#46]
### Clear and concise description of the problem

Currently, in the README the Demo is still marked as `Coming soon`.

### Suggested solution

We could build a small demo website that allows users to:

1. See the different generators and their options
2. Play with the different options and see the result live
3. Allow the result of the generator to be one-click copied in the clipboard
3. Generates the relevant code and allow it to be one-click copied for quick usage in their own code

We could use a Vite/React or Vite/Svelte website as we have @Shinigami92 in our team. 😃 

As Faker is also usable in Node.js, should we have a demo CLI tool? Or a faker-cli? Not sure it's related to this issue though.

**Comment by damienwebdev** [comment]
[I can suggest Stackblitz](https://stackblitz.com/) because its really easy to use. I don't know what all we want to showcase on the site. Perhaps pick some of the most common `faker` scenarios? Words, numbers, etc.

**Comment by ericjeker** [comment]
I have used Stackblitz a lot but now I use [codesandbox.io](https://codesandbox.io/). My experience with it is much better. Just wanted to mention it, both are good.

**Comment by schalkventer** [comment]
I'm the maintainer of the [faker-extra ](https://www.npmjs.com/package/faker-extra) library, obviously the recent development has been a bit of a head-ache for me. Happy to help out in whatever way might be helpful to ensure the continued development (even if community driven) of Faker.js.

I have a lot of design/UI/UX experience as well ([https://www.linkedin.com/in/schalkventer/](https://www.linkedin.com/in/schalkventer/)), so happy to help with the design of a landing-page/demo site. In terms of tech stack I'd likely recommend just going vanilla JS or even Web Component purely for the sake of easing the on-boarding for anyone wanting to contribute. 

Curious the hear everyone's thoughts on this?

**Comment by Shinigami92** [comment]
For a start, we could also try it simple with `typedoc`
But this would be super simple and not really nice if we want to add manually content

**Comment by yashraj-02-techie** [comment]
I would love to work on creating a demo website for faker-js. If you decide that we need one.

**Comment by Shinigami92** [comment]
> I would love to work on creating a demo website for faker-js, if you decide that we need one.

Please go into the Discord server, if you are not there already
and communicate with @JessicaSachs and @ericjeker

**Comment by JessicaSachs** [comment]
> I would love to work on creating a demo website for faker-js, if you decide that we need one.

👋 just to write something outside of Discord... PR #80 has the infra to get a Playground page within the Faker website.

I did some noodling on what a UI/UX would look like, but couldn't come up with anything. If you decide to pick it up, tell me in the Discord so we don't do double work.

**Comment by damienwebdev** [comment]
See also #87

**Comment by imbdb** [comment]
Can we use Runkit for demo?
something like this
```
<h3 style="text-align: center;">Faker Demo</h3>

<script src="https://embed.runkit.com" data-element-id="my-element"></script>

<!-- anywhere else on your page -->
<div id="my-element">// Faker!
var faker = require("@faker-js/faker");

console.log(faker.fake('{{name.firstName}} {{name.lastName}}'))</div>
```

**Comment by ST-DDT** [comment]
We now have the stackblitz demo, so this should be good enough:
https://fakerjs.dev/new
