### ISSUE TITLE
Angolia search bar in docs is returning 'indexName is not valid error'

### ISSUE THREAD

**Issue by shmuelsochet** [faker-js/faker#461]
### Describe the bug

When using the search bar no results are shown and the message in the console reads...

![image](https://user-images.githubusercontent.com/26887125/153423638-d7c1a900-5851-4573-9388-fc7356283f62.png)

### Reproduction

Open docs and try searching for anything in the algolia search bar.

**Comment by Shinigami92** [comment]
Duplicate of #222
