### ISSUE TITLE
vehicle bicycle_type incorrect file names

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#471]
### Describe the bug

The vehicle module access the definitions of `vehicle.bicycle_type`, but this was renamed in one of the last PRs accidentally

### Reproduction

Call `faker.vehicle.bicycle()` results in 'a', 'b' or 'c' (the defaults of `arrayElement`)

**Comment by ST-DDT** [comment]
I will take care of this once #398 is merged.
