### ISSUE TITLE
PIN, account number

### ISSUE THREAD

**Issue by petrzjunior** [faker-js/faker#472]
### Clear and concise description of the problem

I need to generate 4-letter PIN numbers. Since `faker.datatype.number` cannot generate leading zeroes, I was looking at `faker.finance.account` which does exactly this thing. But it doesn't look right to me to use bank account generator for PIN, the bank account format might be localized in the future, since different countries use different formats.
Examples:
- [Belgium](https://www.ecbs.org/iban/belgium-bank-account-number.html): 539-0075470-34
- [Czechia](https://www.ecbs.org/iban/czech-replublic-bank-account-number.html), [Slovakia](https://www.ecbs.org/iban/slovak-republic-bank-account-number.html): 19-2000145399/0800
- [Italy](https://www.ecbs.org/iban/italy-bank-account-number.html): X 05428 11101 000000123456
- [Malta](https://www.ecbs.org/iban/malta-bank-account-number.html): 12345MTLCAST001S
- Some other countries is Europe use BBAN (part of IBAN) as their national format, many more have spaces or dashes in their account numbers.

### Suggested solution

I suggest we create a new generator `faker.finance.pin` or `faker.internet.pin` which generates string of numbers of provided length.
As for the bank account formats, we might start localizing them.

**Comment by ST-DDT** [comment]
This is already possible with:

`faker.helpers.replaceSymbols("####")` -> `0038`

**Comment by petrzjunior** [comment]
@ST-DDT  I see, this can serve well for me.
But since PIN (security code, OTP) digit string are common, do you think it would be beneficial to create a helper for them?
