### ISSUE TITLE
mersenne.rand without min argument returns NaN

### ISSUE THREAD

**Issue by piotrekn** [faker-js/faker#479]
### Describe the bug

>This is buggy, cause if min is not passed but only max, then min will be undefined and this result in NaN for the whole function

https://github.com/faker-js/faker/blob/30b0faa1cba1d3cd74e95315347b98a49ebcb76b/src/mersenne.ts#L31-L40

### Reproduction

``` typescript
new Mersenne().rand(1);
```
This should return `0` no matter the seed, but returns `NaN`.

**Comment by xDivisionByZerox** [comment]
I want to do this. Please assign me.

**Comment by xDivisionByZerox** [comment]
I also implemented an if statement that checks if `min > max` in which case it throws an error. This behavior is breaking 83 test in 4 suits.

What would the expected behavior be here?

**Comment by ST-DDT** [comment]
> I also implemented an if statement that checks if `min > max` in which case it throws an error. This behavior is breaking 83 test in 4 suits.
> 
> What would the expected behavior be here?

Not sure on this one. I tend to allow min and max to be swapped as a kind of undocumented convenience feature.

**Comment by piotrekn** [comment]
If `mersenne.rand` does not bother the min-max swap, should it thrown an error? To maintain the semantic meaning consider swapping values instead.

**Comment by xDivisionByZerox** [comment]
FYI: Swapping the values will not break any existing test cases.
