### ISSUE TITLE
Would markdown is a good idea?

### ISSUE THREAD

**Issue by PeterlitsZo** [faker-js/faker#486]
### Clear and concise description of the problem

Sometime the I wanna to mock markdown to render rather than plain text. If faker.js support it, it will be great!

### Suggested solution

I am not sure what the word `module` meaning...

**Comment by ST-DDT** [comment]
Could you be a little bit more specific regarding your requirements?

What do you need specifically . Do you want some text that contains `` `foobar` `` ?
What about the other "markdown features"? Tables, Images, Links, Lists?

IMO there are too many possible variations to cover them all and they can be put together relatively easy using the existing methods.

**Comment by HonzaMac** [comment]
@PeterlitsZo maybe this gist can help you https://gist.github.com/DavidWells/a75045c89d6f3d453ef4ab68499550f4 ?

**Comment by PeterlitsZo** [comment]
Thanks you~ It is OK! Although it do not have some md features helpful.

**Comment by Shinigami92** [comment]
I think it’s okay if you start to write in your language. We even have some people like @import-brain who is chinese as far as I know. We can use autotranslate tools to try understand what you want to tell us.

Autotranlated: 

我认为如果你开始用你的语言写作就可以了。 据我所知，我们甚至有一些像 @import-brain 这样的中国人。 我们可以使用自动翻译工具来尝试理解您想告诉我们的内容。

**Comment by import-brain** [comment]
> I think it’s okay if you start to write in your language. We even have some people like @import-brain who is chinese as far as I know. We can use autotranslate tools to try understand what you want to tell us.
> 
> Autotranlated: 
> 
> 我认为如果你开始用你的语言写作就可以了。 据我所知，我们甚至有一些像 @import-brain 这样的中国人。 我们可以使用自动翻译工具来尝试理解您想告诉我们的内容。

Well, I'm American, but I'm fluent in Chinese. That google translate certainly is...something😅

**Comment by import-brain** [comment]
@Shinigami92 I think he is asking for the creation of a new method that generates valid markdown.

**Comment by xDivisionByZerox** [comment]
I will close this due to inactivity and the workaround provided by @HonzaMac.
Feel free to reopen if you think this issue should be addressed.

**Comment by PeterlitsZo** [comment]
Yes, I think so.

Fake markdown by hand will be a better idea.
