### ISSUE TITLE
Add resolve parameter to functions returning an image url

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#487]
### Clear and concise description of the problem

Currently the methods that generate random images return only a link to a generic endpoint which then redirects to the actual image.
If you use these to generate some fake data, then the image your are seeing will differ every time you show it.

### Suggested solution

Add a parameter that lets faker resolve the url for you (calling the target url get the redirect url and return that instead).
That way you have actual links to the target image instead of a link that redirects to a random one.

**Comment by CookrC** [comment]
How do we want to resolve the URL? Should we depend on the node-fetch module and use its fetch function?

**Comment by Shinigami92** [comment]
We already us `lock`

https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/src/modules/image/index.ts#L114
