### ISSUE TITLE
docs: remove old documentation and add a new one

### ISSUE THREAD

**Issue by xryshirfxn** [faker-js/faker#49]
In the "Docs" section, the link points to the original [github.io](https://github.io) page which is no longer working. Create a `faker-js.github.io` repository and host the docs there (just a suggestion)

**Comment by bolshoytoster** [comment]
It looks like documentation is still hosted on [netlify](https://fakerjsdocs.netlify.app). We could point to that instead.

**Comment by Shinigami92** [comment]
In 1-2 days we will have hopefully deployed #80
For everything else, please subscribe to #87

**Comment by xryshirfxn** [comment]
Great to know. Thanks

**Comment by JessicaSachs** [comment]
Yeah so we need to kill the old docs and we need to migrate the examples.
