### ISSUE TITLE
Address doesn't use street_name / street_root from locale

### ISSUE THREAD

**Issue by palimondo** [faker-js/faker#491]
### Describe the bug

When testing with `faker.locale = "de"`, I have noticed that the [Address](https://github.com/faker-js/faker/blob/main/src/address.ts#L156).`streetName` generates the street name from English first names and does not use the localized streets provided in **street_name** / [street_root](https://github.com/faker-js/faker/blob/main/src/locales/de/address/street_root.ts) / [street](https://github.com/faker-js/faker/blob/main/src/locales/cz/address/street.ts) files.

This seems like a bug, but I'm completely new to faker-js, so I'm not sure if this is just a preparation for some future refactoring or a regression.

### Reproduction
```
faker.locale = 'de';
console.log(faker.address.streetName())
// expected to return something from:
// https://github.com/faker-js/faker/blob/main/src/locales/de/address/street_root.ts
```

### Additional Info
I would have expected the implementation to look like:
```
  streetName(): string {
    return this.faker.random.arrayElement(
      this.faker.definitions.address.street_name
    );
  }
```

**Comment by Shinigami92** [comment]
I investigated a bit the code and yes, looks weird :thinking: 
We are currently rewriting tests and docs to have a stable project base.
And soon :tm: we can start working on first bug fixes.

Until then I can suggest to use `faker.random.arrayElement(faker.definitions.address.street_name);` on your own, or try something like `faker.fake('{{address.street_name}}');`.
