### ISSUE TITLE
Add separate methods for random key and value

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#492]
Wouldn't it be much easier from an architectural and types perspective, by splitting this method into 2 separate ones? One for object value and one for object key.

_Originally posted by @xDivisionByZerox in https://github.com/faker-js/faker/issues/407#issuecomment-1040411965_

**Comment by xDivisionByZerox** [comment]
Since I, more or less, requested this feature, should I provide help by implementing this change and providing a pull request?

**Comment by ST-DDT** [comment]
Contributions are always welcome. We might not be be able to merge it soon though.

**Comment by import-brain** [comment]
@xDivisionByZerox Assigning to you :)

**Comment by xDivisionByZerox** [comment]
I just opened #503
