### ISSUE TITLE
Add a faker.internet.emoji function

### ISSUE THREAD

**Issue by hugoattal** [faker-js/faker#497]
### Clear and concise description of the problem

I think it would be useful to generate random emoji. My use case is that I have documents that can have an emoji icon (a bit like notion), so I would like to generate random emoji for this.

### Suggested solution

I suggest creating a `faker.internet.emoji()` function that return a random emoji

**Comment by import-brain** [comment]
@hugoattal Do you want to work on this? I can assign this to you.

**Comment by hugoattal** [comment]
@import-brain Yes why not!

**Comment by import-brain** [comment]
Okay, I'll assign it to you :)

**Comment by hugoattal** [comment]
Here it is: https://github.com/faker-js/faker/pull/504 !

**Comment by AbhishekGyizer** [comment]
It's throwing error
  [Error]: The locale data for 'internet.emoji' are missing in this locale.

**Comment by ST-DDT** [comment]
> It's throwing error [Error]: The locale data for 'internet.emoji' are missing in this locale.

Please create a new issue and provide the required information.
