### ISSUE TITLE
Deprecate helpers.userCard/contextualCard/createCard

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#528]
These methods place a maintenance burden on this library while providing little benefit to the users.
Users that need a specific data object usually require custom data structures that can be easily defined in a self-managed method.
We should only provide methods for standardized data structures directly.

**Comment by sprohaszka** [comment]
Hello @ST-DDT.
To be sure to understand, you only want to add `deprecated` JSDoc flag?

**Comment by ST-DDT** [comment]
The deprecation consists of two parts:
`@deprecated` jsdocs and a console.log warning.

Example: https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d43/src/random.ts#L57-L64

**Comment by sprohaszka** [comment]
Tell me you're ok with the wording.

**Comment by Shinigami92** [comment]
Was not linked to the PR, already solved
