### ISSUE TITLE
Willing to help..

### ISSUE THREAD

**Issue by jasonk** [faker-js/faker#54]
It looks like you are attempting to turn this into a community-controlled package, which is a great idea given recent events.  Since I've been using it at my day job I'd be willing to pitch in and help.  FWIW I'm already mentioned in the README, as I wrote the Perl Data::Faker package that it's based on...

**Comment by damienwebdev** [comment]
@jasonk thank you for the offer. Your copyright has been in this repo for a very long time, so having your background is most appreciated. If you use Discord, we have a nice little community server going - #21 Otherwise, I'd love to get any insight from you in general!
