### ISSUE TITLE
Vehicle VIN generate VIN with invalid characters (I, O, Q)

### ISSUE THREAD

**Issue by PerHermanssonPrivat** [faker-js/faker#540]
### Describe the bug

VIN format specifications have since long excluded the characters I, O and Q as they are easily mis-read as numbers 0 and 1.
https://en.wikipedia.org/wiki/Vehicle_identification_number

It seems the faker.vehicle.vin() incorrectly returns sample with these chars included.

### Reproduction

Check output for chars, below test gave me:

````ts
[ 
["8CIN3S2PEDYT56606",true],
["45EANPQJC3MP41287",true]]
["KCCLWSV354WP42784",false],
["LEMZFBAW4VRL60727",false],
["BH3A46LDVQQQ86210",true],
["S5OQ98O54IQQ61168",true]]
["9KMH638TRJA788711",false],
["N13RUH30MLON72093",true],
["HLT4JXLN5DUL71584",false],
["GY6F7J8XG5EW36090",false]
]

function example_vin ()
{
   myvin = faker.vehicle.vin();
   myCheck = myvin.includes("I")||myvin.includes("O")||myvin.includes("Q");

   return [myvin, myCheck];
}

myArray = [];

for (let i = 0; i < 10; i++) {
    mydata = example_vin();
    myArray.push (mydata);
}
return JSON.stringify (myArray);
````

### Additional Info

Remotely related to this other change on the  faker.vehicle.vin()

https://github.com/faker-js/faker/issues/319

**Comment by import-brain** [comment]
Hi, could you please provide a StackBlitz or something of the like with a working reproduction of this issue? I and @xDivisionByZerox were unable to reproduce this.

**Comment by Shinigami92** [comment]
The author did not response for around one week, we can reopen the issue on demand if needed
