### ISSUE TITLE
Source code todo list

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#541]
This issue serves as a container for all todos listed in the source code from 03c3d1156312153428f2db5649b24dd5fc046d43.

This covers only `TODO` and `FIXME` and no `it.todo` statements for now.

Column `method` is a static link to the original comment in 03c3d1156312153428f2db5649b24dd5fc046d43. The other columns will be updated with time so it might be that the description you see in the table will not match with the description in the source file, because it was updated.

| description                                                                                                                      | link                                                                                                                                   | issue/pr  | fixed |
| -------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------- | --------- | ----- |
| Fix types                                                                                                                        | [address.zipCodeByState](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L69)            | #759      | ✔     |
| The string parameter doesn't work as expected.                                                                                   | [address.city](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L94)                      | #682, #948    | ✔    |
| change all these methods that accept a boolean to instead accept an options hash.                                                | [address](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L175)                          | #649      | ✔     |
| this.faker.definitions.address.secondary_address                                                                                 | [address.secondaryAddress](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L248)         | #676      | ✔     |
| Limit the parameter to the two values.                                                                                           | [address.countryCode](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L289)              | #587 #588 | ✔    |
| useAbbr not in use                                                                                                               | [address.state](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L316)                    | #677      | ✔     |
| Allow coordinate parameter to be [string, string].                                                                               | [address.nearbyGPSCoordinate](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L458)      | #780      | ❌    |
| Remove unused code.                                                                                                              | [address.nearbyGPSCoordinate](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L464)      | #668      | ✔     |
| implement either a gaussian/uniform distribution of points in circular region.                                                   | [address.nearbyGPSCoordinate](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/address.ts#L518-L519) | #876          | ✔    |
| unimplemented member functions                                                                                                   | [commerce](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/commerce.ts#L92)                         | #690      | ✔     |
| find undefined here                                                                                                              | [commerce.mergeCategories](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/commerce.ts#L112)        | #690      | ✔     |
| It may be a bug that `lastDate` is passed to parse if it's a `Date` not a `string`                                               | [date.between](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/date.ts#L123)                        | #200      | ✔     |
| This is impossible to access                                                                                                     | [finance.creaditCardNumber](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/finance.ts#L278)        | #375      | ✔     |
| We may want to make it configurable to use just `\n` instead of `\r\n`                                                           | [git.commitEntry](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/git.ts#L63)                       | #679      | ❌    |
| Mark as deprecated                                                                                                               | [helpers.randomize](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L135)                | #466      | ✔     |
| I assume this should be converted to string                                                                                      | [helpers.replaceCreditCardSymbols](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L298) | #755      | ✔     |
| implement for letters e.g. [0-9a-zA-Z] etc.                                                                                      | [helpers.regexpStyleStringParse](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L368)   | -         | ❌    |
| This default will never be taken!?                                                                                               | [helpers.shuffle](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L405)                  | #684      | ✔     |
| Check what to do here                                                                                                            | [helpers.uniqueArray](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L442)              | #613      | ✔     |
| Try to improve the type or maybe use `if`                                                                                        | [helpers.mustache](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L482)                 | #753      | ✔     |
| We may need to convert this to a string                                                                                          | [helpers.contextualCard](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L568)           | -         | ⛔    |
| add a ranged date method                                                                                                         | [helpers.createTransaction](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/helpers.ts#L647)        | #782         | ⛔    |
| This needs to be converted to string                                                                                             | [iban.toDigitString](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/iban.ts#L36)                   | #781         | ✔    |
| iban was not used                                                                                                                | [Faker](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/index.ts#L97)                               | ?         | ✔    |
| Find a way to load this even more dynamically. In a way so that we don't accidentally miss a definition.                         | [Faker.loadDefinitions](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/index.ts#L122)              | #822      | ✔    |
| Add ipv4 alias                                                                                                                   | [internet.ip](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/internet.ts#L207)                     | #649      | ✔     |
| `range` is not in use                                                                                                            | [lorem.sentence](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/lorem.ts#L73)                      | #649      | ✔     |
| The separator looks odd.                                                                                                         | [lorem.paragraphs](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/lorem.ts#L166)                   | #783      | ✔    |
| `times` is not in use                                                                                                            | [lorem.text](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/lorem.ts#L188)                         | #649      | ✔     |
| This is buggy, cause if min is not passed but only max, then min will be undefined and this result in NaN for the whole function | [mersenne.rand](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/mersenne.ts#L274)                   | #577         | ✔    |
| Rewrite this file to a class                                                                                                     | [MersenneTwister19937](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/vendor/mersenne.ts#L32-33)   | #280      | ✔     |
| Not sure if this fallthrough is wanted                                                                                           | [name.findName](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/name.ts#L188)                       | -         | ❌    |
| simplify name to `number()`                                                                                                      | [phone.phoneNumber](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/phone.ts#L24)                   | #693      | ❌    |
| this is strange passing in an array index. discuss removing this method as it tightly couples with localisation.                 | [phone.phoneNumberFormat](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/phone.ts#L40-41)          | -         | ❌    |
| simplify name to `format()`                                                                                                      | [phone.phoneNumberFormat](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/phone.ts#L54)             | -         | ❌    |
| have ability to return specific type of word? As in: noun, adjective, verb, etc                                                  | [random.word](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/random.ts#L220)                       | -         | ⛔    |
| Tests covered `(count, options)`, but they were never typed like that                                                            | [random.alpha](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/random.ts#L309)                      | -         | ❌    |
| A default empty array gets assigned above, we should check the length against 0 or not here                                      | [random.alpha](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/random.ts#L363)                      | -         | ❌    |
| This is not non-deterministic                                                                                                    | [time.recent](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/time.ts#L14)                          | -         | ⛔    |
| add default case                                                                                                                 | [time.recent](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/time.ts#L26)                          | #533      | ✔     |
| address.zipCodeByState() expects only { [state: string]: { min: number; max: number } }                                          | [AddressDefinitions](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/src/definitions/address.ts#L10)    | #759      | ✔     |
| Investigate why this test sometimes fails                                                                                        | [address](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/address.spec.ts#L650)                    | -         | ❌    |
| these are TODOs                                                                                                                  | [allFunctional](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/all_functional.spec.ts#L15)        | -         | ❌    |
| I converted the price string to number to satisfy TS                                                                             | [commerce](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/commerce.spec.ts#L123)                  | -         | ❌    |
| I converted the price string to number to satisfy TS \*(this is no accidental duplication)\*                                     | [commerce](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/commerce.spec.ts#L155)                  | -         | ❌    |
| We will fix the deterministic in #343                                                                                            | [datatype](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/datatype.spec.ts#L25)                   | #343      | ✔     |
| This function doesn't respect seeding                                                                                            | [date](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/date.spec.ts#L286)                          | -         | ✔     |
| add support for more currency and decimal options                                                                                | [finance.amount](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/finance.spec.ts#L217)             | -         | ❌    |
| implement checks for each format with regexp                                                                                     | [finance.creditCardNumber](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/finance.spec.ts#L370)   | -         | ❌    |
| When providing params to `email`, it produces some not that predictable data                                                     | [internet.email](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/internet.spec.ts#L152)            | -         | ❌    |
| Make tests more strict                                                                                                           | [internet.userAgent](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/internet.spec.ts#L406)        | -         | ❌    |
| Understand what's going on                                                                                                       | [internet.color](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/internet.spec.ts#L424)            | -         | ❌    |
| I would say a non memorable password should satisfy `validator.isStrongPassword`, but it does not currently                      | [internet.password](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/internet.spec.ts#L516)         | #768      | ❌    |
| This should definitely be a strong password, but it doesn't :(                                                                   | [internet.password](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/internet.spec.ts#L530)         | #768      | ❌    |
| There is a bug: https://github.com/faker-js/faker/issues/479                                                                     | [mersenne.rand](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/mersenne.spec.ts#L135)             | #479      | ✔     |
| There is a bug: https://github.com/faker-js/faker/issues/373                                                                     | [name.firstName](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/name.spec.ts#L135)                | #373      | ✔     |
| jobTitle and title are the same                                                                                                  | [name.title](https://github.com/faker-js/faker/blob/214a77b437aaff1282248a6ee14fd227d5e42c42/test/name.spec.ts#L529)                   | #766      | ✔     |
| Add multiple seed based expectations.                                                                                            | [seedRuns](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/system.spec.ts#L5)                      | #765      | ✔     |
| Add test to validate if the path has ext on the end.                                                                             | [system.filePath](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/system.spec.ts#L240)             | #765      | ✔     |
| Results are not seeded yet                                                                                                       | [time](https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d4/test/time.spec.ts#L36)                           | -         | ⛔    |

Legend:
- ❌ not yet fixed/fix not merged yet
- ✔ fixed
- ⛔ won't fix

**Comment by prisis** [comment]
Thank you very much, for collecting all the todos :)

**Comment by xDivisionByZerox** [comment]
Should i add a column for `fixed` to keep track of fixed todos, so this issue can get closed of all other issues are closed?

**Comment by ST-DDT** [comment]
That would be helpful. Thank you.

**Comment by ST-DDT** [comment]
The list is getting shorter. We are now at ~50% 🥳 
- 29 ✔
- 27 ❌
- 4 ⛔

**Comment by ST-DDT** [comment]
Most of the TODOs have been fixed and the rest of the links point to very old commits.
So I'm going to close this one. But we should probably create a new issue with the remaining TODOs.
@xDivisionByZerox did you create the list by hand or do you have a script for it?

**Comment by xDivisionByZerox** [comment]
I did it by hand. Probably should have written a script now that you say it ^^
