### ISSUE TITLE
Rewrite locale files to a non js/ts source file format and load them on demand

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#546]
### Clear and concise description of the problem

Currently we bundle the locale files twice, 1x for `cjs` and 1x for `esm`.
We should outsource the locale files to it's own folder and rewrite them to a format that can be as small as possible minified.
Please note: the source files could be yaml, so it is easier to read and write to it, but the bundled minified outfiles should be e.g. json.

Also the cjs and esm bundled code should read from one bundled locale source, so the bundle size will likely split into half its current size.

### Suggested solution

Rewrite via one-time automation script the locales into a new format and minify them in an extra step while building.

### Additional context

https://github.com/faker-js/faker/issues/405#issuecomment-1048740437

**Comment by ST-DDT** [comment]
> Please note: the source files could be yaml, so it is easier to read and write to it

It must be possible to have compile time type checks on them.

**Comment by Shinigami92** [comment]
Yes, we can do that with schema validation, good point :+1:

**Comment by ST-DDT** [comment]
> Yes, we can do that with schema validation, good point 👍
> 
> **Edit:** Real quick search => [paazmaya/yaml-validator](https://github.com/paazmaya/yaml-validator)

If this does not require us to specify the schema again (LocaleDefinition and subtypes).

**Comment by ST-DDT** [comment]
> Please note: the source files could be yaml, so it is easier to read and write to it

This should not be the sole reason, as its quite simple to convert between json and yaml anyway.

**Comment by ST-DDT** [comment]
**Team Decision**

Won't fix for now. We will focus on more important features in the meantime.
