### ISSUE TITLE
Incorrect behavior of `faker.image` functions

### ISSUE THREAD

**Issue by JoCat** [faker-js/faker#556]
### Describe the bug

Some image functions associated with the placeimg.com service do not work due to the fact that the service has abolished some image categories.

example:
```js
faker.image.abstract()
faker.image.business()
faker.image.cats()
faker.image.city() // replace link to arch
faker.image.fashion()
faker.image.food()
faker.image.nightlife()
faker.image.sports()
faker.image.technics() // replace link to tech
faker.image.transport()
```

maybe you should also check related function `faker.image.image()`

list of current categories taken from placeimg.com:
![image](https://user-images.githubusercontent.com/13483132/155488599-6e8d4842-a549-44f2-a6be-996466123747.png)

### Reproduction

https://stackblitz.com/edit/faker-js-demo-bbhemk?file=index.ts

**Comment by ST-DDT** [comment]
There are other categories that aren't working either e.g. `cats`.

**Comment by Shinigami92** [comment]
> There are other categories that aren't working either e.g. `cats`.

<img src="https://media3.giphy.com/media/RJDmEeLNgzgxW/giphy.gif?cid=790b7611b4decfe15cd4e594cad45126fbf644a08efb7a00&rid=giphy.gif&ct=g"/>

**Comment by franznoel** [comment]
So, do we have other alternative sources? or are we going to remove the non-existing ones?

**Comment by JoCat** [comment]
In principle, there are enough services on the Internet for obtaining images. It remains only to choose normal

**Comment by Shinigami92** [comment]
I'm not yet sure if we want to just provide more and more alternative services, or if we may want to provide a helper/factory functionality to just provide an image provider yourself but have a defined way of getting the random images.
That way you could easily swap in and out an image provider :thinking: 

@ST-DDT should we count this as v6.1 bug fix? or is it really needed right now in v6.0 and holding us back to release a v6.0.0?
I think and assume this issue is also present in v5.5.3 also :thinking:

**Comment by ST-DDT** [comment]
The links are working (although the show wrong content). removing the methods would be more breaking.
Thus I agree with moving this to v6.1.

**Comment by JoCat** [comment]
faker.image.cat() maybe raplaced to https://placekitten.com/

**Comment by Shinigami92** [comment]
IMO this is a bigger issue to tackle, so unless someone wants to propose a PR that somehow easily fix this, I would like to move this into v7+ and rethink about the whole image provider structure.
So now we can fix and release soon the `v6.1` bug fixes and move on to `v6.2`.

**Comment by JoCat** [comment]
I can try to implement this, only a little later
weekends for example

**Comment by JoCat** [comment]
> rethink about the whole image provider structure

Yes, I think it won't hurt

by the way, I noticed that there are other image providers in the code. But the site is the same lorempixel.com does not work

**Comment by damienwebdev** [comment]
I think this can be closed. There's a much larger project here which is to decide upon a `FakeImageProvider` interface that has externally provided options with a sane default. This would allow us to mitigate these kinds of problems. When we begin that process, I'll open a new issue and link it from here.
