### ISSUE TITLE
Base64 images support

### ISSUE THREAD

**Issue by vuki656** [faker-js/faker#572]
### Clear and concise description of the problem

I'm currently writing a test for an API that accepts images in `base64` format that will be uploaded to an S3 bucket. Faker doesn't have support for generating `base64` representation of images. 

I'd be willing to open a PR just unsure about the approach. I was thinking about hardcoding x amount of image `base64` strings and picking a random one each time. Let me know if you think there is a better approach. 

### Suggested solution

In the module `image` we could have `image.base64Image` or something alike. 

### Alternative

Currently, the solution I'm going with is just storing a few `base64` images in a separate file and importing them.

**Comment by ST-DDT** [comment]
How about adding a `format` parameter to the existing image methods?

- `simple`: Just returns the url (current)
- `resolved`: Returns a resolved url (resolve the redirect or require the seed to be in the url)
- `base64`: Download the image and convert it to base64

Would that also cover your usecase?

**Comment by vuki656** [comment]
That would be awesome.

Beats my idea of hardcoding them for sure.

**Comment by xDivisionByZerox** [comment]
Related to #487

**Comment by ST-DDT** [comment]
**Team Decision**

- The implementation is too difficult to produce usable images.
- It is far easier to just pick the data you need and base64 encode them yourself.
