### ISSUE TITLE
Change `faker.datatype.hexaDeciamal` implementation

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#575]
### Clear and concise description of the problem

`faker.datatype.hexaDeciamal` has its own implementation on generating a random number in hexadecimal representation. This brings multiple problems:

1. Increase the complexity of the library
1. Increase the chances of  errors
1. Increase the test cases that need to be written for this implementation

### Suggested solution

Use the number conversion system already in place in JavaScript.
```typescript
const myDecimalNumber = 255;
const myHexNumber = myDecimalNumber.toString(16); // "ff"
```

This would result in a implementation like this:
```typescript
function hexaDeciamal(length = 1) {
    return faker.datatype.number({
        max: (Math.pow(16, length) - 1),
        min: 0,
    }).toString(16);
}
```

This has multiple improvements:
1. reduce the complexity by reusing the existing random number generator in the library
1. reduce the risk of false behavior by using an already tested method to generate random numbers
1. increase the reusability for other methods that need hexadecimal strings (example: `faker.internet.ipv6`)
1. increase the performance exponentially with growing hexadecimal string length ('more in Additional context')

### Additional context

I ran some performance tests regarding the current and proposed implementation. The current implementation is a little bit faster while generated strings are really small, but is already twice as slow when the generated string length is at least 10.

I ran the test in javascript to exclude concerns about typescript (on the fly) compilation time.

### Code for benchmark
```javascript
const faker = require('./index').default;
const { Benchmark } = require('benchmark');
const { writeFileSync } = require('fs');

const currentImplementation = faker.datatype.hexaDecimal;
const newImplementation = (length = 1) => {
  return '0x' + faker.datatype.number({
    max: (Math.pow(16, length) - 1),
    min: 0,
  }).toString(16);
}

const logs = [];

(async () => {
  let times = 1;
  while (times <= 10) {
    const tile = `##### BENCHMARK - ${times} #####`;
    const decorator = '#'.repeat(tile.length);
    logs.push(decorator);
    logs.push(tile)
    logs.push(decorator);

    await (async () => new Promise((resolve) => {
      const suite = new Benchmark.Suite();
      const lengths = [
        1,
        10,
        100,
        1e3,
      ];

      for (const length of lengths) {
        suite.add(`current implementation with length ${length}`, () => {
          currentImplementation(length);
        });

        suite.add(`new implementation with length ${length}`, () => {
          newImplementation(length);
        });
      }

      suite.on("cycle", (event) => {
        logs.push(event.target.toString());
      });

      suite.on("complete", () => {
        resolve();
      });

      suite.run();
    }))();

    times++;
    logs.push('');
  }

  const path = './benchmark-logs.txt';
  writeFileSync(path, logs.join('\n'));
})();
```

#########################
\##### BENCHMARK - 1 ######
#########################
current implementation with length 1 x 6,059,013 ops/sec ±1.88% (82 runs sampled)
new implementation with length 1 x 5,292,875 ops/sec ±2.15% (87 runs sampled)
current implementation with length 10 x 568,246 ops/sec ±2.03% (76 runs sampled)
new implementation with length 10 x 1,074,681 ops/sec ±2.96% (83 runs sampled)
current implementation with length 100 x 68,818 ops/sec ±1.90% (89 runs sampled)
new implementation with length 100 x 544,094 ops/sec ±1.32% (85 runs sampled)
current implementation with length 1000 x 6,999 ops/sec ±2.84% (88 runs sampled)
new implementation with length 1000 x 5,544,341 ops/sec ±1.95% (90 runs sampled)

#########################
\##### BENCHMARK - 2 ######
#########################
current implementation with length 1 x 6,140,620 ops/sec ±1.80% (83 runs sampled)
new implementation with length 1 x 5,143,258 ops/sec ±3.63% (86 runs sampled)
current implementation with length 10 x 548,985 ops/sec ±2.11% (81 runs sampled)
new implementation with length 10 x 1,076,976 ops/sec ±2.34% (85 runs sampled)
current implementation with length 100 x 67,737 ops/sec ±2.95% (87 runs sampled)
new implementation with length 100 x 519,398 ops/sec ±2.40% (83 runs sampled)
current implementation with length 1000 x 7,186 ops/sec ±1.10% (89 runs sampled)
new implementation with length 1000 x 5,452,535 ops/sec ±3.05% (82 runs sampled)

#########################
\##### BENCHMARK - 3 ######
#########################
current implementation with length 1 x 6,065,911 ops/sec ±2.08% (88 runs sampled)
new implementation with length 1 x 5,287,262 ops/sec ±1.62% (85 runs sampled)
current implementation with length 10 x 559,164 ops/sec ±3.03% (83 runs sampled)
new implementation with length 10 x 1,116,786 ops/sec ±1.72% (82 runs sampled)
current implementation with length 100 x 70,413 ops/sec ±1.30% (92 runs sampled)
new implementation with length 100 x 472,916 ops/sec ±3.98% (80 runs sampled)
current implementation with length 1000 x 6,705 ops/sec ±2.46% (81 runs sampled)
new implementation with length 1000 x 5,225,158 ops/sec ±1.81% (81 runs sampled)

#########################
\##### BENCHMARK - 4 #####
#########################
current implementation with length 1 x 5,938,998 ops/sec ±2.82% (82 runs sampled)
new implementation with length 1 x 5,209,466 ops/sec ±2.95% (84 runs sampled)
current implementation with length 10 x 574,643 ops/sec ±1.99% (90 runs sampled)
new implementation with length 10 x 1,082,204 ops/sec ±2.56% (87 runs sampled)
current implementation with length 100 x 69,652 ops/sec ±1.93% (88 runs sampled)
new implementation with length 100 x 502,548 ops/sec ±3.78% (82 runs sampled)
current implementation with length 1000 x 7,183 ops/sec ±2.76% (90 runs sampled)
new implementation with length 1000 x 5,398,967 ops/sec ±2.40% (86 runs sampled)

#########################
\##### BENCHMARK - 5 #####
#########################
current implementation with length 1 x 5,095,806 ops/sec ±8.14% (70 runs sampled)
new implementation with length 1 x 4,048,683 ops/sec ±9.13% (67 runs sampled)
current implementation with length 10 x 532,285 ops/sec ±7.47% (73 runs sampled)
new implementation with length 10 x 1,406,007 ops/sec ±1.20% (88 runs sampled)
current implementation with length 100 x 85,627 ops/sec ±1.89% (94 runs sampled)
new implementation with length 100 x 724,187 ops/sec ±0.29% (93 runs sampled)
current implementation with length 1000 x 8,927 ops/sec ±0.53% (96 runs sampled)
new implementation with length 1000 x 6,317,922 ops/sec ±1.90% (92 runs sampled)

#########################
\##### BENCHMARK - 6 #####
#########################
current implementation with length 1 x 7,644,804 ops/sec ±0.60% (91 runs sampled)
new implementation with length 1 x 6,354,759 ops/sec ±0.39% (91 runs sampled)
current implementation with length 10 x 749,997 ops/sec ±1.71% (89 runs sampled)
new implementation with length 10 x 1,439,880 ops/sec ±0.25% (96 runs sampled)
current implementation with length 100 x 86,779 ops/sec ±0.35% (95 runs sampled)
new implementation with length 100 x 713,438 ops/sec ±1.62% (92 runs sampled)
current implementation with length 1000 x 8,924 ops/sec ±0.34% (94 runs sampled)
new implementation with length 1000 x 6,406,604 ops/sec ±0.40% (95 runs sampled)

#########################
\##### BENCHMARK - 7 #####
#########################
current implementation with length 1 x 7,428,641 ops/sec ±1.80% (90 runs sampled)
new implementation with length 1 x 6,490,248 ops/sec ±0.33% (90 runs sampled)
current implementation with length 10 x 750,609 ops/sec ±0.25% (94 runs sampled)
new implementation with length 10 x 1,383,240 ops/sec ±1.93% (90 runs sampled)
current implementation with length 100 x 87,274 ops/sec ±0.13% (96 runs sampled)
new implementation with length 100 x 723,133 ops/sec ±0.25% (93 runs sampled)
current implementation with length 1000 x 8,885 ops/sec ±1.64% (96 runs sampled)
new implementation with length 1000 x 6,420,669 ops/sec ±0.77% (93 runs sampled)

#########################
\##### BENCHMARK - 8 #####
#########################
current implementation with length 1 x 7,452,487 ops/sec ±0.39% (94 runs sampled)
new implementation with length 1 x 6,369,906 ops/sec ±0.66% (93 runs sampled)
current implementation with length 10 x 749,304 ops/sec ±0.31% (94 runs sampled)
new implementation with length 10 x 1,435,491 ops/sec ±0.29% (91 runs sampled)
current implementation with length 100 x 87,099 ops/sec ±0.14% (97 runs sampled)
new implementation with length 100 x 724,894 ops/sec ±0.21% (93 runs sampled)
current implementation with length 1000 x 8,917 ops/sec ±0.15% (97 runs sampled)
new implementation with length 1000 x 6,551,496 ops/sec ±0.34% (94 runs sampled)

#########################
\##### BENCHMARK - 9 #####
#########################
current implementation with length 1 x 7,265,736 ops/sec ±2.42% (93 runs sampled)
new implementation with length 1 x 6,508,867 ops/sec ±0.48% (93 runs sampled)
current implementation with length 10 x 752,791 ops/sec ±1.99% (89 runs sampled)
new implementation with length 10 x 1,450,332 ops/sec ±0.21% (93 runs sampled)
current implementation with length 100 x 86,960 ops/sec ±0.15% (95 runs sampled)
new implementation with length 100 x 727,326 ops/sec ±0.23% (94 runs sampled)
current implementation with length 1000 x 8,869 ops/sec ±1.77% (97 runs sampled)
new implementation with length 1000 x 6,586,329 ops/sec ±0.39% (87 runs sampled)

##########################
\##### BENCHMARK - 10 ######
##########################
current implementation with length 1 x 7,494,050 ops/sec ±2.06% (89 runs sampled)
new implementation with length 1 x 6,543,352 ops/sec ±0.36% (94 runs sampled)
current implementation with length 10 x 760,967 ops/sec ±0.17% (90 runs sampled)
new implementation with length 10 x 1,440,680 ops/sec ±1.46% (93 runs sampled)
current implementation with length 100 x 87,059 ops/sec ±0.14% (97 runs sampled)
new implementation with length 100 x 728,431 ops/sec ±0.23% (93 runs sampled)
current implementation with length 1000 x 8,496 ops/sec ±2.55% (92 runs sampled)
new implementation with length 1000 x 6,184,108 ops/sec ±2.38% (92 runs sampled)

**Comment by xDivisionByZerox** [comment]
I used [benchmarkjs](https://benchmarkjs.com/) for the performance tests.

**Comment by ST-DDT** [comment]
Have you checked, that your new implementation actually works?

````ts
function hexaDeciamal(length = 1) {
  return faker.datatype
    .number({
      max: Math.pow(16, length) - 1,
      min: 0,
    })
    .toString(16);
}

console.log(hexaDeciamal(1000)); // Infinity
console.log(hexaDeciamal(1000).length); // 8
````

**Comment by xDivisionByZerox** [comment]
Good point. I forgot integers have something like a limit. My implementation works till `length === 255`. But since the method is like 10 times faster for sting with `length = 100` you could simple repetitive call the method resulting in something like this:
```typescript
function hexaDeciamal(length = 1) {
  const maxLength = 50;
  let result = '';
  while (length > 0) {
    const useLength = length > maxLength ? maxLength : length;
    result += faker.datatype
      .number({
        max: Math.pow(16, useLength) - 1,
        min: 0,
      })
      .toString(16);

    length -= maxLength;
  }

  return result;
}
```

This also explains why the benchmark is so much faster for my implementation for the `length = 1e3` test.

**Comment by xDivisionByZerox** [comment]
Okay, this works but brings the new issue that the hex values generated are valid but not very pleasing to look at. Since the random numbers generated are sliced off after the 20th precision point.

**Comment by xDivisionByZerox** [comment]
These are the performance results for the implementation of [my last comment](https://github.com/faker-js/faker/issues/575#issuecomment-1052565588).

| name | length | ops per sec | fluctuation | sample size|
| ------ | ------- | ------------- | ------------ | ----------- |
| current | 1 | 4118425 | 12.73 | 64 |
|new|1|2815434|10.84|58|
|current|2|1062004|11.69|44|
|new|2|1344614|8.52|44|
|current|3|993633|6.44|61|
|new|3|872640|11.06|45|
|current|4|849343|7.04|73|
|new|4|787870|6.27|74|
|current|5|752048|4.37|51|
|new|5|660953|6.2|68|
|current|6|628335|4.69|72|
|new|6|595806|4.2|75|
|current|7|551526|5.44|74|
|new|7|502898|4.85|76|
|current|8|495251|2.97|78|
|new|8|442484|3.89|76|
|current|9|425418|4.85|71|
|new|9|400793|2.41|77|
|current|10|413763|3.79|63|
|new|10|354900|4.82|74|
|current|20|234804|6.46|72|
|new|20|210124|4.12|75|
|current|30|132546|7.23|63|
|new|30|97850|9.35|64|
|current|40|87750|9.96|66|
|new|40|106844|2.71|75|
|current|50|87646|4.59|72|
|new|50|78080|7.57|69|
|current|60|68187|8.9|69|
|new|60|65990|4.09|69|
|current|70|60877|8.17|69|
|new|70|56103|7.77|73|
|current|80|56345|3.69|73|
|new|80|56463|4.77|73|
|current|90|50928|5.03|74|
|new|90|49378|3.65|77|
|current|100|45742|5.72|71|
|new|100|41278|4.75|70|
|current|200|24491|4.76|75|
|new|200|21750|5.04|72|
|current|300|16071|7.45|77|
|new|300|14169|5.41|70|
|current|400|13047|2.53|77|
|new|400|11373|3.33|75|
|current|500|9330|12.53|71|
|new|500|8743|4.89|66|
|current|600|7824|4.44|70|
|new|600|7960|2.24|76|
|current|700|7202|4.58|74|
|new|700|6418|4.95|65|
|current|800|6075|4.82|71|
|new|800|5915|4.85|77|
|current|900|5725|5.04|70|
|new|900|5179|3.81|73|
|current|1000|5310|4.15|78|
|new|1000|3688|13.11|56|

**Comment by ST-DDT** [comment]
If you include these benchmarks, please also always include a one sentence summary, to make these easier to grasp.

In this case: "The performance of the new variant is ~25% slower".

**Comment by xDivisionByZerox** [comment]
So now the decision would be if we value performance or readability/maintainability more. Correct?
Any suggestions on this?

**Comment by ST-DDT** [comment]
For me the current implementation is easy to read (maybe move the array of chars to a const/variable and wnsure that they are equally distributed (a-f are currently over-represented, as they appear in both their lowercase and uppercase forms).)
Not sure what others think though.

````ts
 hexaDecimal(length = 1): string {
    let hexString = '0x';

    for (let i = 0; i < length; i++) {
      hexString += this.faker.random.arrayElement(hexChars);
    }

    return hexString;
  }
````

**Comment by nhammond101** [comment]
My preference is maintainability, especially given these type of "base" functions are utilised by others throughout the codebase.

Being able to quickly understand, and adapt, a function is key to developer productivity

**Comment by xDivisionByZerox** [comment]
> For me the current implementation is easy to read (maybe move the array of chars to a const/variable and wnsure that they are equally distributed (a-f are currently over-represented, as they appear in both their lowercase and uppercase forms).) Not sure what others think though.
> 
> ```ts
>  hexaDecimal(length = 1): string {
>     let hexString = '0x';
> 
>     for (let i = 0; i < length; i++) {
>       hexString += this.faker.random.arrayElement(hexChars);
>     }
> 
>     return hexString;
>   }
> ```

I like this approach as well.

I will close this issue and wait for discussions about the hex characters.
