### ISSUE TITLE
TypeError: faker.random.arrayElemet is not a function

### ISSUE THREAD

**Issue by Lisa-V-Sau** [faker-js/faker#579]
### Describe the bug

Summary: Run time error: "TypeError: faker.random.arrayElemet is not a function"

### Reproduction

Example Used: faker.random.arrayElement(['head teacher', 'case worker'])

**Comment by ST-DDT** [comment]
This works perfectly fine for me.

Could you please provide a complete example including, the import and the faker version number?

**Comment by Lisa-V-Sau** [comment]
Hi, 

Thank you for getting back to me on this. 

I am using v6.0.0-alpha.7. 

This is the example which I am using: 
> applicationRole: faker.random.arrayElements(["head teacher", "case worker"])

My import Method: 
> module.exports = function() {
>   const faker = require("faker");

Error:
> TypeError: faker.random.arrayElemet is not a function


Sorry if this is not helpful - I'm not sure what else I could provide. Annoyingly each time I comment out this piece of code my server is also generated.

**Comment by Lisa-V-Sau** [comment]
This seems to be working in some areas but not in others which is somewhat unusual. 

Closing ticket as this is resolved. 

Thank you so much for helping to diagnose the issue.
