### ISSUE TITLE
Remove default value from `helpers.arrayElement()`

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#581]
https://github.com/faker-js/faker/blob/4eef328a90657ce64a5210862ad372ecd97d7e7a/src/random.ts#L106-L108

This causes issues with missing data, that then gets magically replaced with these defaults, which results in unexpected behavior.
This change could be considered breaking, but IMO calling that method without an array to choose from is a bug itself.
Thus why I consider this a bug, that needs fixing more than retaining backwards compatibility.

We observed this method misbehaving in our tests before.

**Alternatives considered**

Create a new method and deprecate the old one.

**Additional Information**

Related to #219

**Comment by xDivisionByZerox** [comment]
If calling the method with an empty array is considered a bug, what would the correct behavior be for empty ararys as input?

**Comment by Shinigami92** [comment]
IMO we should "just" remove the `= ['a', 'b', 'c'] as unknown as ReadonlyArray<T>` part, so that a given argument is required.
But is it really a bug if calling it with an empty array? Cause this would be already a bug now :eyes: 
I would assume that it would throw an error or just return `undefined` :thinking:

**Comment by xDivisionByZerox** [comment]
If it could return `undefined` you must extend the method signature with `undefined` as return value. This can be very exhausting for end-users (because undefined check). So I would say throwing an error would be the way to go.

**Comment by xDivisionByZerox** [comment]
Can you assign me either way?

**Comment by xDivisionByZerox** [comment]
#588 will fix this.

**Comment by xDivisionByZerox** [comment]
Fixed by #2045.
