### ISSUE TITLE
There is no documentation on how to use the unique function

### ISSUE THREAD

**Issue by shunkica** [faker-js/faker#582]
I do not understand how to use the unique function.
I can not find any mention of this on the readme or on the website.
I see it takes some method as the first parameter but I can't figure out what this is or how to get unique values with it.

**Comment by ST-DDT** [comment]
Like this: https://github.com/faker-js/faker/blob/4eef328a90657ce64a5210862ad372ecd97d7e7a/src/unique.ts#L42

The docs will be added by #564

Does that answer your question?

**Comment by shunkica** [comment]
Yes. Thank you.
