### ISSUE TITLE
Change `address.countryCode` method signature

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#587]
## The Problem
Existing comment about this issue:
By @ST-DDT: `Limit the parameter to the two values.`
https://github.com/faker-js/faker/blob/f4768592dd49c7285d4fb7bb7e6d11b08623294d/src/address.ts#L289-L306

## The Solution
Only except `'alpha-2'` and `'alpha-3'` as valid string inputs
```typescript
countryCode(alphaCode: 'alpha-2' | 'alpha-3' = 'alpha-2'): string
```

**Comment by ST-DDT** [comment]
Not sure, whether this should be in v6.1 or v6.2,

**Comment by xDivisionByZerox** [comment]
We could first put this in v6.2. But can put in v6.1 if we magically get everything else done?^^

**Comment by xDivisionByZerox** [comment]
I provided a PR that fixes this. Please assign me to this issue.
