### ISSUE TITLE
Publish 6.0.0 as `@faker-js/faker`

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#6]
If you need earlier versions of faker, see #5

**Comment by Shinigami92** [comment]
Did we already claim the npm org?
If not, please do that immediately

https://www.npmjs.com/package/@faker-js/faker

Maybe we could also release a 5.5.3 :thinking: 
That way the community can already just replace the dep to our package without any issues (except for no TS support :thinking:)

**Comment by damienwebdev** [comment]
I've already acquired ownership -- see: #19
