### ISSUE TITLE
Could not find a declaration file for module '@faker-js/faker'.

### ISSUE THREAD

**Issue by josevelaz** [faker-js/faker#606]
### Describe the bug

When attempting to use `@fakerjs/faker` I get a type error that says: ` Could not find a declaration file for module '@faker-js/faker'.`

Error occurs when importing the package.
![Screen Shot 2022-03-07 at 2 38 09 PM](https://user-images.githubusercontent.com/8031323/157105607-9aedcb00-84d8-4fdc-9bba-e08d00c774fe.png)

### Reproduction

Run `npm install @faker-js/faker`, then try importing into a typescript project

### Additional Info

- Typescript v3.9.7
- Node v12
- Webstorm 2021.3
- All tsconfig settings are properly set.

**Comment by Shinigami92** [comment]
You TypeScript version is not supported, please use the `v5.5.3`
We only support TS v4+

**Comment by prisis** [comment]
And Node v14 if you want older node version support pls use @faker-js/faker v5.5.3

**Comment by rancharaz** [comment]
note that your node version should be v14+
at the time of this comment, my version is v16.15.1

//install faker ->
npm install --save-dev faker@5.5.3


// on your selected component ->
import faker from "faker"; 

//check on your package.json ->

"devDependencies": {
    "faker": "^5.5.3"
  }

**Comment by RanaRabees** [comment]
only run this command

**npm install @faker-js/faker --save-dev**
