### ISSUE TITLE
Petition to undeprecate random primitives

### ISSUE THREAD

**Issue by AustinGil** [faker-js/faker#607]
In an older version, many of the methods on `faker.random` that return primitive values were deprecated and moved to `faker.datatype`. I never understood the reason, and I'd argue that restoring them is better developer experience.

* When trying to generate a random value (ie Number), it's more intuitive to go to `faker.random`
* Using `random` is better for intellisense because `faker.datatype` clashes with `faker.database`. It's much nicer to just type "faker.r" then tab.
* It feels to me like `faker.random` and `faker.datatype` serve the same purpose of grabbing fake primitives.

I'm bringing some of my own bias and assumptions here, so I reserve the right to be totally wrong, but I thought I would mention it in the spirit of trying to make this library better.

**Comment by ST-DDT** [comment]
FFR: This was added in https://github.com/faker-js/faker/commit/7ad22c2e2aae2f5e6215bcdb91cf3fd28e727d92

The actual issue is lost to time.

Currently the helper, random and datatype modules are kind of ambiguous.
So I consider removing datatype to be a viable solution, not sure what the other maintainers think though.

**Comment by ST-DDT** [comment]
We created a discussion on how to improve on this: https://github.com/faker-js/faker/discussions/805

**Comment by Shinigami92** [comment]
When we bring stuff from datatype back to random, I think we should use new names like:
- `datatype.number` => `random.int` (or `random.nextInt`? This would align with some other languages like Java :thinking:)
- `datatype.float` => `random.number`

**Comment by ST-DDT** [comment]
I think moving it to individual modules (strings/numbers) might provide a better developer experience, because first you select what you want and then you have all the variations available for use.

**Comment by Shinigami92** [comment]
> I think moving it to individual modules (strings/numbers) might provide a better developer experience, because first you select what you want and then you have all the variations available for use.

Where would you put `boolean`, `hex`, `datetime` and `uuid`?
I think functions like `array` and `json` can be removed because I don't know which use-case they fulfill :shrug:

**Comment by ST-DDT** [comment]
- Datetime delete
- uuid -> string
- hex -> string
- boolean can remain in random or helpers
- array and json/object/record should be modified and may be moved to helpers: `array( numOrRange, elemSource())`, ...

**Comment by pkuczynski** [comment]
I can see the discussion going on here and in #805 - this is a bit confusing. Maybe we should close this issue and focus on the discussion only, which should then be spit into smaller issues?
