### ISSUE TITLE
Improve methods with a length: number argument to support ranges

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#617]
### Clear and concise description of the problem

Some methods like hexadecimal take only a fixed range as parameter. If you want to allow a dynamic range, you have to combine it with another method first.
`faker.datatype.hexaDecimal(faker.datatype.number(...))`
This reduces the readability of the code.

### Suggested solution

Improve their method signature to allow for ranges:
`hexaDecimal(length: number | {min,max})`

### Additional context

What do you think?

**Comment by Shinigami92** [comment]
> What do you think?

- For the short run, I think yes, this could be helpful.
- For the long run, I would love to introduce always "Options" as arguments, cause this increases readability while using faker.

It's a common pattern in JS ecosystem to accept options - especially in the Vue ecosystem.
But we can do this only from v7+

So it would be like

```ts
faker.module.func({ length: 42 })
faker.module.func({ min: 13, max: 17 })

// Or we would merge it directly together
faker.module.func({ maxLength: 42 }) // always has length 42
faker.module.func({ minLength: 13, maxLength: 42 }) // always has length between 13 and 42
// but that would be confusing :(
```

I may need to think about that further, but until then, you are right and we can implement your proposal in v6.2
