### ISSUE TITLE
`address.cityPrefix` returning undefined on `pt_BR`

### ISSUE THREAD

**Issue by ponei** [faker-js/faker#623]
### Describe the bug

Title pretty much sums it up. This is dependent on locale and doesn't happen on english - did not test on other locales other than `pt_BR` and `en`.

### Reproduction

Calling `address.cityPrefix` or any other function that uses it (`address.city` sometimes does) returns `undefined`

**Comment by Shinigami92** [comment]
https://github.com/faker-js/faker/blob/main/src/locales/pt_BR/address/city_prefix.ts

There is a city_prefix, but it is empty 🤔

Was this also the case with v5.5.3?

I will look into this after I fully woke up.

**Comment by ST-DDT** [comment]
FFR: https://github.com/faker-js/faker/blob/v5.5.3/lib/locales/pt_BR/address/city_prefix.js

**Comment by ST-DDT** [comment]
@ponei Are you fluent/familiar with pt_br?
If yes, could you create a PR that adds some common city prefixes?

**Comment by Shinigami92** [comment]
The only question I have right now is: was it different in v5.5.3, then it could be a `|| => ??` change somewhere or something like that. So maybe we accidentally changed behavior somewhere.

**Comment by ST-DDT** [comment]
> The only question I have right now is: was it different in v5.5.3, then it could be a `|| => ??` change somewhere or something like that. So maybe we accidentally changed behavior somewhere.

This doesn't have any impact. An empty array wouldn't get replaced either way.

**Comment by Shinigami92** [comment]
We have a somewhat related PR for the general issue: https://github.com/faker-js/faker/pull/609

But adding some city prefixes for `pt_BR` would definitely be nice anyway

**Comment by ST-DDT** [comment]
Maybe add/fix `citySuffix` as well?

**Comment by ponei** [comment]
> @ponei Are you fluent/familiar with pt_br?
> If yes, could you create a PR that adds some common city prefixes?

Yes, I'm fluent with portuguese. I could come up with some after work, but prefixes for cities aren't very common here, suffixes are.
In english you would have something like `West {cityName}` but that doesn't translate really well. 
Regions/other adjectives are suffixes because that's how they work in portuguese, so you would have something like `{cityName} do Sul` (south region).

Maybe the locale should say what it prefers? (suffix or prefix). Then if you want to override you could pass arguments explicitly saying otherwise.

**Comment by ST-DDT** [comment]
Yeah the generator patterns should be in the locale definitions as well (v6.2 or later).

Maybe add `''` as prefix for now, that way you don't get undefined in those texts anymore.
The extra space in the city names is hopefully negligible.

**Comment by Shinigami92** [comment]
For now please call `faker.fake('{{address.cityName}}')` as a workaround.

I looked into the implementation of 

https://github.com/faker-js/faker/blob/2b934c51e4e090ea169b7ef1ced9881b93f7eb79/src/address.ts#L95-L112

and damn, this is a mess :rofl: 
We need to fully rework this implementation, but this will be a breaking change. So I will move this to v7, because there is a workaround for now.

**Comment by ST-DDT** [comment]
Now there is `faker.address.cityName()` and `faker.address.city()` uses a localized pattern (not sure whether its correct though).
If its not correct, please open a PR/issue and provide us with the correct one.

https://github.com/faker-js/faker/blob/c5ac124ecafafc89bdd31a5870f325d671c7e9cf/src/locales/pt_BR/address/city.ts#L2-L5

The cityPrefix and suffix methods itself will be deprecated for removal in #1041 .
