### ISSUE TITLE
Add Panda with Ukranian Flag 🇺🇦 

### ISSUE THREAD

**Issue by JessicaSachs** [faker-js/faker#628]
### Clear and concise description of the problem

👋🏻 I'd like to promote awareness about the war in Ukraine by adding a Ukranian flag to our beloved Panda. I've already added the little guy to Twitter.

### Suggested solution

**Straightened** (This looks best in avatars like Twitter + Discord)
<img src="https://user-images.githubusercontent.com/2801156/158720875-182fd7ff-7085-4cc3-8630-b79d6c3c16ef.png" width="200" />

**Tilted** (This looks best on web pages like GitHub README and fakerjs.dev)
<img width="200" src="https://user-images.githubusercontent.com/2801156/158721044-03ee2b2c-e1ef-49b8-b75d-ad9740731440.png" />

**Locations to add**

- [ ] Add to Discord
- [ ] Add to README
- [ ] Add to Website
- [ ] Add to favicon
- [x] Add to Twitter avatar
- [ ] Add to Twitter header image

**Comment by Shinigami92** [comment]
I think it's okay to do this in social media platforms like twitter, but IMO GitHub is a political-free place. So I wont like to have this in the Repository.

As you also can see, there is also already one downvote from @xingming2020. I don't know the reason behind this downvote, but this shows me already that there are people in the community - especially around russia and china - that could feel attacked by this.
So I also give my downvote to add this in the repository. Sry 🤷

**Comment by Shinigami92** [comment]
So I visit this issue back and see now that there are 8 downvotes on the initial message and 11 upvotes on my message.
This shows me that already this part of the community seems to think like me.

So I hope it's okay that I just close this now.
