### ISSUE TITLE
Improve specification of `Address.countryCode()`

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#648]
https://github.com/faker-js/faker/blob/56424709b7ccd7aa7fe6130c78a770a0a901d7b5/src/address.ts#L277-L288

https://github.com/faker-js/faker/blob/56424709b7ccd7aa7fe6130c78a770a0a901d7b5/src/definitions/address.ts#L74-L81

Currently it is not clear whether the method should return a country code related to that locale/language or any of the world.
We should decide on either of these and thus adjust the documentation.

Affects:

- `src/locales/de_CH/address/country_code.ts` (Related to the locale)
- `src/locales/fa/address/country_code.ts` (Duplicates en)
- `src/locales/fr_CH/address/country_code.ts` (Related to the locale)
- `src/locales/he/address/country_code.ts` (Empty/Invalid)
- Respective alpha3 files

If we use "any of the world" these files have to be deleted. ( `*` -> `anyof ['AZ', ..., 'ZY']`)
If we use "related to that locale" we have to update them. ( `de` -> `anyof ['CH', 'DE']`)

**Blocks #609**

**Comment by ST-DDT** [comment]
If we limit it to "related to that locale" ( de -> anyof ['CH', 'DE']), then we have to apply the same logic to some of the other methods too, such as iban generation.

**Comment by Shinigami92** [comment]
Maybe this issue is so huge, that we should put it on agenda for team meeting :thinking:

**Comment by ST-DDT** [comment]
In our last team meeting we decided to let the locale decide which countries to return.
I will create a PR that removes the invalid files.
