### ISSUE TITLE
Extend IBAN tests

### ISSUE THREAD

**Issue by MrGussio** [faker-js/faker#660]
In https://github.com/faker-js/faker/blob/main/test/finance_iban.spec.ts, only a handful of IBAN tests are implemented.
Since the discovery of #646, it seems like a good idea to expand this list to cover all IBANs to check if the generation is actually implemented as expected.

- [ ] AL
- [ ] AD
- [ ] AT
- [x] AZ
- [ ] BH
- [ ] BE
- [ ] BA
- [ ] BR
- [ ] BG
- [ ] CR
- [ ] HR
- [ ] CY
- [ ] CZ
- [ ] DK
- [ ] DO
- [ ] TL
- [ ] EE
- [ ] FO
- [ ] FI
- [ ] FR
- [x] GE
- [ ] DE
- [ ] GI
- [ ] GR
- [ ] GL
- [ ] GT
- [ ] HU
- [ ] IS
- [ ] IE
- [ ] IL
- [ ] IT
- [ ] JO
- [ ] KZ
- [ ] XK
- [ ] KW
- [ ] LV
- [ ] LB
- [ ] LI
- [ ] LT
- [ ] LU
- [ ] MK
- [ ] MT
- [ ] MR
- [ ] MU
- [ ] MC
- [ ] MD
- [ ] ME
- [ ] NL
- [ ] NO
- [x] PK
- [ ] PS
- [ ] PL
- [ ] PT
- [ ] QA
- [ ] RO
- [ ] SM
- [ ] SA
- [ ] RS
- [ ] SK
- [ ] SI
- [ ] ES
- [ ] SE
- [ ] CH
- [ ] TN
- [x] TR
- [ ] AE
- [ ] GB
- [ ] VG

**Comment by ST-DDT** [comment]
Not sure about this one. Sure tests are nice, but these tests actually just test that the definition is correct.
IMO we have to compare the faker definitions with the official definitions first.
I expect every change to these definitions to be covered by tests, but not every definition.

**Comment by MrGussio** [comment]
If we construct the tests according to the right definition, we will automatically also find other mistakes if there are any.

The way I discovered the Costa Rica formatting mistake, is that my tests sometimes randomly failed on the IBAN when validating the generated response with [validator.js](https://github.com/validatorjs/validator.js/). Since the same library seems to be used with the tests here, we can cross-validate if the definitions are correct using these tests.

**Comment by Shinigami92** [comment]
I would like to have generic test for every IBAN `countryCode` but using a `it.each` for that.
Then if needed a selection of special IBANs that could somehow also be checked via `it.each` in a more complex form 🤔 

Otherwise: I'm with @ST-DDT https://github.com/faker-js/faker/issues/660#issuecomment-1075740583

**Comment by ST-DDT** [comment]
Lets use validator.js for the test:
https://github.com/validatorjs/validator.js/blob/master/src/lib/isIBAN.js#L8

**Comment by Shinigami92** [comment]
> Lets use validator.js for the generic test:
[https://github.com/validatorjs/validator.js/blob/master/src/lib/isIBAN.js#L8](https://github.com/validatorjs/validator.js/blob/master/src/lib/isIBAN.js?rgh-link-date=2022-03-23T08%3A37%3A12Z#L8)

<img src="https://c.tenor.com/6tlIWiAlT_gAAAAM/cat-impressed-cat-wow.gif"/>
