### ISSUE TITLE
`address.secondaryAddress` doesn't use `faker.definitions.address.secondary_address`

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#676]
### Clear and concise description of the problem

The current implementation of `faker.address.secondaryAddress` uses a hardcoded string array to choose from instead of the definition one. This means locales are ignored for this method.

https://github.com/faker-js/faker/blob/e62fd15cc7b83cc314a22ad9b13cd68f222d4076/src/address.ts#L311-L316

### Suggested solution

Use `faker.definitions.address.secondary_address` instead of the hardcoded string array

```typescript
secondaryAddress(): string {
  return this.Helpers.replaceSymbolWithNumber(
    this.faker.random.arrayElement(this.faker.definitions.address.secondary_address)
  );
}
```

**Comment by Shinigami92** [comment]
Is this related to #88?

**Comment by xDivisionByZerox** [comment]
I would say yes. But it breaks down the issue described in #88 in a smaller task that can be picked up.

**Comment by xDivisionByZerox** [comment]
I provided #680 to fix this.
