### ISSUE TITLE
`address.city` string parameter ignored

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#682]
### Describe the bug

When using the `address.city` function you are allowed to pass a format as a string (for custom format) or as a number for index-based selection. When providing a custom string format it will be ignored.

### Reproduction

faker.address.city('{{address.cityPrefix}} {{datatype.string}}')

### Additional Info

Is marked as todo in #541

**Comment by ST-DDT** [comment]
The parameter has been deprecated for removal in #948.
