### ISSUE TITLE
remove dead code in `commerce` module

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#690]
### Clear and concise description of the problem

The`commerce` module has a lot of dead code in it that is marked with a TODO to remove it.

https://github.com/faker-js/faker/blob/877ac76b2811c948c560fee4fa76908b142557d1/src/commerce.ts#L92-L118 

### Suggested solution

Remove the dead code.

**Comment by Shinigami92** [comment]
IMO this can removed right now, cause it will not touch the runtime code in any way

**Comment by xDivisionByZerox** [comment]
But it's not a bugfix by definition. But if majority of maintainers is fine with it being removed right away I will not say anything.

**Comment by ST-DDT** [comment]
We also do a lot of cleanup so it's ok to be in v6.1

**Comment by rimakan** [comment]
hey! is the issue still actual? could I take it please?

**Comment by xDivisionByZerox** [comment]
Sure go ahead. I'll assign you to it.

**Comment by rimakan** [comment]
@xDivisionByZerox , added a PR https://github.com/faker-js/faker/pull/745, could you please check it out?
