### ISSUE TITLE
rename `phone.phoneNumber` to `phone.number`

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#693]
### Clear and concise description of the problem

Function name is repeating the module name.

### Suggested solution

Create a new function `number` in the `phone` module that is a copy of the current `phoneNumber` function. Call this new function in the current function and add a deprecation warning.

### Additional context

Marked as todo in #541

**Comment by import-brain** [comment]
How would we go about this? Would we simply rename all instances of ```phone.phoneNumber()``` to ```phone.number()```? Or should we keep ```phone.phoneNumber()``` and add a deprecation warning saying to use the new ```phone.number()``` function which will be a copy paste of ```phone.phoneNumber()```.

**Comment by Shinigami92** [comment]
wait on #689, then yes, add deprecation warning + alias

**Comment by xDivisionByZerox** [comment]
And remove completely in v7?

**Comment by xDivisionByZerox** [comment]
This was resolved in #1063.
