### ISSUE TITLE
deprecate `phone.phoneFormat`

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#694]
### Clear and concise description of the problem

Phone formats should not be exposed directly.

### Suggested solution

Deprecate `phone.phoneFormat` in favor of `phone.phoneNumber`. 

### Additional context

Marked as TODO in #541

**Comment by ST-DDT** [comment]
IMO we should not expose the format directly.

**Comment by xDivisionByZerox** [comment]
I agree with you on that (if you really need to access them you could simply `faker.definitions.phone_number.formats`). Should I rephrase this issue to remove the util functions that expose phone formats and mark for discussion?
