### ISSUE TITLE
Why is npm 7 required with node 14?

### ISSUE THREAD

**Issue by sergavshin** [faker-js/faker#723]
Hello. Is any reason to use npm 7? Node 14 ships with npm 6 and not everyone can change that in a company's CI.

**Comment by sergavshin** [comment]
Yeah. But the installation fails if engine-strict in npmrc on the user side.

**Comment by sergavshin** [comment]
If there are no problems for switching to npm 6, can I make PR?

**Comment by Shinigami92** [comment]
> Yeah. But the installation fails if engine-strict in npmrc on the user side.

I'm currently not sure why we need to care about user setted `.npmrc` files? IMO that's an problem created by your own?!
Just don't set it globally to `engine-strict` and only use it for project where you really need it.
And even if, why is it useful in any way to set this to strict?

**Comment by sergavshin** [comment]
> why we need to care about user setted .npmrc files? IMO that's an problem created by your own?!

This is a valid case for npm, and for good reason. Why shouldn't the package respect this?

> Just don't set it globally to engine-strict and only use it for project where you really need it.

But how do I use the package in a project where I really need `engine-strict`?

> And even if, why is it useful in any way to set this to strict?

For lock node/npm versions in a project team. And node/npm version mismatch forces additional installation of npm 7 on top of node 14 docker image

**Comment by alexkvak** [comment]
@Shinigami92 current CI is inconsistent. It runs on `node@14` which ships with `npm@6`. So values in `engines` are also wrong.

**Comment by ST-DDT** [comment]
Could you create a PR for it?

**Comment by sergavshin** [comment]
@ST-DDT done #744

**Comment by ST-DDT** [comment]
Thanks! We will review it this weekend.
