### ISSUE TITLE
`address.nearbyGPSCoordinate` non deterministic results

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#736]
### Describe the bug

`address.nearbyGPSCoordinate` generates non-deterministic values when reference coordinates are given.

### Reproduction

```
for (let i = 0; i < 5; i++) {
  faker.seed(522003803);

  const coordinate = faker.address.nearbyGPSCoordinate([0, 0]);

  console.log(coordinate);
}
```

You will see 5 different string tuples being printed to the console.

Stackblitz URL:
https://stackblitz.com/edit/typescript-hm6h4k

### Additional Info

`address.nearbyGPSCoordinate` uses `Math.random` when generating the bearing for random coordinates.
https://github.com/faker-js/faker/blob/7afd8c55baac6f7d895caabeb623cc6a0514d6cb/src/address.ts#L539-L544

Also, this can cause the tests randomly to fail. 
That's how I noticed this.

**Comment by ST-DDT** [comment]
Since this is a bug, I think this should be in 6.1.
