### ISSUE TITLE
Reorganize src folder structure

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#751]
Move all modules into a `src/modules` folder

As this will mostly destroy work from active open PRs, we should do this when we have a low amount of open PRs
As I also don't know which side effects this could potentially cause, I would like to earliest target this for v7, also so we can currently focus on more important stuff right now

**Comment by Shinigami92** [comment]
I highly recommend to follow a file structure like 

```
- src/
  - modules/
    - address/
      - index.ts
      - module.ts
      - definition.ts
      - <...>.ts
    - /animal
      - ...
    - index.ts
  - index.ts
```

That way we do not need to open multiple path and search for loosely-coupled files and as a VSCode user I could benefit from file-nesting

**Comment by ST-DDT** [comment]
What about the actual locales data?
The current structure is based on types.
If you structure them based on usage you have to do it consistently.

**Comment by Shinigami92** [comment]
> What about the actual locales data? The current structure is based on types (the definition files describe the folder structure for locales). If you structure them based on usage you have to do it consistently.

Yeah, I would like to move the content inside locales completely out of the `src` code and define them via static files that are accessible like assets and can be accessed from `dist/esm` and `dist/cjs` without duplicating them. So maybe bundled minified in `dist/assets` or `dist/locales`.
But I see this change after we are done with other stuff.
Also I think we should not move them before that into my suggested `src/modules/*` because then I assume stuff inside https://github.com/faker-js/faker/blob/main/scripts/generateLocales.ts would break or at least will be harder to do.
