### ISSUE TITLE
issue-labeling.yml

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#758]
### Describe the bug

While working on PR #757, I noticed that the file ```issue-labeling.yml``` has some old stuff in it, see below.

https://github.com/faker-js/faker/blob/main/.github/workflows/issue-labeling.yml#L1-L32

Wouldn't none of this workflow work anymore, because we changed the labeling structure and naming scheme of the labels?

### Reproduction

https://github.com/faker-js/faker/blob/main/.github/workflows/issue-labeling.yml#L1-L32

**Comment by Shinigami92** [comment]
Seems we can just remove this file.
We are labeling it in a good speed anyway
