### ISSUE TITLE
How to handle the incompatible types in address.zipCodeByState()

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#759]
https://github.com/faker-js/faker/blob/f520968e4621c2830c2314f9a59cd1b071f58169/src/address.ts#L126-L133

https://github.com/faker-js/faker/blob/f520968e4621c2830c2314f9a59cd1b071f58169/src/definitions/address.ts#L7-L13

The following languages specify a `string[]` (4):

- ar
- en
- he
- ur

The following locales specify `Parameters<Datatype['number']>` (1):

- en_US

AFAICT there is no way to access the `string[]` values using a string key and if there was a way the result would be incompatible with the `datatype.number()` function.

I checked the `string[]` `postcode_by_state` locale files and it is exactly like their `postcode` locale file, so even if we remove them, the fallback to the normal zipCode method would work and return the same values.

We have two choices:

- Add support for `string[]` values
- Remove the `string[]` from the type and the corresponding files

Created from #541

**Comment by ST-DDT** [comment]
I'm in favor or removing `string[]` and the offending files.

**Comment by xDivisionByZerox** [comment]
After some investigation, I come to the same conclusion. A `string[]` doesn't make sense for the use case IMO.

**Comment by import-brain** [comment]
I'm also in favor of removing ```string[]```.
