### ISSUE TITLE
Small issue with mersenne jsdoc

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#775]
### Describe the bug

https://fakerjs.dev/api/mersenne.html#rand

In the examples, it says ```faker.mersenne.rand(500, 1000)```. However, the ```max``` parameter is listed first. I saw the code on how we got around listing ```max``` first (L33 to L37 of mersenne.ts), but is there any possible way we could improve the mersenne jsdoc examples? Could be a bit confusing, considering ```max``` is shown first in the function signature.

### Reproduction

faker.mersenne.rand(500, 1000)

**Comment by Shinigami92** [comment]
Oh yeah, you mean it should be `faker.mersenne.rand(1000, 500)`

**Comment by ST-DDT** [comment]
Good catch.

https://github.com/faker-js/faker/blob/b34ef465fb23829e4f07f3ffbba4203737f74b08/src/mersenne.ts#L30

**Comment by gregoriomario** [comment]
Hi! Can I take this issue? thx

**Comment by import-brain** [comment]
> Hi! Can I take this issue? thx

Sure! Assigning to you
