### ISSUE TITLE
Cannot directly import _Date

### ISSUE THREAD

**Issue by JontyMC** [faker-js/faker#778]
### Describe the bug

After importing the _Date class like this:

`import { _Date } from '@faker-js/faker/date';`

When running, I get the following error:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './date' is not defined by "exports" in ******\node_modules\@faker-js\faker\package.json`

### Reproduction

`import { _Date } from '@faker-js/faker/date';`

### Additional Info

I want to import _Date because I want to use it in a delegate for configuring a test data builder:

`date?: (date: _Date) => Date;`

**Comment by Shinigami92** [comment]
Yeah, we could export it, but we should then name it like `FakerDate` or something like this
Currently it is an internal not exported type

**Comment by JontyMC** [comment]
Thanks for workaround.

The type is in the public API, so it is really external. What would be the downside in exporting it?

**Comment by ST-DDT** [comment]
> I want to import _Date because I want to use it in a delegate for configuring a test data builder:
> 
> `date?: (date: _Date) => Date;`

You should probably use the `Faker` instance there instead. Since you cannot create the `_Date` type independently.
Is there a specific reason, why you want to use the `_Date` instance instead of the `Faker` instance?

**Comment by JontyMC** [comment]
Using the _Date instance creates a nicer API, as you would ony ever want to use that module in this case.

**Comment by ST-DDT** [comment]
I like both the `FakerDate` and `DateModule` names. Any preference?

But I'm unsure whether these names are really easier to use then `Faker['date']` and how often they will be used.
I assume most of the time Faker will be used like this `x: (faker: Faker) => X`

**Comment by JontyMC** [comment]
I don't see a downside to exporting the types (probably prefer FakerDate), it might stop someone raising the same issue. Workarounds are fine now I know them.

**Comment by JontyMC** [comment]
The faker.date API is externally facing and has a contract in terms of the functions and properties it provides. I assume these won't change without deprecation and version bump, so in that sense the "type" is officially supported. Given this contract has a type already, it may as well be exported (perhaps it would be better as a typescript type or interface).

Also, the typescript _Date class is exported in the dist folder and visual studio auto imports @faker-js/faker/date when I used it.

**Comment by ST-DDT** [comment]
Note: The import will probably stop working in v6.2 because we intend to move the modules from `src/<module>.ts` to `src/modules/<module>.ts`
