### ISSUE TITLE
Allow coordinate nearbyGPSCoordinate parameter to be `[string, string]`

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#780]
https://github.com/faker-js/faker/blob/ccb58a177f2c311130b85b7a7c2efe0e0402d886/src/address.ts#L498-L503

The `nearbyGPSCoordinate()` method should be able to take the values returned from `latitude()`, `longitude()` and `nearbyGPSCoordinate()`.

Ref: #541

**Comment by Shinigami92** [comment]
I would like to discuss if it is worth it that we need to return [string, string] just to have same fixed precision for both values.
Instead the user could call that theyself if needed and then they can use the exact numbers as is.
In our tests we use `+coordinate[0]` to convert it back to a number...
