### ISSUE TITLE
Api docs parameter default extraction removes parts of the description

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#794]
### Describe the bug

Found while reviewing https://github.com/faker-js/faker/pull/792#discussion_r844871900 and writing https://github.com/faker-js/faker/pull/793.

https://github.com/faker-js/faker/blob/81171c9f9f2e548f9a86eaae3683ead7e28dbd72/scripts/apidoc/signature.ts#L301-L305

The code removes the description after the parameter default section.

### Reproduction

https://github.com/faker-js/faker/blob/81171c9f9f2e548f9a86eaae3683ead7e28dbd72/src/time.ts#L13-L18

![grafik](https://user-images.githubusercontent.com/1579362/162177717-92b06330-2ae8-46b8-a055-a6c18bd64b26.png)

### Additional Info

Possible solutions:

1) Require the default to be the last segment
2) Fix the code to not erase the suffix
3) Intentionally ignore the parts after the defaults (not recommended)

**Comment by Shinigami92** [comment]
I would love to go with `1. Require the default to be the last segment` so we have a specific convention.

**Comment by Shinigami92** [comment]
> So the docs should fail if it's specified otherwise?

I assume yes, not the docs should fail, but the generation of the docs should.
