### ISSUE TITLE
Improve api docs representation of `LiteralUnion`s

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#795]
### Clear and concise description of the problem

Currently `LiteralUnions` are displayed as their full generic type. This is unessesarily bulky.

![grafik](https://user-images.githubusercontent.com/1579362/162177717-92b06330-2ae8-46b8-a055-a6c18bd64b26.png)

### Suggested solution

Since we usually only expect the specified values from that type, we might as well just display them.

`LiteralUnion<"abbr" | "date" | "unix" | "wide", string>` -> `"abbr" | "date" | "unix" | "wide"`

### Alternative

Change the representation to either:

- `"abbr" | "date" | "unix" | "wide" | string`
- `LiteralUnion<"abbr" | "date" | "unix" | "wide">`

### Additional context

Found while writing issue https://github.com/faker-js/faker/issues/794.

**Comment by Shinigami92** [comment]
I would suggest going with `"abbr" | "date" | "unix" | "wide" | string`
