### ISSUE TITLE
Docs: add v6.fakerjs.dev

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#812]
### Clear and concise description of the problem

We need a v6.fakerjs.dev that currently redirects to fakerjs.dev
When switching major we add v7.fakerjs.dev that redirects ti fakerjs.dev and v6.fakerjs.dev will be one-time-deployed and freezed

### Suggested solution

do stuff

**Comment by Shinigami92** [comment]
optional somehow try to gen a doc for v5 also

**Comment by ST-DDT** [comment]
> optional somehow try to gen a doc for v5 also

We could try to run the current api docs generator with the the v6 alpha 1 docs, but not sure how useful that is since there are no jsdocs for the methods. We could use v6.0, but that might already have tiny differences specially related to the imports.

**Comment by import-brain** [comment]
Could we have a dropdown switcher, kind of like how Tailwind does their documentation? It looks great

https://tailwindcss.com/docs/installation

**Comment by Shinigami92** [comment]
For reference: https://github.com/vitejs/vite/pull/8065/files

**Comment by Shinigami92** [comment]
https://v6.fakerjs.dev
