### ISSUE TITLE
Random IMEI number

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#826]
### Clear and concise description of the problem

I want to be able to generate a random IMEI number.

### Suggested solution

Would this be under ```phone``` or ```internet```? I think it could go under either of them, honestly.

### Additional context

IMEI numbers follow the same Luhn algorithm that is used for credit cards, the ```luhnCheck.ts``` file can be used to check for IMEI validity. Also, I'm pretty sure ```helpers.replaceCreditCardSymbols()``` could be adapted for this usage.

**Comment by ST-DDT** [comment]
I would put it under phone.
