### ISSUE TITLE
investigate stalling semantic pull request

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#843]
### Describe the bug

<img width="926" alt="Screen Shot 2022-04-16 at 12 06 26 PM" src="https://user-images.githubusercontent.com/68196762/163682575-8f8c3a9f-8b5c-4fc8-acb8-fcdbb7e7ac40.png">

### Reproduction

Look at PR #839 and #840

**Comment by Shinigami92** [comment]
https://github.com/zeke/semantic-pull-requests/issues/183

**Comment by import-brain** [comment]
> [zeke/semantic-pull-requests#183](https://github.com/zeke/semantic-pull-requests/issues/183)

Ahhh, didn't see that. Should I close this?

**Comment by ST-DDT** [comment]
No, we can link this as long as the issue persists.
Maybe we have to remove it, if it isnt fixable short term.

**Comment by Shinigami92** [comment]
Thanks to @bluwy (also from the Vite Team :slightly_smiling_face:) we could investigate https://github.com/amannn/action-semantic-pull-request
