### ISSUE TITLE
Use get and set for faker.seed

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#855]
Deprecate seedValue in favor of get and set seed

https://github.com/faker-js/faker/pull/853#discussion_r854367579

**Comment by ST-DDT** [comment]
IMO this is ambiguous, because you don't know whether this is the `initialSeed` or the `currentSeed`.
At least VSCode doesn't work with separate jsdocs for getters and setters.
Adding clarifying jsdocs for both in one might cause confusion.

**Comment by Shinigami92** [comment]
> At least VSCode doesn't work with separate jsdocs for getters and setters.

As far as I know this was fixed via https://github.com/microsoft/TypeScript/pull/37451
Maybe you need to update your VSCode? If the bug still appears, please open a new issue for TypeScript or VSCode.

**Comment by ST-DDT** [comment]
<details>
<summary><strong>VSCode (v1.66.2) (Click to expand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/164467807-ce841a7a-b162-4398-921c-e19e16db4385.png)

</details>

<details>
<summary><strong>Stackblitz (TS-Sample) (Click to expand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/164469423-7b571dd9-137f-4541-a378-995b0268923d.png)


</details>

<details>
<summary><strong>Code (Click to expand)</strong></summary>

````ts
export class Test {

  /**
   * Do some stuff here.
   *
   * @see any other method.
   *
   * @deprecated This is strange stuff.
   */
   get x(): string {
    return 'x';
  }

  /**
   * Do some stuff here.
   *
   * @param x The new value.
   * @see any other method.
   *
   * @deprecated This is strange stuff.
   */
  set x(x: string) {
    console.log(x);
  }

  test(): void {
    this.x = 'x';
  }

}
````

</details>

Who should I report this bug to? MS/TS?

**Comment by Shinigami92** [comment]
> Who should I report this bug to? [microsoft/TypeScript](https://github.com/microsoft/TypeScript)?

I assume yes, feel free to link:
- `https://github.com/microsoft/TypeScript/issues/37716`
- `https://github.com/microsoft/TypeScript/issues/20966`
- `https://github.com/microsoft/TypeScript/pull/37451`

**Comment by Shinigami92** [comment]
Obsolete due to we now have a `seed()` function that returns the seed
