### ISSUE TITLE
feat: faker optional with probability

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#870]
### Clear and concise description of the problem

I need to create mock data and would like to generate some optional fields for entities.
I would also like to pass a probability so I can control a bit how often a value will be set.
The function needs to be deterministic.

### Suggested solution

My current own written function looks like this: 

```ts
function optional<T>(
  callback: () => T,
  { probability = 0.5 }: { probability: number } = { probability: 0.5 },
): T | undefined {
  if (faker.datatype.float({ min: 0, max: 1 }) < probability) {
    return callback();
  }
  return undefined;
}
```

**Comment by ST-DDT** [comment]
I think that it is a good suggestion.
However I would like to propose three minor changes
1) allow for fallback values, e.g. to allow empty string as fallback for an optional string section
2) add support for hardcoded values in addition to the functions
3) change the param order to `(probability, hitValue, missValue)` (not sure about this one)

**Comment by Shinigami92** [comment]
> I think that it is a good suggestion. However I would like to propose three minor changes
> 
> 1. allow for fallback values, e.g. to allow empty string as fallback for an optional string section
> 2. add support for hardcoded values in addition to the functions
> 3. change the param order to `(probability, hitValue, missValue)` (not sure about this one)
> 
> I think this method should be located in helpers.

1. A fallback value can be absolutely easily be done via `optional(...) ?? 'fallback'`, so I don't see the need to handle this in our code
2. Yeah, we could update the signature to
   ```ts
   function optional<T>(
      callbackOrValue: (() => T) | T,
      { probability = 0.5 }: { probability: number } = { probability: 0.5 },
   ): T | undefined
   ```
   But keep in mind that it should be preferred to call `optional(() => faker.name.firstName())` instead of `optional(faker.name.firstName())` as second would always call and then throw away the value instead of lazy call it.
3. See 1. and 2. + The `probability` should be optional and default to 50/50 (50%) so it is also possible to call the function without using extra stuff.

**Comment by ST-DDT** [comment]
Implemented as **`faker.helpers.maybe`**.
