### ISSUE TITLE
add probability option to datatype.boolean()

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#871]
### Clear and concise description of the problem

In our code, we have some parts that are locked behind probability checks.
It would be nice if we could just use a direct boolean call instead of random numbers and floats being compared to magic numbers.

### Suggested solution

````ts
boolean(probability: 0.5, base = 1): boolean {
    return faker.datatype.number(base) <= probability;
}
````

**Comment by xDivisionByZerox** [comment]
Can you give an example where this would be helpful?

**Comment by ST-DDT** [comment]
> Can you give an example where this would be helpful?

See also #870 

https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/git.ts#L73
https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/name.ts#L200
https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/address.ts#L236-L243
https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/finance.ts#L347

**Comment by xDivisionByZerox** [comment]
Why is a probability needed for these checks? 
In `git.ts` For example, why should a merge only in 25% of the cases be applied? Why cant it be a 50-50 thing by using the existing `faker.datatype.boolean()`? 
This question can obviously be applied to any probability check.

**Comment by xDivisionByZerox** [comment]
And if these checks are really needed, who decides the probability an event happens? Do we have any datasets that provide the information we base our return values on? This seems very unfounded to me.

**Comment by Shinigami92** [comment]
I think @xDivisionByZerox has a point here :thinking: 
Why don't we let the user decide via e.g. options and if the user wants to have a probability for that option, the can use faker.boolean or some thing else.

**Comment by ST-DDT** [comment]
> And if these checks are really needed, who decides the probability an event happens?

In some cases, there are options for the explicit toggle and a random chance fallback. See my first code example:

https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/git.ts#L73

The user has the chance to enable or disable it. However, if he doesn't like our default probability of 1/5, then they have to write verbose code to address that. The boolean probability param is there to simplify that for our users and us:

User:
````ts
faker.git.commitEntry({ merge: faker.datatype.boolean(0.4) });
````

Us:

````diff
- if (options.merge || this.faker.datatype.number({ min: 0, max: 4 }) === 0) {
+ if (options.merge || this.faker.datatype.boolean(0.2)) {
      lines.push(`Merge: ${this.shortSha()} ${this.shortSha()}`);
  }
````

I assume `||` should be `??` here instead, but that's another issue altogether.
We could also change the method to `faker.git.commitEntry({ merge: 0.4 });`, 
but that once again would use the boolean probability internally and would also be a different issue.
Last but not least, this issue is not about which probabilities we use ourselves at this point in time,
but the ability to convert `%` -> `boolean` similar on how we have ranges+precision for numbers.

**Comment by Shinigami92** [comment]
I would prefer `faker.datatype.boolean({ probability: 0.4 })` over `faker.datatype.boolean(0.4)` because it is more clear and it is more future extendable for us.
For `faker.git.commitEntry` I would go with `{ mergeCommitProbability: 0.4 }`, it is longer but just easier to understand what is going on.

**Comment by ST-DDT** [comment]
> I would prefer `faker.datatype.boolean({ probability: 0.4 })` over `faker.datatype.boolean(0.4)`

I don't really mind. 
(For context: I would like to have a similar to a method for numbers later: 
`number | { min: number, max: number} -> number` that I would like to use for the lorem module
e.g. exactly 3 vs 2-4 lines of lorem).

https://github.com/faker-js/faker/blob/65289e5dfbe990d7d03686cca2dbd3a891d78935/src/lorem.ts#L199-L202

> Do we have more places where we could benefit from such an option property?

I haven't checked, the entire code base yet adding the option would be a different issue anyway.

**Comment by xDivisionByZerox** [comment]
Is this issue resoved due to #874?

**Comment by ST-DDT** [comment]
Yes.
