### ISSUE TITLE
Credit/debit cards

### ISSUE THREAD

**Issue by beninsydney** [faker-js/faker#882]
### Clear and concise description of the problem

I would like to be able to generate fake customer information with fake banking information, like

{ name: 'Chase Sapphire Mastercard', bank: 'Chase', number: '1234-1234-1234-1234', exp: '12/23' },
{ name: 'BankAmericard VISA', bank: 'Bank of America', last4: '1234-1234-1234-1234', exp: '11/21' }

### Suggested solution

This could perhaps fit in 

    faker.finance.card()

or maybe

    faker.helpers.bankCard()

### Alternative

I have an array with some names that I randomly select from

const cardTypes = [
  'American Express',
  'Diners Club - Carte Blanche',
  'Diners Club',
  'Discover',
  'InstaPayment',
  'JCB',
  'Laser',
  'Maestro',
  'MasterCard',
  'Visa',
  'Visa Electron'
]

**Comment by xDivisionByZerox** [comment]
Just want to make sure I understand you correctly:
Do you want the entire card as a feature or the banking card names?

The first could be really hard to implement since there is no standardized way to provide this object. The card names seem more reasonable and would allow you to build the desired object yourself.

**Comment by beninsydney** [comment]
I don't think an object is required things like card numbers and expiration works well enough with random numbers.

**Comment by xDivisionByZerox** [comment]
Alright, gotcha :)

Feel free to open a PR to accelerate the implementation process.

**Comment by ST-DDT** [comment]
Potential workaround available:

````ts
faker.random.objectElement(faker.definitions.finance.credit_card, 'key')
````

Suggested future method name/location:

````ts
faker.finance.creditCardProvider()
````
