### ISSUE TITLE
Feat: Add typescript types for @faker-js/faker

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#9]

**Comment by nick-krantz** [comment]
I'd be interested in contributing to getting types going for the project. Based on the discussion in #14, I think the intention is to add the types to DefinitelyTyped? Is that correct?

**Comment by Shinigami92** [comment]
For now please create a file in your repo with content:

```ts
// faker.d.ts
declare module '@faker-js/faker' {
  import faker from 'faker';
  export default faker;
}
```

and then just use the `@types/faker`

**Comment by Shinigami92** [comment]
The rewrite to TS could take some days

**Comment by damienwebdev** [comment]
read: weeks.

**Comment by nick-krantz** [comment]
Oh I must have misunderstood, I thought there would be an intermediate state where types would come before the TS rewrite.

> read: weeks.

I believe it

**Comment by Shinigami92** [comment]
> ```ts
> // faker.d.ts
> declare module '@faker-js/faker' {
>   import faker from 'faker';
>   export default faker;
> }
> ```

It works! I tested this im my own repo at work!

**Comment by sramam** [comment]
Can't this be actually included in the current repo? 
That way, it'll get fixed when it'll get fixed and we won't have to back out this change from a 10^6 downstream modules.

Happy to submit a PR is that seems like an acceptable band-aid.

**Comment by MilosPaunovic** [comment]
Hello @MohdImran001,

You were willing to help with types on `community-faker`, https://github.com/MilosPaunovic/community-faker/issues/3, but, for the benefit of the OpenSource, we are moving the official community-driven fork here, so, are you willing to help out here, as well?

**Comment by Shinigami92** [comment]
> Can't this be actually included in the current repo? That way, it'll get fixed when it'll get fixed and we won't have to back out this change from a 10^6 downstream modules.
> 
> Happy to submit a PR is that seems like an acceptable band-aid.

This will not work, cause the current versions <=5.5.3 are already released and not touched by us except the package name.
But I already working on TS migration at all #72, but sadly I'm a human and not a AI, so this could take a week or so

**Comment by MohdImran001** [comment]
Thanks, for tagging me here @MilosPaunovic. 😃.  As far as I have understood, @Shinigami92 is working on all the Typescript related things in #72. @Shinigami92 Please let me know, how can I get started. I have joined the discord server.

**Comment by damienwebdev** [comment]
Given the workaround here: https://github.com/faker-js/faker/issues/9#issuecomment-1009172915 I'm closing this issue.

**Comment by nicolasrouanne** [comment]
FWIW in order to use named imports, I had to make a slightly different export from the `.d.ts` file than the [proposed solution](https://github.com/faker-js/faker/issues/9#issuecomment-1009172915):

```ts
// faker.d.ts
declare module '@faker-js/faker' {
  import faker from 'faker';
  export = faker;
}
```

Using it as named imports
```ts
// some test file
import { datatype, date, hacker } from '@faker-js/faker';
```

**Comment by micalevisk** [comment]
another way is using TS path aliases like:

```json
{
  "compilerOptions": {
    "paths": {
      "faker/*": ["@faker-js/faker/*"],
      "faker": ["@faker-js/faker"]
    }
  }
}
```

thus you don't need to change anything besides the `tsconfig` file.

**Comment by SametSahin10** [comment]
> For now please create a file in your repo with content:
> 
> ```ts
> // faker.d.ts
> declare module '@faker-js/faker' {
>   import faker from 'faker';
>   export default faker;
> }
> ```
> 
> and then just use the `@types/faker`

Does the location of the faker.d.ts file matter? Where should we put the file?

**Comment by Shinigami92** [comment]
> Does the location of the faker.d.ts file matter? Where should we put the file?

Please note that you can already switch to v6.0.0-alpha.3 with native TS support :raised_hands:

**Comment by SametSahin10** [comment]
> > Does the location of the faker.d.ts file matter? Where should we put the file?
> 
> Please note that you can already switch to v6.0.0-alpha.3 with native TS support raised_hands

Oh, really? I spent some time trying to figure out how I can link the faker.d.ts with the @types/faker package. Maybe the README file could be updated to remove the [Typescript Support section](https://github.com/faker-js/faker#typescript-support) or there could be a mention of the fact that TS support is available in the latest version.

**Comment by Shinigami92** [comment]
> Oh, really? I spent some time trying to figure out how I can link the faker.d.ts with the @types/faker package. Maybe the README file could be updated to remove the [Typescript Support section](https://github.com/faker-js/faker#typescript-support) or there could be a mention of the fact that TS support is available in the latest version.

Already planed :wink: 
But we decide it to leave as is for now, until v6.0.0 is fully released

**Comment by SametSahin10** [comment]
The index.d.ts file handles the linking, right? Back then, we needed to create the faker.d.ts file because the index.d.ts did not exist. I'm currently learning how declaration files work in TS. @Shinigami92

**Comment by Shinigami92** [comment]
> The index.d.ts file handles the linking, right? Back then, we needed to create the faker.d.ts file because the index.d.ts did not exist. I'm currently learning how declaration files work in TS. @Shinigami92

Yes it does, sadly we have currently for some an issue in the `-alpha.3` because we shipped the `index.ts` next to `index.d.ts`, but this will be already fixed in `-alpha.4`

**Comment by SametSahin10** [comment]
> > The index.d.ts file handles the linking, right? Back then, we needed to create the faker.d.ts file because the index.d.ts did not exist. I'm currently learning how declaration files work in TS. @Shinigami92
> 
> Yes it does, sadly we have currently for some an issue in the `-alpha.3` because we shipped the `index.ts` next to `index.d.ts`, but this will be already fixed in `-alpha.4`

Is the issue about importing? Cause I cannot import faker with:

`import * as faker from "faker"`

I get "Cannot find module or its type declarations" and "Unable to resolve path to module faker".

**Comment by Shinigami92** [comment]
@SametSahin10 Please try `import faker from "@faker-js/faker"` :wink: 

Could also be that you need `"esModuleInterop": true` in tsconfig.json

**Comment by SametSahin10** [comment]
> @SametSahin10 Please try `import faker from "@faker-js/faker"` wink
> 
> Could also be that you need `"esModuleInterop": true` in tsconfig.json

I needed to add `"esModuleInterop": true` into tsconfig.json and it worked.
