### ISSUE TITLE
Deprecation message before refactoring - arrayElement()

### ISSUE THREAD

**Issue by rota-rossi** [faker-js/faker#902]
### Describe the bug

On release 6.3.0,  it was added a warning that `faker.random.arrayElement` is deprecated - but other functions like `faker.random.alphaNumeric` are still referencing the obsolete one.

### Reproduction

just call `fake.random.alphaNumeric()`: 

```
$ node                                                                                                                                                              ─╯
Welcome to Node.js v16.14.0.
Type ".help" for more information.
> const {faker} = require('@faker-js/faker');
undefined
> faker.random.alphaNumeric()
[@faker-js/faker]: faker.random.arrayElement() is deprecated since v6.3.0 and will be removed in v7.0.0. Please use faker.helpers.arrayElement() instead.
'l'
```

### Additional Info

should be considered holding adding deprecation notices until all internal functions are refactored to remove the dependency from the deprecated method.

**Comment by Shinigami92** [comment]
Thx for the report
We used search and replace, but missed the calls inside the random module itself

**Comment by rota-rossi** [comment]
@Shinigami92, not a problem - sorry if I sounded aggressive in my report (I was re-reading it and it sounded to me like I was).

and thanks a lot for your work on keeping this library up-to-date!

**Comment by Shinigami92** [comment]
> @Shinigami92, not a problem - sorry if I sounded aggressive in my report (I was re-reading it and it sounded to me like I was).
> 
> and thanks a lot for your work on keeping this library up-to-date!

To be fair, I didn't really read your issue :rofl: I just saw the problem and fixed it :heart:
