### ISSUE TITLE
Random status code

### ISSUE THREAD

**Issue by Minozzzi** [faker-js/faker#906]
### Clear and concise description of the problem

Hello guys, I think that we need a function to generate random http status code

### Suggested solution

We can implement in internet module

**Comment by ST-DDT** [comment]
Are you referring to the codes (400) or the names (Bad_Request)?
I'm not sure whether the later ones are standardized.

**Comment by Minozzzi** [comment]
I'm referring to the codes, generating a random statusCode from 100 to 500. And, we could have a prop to get the status of only one type.
Examples: 
`getStatusCode() // generate random status code between 100 and 500`
`getStatusCode(success) //generate random success status code`

**Comment by ST-DDT** [comment]
Sounds good. Should we stick to common ones/or should we have a separate flag for that? (common = 200,301,302,400,401,403,404,500,?)

**Comment by Shinigami92** [comment]
I want `418` 👀

**Comment by Minozzzi** [comment]
i think we can make an object with all httpStatusCode and get a random element.
Example:
```ts
const httpStatusCode = {
    success: [200, 201....], // all success codes
    clientError: [400, 401...] // all clients error
}
```

So we can draw between a specific status type as well. Do you guys think it works?

**Comment by ST-DDT** [comment]
We do something similar for emojis already:

https://github.com/faker-js/faker/blob/18614fbecc48490cc669a8e60ffe82122233e6a7/src/modules/internet/index.ts#L447-L457

**Comment by Minozzzi** [comment]
Its ok, I will start development during the week
