### ISSUE TITLE
unpkg not working

### ISSUE THREAD

**Issue by amchconsult** [faker-js/faker#914]
### Describe the bug

<script type="text/javascript" src="https://unpkg.com/@faker-js/faker"></script>

As described on documentation is not working.
I am trying to use it on browser.

thank you

### Reproduction

script type="text/javascript" src="https://unpkg.com/@faker-js/faker"></script>

**Comment by Shinigami92** [comment]
Yeah, I think we need to remove this from our docs as we do not bundle UMD or _register_ the faker instance in `window`/`globalThis`.
So if unpkg is not doing some magic on its side, this will not work in any way.

Please use one of the other strategies like described here: https://fakerjs.dev/guide/#alternative-cdn-links
Also note that `cdn.skypack.dev` had some issues and you may want to use one of the alternative CDNs

**Comment by ST-DDT** [comment]
See also: #635

**Comment by Shinigami92** [comment]
We already removed and adjusted the docs
- https://github.com/faker-js/faker/pull/1249
