### ISSUE TITLE
ci: check whether scripts still compile

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#917]
### Clear and concise description of the problem

In #910 I removed code from the sources, that were used in the scripts.
Unfortunately, there isn't a build step that checks them with TS powers.

### Suggested solution

Check the types in the ci pipeline.

### Alternative

Run all scripts (#813), however that still wouldn't catch most type errors.

**Comment by ST-DDT** [comment]
I'm not sure, how to proceed here. Any input is welcome.

**Comment by Shinigami92** [comment]
Duplicate of https://github.com/faker-js/faker/issues/813 ?

**Comment by ST-DDT** [comment]
#813 is for actually running them, as mentioned above, that wouldn't necessarily uncover all type errors.
