### ISSUE TITLE
Science module

### ISSUE THREAD

**Issue by import-brain** [faker-js/faker#944]
### Clear and concise description of the problem

I think it would be a good idea to add a science module to Faker to generate random scientific data. See below for examples.

### Suggested solution

Create a new module called science

`faker.science.elementName() // "Lithium"`
`faker.science.elementSymbol() // "F"`
`faker.science.siUnit() // "kg"`
`faker.science.siUnit({ long: true, plural: false }) // "meter"`

**Comment by ST-DDT** [comment]
IMO this discussion is off topic. Please open a new dedicated issue for that.

**Comment by import-brain** [comment]
@Shinigami92 Can you please create that issue? It's your idea, haha

Now that we're back on track, I would like some input from @faker-js/maintainers and/or @faker-js/members about this proposal. Thanks :)

**Comment by ST-DDT** [comment]
The elementNames might be useful, but I'm not sure when you would need a random unit, usually the unit is fix and the value is dynamic. But I'm not really against it.

**Comment by pkuczynski** [comment]
Sounds fine to me. Although I would probably do `faker.science.element` and return a hash, so people could use it like this:

```
faker.science.element().name
faker.science.element().symbol
```

Why? Because they might need both, symbol and name at the same time...

And for units, I would just call it `faker.science.unit`...

**Comment by import-brain** [comment]
> Sounds fine to me. Although I would probably do `faker.science.element` and return a hash, so people could use it like this:
> 
> ```
> faker.science.element().name
> faker.science.element().symbol
> ```
> 
> Why? Because they might need both, symbol and name at the same time...
> 
> And for units, I would just call it `faker.science.unit`...

Yeah, these names you suggested are much better than what I thought of, thanks for the input!
