### ISSUE TITLE
The original repo was not deleted for unknown reasons

### ISSUE THREAD

**Issue by AllanOricil** [faker-js/faker#99]
### Describe the bug

The original repo was not deleted for unknown reasons.
That was also an attempt to show private companies that open source developers also need support. Doing this is probably not what the community wants. It also is kind disrespectful with the creators of faker, as it does not help them at all.

### Reproduction

something

**Comment by MilosPaunovic** [comment]
Hello,

We can't be sure of the real reasons behind why the original creator decided to do what he did, but we can keep it going (and improve) for the community to use.

For more information, check [https://github.com/faker-js/faker/discussions/52](https://github.com/faker-js/faker/discussions/52).

**Comment by AllanOricil** [comment]
Why not let this open and see what the community has to say?

**Comment by AllanOricil** [comment]
https://www.reddit.com/r/programming/comments/rz5rul/marak_creator_of_fakerjs_who_recently_deleted_the/

**Comment by damienwebdev** [comment]
Please continue discussion here: https://github.com/faker-js/faker/discussions/52 not in issues.
