### ISSUE TITLE
Add integration test that catches errors like #989

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#991]
### Clear and concise description of the problem

Currently, these build errors can only be detected by "external" applications that use our library.

### Suggested solution

Add an integration test that uses our library as dependency and execute some of our methods.

### Additional context

- #989
- #979

**Comment by Shinigami92** [comment]
Kinda done via reworking https://github.com/faker-js/playground
_sadly_ we still need to execute that manually, as we do not have commit-releases (yet?)

**Comment by ST-DDT** [comment]
Shini does this by hand...
