### ISSUE TITLE
In email functionality : allow special character false is not working.

### ISSUE THREAD

**Issue by Pandicool** [faker-js/faker#999]
### Describe the bug

Trying to create 100 email with firstname, secondname , provider and allow special character is false object, but the generating email is having special character's like underscore and dot.

### Used code:
```ts
const { faker } = require('@faker-js/faker');
describe("create 100 email", async () => {
    it("by using faker generate 100 email address", async () => {
        for(let i =0 ;i <100;i++){
            console.log(await faker.internet.email("","","gmail.com",{allowSpecialCharacters:false}))
        }
    })
})
```

### Response:
`0-0] Devante_Stroman75@gmail.com
[0-0] Casandra_Denesik73@gmail.com
[0-0] Elijah80@gmail.com
[0-0] Sandra.Legros73@gmail.com
[0-0] Ervin_Erdman59@gmail.com
[0-0] Kiarra33@gmail.com
[0-0] Sierra_Keeling@gmail.com
[0-0] Elza_Hartmann@gmail.com
[0-0] Briana.Kilback11@gmail.com
[0-0] Rashad54@gmail.com
[0-0] Karianne55@gmail.com
[0-0] Randy48@gmail.com
[0-0] Sierra_Heidenreich20@gmail.com

**Comment by Shinigami92** [comment]
I assume underscore and dot are not counted as special characters but common separators.

But I think you are right at least for the underscore as I tried to create an email in gmail and underscore was not allowed. 🤔

So we may research what are possible separators for knows email providers and make it maybe even configurable via an additional option property.

**Comment by Pandicool** [comment]
@Shinigami92  sure thank you

**Comment by xDivisionByZerox** [comment]
Close this as the issue seem to be resolved.
